CREATE TABLE UUIDUUIDGENENTITY (ID VARCHAR2(255) NOT NULL, STRDATA VARCHAR2(255) NULL, PRIMARY KEY (ID));
CREATE TABLE UUIDIDCLASSENTITY (UUID_ID VARCHAR2(255) NOT NULL, L_ID NUMBER(19) NOT NULL, STRDATA VARCHAR2(255) NULL, PRIMARY KEY (UUID_ID, L_ID));
CREATE TABLE UUIDAUTOGENENTITY (ID VARCHAR2(255) NOT NULL, STRDATA VARCHAR2(255) NULL, PRIMARY KEY (ID));
CREATE TABLE UUIDENTITY (ID VARCHAR2(255) NOT NULL, STRDATA VARCHAR2(255) NULL, PRIMARY KEY (ID));
CREATE TABLE UUIDEMBEDDABLEIDENTITY (STRDATA VARCHAR2(255) NULL, ID VARCHAR2(255) NOT NULL, PRIMARY KEY (ID));

CREATE TABLE XMLUUIDUUIDGENENTITY (ID VARCHAR2(255) NOT NULL, STRDATA VARCHAR2(255) NULL, PRIMARY KEY (ID));
CREATE TABLE XMLUUIDIDCLASSENTITY (UUID_ID VARCHAR2(255) NOT NULL, L_ID NUMBER(19) NOT NULL, STRDATA VARCHAR2(255) NULL, PRIMARY KEY (UUID_ID, L_ID));
CREATE TABLE XMLUUIDAUTOGENENTITY (ID VARCHAR2(255) NOT NULL, STRDATA VARCHAR2(255) NULL, PRIMARY KEY (ID));
CREATE TABLE XMLUUIDENTITY (ID VARCHAR2(255) NOT NULL, STRDATA VARCHAR2(255) NULL, PRIMARY KEY (ID));
CREATE TABLE XMLUUIDEMBEDDABLEIDENTITY (STRDATA VARCHAR2(255) NULL, EID VARCHAR2(255) NOT NULL, PRIMARY KEY (EID));

CREATE TABLE QUERYDATETIMEENTITY (ID NUMBER(10) NOT NULL, LOCALDATEDATA DATE NULL, LOCALDATETIMEDATA TIMESTAMP NULL, LOCALTIMEDATA TIMESTAMP NULL, PRIMARY KEY (ID));
CREATE TABLE QUERYENTITY (ID NUMBER(10) NOT NULL, DOUBLEVAL NUMBER(19,4) NULL, FLOATVAL NUMBER(19,4) NULL, INTVAL NUMBER(10) NULL, LONGVAL NUMBER(19) NULL, STRVAL VARCHAR2(255) NULL, PRIMARY KEY (ID));

CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR2(255) NOT NULL, SEQ_COUNT NUMBER);
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);

CREATE TABLE CaseEntity (KEY_CHAR VARCHAR2(255) NOT NULL, ITEM_INTEGER1 NUMBER, ITEM_INTEGER2 NUMBER, ITEM_STRING1 VARCHAR2(255), ITEM_STRING2 VARCHAR2(255), ITEM_STRING3 VARCHAR2(255), ITEM_STRING4 VARCHAR2(255), PRIMARY KEY (KEY_CHAR));
CREATE TABLE Case2Entity (ID NUMBER(19) NOT NULL, INTVAL1 NUMBER(10) NULL, INTVAL2 NUMBER(10) NULL, STRVAL1 VARCHAR2(255) NULL, STRVAL2 VARCHAR2(255) NULL, PRIMARY KEY (ID));
CREATE TABLE COLTABLE1 (ent_id NUMBER(19) NULL, COLVAL1 VARCHAR2(255) NULL);
ALTER TABLE COLTABLE1 ADD CONSTRAINT FK_COLTABLE1_ent_id FOREIGN KEY (ent_id) REFERENCES ${schemaname}.Case2Entity (ID);
CREATE TABLE Case3Entity (KEY_CHAR VARCHAR2(255) NOT NULL, ITEM_INTEGER1 NUMBER, ITEM_STRING1 VARCHAR2(255), ITEM_STRING2 VARCHAR2(255), ITEM_STRING3 VARCHAR2(255), ITEM_STRING4 VARCHAR2(255), PRIMARY KEY (KEY_CHAR));