CREATE TABLE ${schemaname}.JPA10EntityManagerEntityA (id INT NOT NULL, strData VARCHAR(255) NULL NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.JPA10EntityManagerEntityA_JPA10EntityManagerEntityB (ENTITYALIST_ID INT NULL, ENTITYBLIST_ID INT NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE);
CREATE TABLE ${schemaname}.JPA10EntityManagerEntityB (id INT NOT NULL, strData VARCHAR(255) NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.JPA10EntityManagerEntityC (id INT NOT NULL, strData VARCHAR(255) NULL, ENTITYA_ID INT NULL, ENTITYALAZY_ID INT NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));
CREATE INDEX I_JP10JP1_ELEMENT ON ${schemaname}.JPA10EntityManagerEntityA_JPA10EntityManagerEntityB (ENTITYBLIST_ID);
CREATE INDEX I_JP10JP1_ENTITYALIST_ID ON ${schemaname}.JPA10EntityManagerEntityA_JPA10EntityManagerEntityB (ENTITYALIST_ID);
CREATE INDEX I_JP10TYC_ENTITYA ON ${schemaname}.JPA10EntityManagerEntityC (ENTITYA_ID);
CREATE INDEX I_JP10TYC_ENTITYALAZY ON ${schemaname}.JPA10EntityManagerEntityC (ENTITYALAZY_ID);