CREATE TABLE JPA10EntityManagerEntityA (id INT NOT NULL, strData VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE JPA10EntityManagerEntityA_JPA10EntityManagerEntityB (ENTITYALIST_ID INT, ENTITYBLIST_ID INT);
CREATE TABLE JPA10EntityManagerEntityB (id INT NOT NULL, strData VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE JPA10EntityManagerEntityC (id INT NOT NULL, strData VARCHAR(255), ENTITYA_ID INT, ENTITYALAZY_ID INT, PRIMARY KEY (id));
CREATE INDEX I_JP10TYB_ELEMENT ON JPA10EntityManagerEntityA_JPA10EntityManagerEntityB (ENTITYBLIST_ID);
CREATE INDEX I_JP10TYB_ENTITYALIST_ID ON JPA10EntityManagerEntityA_JPA10EntityManagerEntityB (ENTITYALIST_ID);
CREATE INDEX I_JP10TYC_ENTITYA ON JPA10EntityManagerEntityC (ENTITYA_ID);
CREATE INDEX I_JP10TYC_ENTITYALAZY ON JPA10EntityManagerEntityC (ENTITYALAZY_ID);