# Common test ports
bvt.prop.HTTP_default=8010
bvt.prop.HTTP_default.secure=8020
bvt.prop.IIOP=2809
bvt.prop.IIOP.2=2810
bvt.prop.jms=1414
bvt.prop.jms.ssl=1415
bvt.prop.jms.2=1416
bvt.prop.jms.2.ssl=1417
bvt.prop.http.1=8011
bvt.prop.http.1.ssl=8021
bvt.prop.http.2=8012
bvt.prop.http.2.ssl=8022
bvt.prop.http.3=8013
bvt.prop.http.3.ssl=8023
bvt.prop.jms.1=1414
bvt.prop.jms.1.ssl=1415
