<?xml version="1.0" encoding="UTF-8"?>
<!--
# COPYRIGHT LICENSE: 
# This information contains sample code provided in source code form. You may 
# copy, modify, and distribute these sample programs in any form without 
# payment to IBM for the purposes of developing, using, marketing or 
# distributing application programs conforming to the application programming
# interface for the operating platform for which the sample code is written. 
# Notwithstanding anything to the contrary, IBM PROVIDES THE SAMPLE SOURCE CODE
# ON AN "AS IS" BASIS AND IBM DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, 
# INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OR CONDITIONS OF 
# MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, 
# TITLE, AND ANY WARRANTY OR CONDITION OF NON-INFRINGEMENT. IBM SHALL NOT BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OR OPERATION OF THE SAMPLE SOURCE CODE. IBM HAS NO 
# OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS OR 
# MODIFICATIONS TO THE SAMPLE SOURCE CODE.
 -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsp="http://www.w3.org/ns/ws-policy"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
                  xmlns:sp13="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200802"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://com/ibm/was/wssample/sei/echo/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  name="WSSampleSeiBsp"
                  xmlns:wsaws="http://www.w3.org/2005/08/addressing"
                  targetNamespace="http://com/ibm/was/wssample/sei/echo/">
   <wsdl:types>
      <xsd:schema targetNamespace="http://com/ibm/was/wssample/sei/echo/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <xsd:element name="echoStringResponse">
            <xsd:complexType>
               <xsd:sequence>
                  <xsd:element name="echoResponse"
                               type="xsd:string"/>
               </xsd:sequence>
            </xsd:complexType>
         </xsd:element>
         <xsd:element name="echoStringInput">
            <xsd:complexType>
               <xsd:sequence>
                  <xsd:element name="echoInput"
                               type="xsd:string"/>
               </xsd:sequence>
            </xsd:complexType>
         </xsd:element>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="echoOperationRequest">
      <wsdl:part element="tns:echoStringInput"
                 name="parameter"/>
   </wsdl:message>
   <wsdl:message name="echoOperationResponse">
      <wsdl:part element="tns:echoStringResponse"
                 name="parameter"/>
   </wsdl:message>
   <wsdl:portType name="EchoServicePortType">
      <wsdl:operation name="echoOperation">
         <wsdl:input message="tns:echoOperationRequest"/>
         <wsdl:output message="tns:echoOperationResponse"/>
      </wsdl:operation>
   </wsdl:portType>

   <!-- bsp11 -->
   <wsp:Policy wsu:Id="bsp11Policy">
      <ns1:AsymmetricBinding xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:Layout>
               <wsp:Policy>
                  <ns1:Strict/>
               </wsp:Policy>
            </ns1:Layout>
            <ns1:RecipientToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToInitiator">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:RecipientToken>
            <ns1:AlgorithmSuite>
               <wsp:Policy>
                  <!--ns1:XPathFilter20/ -->
                  <ns1:Basic128Rsa15/>
               </wsp:Policy>
            </ns1:AlgorithmSuite>
            <ns1:InitiatorToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:InitiatorToken>
            <ns1:IncludeTimestamp/>
         </wsp:Policy>
      </ns1:AsymmetricBinding>
      <ns1:Wss10 xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:MustSupportRefKeyIdentifier/>
         </wsp:Policy>
      </ns1:Wss10>
      <sp:SignedParts>
          <sp:Body/>
          <sp:Header Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing"/>
          <sp:Header Namespace="http://www.w3.org/2005/08/addressing"/>
      </sp:SignedParts>
      <sp:SignedElements>
          <sp:XPath>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Envelope']/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
      </sp:SignedElements>
      <sp:EncryptedParts>
          <sp:Body/>
          <sp:Header xmlns="" Namespace="http://www.example.org/getMessage/" Name="msgHeaderElement"/>
      </sp:EncryptedParts>
   </wsp:Policy>
   <wsp:Policy wsu:Id="bsp11OutPolicy">
      <ns1:AsymmetricBinding xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:Layout>
               <wsp:Policy>
                  <ns1:Strict/>
               </wsp:Policy>
            </ns1:Layout>
            <ns1:RecipientToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToInitiator">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:RecipientToken>
            <ns1:AlgorithmSuite>
               <wsp:Policy>
                  <!--ns1:XPathFilter20/ -->
                  <ns1:Basic128Rsa15/>
               </wsp:Policy>
            </ns1:AlgorithmSuite>
            <ns1:InitiatorToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:InitiatorToken>
            <ns1:IncludeTimestamp/>
         </wsp:Policy>
      </ns1:AsymmetricBinding>
      <ns1:Wss10 xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:MustSupportRefKeyIdentifier/>
         </wsp:Policy>
      </ns1:Wss10>
      <sp:SignedParts>
          <sp:Body/>
          <sp:Header Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing"/>
          <sp:Header Namespace="http://www.w3.org/2005/08/addressing"/>
      </sp:SignedParts>
      <sp:SignedElements>
          <sp:XPath>/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Envelope']/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd' and local-name()='SignatureConfirmation']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd' and local-name()='SignatureConfirmation']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Envelope']/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
      </sp:SignedElements>
      <sp:EncryptedParts>
          <sp:Body/>
      </sp:EncryptedParts>
   </wsp:Policy>
   <wsdl:binding name="Echo11SOAP"
                 type="tns:EchoServicePortType">
      <wsp:PolicyReference URI="#bsp11Policy"/>
      <soap:binding style="document"
                    transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="echoOperation">
         <soap:operation soapAction="echoOperation"
                         style="document"/>
         <wsdl:input>
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output>
            <wsp:PolicyReference URI="#bsp11OutPolicy"/>
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="Echo11Service">
      <wsdl:port binding="tns:Echo11SOAP"
                 name="Echo11ServicePort">
         <soap:address location="http://localhost:8010/WSSampleSei/Echo11Service"/>
      </wsdl:port>
   </wsdl:service>

  <!-- bsp12 -->
   <wsp:Policy wsu:Id="bsp12Policy">
      <ns1:Wss11 xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:RequireSignatureConfirmation/>
            <ns1:MustSupportRefKeyIdentifier/>
         </wsp:Policy>
      </ns1:Wss11>
      <ns1:AsymmetricBinding xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:Layout>
               <wsp:Policy>
                  <ns1:Strict/>
               </wsp:Policy>
            </ns1:Layout>
            <ns1:RecipientToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToInitiator">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:RecipientToken>
            <ns1:AlgorithmSuite>
               <wsp:Policy>
                  <!-- ns1:XPathFilter20/ -->
                  <ns1:Basic128Rsa15/>
               </wsp:Policy>
            </ns1:AlgorithmSuite>
            <ns1:InitiatorToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:InitiatorToken>
            <ns1:IncludeTimestamp/>
         </wsp:Policy>
      </ns1:AsymmetricBinding>
      <sp:SignedParts>
          <sp:Body/>
          <sp:Header Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing"/>
          <sp:Header Namespace="http://www.w3.org/2005/08/addressing"/>
          <sp:Header xmlns="" Namespace="http://www.example.org/getMessage/" Name="msgHeaderElement"/>
      </sp:SignedParts>
      <sp:SignedElements>
          <sp:XPath>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Envelope']/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
      </sp:SignedElements>
      <sp:EncryptedParts>
          <sp:Body/>
          <sp:Header xmlns="" Namespace="http://www.example.org/getMessage/" Name="msgHeaderElement"/>
      </sp:EncryptedParts>
   </wsp:Policy>
   <wsp:Policy wsu:Id="bsp12OutPolicy">
      <ns1:Wss11 xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:RequireSignatureConfirmation/>
            <ns1:MustSupportRefKeyIdentifier/>
         </wsp:Policy>
      </ns1:Wss11>
      <ns1:AsymmetricBinding xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:Layout>
               <wsp:Policy>
                  <ns1:Strict/>
               </wsp:Policy>
            </ns1:Layout>
            <ns1:RecipientToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToInitiator">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:RecipientToken>
            <ns1:AlgorithmSuite>
               <wsp:Policy>
                  <!-- ns1:XPathFilter20/ -->
                  <ns1:Basic128Rsa15/>
               </wsp:Policy>
            </ns1:AlgorithmSuite>
            <ns1:InitiatorToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:InitiatorToken>
            <ns1:IncludeTimestamp/>
         </wsp:Policy>
      </ns1:AsymmetricBinding>
      <sp:SignedParts>
          <sp:Body/>
          <sp:Header Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing"/>
          <sp:Header Namespace="http://www.w3.org/2005/08/addressing"/>
      </sp:SignedParts>
      <sp:SignedElements>
          <sp:XPath>/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Envelope']/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd' and local-name()='SignatureConfirmation']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd' and local-name()='SignatureConfirmation']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Envelope']/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
      </sp:SignedElements>
      <sp:EncryptedParts>
          <sp:Body/>
      </sp:EncryptedParts>
   </wsp:Policy>
   <wsdl:binding name="Echo12SOAP"
                 type="tns:EchoServicePortType">
      <wsp:PolicyReference URI="#bsp12Policy"/>
      <soap:binding style="document"
                    transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="echoOperation">
         <soap:operation soapAction="echoOperation"
                         style="document"/>
         <wsdl:input>
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output>
            <wsp:PolicyReference URI="#bsp12OutPolicy"/>
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="Echo12Service">
      <wsdl:port binding="tns:Echo12SOAP"
                 name="Echo12ServicePort">
         <soap:address location="http://localhost:8010/WSSampleSei/Echo12Service"/>
      </wsdl:port>
   </wsdl:service>


   <!-- bsp13 -->
   <wsp:Policy wsu:Id="bsp13Policy">
      <ns1:Wss11 xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:RequireSignatureConfirmation/>
            <ns1:MustSupportRefKeyIdentifier/>
         </wsp:Policy>
      </ns1:Wss11>
      <ns1:AsymmetricBinding xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:Layout>
               <wsp:Policy>
                  <ns1:Strict/>
               </wsp:Policy>
            </ns1:Layout>
            <ns1:RecipientToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToInitiator">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:RecipientToken>
            <ns1:AlgorithmSuite>
               <wsp:Policy>
                  <!-- ns1:XPathFilter20/ -->
                  <ns1:Basic128Rsa15/>
               </wsp:Policy>
            </ns1:AlgorithmSuite>
            <ns1:InitiatorToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:InitiatorToken>
            <ns1:IncludeTimestamp/>
         </wsp:Policy>
      </ns1:AsymmetricBinding>
      <sp:SignedParts>
          <sp:Body/>
          <sp:Header Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing"/>
          <sp:Header Namespace="http://www.w3.org/2005/08/addressing"/>
      </sp:SignedParts>
      <sp:SignedElements>
          <sp:XPath>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Envelope']/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
      </sp:SignedElements>
      <sp:EncryptedParts>
          <sp:Body/>
      </sp:EncryptedParts>
   </wsp:Policy>
   <wsp:Policy wsu:Id="bsp13OutPolicy">
      <ns1:Wss11 xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:RequireSignatureConfirmation/>
            <ns1:MustSupportRefKeyIdentifier/>
         </wsp:Policy>
      </ns1:Wss11>
      <ns1:AsymmetricBinding xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:Layout>
               <wsp:Policy>
                  <ns1:Strict/>
               </wsp:Policy>
            </ns1:Layout>
            <ns1:RecipientToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToInitiator">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:RecipientToken>
            <ns1:AlgorithmSuite>
               <wsp:Policy>
                  <!-- ns1:XPathFilter20/ -->
                  <ns1:Basic128Rsa15/>
               </wsp:Policy>
            </ns1:AlgorithmSuite>
            <ns1:InitiatorToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:InitiatorToken>
            <ns1:IncludeTimestamp/>
         </wsp:Policy>
      </ns1:AsymmetricBinding>
      <sp:SignedParts>
          <sp:Body/>
          <sp:Header Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing"/>
          <sp:Header Namespace="http://www.w3.org/2005/08/addressing"/>
      </sp:SignedParts>
      <sp:SignedElements>
          <sp:XPath>/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Envelope']/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd' and local-name()='SignatureConfirmation']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd' and local-name()='SignatureConfirmation']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Envelope']/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
      </sp:SignedElements>
      <sp:EncryptedParts>
          <sp:Body/>
      </sp:EncryptedParts>
   </wsp:Policy>
   <wsdl:binding name="Echo13SOAP"
                 type="tns:EchoServicePortType">
      <wsp:PolicyReference URI="#bsp13Policy"/>
      <soap:binding style="document"
                    transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="echoOperation">
         <soap:operation soapAction="echoOperation"
                         style="document"/>
         <wsdl:input>
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output>
            <wsp:PolicyReference URI="#bsp13OutPolicy"/>
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="Echo13Service">
      <wsdl:port binding="tns:Echo13SOAP"
                 name="Echo13ServicePort">
         <soap:address location="http://localhost:8010/WSSampleSei/Echo13Service"/>
      </wsdl:port>
   </wsdl:service>



   <!-- bsp14 -->
   <wsp:Policy wsu:Id="bsp14Policy">
      <ns1:AsymmetricBinding xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:Layout>
               <wsp:Policy>
                  <ns1:Strict/>
               </wsp:Policy>
            </ns1:Layout>
            <ns1:RecipientToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToInitiator">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:RecipientToken>
            <ns1:AlgorithmSuite>
               <wsp:Policy>
                  <!-- ns1:XPathFilter20/ -->
                  <ns1:Basic128Rsa15/>
               </wsp:Policy>
            </ns1:AlgorithmSuite>
            <ns1:InitiatorToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:InitiatorToken>
            <ns1:IncludeTimestamp/>
         </wsp:Policy>
      </ns1:AsymmetricBinding>
      <ns1:Wss11 xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:MustSupportRefThumbprint/>
         </wsp:Policy>
      </ns1:Wss11>
      <sp:SignedParts>
          <sp:Body/>
          <sp:Header Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing"/>
          <sp:Header Namespace="http://www.w3.org/2005/08/addressing"/>
      </sp:SignedParts>
      <sp:SignedElements>
          <sp:XPath>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Envelope']/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
      </sp:SignedElements>
      <sp:EncryptedParts>
          <sp:Body/>
      </sp:EncryptedParts>
   </wsp:Policy>
   <wsp:Policy wsu:Id="bsp14OutPolicy">
      <ns1:AsymmetricBinding xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:Layout>
               <wsp:Policy>
                  <ns1:Strict/>
               </wsp:Policy>
            </ns1:Layout>
            <ns1:RecipientToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToInitiator">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:RecipientToken>
            <ns1:AlgorithmSuite>
               <wsp:Policy>
                  <!-- ns1:XPathFilter20/ -->
                  <ns1:Basic128Rsa15/>
               </wsp:Policy>
            </ns1:AlgorithmSuite>
            <ns1:InitiatorToken>
               <wsp:Policy>
                  <ns1:X509Token ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                     <wsp:Policy>
                        <ns1:WssX509V3Token10/>
                     </wsp:Policy>
                  </ns1:X509Token>
               </wsp:Policy>
            </ns1:InitiatorToken>
            <ns1:IncludeTimestamp/>
         </wsp:Policy>
      </ns1:AsymmetricBinding>
      <ns1:Wss11 xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
         <wsp:Policy>
            <ns1:MustSupportRefThumbprint/>
         </wsp:Policy>
      </ns1:Wss11>
      <sp:SignedParts>
          <sp:Body/>
          <sp:Header Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing"/>
          <sp:Header Namespace="http://www.w3.org/2005/08/addressing"/>
      </sp:SignedParts>
      <sp:SignedElements>
          <sp:XPath>/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Envelope']/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd' and local-name()='SignatureConfirmation']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd' and local-name()='SignatureConfirmation']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Envelope']/*[namespace-uri()='http://www.w3.org/2003/05/soap-envelope' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
      </sp:SignedElements>
      <sp:EncryptedParts>
          <sp:Body/>
      </sp:EncryptedParts>
   </wsp:Policy>
   <wsdl:binding name="Echo14SOAP"
                 type="tns:EchoServicePortType">
      <wsp:PolicyReference URI="#bsp14Policy"/>
      <soap:binding style="document"
                    transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="echoOperation">
         <soap:operation soapAction="echoOperation"
                         style="document"/>
         <wsdl:input>
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output>
            <wsp:PolicyReference URI="#bsp14Policy"/>
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="Echo14Service">
      <wsdl:port binding="tns:Echo14SOAP"
                 name="Echo14ServicePort">
         <soap:address location="http://localhost:8010/WSSampleSei/Echo14Service"/>
      </wsdl:port>
   </wsdl:service>

</wsdl:definitions>

