CREATE TABLE ${schemaname}.OPENJPA_SEQUENCE_TABLE (ID NUMBER NOT NULL, SEQUENCE_VALUE NUMBER, PRIMARY KEY (ID));
CREATE TABLE ${schemaname}.SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMBER(38), PRIMARY KEY (SEQ_NAME));
CREATE TABLE ${schemaname}.Widget (id NUMBER NOT NULL, description VARCHAR2(255), name VARCHAR2(255), PRIMARY KEY (id));