CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID TINYINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC, PRIMARY KEY (SEQ_NAME));
CREATE TABLE Widget (id INT NOT NULL, description VARCHAR(255), name VARCHAR(255), PRIMARY KEY (id));