CREATE TABLE ${schemaname}.OPENJPA_SEQUENCE_TABLE (ID TINYINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID)) ENGINE = innodb;
CREATE TABLE ${schemaname}.SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME)) ENGINE = innodb;
CREATE TABLE ${schemaname}.Widget (id INTEGER NOT NULL, description VARCHAR(255), name VARCHAR(255), PRIMARY KEY (id)) ENGINE = innodb;