CREATE TABLE ${schemaname}.OPENJPA_SEQUENCE_TABLE (ID INT8 NOT NULL, SEQUENCE_VALUE NUMERIC(32,0), PRIMARY KEY (ID)) LOCK MODE ROW;
CREATE TABLE ${schemaname}.SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC, PRIMARY KEY (SEQ_NAME)) LOCK MODE ROW;
CREATE TABLE ${schemaname}.Widget (id INTEGER NOT NULL, description VARCHAR(255), name VARCHAR(255), PRIMARY KEY (id)) LOCK MODE ROW;