CREATE TABLE ${schemaname}.OPENJPA_SEQUENCE_TABLE (ID TINYINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
CREATE TABLE ${schemaname}.SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC, PRIMARY KEY (SEQ_NAME));
CREATE TABLE ${schemaname}.Widget (id INTEGER NOT NULL, description VARCHAR(255), name VARCHAR(255), PRIMARY KEY (id));