//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:33 PM(foreman)-)
//


package com.ibm.was.wssample.sei.echo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "EchoService", targetNamespace = "http://echo.sei.wssample.was.ibm.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EchoService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://echo.sei.wssample.was.ibm.com", className = "com.ibm.was.wssample.sei.echo.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://echo.sei.wssample.was.ibm.com", className = "com.ibm.was.wssample.sei.echo.EchoResponse")
    public String echo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
