alter session set "_ORACLE_SCRIPT"=true;
create user DefSchmea identified by rubbish;
create user XMLSchName identified by rubbish;
alter user system quota unlimited on users;
grant connect, create session to DefSchmea;
grant unlimited tablespace to DefSchmea;
grant connect, create session to XMLSchName;
grant unlimited tablespace to XMLSchName;

CREATE TABLE XMLSchName.XMLTableName (id NUMBER NOT NULL, XMLName VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.PKGAO_GAOE (id NUMBER NOT NULL, annotatedEagerName VARCHAR2(255), annotatedLazyName VARCHAR2(255), annotatedNonUniqueName VARCHAR2(255) NOT NULL, annotatedUniqueName VARCHAR2(255), lengthBoundString VARCHAR2(20), name VARCHAR2(255), PRIMARY KEY (id), CONSTRAINT U_PKGO_GO_ANNOTATEDNONUNIQUENA UNIQUE (annotatedNonUniqueName) DEFERRABLE);

CREATE TABLE DefSchmea.EntListTestEntity (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE DefSchmea.MFDEntity1 (id NUMBER NOT NULL, city VARCHAR2(255), name VARCHAR2(255), state VARCHAR2(255), street VARCHAR2(255), zip VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE DefSchmea.MFDEntity2 (id NUMBER NOT NULL, city VARCHAR2(255), name VARCHAR2(255), state VARCHAR2(255), street VARCHAR2(255), zip VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE DefSchmea.MFDFQEmbedEnt (id NUMBER NOT NULL, name VARCHAR2(255), city VARCHAR2(255), state VARCHAR2(255), street VARCHAR2(255), zip VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE DefSchmea.MFDMSC1Ent (id NUMBER NOT NULL, name VARCHAR2(255), city VARCHAR2(255), state VARCHAR2(255), street VARCHAR2(255), zip VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE DefSchmea.MFDMSC2Ent (id NUMBER NOT NULL, name VARCHAR2(255), city VARCHAR2(255), state VARCHAR2(255), street VARCHAR2(255), zip VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE DefSchmea.MFDNFQEmbedEnt (id NUMBER NOT NULL, name VARCHAR2(255), city VARCHAR2(255), state VARCHAR2(255), street VARCHAR2(255), zip VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE DefSchmea.MFDRelationalEntA (id NUMBER NOT NULL, name VARCHAR2(255), MANYXONEENTITYB_ID NUMBER, ONEXONEENTITYB_ID NUMBER, PRIMARY KEY (id));
CREATE TABLE DefSchmea.MFDRelationalMMB (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE DefSchmea.MFDRelationalMOB (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE DefSchmea.MFDRelationalOMB (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE DefSchmea.MFDRelationalOOB (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE DefSchmea.PKGMFD_REA_MMEBC_TBL (MFDRelationalEntA NUMBER, MFDRelationalMMB NUMBER);
CREATE TABLE DefSchmea.PKGMFD_REA_OMEBC_TBL (MFDRelationalEntA NUMBER, MFDRelationalOMB NUMBER);
CREATE INDEX I_MFDRLNT_MANYXONEENTITYB ON DefSchmea.MFDRelationalEntA (MANYXONEENTITYB_ID);
CREATE INDEX I_MFDRLNT_ONEXONEENTITYB ON DefSchmea.MFDRelationalEntA (ONEXONEENTITYB_ID);
CREATE INDEX I_PKGMTBL_ELEMENT ON DefSchmea.PKGMFD_REA_MMEBC_TBL (MFDRelationalMMB);
CREATE INDEX I_PKGMTBL_MFDRELATIONALENTA ON DefSchmea.PKGMFD_REA_MMEBC_TBL (MFDRelationalEntA);
CREATE INDEX I_PKGMTBL_ELEMENT1 ON DefSchmea.PKGMFD_REA_OMEBC_TBL (MFDRelationalOMB);
CREATE INDEX I_PKGMTBL_MFDRELATIONALENTA1 ON DefSchmea.PKGMFD_REA_OMEBC_TBL (MFDRelationalEntA);

CREATE TABLE ${schemaname}.MDCEmbedEntity (id NUMBER NOT NULL, name VARCHAR2(30), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.MDCEntity (id NUMBER NOT NULL, name VARCHAR2(30), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.MDCMSCEntity (id NUMBER NOT NULL, name VARCHAR2(30), PRIMARY KEY (id));

CREATE TABLE ${schemaname}.AnnotationOnlyEntity (id NUMBER NOT NULL, name VARCHAR2(12), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLCompleteTestEntity (id NUMBER NOT NULL, nonOptionalName VARCHAR2(255), PRIMARY KEY (id));
             
