INSERT INTO ${schemaname}.JPA20EntityManagerDetachEntity (id, strData, ENTAM2O_ID, ENTAM2O_CA_ID, ENTAM2O_CD_ID, ENTAO2O_ID, ENTAO2O_CA_ID, ENTAO2O_CD_ID) VALUES (20, 'String Data', 1, 2, 3, 4, 5, 6);
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (101, 'JPA20EntityManagerEntityA 101');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (102, 'JPA20EntityManagerEntityA 102');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (111, 'JPA20EntityManagerEntityA 111');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (112, 'JPA20EntityManagerEntityA 112');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (121, 'JPA20EntityManagerEntityA 121');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (122, 'JPA20EntityManagerEntityA 122');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (1, 'JPA20EntityManagerEntityA 1');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (2, 'JPA20EntityManagerEntityA 2');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (3, 'JPA20EntityManagerEntityA 3');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (131, 'JPA20EntityManagerEntityA 131');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (132, 'JPA20EntityManagerEntityA 132');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (141, 'JPA20EntityManagerEntityA 141');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (142, 'JPA20EntityManagerEntityA 142');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (151, 'JPA20EntityManagerEntityA 151');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (152, 'JPA20EntityManagerEntityA 152');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (4, 'JPA20EntityManagerEntityA 4');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (5, 'JPA20EntityManagerEntityA 5');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (6, 'JPA20EntityManagerEntityA 6');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (10, 'A String');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (40, 'A String');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (50, 'A String');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (60, 'A String');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (70, 'A String');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA (id, strData) VALUES (100, 'A String');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityB (id, strData) VALUES (100, 'A String');
INSERT INTO ${schemaname}.JPA20EntityManagerEntityC (id, strData, ENTITYA_ID, ENTITYALAZY_ID) VALUES (100, 'A String', 100, NULL);
INSERT INTO ${schemaname}.JPA20EntityManagerEntityA_JPA20EntityManagerEntityB (ENTITYALIST_ID, ENTITYBLIST_ID) VALUES (100, 100);
INSERT INTO ${schemaname}.EMDETACH_ENTAM2MLIST (JPA20ENTITYMANAGERDETACHENTITY_ID, ENTAM2MLIST_ID) VALUES (20, 101);
INSERT INTO ${schemaname}.EMDETACH_ENTAM2MLIST (JPA20ENTITYMANAGERDETACHENTITY_ID, ENTAM2MLIST_ID) VALUES (20, 102);
INSERT INTO ${schemaname}.EMDETACH_ENTAM2MLIST_CA (JPA20ENTITYMANAGERDETACHENTITY_ID, ENTAM2MLIST_CA_ID) VALUES (20, 111);
INSERT INTO ${schemaname}.EMDETACH_ENTAM2MLIST_CA (JPA20ENTITYMANAGERDETACHENTITY_ID, ENTAM2MLIST_CA_ID) VALUES (20, 112);
INSERT INTO ${schemaname}.EMDETACH_ENTAM2MLIST_CD (JPA20ENTITYMANAGERDETACHENTITY_ID, ENTAM2MLIST_CD_ID) VALUES (20, 121);
INSERT INTO ${schemaname}.EMDETACH_ENTAM2MLIST_CD (JPA20ENTITYMANAGERDETACHENTITY_ID, ENTAM2MLIST_CD_ID) VALUES (20, 122);
INSERT INTO ${schemaname}.EMDETACH_ENTAO2MLIST (JPA20ENTITYMANAGERDETACHENTITY_ID, ENTAO2MLIST_ID) VALUES (20, 131);
INSERT INTO ${schemaname}.EMDETACH_ENTAO2MLIST (JPA20ENTITYMANAGERDETACHENTITY_ID, ENTAO2MLIST_ID) VALUES (20, 132);
INSERT INTO ${schemaname}.EMDETACH_ENTAO2MLIST_CA (JPA20ENTITYMANAGERDETACHENTITY_ID, ENTAO2MLIST_CA_ID) VALUES (20, 141);
INSERT INTO ${schemaname}.EMDETACH_ENTAO2MLIST_CA (JPA20ENTITYMANAGERDETACHENTITY_ID, ENTAO2MLIST_CA_ID) VALUES (20, 142);
INSERT INTO ${schemaname}.EMDETACH_ENTAO2MLIST_CD (JPA20ENTITYMANAGERDETACHENTITY_ID, ENTAO2MLIST_CD_ID) VALUES (20, 151);
INSERT INTO ${schemaname}.EMDETACH_ENTAO2MLIST_CD (JPA20ENTITYMANAGERDETACHENTITY_ID, ENTAO2MLIST_CD_ID) VALUES (20, 152);
INSERT INTO ${schemaname}.JPA20EntityManagerFindEntity (id, firstName, lastName, vacationDays) VALUES (1, NULL, NULL, 0);
INSERT INTO ${schemaname}.JPA20EntityManagerFindEntity (id, firstName, lastName, vacationDays) VALUES (2, NULL, NULL, 0);