CREATE TABLE AnnEmbedMultiTableEnt (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE AnnMSCMultiTableEnt (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE AnnMultiTableEnt (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));

#CREATE TABLE DatatypeSupPropTestEntity (id INTEGER NOT NULL, bigDecimalAttrDefault NUMERIC, bigIntegerAttrDefault BIGINT, booleanAttrDefault BOOL, booleanWrapperAttrDefault BOOL, byteArrayAttrDefault BYTEA, byteAttrDefault SMALLINT, byteWrapperArrayAttrDefault BYTEA, byteWrapperAttrDefault SMALLINT, charArrayAttrDefault VARCHAR(255), charAttrDefault TEXT, charWrapperArrayAttrDefault VARCHAR(255), characterWrapperAttrDefault TEXT, doubleAttrDefault DOUBLE PRECISION, doubleWrapperAttrDefault DOUBLE PRECISION, enumeration SMALLINT, floatAttrDefault FLOAT4, floatWrapperAttrDefault FLOAT4, intAttrDefault INTEGER, integerWrapperAttrDefault INTEGER, longAttrDefault BIGINT, longWrapperAttrDefault BIGINT, serializableClass BYTEA, shortAttrDefault SMALLINT, shortWrapperAttrDefault SMALLINT, sqlDateAttrDefault DATE, sqlTimeAttrDefault TIME, sqlTimestampAttrDefault TIMESTAMP, stringAttrDefault VARCHAR(255), utilCalendarAttrDefault DATE, utilDateAttrDefault DATE, PRIMARY KEY (id));
CREATE TABLE DatatypeSupPropTestEntity (ID INTEGER NOT NULL, BIGDECIMALATTRDEFAULT DECIMAL(38), BIGINTEGERATTRDEFAULT BIGINT, BOOLEANATTRDEFAULT BOOLEAN, BOOLEANWRAPPERATTRDEFAULT BOOLEAN, BYTEARRAYATTRDEFAULT BYTEA, BYTEATTRDEFAULT SMALLINT, BYTEWRAPPERARRAYATTRDEFAULT BYTEA, BYTEWRAPPERATTRDEFAULT SMALLINT, CHARARRAYATTRDEFAULT TEXT, CHARATTRDEFAULT CHAR(1), CHARWRAPPERARRAYATTRDEFAULT TEXT, CHARACTERWRAPPERATTRDEFAULT CHAR(1), DOUBLEATTRDEFAULT FLOAT, DOUBLEWRAPPERATTRDEFAULT FLOAT, ENUMERATION INTEGER, FLOATATTRDEFAULT FLOAT, FLOATWRAPPERATTRDEFAULT FLOAT, INTATTRDEFAULT INTEGER, INTEGERWRAPPERATTRDEFAULT INTEGER, LONGATTRDEFAULT BIGINT, LONGWRAPPERATTRDEFAULT BIGINT, SERIALIZABLECLASS BYTEA, SHORTATTRDEFAULT SMALLINT, SHORTWRAPPERATTRDEFAULT SMALLINT, SQLDATEATTRDEFAULT DATE, SQLTIMEATTRDEFAULT TIME, SQLTIMESTAMPATTRDEFAULT TIMESTAMP, STRINGATTRDEFAULT VARCHAR(255), UTILCALENDARATTRDEFAULT DATE, UTILDATEATTRDEFAULT DATE, PRIMARY KEY (ID));

#CREATE TABLE DatatypeSupTestEntity (id INTEGER NOT NULL, bigDecimalAttrDefault NUMERIC, bigIntegerAttrDefault BIGINT, booleanAttrDefault BOOL, booleanWrapperAttrDefault BOOL, byteArrayAttrDefault BYTEA, byteAttrDefault SMALLINT, byteWrapperArrayAttrDefault BYTEA, byteWrapperAttrDefault SMALLINT, charArrayAttrDefault VARCHAR(255), charAttrDefault TEXT, charWrapperArrayAttrDefault VARCHAR(255), characterWrapperAttrDefault TEXT, doubleAttrDefault DOUBLE PRECISION, doubleWrapperAttrDefault DOUBLE PRECISION, enumeration SMALLINT, floatAttrDefault FLOAT4, floatWrapperAttrDefault FLOAT4, intAttrDefault INTEGER, integerWrapperAttrDefault INTEGER, longAttrDefault BIGINT, longWrapperAttrDefault BIGINT, serializableClass BYTEA, shortAttrDefault SMALLINT, shortWrapperAttrDefault SMALLINT, sqlDateAttrDefault DATE, sqlTimeAttrDefault TIME, sqlTimestampAttrDefault TIMESTAMP, stringAttrDefault VARCHAR(255), utilCalendarAttrDefault DATE, utilDateAttrDefault DATE, PRIMARY KEY (id));
CREATE TABLE DatatypeSupTestEntity (ID INTEGER NOT NULL, BIGDECIMALATTRDEFAULT DECIMAL(38), BIGINTEGERATTRDEFAULT BIGINT, BOOLEANATTRDEFAULT BOOLEAN, BOOLEANWRAPPERATTRDEFAULT BOOLEAN, BYTEARRAYATTRDEFAULT BYTEA, BYTEATTRDEFAULT SMALLINT, BYTEWRAPPERARRAYATTRDEFAULT BYTEA, BYTEWRAPPERATTRDEFAULT SMALLINT, CHARARRAYATTRDEFAULT TEXT, CHARATTRDEFAULT CHAR(1), CHARWRAPPERARRAYATTRDEFAULT TEXT, CHARACTERWRAPPERATTRDEFAULT CHAR(1), DOUBLEATTRDEFAULT FLOAT, DOUBLEWRAPPERATTRDEFAULT FLOAT, ENUMERATION INTEGER, FLOATATTRDEFAULT FLOAT, FLOATWRAPPERATTRDEFAULT FLOAT, INTATTRDEFAULT INTEGER, INTEGERWRAPPERATTRDEFAULT INTEGER, LONGATTRDEFAULT BIGINT, LONGWRAPPERATTRDEFAULT BIGINT, SERIALIZABLECLASS BYTEA, SHORTATTRDEFAULT SMALLINT, SHORTWRAPPERATTRDEFAULT SMALLINT, SQLDATEATTRDEFAULT DATE, SQLTIMEATTRDEFAULT TIME, SQLTIMESTAMPATTRDEFAULT TIMESTAMP, STRINGATTRDEFAULT VARCHAR(255), UTILCALENDARATTRDEFAULT DATE, UTILDATEATTRDEFAULT DATE, PRIMARY KEY (ID));

CREATE TABLE EmbeddableIdEntity (country VARCHAR(255) NOT NULL, id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (country, id));

#CREATE TABLE EmbeddedObjectAOEntity (id INTEGER NOT NULL, localIntVal INTEGER, localStrVal VARCHAR(255), booleanVal BOOL, byteVal SMALLINT, charVal INTEGER, doubleVal DOUBLE PRECISION, floatVal FLOAT4, intValCol INTEGER, longValCol BIGINT, shortVal SMALLINT, stringVal VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE EMBEDDEDOBJECTAOENTITY (ID INTEGER NOT NULL, LOCALINTVAL INTEGER, LOCALSTRVAL VARCHAR(255), BOOLEANVAL BOOLEAN, BYTEVAL SMALLINT, CHARVAL CHAR(1), DOUBLEVAL FLOAT, FLOATVAL FLOAT, intValCol INTEGER, longValCol BIGINT, SHORTVAL SMALLINT, STRINGVAL VARCHAR(255), PRIMARY KEY (ID));

#CREATE TABLE EmbeddedObjectEntity (id INTEGER NOT NULL, localIntVal INTEGER, localStrVal VARCHAR(255), booleanVal BOOL, byteVal SMALLINT, charVal INTEGER, doubleVal DOUBLE PRECISION, floatVal FLOAT4, intVal INTEGER, longVal BIGINT, shortVal SMALLINT, stringVal VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE EMBEDDEDOBJECTENTITY (ID INTEGER NOT NULL, LOCALINTVAL INTEGER, LOCALSTRVAL VARCHAR(255), BOOLEANVAL BOOLEAN, BYTEVAL SMALLINT, CHARVAL CHAR(1), DOUBLEVAL FLOAT, FLOATVAL FLOAT, INTVAL INTEGER, LONGVAL BIGINT, SHORTVAL SMALLINT, STRINGVAL VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE IdClassEntity (country VARCHAR(255) NOT NULL, id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (country, id));
CREATE TABLE OPENJPA_SEQUENCES_TABLE (ID VARCHAR(255) NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID SMALLINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
CREATE TABLE PKEntityByte (pkey SMALLINT NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE PKEntityByteWrapper (pkey SMALLINT NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));

#CREATE TABLE PKEntityChar (pkey INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE PKENTITYCHAR (PKEY CHAR(1) NOT NULL, INTVAL INTEGER, PRIMARY KEY (PKEY));

#CREATE TABLE PKEntityCharacterWrapper (pkey INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE PKENTITYCHARACTERWRAPPER (PKEY CHAR(1) NOT NULL, INTVAL INTEGER, PRIMARY KEY (PKEY));

CREATE TABLE PKEntityInt (pkey INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE PKEntityIntWrapper (pkey INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE PKEntityJavaSqlDate (pkey DATE NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE PKEntityJavaUtilDate (pkey DATE NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE PKEntityLong (pkey BIGINT NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE PKEntityLongWrapper (pkey BIGINT NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE PKEntityShort (pkey SMALLINT NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE PKEntityShortWrapper (pkey SMALLINT NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE PKEntityString (pkey VARCHAR(255) NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE PKGenAutoEntity (id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (id));
CREATE TABLE PKGenIdentityEntity (id BIGSERIAL NOT NULL, intVal INTEGER, PRIMARY KEY (id));
CREATE TABLE PKGenTableType1Entity (id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (id));
CREATE TABLE PKGenTableType2Entity (id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (id));
CREATE TABLE PKGenTableType3Entity (id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (id));
CREATE TABLE PKGenTableType4Entity (id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (id));
CREATE TABLE ReadOnlyEntity (id INTEGER NOT NULL, intVal INTEGER, noInsertIntVal INTEGER, noUpdatableIntVal INTEGER, readOnlyIntVal INTEGER, PRIMARY KEY (id));
CREATE TABLE SEC_TABLE1 (id INTEGER, city VARCHAR(255), state VARCHAR(255), street VARCHAR(255), zip VARCHAR(255));
CREATE TABLE SEC_TABLE2AMSC (id INTEGER, city VARCHAR(255), state VARCHAR(255), street VARCHAR(255), zip VARCHAR(255));
CREATE TABLE SEC_TABLEEMB (id INTEGER, city VARCHAR(255), state VARCHAR(255), street VARCHAR(255), zip VARCHAR(255));

#CREATE TABLE SerialDatatypeSupPropTE (id INTEGER NOT NULL, bigDecimalAttrDefault NUMERIC, bigIntegerAttrDefault BIGINT, booleanAttrDefault BOOL, booleanWrapperAttrDefault BOOL, byteArrayAttrDefault BYTEA, byteAttrDefault SMALLINT, byteWrapperArrayAttrDefault BYTEA, byteWrapperAttrDefault SMALLINT, charArrayAttrDefault TEXT, charAttrDefault CHAR, charWrapperArrayAttrDefault TEXT, characterWrapperAttrDefault CHAR, doubleAttrDefault DOUBLE PRECISION, doubleWrapperAttrDefault DOUBLE PRECISION, enumeration SMALLINT, floatAttrDefault FLOAT4, floatWrapperAttrDefault FLOAT4, intAttrDefault INTEGER, integerWrapperAttrDefault INTEGER, longAttrDefault BIGINT, longWrapperAttrDefault BIGINT, serializableClass BYTEA, shortAttrDefault SMALLINT, shortWrapperAttrDefault SMALLINT, sqlDateAttrDefault DATE, sqlTimeAttrDefault TIME, sqlTimestampAttrDefault TIMESTAMP, stringAttrDefault VARCHAR(255), utilCalendarAttrDefault DATE, utilDateAttrDefault DATE, PRIMARY KEY (id));
CREATE TABLE SerialDatatypeSupPropTE (ID INTEGER NOT NULL, BIGDECIMALATTRDEFAULT DECIMAL(38), BIGINTEGERATTRDEFAULT BIGINT, BOOLEANATTRDEFAULT BOOLEAN, BOOLEANWRAPPERATTRDEFAULT BOOLEAN, BYTEARRAYATTRDEFAULT BYTEA, BYTEATTRDEFAULT SMALLINT, BYTEWRAPPERARRAYATTRDEFAULT BYTEA, BYTEWRAPPERATTRDEFAULT SMALLINT, CHARARRAYATTRDEFAULT TEXT, CHARATTRDEFAULT CHAR(1), CHARWRAPPERARRAYATTRDEFAULT TEXT, CHARACTERWRAPPERATTRDEFAULT CHAR(1), DOUBLEATTRDEFAULT FLOAT, DOUBLEWRAPPERATTRDEFAULT FLOAT, ENUMERATION INTEGER, FLOATATTRDEFAULT FLOAT, FLOATWRAPPERATTRDEFAULT FLOAT, INTATTRDEFAULT INTEGER, INTEGERWRAPPERATTRDEFAULT INTEGER, LONGATTRDEFAULT BIGINT, LONGWRAPPERATTRDEFAULT BIGINT, SERIALIZABLECLASS BYTEA, SHORTATTRDEFAULT SMALLINT, SHORTWRAPPERATTRDEFAULT SMALLINT, SQLDATEATTRDEFAULT DATE, SQLTIMEATTRDEFAULT TIME, SQLTIMESTAMPATTRDEFAULT TIMESTAMP, STRINGATTRDEFAULT VARCHAR(255), UTILCALENDARATTRDEFAULT DATE, UTILDATEATTRDEFAULT DATE, PRIMARY KEY (ID));

#CREATE TABLE SerialDatatypeSupTE (id INTEGER NOT NULL, bigDecimalAttrDefault NUMERIC, bigIntegerAttrDefault BIGINT, booleanAttrDefault BOOL, booleanWrapperAttrDefault BOOL, byteArrayAttrDefault BYTEA, byteAttrDefault SMALLINT, byteWrapperArrayAttrDefault BYTEA, byteWrapperAttrDefault SMALLINT, charArrayAttrDefault TEXT, charAttrDefault CHAR, charWrapperArrayAttrDefault TEXT, characterWrapperAttrDefault CHAR, doubleAttrDefault DOUBLE PRECISION, doubleWrapperAttrDefault DOUBLE PRECISION, enumeration SMALLINT, floatAttrDefault FLOAT4, floatWrapperAttrDefault FLOAT4, intAttrDefault INTEGER, integerWrapperAttrDefault INTEGER, longAttrDefault BIGINT, longWrapperAttrDefault BIGINT, serializableClass BYTEA, shortAttrDefault SMALLINT, shortWrapperAttrDefault SMALLINT, sqlDateAttrDefault DATE, sqlTimeAttrDefault TIME, sqlTimestampAttrDefault TIMESTAMP, stringAttrDefault VARCHAR(255), utilCalendarAttrDefault DATE, utilDateAttrDefault DATE, PRIMARY KEY (id));
CREATE TABLE SerialDatatypeSupTE (ID INTEGER NOT NULL, BIGDECIMALATTRDEFAULT DECIMAL(38), BIGINTEGERATTRDEFAULT BIGINT, BOOLEANATTRDEFAULT BOOLEAN, BOOLEANWRAPPERATTRDEFAULT BOOLEAN, BYTEARRAYATTRDEFAULT BYTEA, BYTEATTRDEFAULT SMALLINT, BYTEWRAPPERARRAYATTRDEFAULT BYTEA, BYTEWRAPPERATTRDEFAULT SMALLINT, CHARARRAYATTRDEFAULT TEXT, CHARATTRDEFAULT CHAR(1), CHARWRAPPERARRAYATTRDEFAULT TEXT, CHARACTERWRAPPERATTRDEFAULT CHAR(1), DOUBLEATTRDEFAULT FLOAT, DOUBLEWRAPPERATTRDEFAULT FLOAT, ENUMERATION INTEGER, FLOATATTRDEFAULT FLOAT, FLOATWRAPPERATTRDEFAULT FLOAT, INTATTRDEFAULT INTEGER, INTEGERWRAPPERATTRDEFAULT INTEGER, LONGATTRDEFAULT BIGINT, LONGWRAPPERATTRDEFAULT BIGINT, SERIALIZABLECLASS BYTEA, SHORTATTRDEFAULT SMALLINT, SHORTWRAPPERATTRDEFAULT SMALLINT, SQLDATEATTRDEFAULT DATE, SQLTIMEATTRDEFAULT TIME, SQLTIMESTAMPATTRDEFAULT TIMESTAMP, STRINGATTRDEFAULT VARCHAR(255), UTILCALENDARATTRDEFAULT DATE, UTILDATEATTRDEFAULT DATE, PRIMARY KEY (ID));


#CREATE TABLE TableIDGen4Table (GEN_NAME VARCHAR(255) NOT NULL, GEN_VAL BIGINT, PRIMARY KEY (GEN_NAME));
#CREATE TABLE TableIDGenTable (GEN_NAME VARCHAR(255) NOT NULL, GEN_VAL BIGINT, PRIMARY KEY (GEN_NAME));
CREATE TABLE VersionedIntEntity (id INTEGER NOT NULL, intVal INTEGER, stringVal VARCHAR(255), version INTEGER, PRIMARY KEY (id));
CREATE TABLE VersionedIntWrapperEntity (id INTEGER NOT NULL, intVal INTEGER, stringVal VARCHAR(255), version INTEGER, PRIMARY KEY (id));
CREATE TABLE VersionedLongEntity (id INTEGER NOT NULL, intVal INTEGER, stringVal VARCHAR(255), version BIGINT, PRIMARY KEY (id));
CREATE TABLE VersionedLongWrapperEntity (id INTEGER NOT NULL, intVal INTEGER, stringVal VARCHAR(255), version BIGINT, PRIMARY KEY (id));
CREATE TABLE VersionedShortEntity (id INTEGER NOT NULL, intVal INTEGER, stringVal VARCHAR(255), version SMALLINT, PRIMARY KEY (id));
CREATE TABLE VersionedShortWrapperEntity (id INTEGER NOT NULL, intVal INTEGER, stringVal VARCHAR(255), version SMALLINT, PRIMARY KEY (id));
CREATE TABLE VersionedSqlTimestampEntity (id INTEGER NOT NULL, intVal INTEGER, stringVal VARCHAR(255), version TIMESTAMP, PRIMARY KEY (id));
CREATE TABLE XMLDatatypeSupPropTestEntity (id INTEGER NOT NULL, bigDecimalAttrDefault NUMERIC, bigIntegerAttrDefault BIGINT, booleanAttrDefault BOOL, booleanWrapperAttrDefault BOOL, byteArrayAttrDefault BYTEA, byteAttrDefault SMALLINT, byteWrapperArrayAttrDefault BYTEA, byteWrapperAttrDefault SMALLINT, charArrayAttrDefault VARCHAR(255), charAttrDefault CHAR, charWrapperArrayAttrDefault VARCHAR(255), characterWrapperAttrDefault CHAR, doubleAttrDefault DOUBLE PRECISION, doubleWrapperAttrDefault DOUBLE PRECISION, enumeration SMALLINT, floatAttrDefault FLOAT4, floatWrapperAttrDefault FLOAT4, intAttrDefault INTEGER, integerWrapperAttrDefault INTEGER, longAttrDefault BIGINT, longWrapperAttrDefault BIGINT, serializableClass BYTEA, shortAttrDefault SMALLINT, shortWrapperAttrDefault SMALLINT, sqlDateAttrDefault DATE, sqlTimeAttrDefault TIME, sqlTimestampAttrDefault TIMESTAMP, stringAttrDefault VARCHAR(255), utilCalendarAttrDefault DATE, utilDateAttrDefault DATE, PRIMARY KEY (id));
CREATE TABLE XMLDatatypeSupTestEntity (id INTEGER NOT NULL, bigDecimalAttrDefault NUMERIC, bigIntegerAttrDefault BIGINT, booleanAttrDefault BOOL, booleanWrapperAttrDefault BOOL, byteArrayAttrDefault BYTEA, byteAttrDefault SMALLINT, byteWrapperArrayAttrDefault BYTEA, byteWrapperAttrDefault SMALLINT, charArrayAttrDefault VARCHAR(255), charAttrDefault CHAR, charWrapperArrayAttrDefault VARCHAR(255), characterWrapperAttrDefault CHAR, doubleAttrDefault DOUBLE PRECISION, doubleWrapperAttrDefault DOUBLE PRECISION, enumeration SMALLINT, floatAttrDefault FLOAT4, floatWrapperAttrDefault FLOAT4, intAttrDefault INTEGER, integerWrapperAttrDefault INTEGER, longAttrDefault BIGINT, longWrapperAttrDefault BIGINT, serializableClass BYTEA, shortAttrDefault SMALLINT, shortWrapperAttrDefault SMALLINT, sqlDateAttrDefault DATE, sqlTimeAttrDefault TIME, sqlTimestampAttrDefault TIMESTAMP, stringAttrDefault VARCHAR(255), utilCalendarAttrDefault DATE, utilDateAttrDefault DATE, PRIMARY KEY (id));
CREATE TABLE XMLEmbeddableIdEntity (country VARCHAR(255) NOT NULL, id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (country, id));

#CREATE TABLE XMLEmbeddedObjectAOEntity (id INTEGER NOT NULL, localIntVal INTEGER, localStrVal VARCHAR(255), booleanVal BOOL, byteVal SMALLINT, charVal INTEGER, doubleVal DOUBLE PRECISION, floatVal FLOAT4, intValCol INTEGER, longValCol BIGINT, shortVal SMALLINT, stringVal VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE XMLEmbeddedObjectAOEntity (ID INTEGER NOT NULL, LOCALINTVAL INTEGER, LOCALSTRVAL VARCHAR(255), BOOLEANVAL BOOLEAN, BYTEVAL SMALLINT, CHARVAL CHAR(1), DOUBLEVAL FLOAT, FLOATVAL FLOAT, intValCol INTEGER, longValCol BIGINT, SHORTVAL SMALLINT, STRINGVAL VARCHAR(255), PRIMARY KEY (ID));

#CREATE TABLE XMLEmbeddedObjectEntity (id INTEGER NOT NULL, localIntVal INTEGER, localStrVal VARCHAR(255), booleanVal BOOL, byteVal SMALLINT, charVal INTEGER, doubleVal DOUBLE PRECISION, floatVal FLOAT4, intVal INTEGER, longVal BIGINT, shortVal SMALLINT, stringVal VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE XMLEmbeddedObjectEntity (ID INTEGER NOT NULL, LOCALINTVAL INTEGER, LOCALSTRVAL VARCHAR(255), BOOLEANVAL BOOLEAN, BYTEVAL SMALLINT, CHARVAL CHAR(1), DOUBLEVAL FLOAT, FLOATVAL FLOAT, INTVAL INTEGER, LONGVAL BIGINT, SHORTVAL SMALLINT, STRINGVAL VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE XMLEmbedMultiTableEnt (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE XMLIdClassEntity (country VARCHAR(255) NOT NULL, id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (country, id));
CREATE TABLE XMLMSCMultiTableEnt (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE XMLMultiTableEnt (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE XMLPKEntityByte (pkey SMALLINT NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE XMLPKEntityByteWrapper (pkey SMALLINT NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));

#CREATE TABLE XMLPKEntityChar (pkey INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE XMLPKENTITYCHAR (PKEY CHAR(1) NOT NULL, INTVAL INTEGER, PRIMARY KEY (PKEY));

#CREATE TABLE XMLPKEntityCharacterWrapper (pkey INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE XMLPKEntityCharacterWrapper (PKEY CHAR(1) NOT NULL, INTVAL INTEGER, PRIMARY KEY (PKEY));

CREATE TABLE XMLPKEntityInt (pkey INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE XMLPKEntityIntWrapper (pkey INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE XMLPKEntityJavaSqlDate (pkey DATE NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE XMLPKEntityJavaUtilDate (pkey DATE NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE XMLPKEntityLong (pkey BIGINT NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE XMLPKEntityLongWrapper (pkey BIGINT NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE XMLPKEntityShort (pkey SMALLINT NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE XMLPKEntityShortWrapper (pkey SMALLINT NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE XMLPKEntityString (pkey VARCHAR(255) NOT NULL, intVal INTEGER, PRIMARY KEY (pkey));
CREATE TABLE XMLPKGenAutoEntity (id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (id));
CREATE TABLE XMLPKGenIdentityEntity (id BIGSERIAL NOT NULL, intVal INTEGER, PRIMARY KEY (id));
CREATE TABLE XMLPKGenTableType1Entity (id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (id));
CREATE TABLE XMLPKGenTableType2Entity (id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (id));
CREATE TABLE XMLPKGenTableType3Entity (id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (id));
CREATE TABLE XMLPKGenTableType4Entity (id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (id));
CREATE TABLE XMLReadOnlyEntity (id INTEGER NOT NULL, intVal INTEGER, noInsertIntVal INTEGER, noUpdatableIntVal INTEGER, readOnlyIntVal INTEGER, PRIMARY KEY (id));

#CREATE TABLE XMLSerialDatatypeSupPropTE (id INTEGER NOT NULL, bigDecimalAttrDefault NUMERIC, bigIntegerAttrDefault BIGINT, booleanAttrDefault BOOL, booleanWrapperAttrDefault BOOL, byteArrayAttrDefault BYTEA, byteAttrDefault SMALLINT, byteWrapperArrayAttrDefault BYTEA, byteWrapperAttrDefault SMALLINT, charArrayAttrDefault VARCHAR(255), charAttrDefault CHAR, charWrapperArrayAttrDefault VARCHAR(255), characterWrapperAttrDefault CHAR, doubleAttrDefault DOUBLE PRECISION, doubleWrapperAttrDefault DOUBLE PRECISION, enumeration SMALLINT, floatAttrDefault FLOAT4, floatWrapperAttrDefault FLOAT4, intAttrDefault INTEGER, integerWrapperAttrDefault INTEGER, longAttrDefault BIGINT, longWrapperAttrDefault BIGINT, serializableClass BYTEA, shortAttrDefault SMALLINT, shortWrapperAttrDefault SMALLINT, sqlDateAttrDefault DATE, sqlTimeAttrDefault TIME, sqlTimestampAttrDefault TIMESTAMP, stringAttrDefault VARCHAR(255), utilCalendarAttrDefault DATE, utilDateAttrDefault DATE, PRIMARY KEY (id));
CREATE TABLE XMLSerialDatatypeSupPropTE (ID INTEGER NOT NULL, BIGDECIMALATTRDEFAULT DECIMAL(38), BIGINTEGERATTRDEFAULT BIGINT, BOOLEANATTRDEFAULT BOOLEAN, BOOLEANWRAPPERATTRDEFAULT BOOLEAN, BYTEARRAYATTRDEFAULT BYTEA, BYTEATTRDEFAULT SMALLINT, BYTEWRAPPERARRAYATTRDEFAULT BYTEA, BYTEWRAPPERATTRDEFAULT SMALLINT, CHARARRAYATTRDEFAULT TEXT, CHARATTRDEFAULT CHAR(1), CHARWRAPPERARRAYATTRDEFAULT TEXT, CHARACTERWRAPPERATTRDEFAULT CHAR(1), DOUBLEATTRDEFAULT FLOAT, DOUBLEWRAPPERATTRDEFAULT FLOAT, ENUMERATION INTEGER, FLOATATTRDEFAULT FLOAT, FLOATWRAPPERATTRDEFAULT FLOAT, INTATTRDEFAULT INTEGER, INTEGERWRAPPERATTRDEFAULT INTEGER, LONGATTRDEFAULT BIGINT, LONGWRAPPERATTRDEFAULT BIGINT, SERIALIZABLECLASS BYTEA, SHORTATTRDEFAULT SMALLINT, SHORTWRAPPERATTRDEFAULT SMALLINT, SQLDATEATTRDEFAULT DATE, SQLTIMEATTRDEFAULT TIME, SQLTIMESTAMPATTRDEFAULT TIMESTAMP, STRINGATTRDEFAULT VARCHAR(255), UTILCALENDARATTRDEFAULT DATE, UTILDATEATTRDEFAULT DATE, PRIMARY KEY (ID));

#CREATE TABLE XMLSerialDatatypeSupTE (id INTEGER NOT NULL, bigDecimalAttrDefault NUMERIC, bigIntegerAttrDefault BIGINT, booleanAttrDefault BOOL, booleanWrapperAttrDefault BOOL, byteArrayAttrDefault BYTEA, byteAttrDefault SMALLINT, byteWrapperArrayAttrDefault BYTEA, byteWrapperAttrDefault SMALLINT, charArrayAttrDefault VARCHAR(255), charAttrDefault CHAR, charWrapperArrayAttrDefault VARCHAR(255), characterWrapperAttrDefault CHAR, doubleAttrDefault DOUBLE PRECISION, doubleWrapperAttrDefault DOUBLE PRECISION, enumeration SMALLINT, floatAttrDefault FLOAT4, floatWrapperAttrDefault FLOAT4, intAttrDefault INTEGER, integerWrapperAttrDefault INTEGER, longAttrDefault BIGINT, longWrapperAttrDefault BIGINT, serializableClass BYTEA, shortAttrDefault SMALLINT, shortWrapperAttrDefault SMALLINT, sqlDateAttrDefault DATE, sqlTimeAttrDefault TIME, sqlTimestampAttrDefault TIMESTAMP, stringAttrDefault VARCHAR(255), utilCalendarAttrDefault DATE, utilDateAttrDefault DATE, PRIMARY KEY (id));
CREATE TABLE XMLSerialDatatypeSupTE (ID INTEGER NOT NULL, BIGDECIMALATTRDEFAULT DECIMAL(38), BIGINTEGERATTRDEFAULT BIGINT, BOOLEANATTRDEFAULT BOOLEAN, BOOLEANWRAPPERATTRDEFAULT BOOLEAN, BYTEARRAYATTRDEFAULT BYTEA, BYTEATTRDEFAULT SMALLINT, BYTEWRAPPERARRAYATTRDEFAULT BYTEA, BYTEWRAPPERATTRDEFAULT SMALLINT, CHARARRAYATTRDEFAULT TEXT, CHARATTRDEFAULT CHAR(1), CHARWRAPPERARRAYATTRDEFAULT TEXT, CHARACTERWRAPPERATTRDEFAULT CHAR(1), DOUBLEATTRDEFAULT FLOAT, DOUBLEWRAPPERATTRDEFAULT FLOAT, ENUMERATION INTEGER, FLOATATTRDEFAULT FLOAT, FLOATWRAPPERATTRDEFAULT FLOAT, INTATTRDEFAULT INTEGER, INTEGERWRAPPERATTRDEFAULT INTEGER, LONGATTRDEFAULT BIGINT, LONGWRAPPERATTRDEFAULT BIGINT, SERIALIZABLECLASS BYTEA, SHORTATTRDEFAULT SMALLINT, SHORTWRAPPERATTRDEFAULT SMALLINT, SQLDATEATTRDEFAULT DATE, SQLTIMEATTRDEFAULT TIME, SQLTIMESTAMPATTRDEFAULT TIMESTAMP, STRINGATTRDEFAULT VARCHAR(255), UTILCALENDARATTRDEFAULT DATE, UTILDATEATTRDEFAULT DATE, PRIMARY KEY (ID));

#CREATE TABLE XMLTableIDGen4Table (GEN_NAME VARCHAR(255) NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (GEN_NAME));
#CREATE TABLE XMLTableIDGenTable (GEN_NAME VARCHAR(255) NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (GEN_NAME));
CREATE TABLE XMLVersionedIntEntity (id INTEGER NOT NULL, intVal INTEGER, stringVal VARCHAR(255), version INTEGER, PRIMARY KEY (id));
CREATE TABLE XMLVersionedIntWrapperEntity (id INTEGER NOT NULL, intVal INTEGER, stringVal VARCHAR(255), version INTEGER, PRIMARY KEY (id));
CREATE TABLE XMLVersionedLongEntity (id INTEGER NOT NULL, intVal INTEGER, stringVal VARCHAR(255), version BIGINT, PRIMARY KEY (id));
CREATE TABLE XMLVersionedLongWrapperEnt (id INTEGER NOT NULL, intVal INTEGER, stringVal VARCHAR(255), version BIGINT, PRIMARY KEY (id));
CREATE TABLE XMLVersionedShortEntity (id INTEGER NOT NULL, intVal INTEGER, stringVal VARCHAR(255), version SMALLINT, PRIMARY KEY (id));
CREATE TABLE XMLVersionedShortWrapperEnt (id INTEGER NOT NULL, intVal INTEGER, stringVal VARCHAR(255), version SMALLINT, PRIMARY KEY (id));
CREATE TABLE XMLVersionedSqlTimestampEnt (id INTEGER NOT NULL, intVal INTEGER, stringVal VARCHAR(255), version TIMESTAMP, PRIMARY KEY (id));
CREATE TABLE XSEC_TABLE1 (id INTEGER, city VARCHAR(255), state VARCHAR(255), street VARCHAR(255), zip VARCHAR(255));
CREATE TABLE XSEC_TABLE2AMSC (id INTEGER, city VARCHAR(255), state VARCHAR(255), street VARCHAR(255), zip VARCHAR(255));
CREATE TABLE XSEC_TABLEEMB (id INTEGER, city VARCHAR(255), state VARCHAR(255), street VARCHAR(255), zip VARCHAR(255));

create schema jpaschema;

#CREATE TABLE jpaschema.ACfgFldEn (id INTEGER NOT NULL, floatValColumnPrecision NUMERIC, floatValColumnScale NUMERIC, intValColName INTEGER, notNullable BYTEA NOT NULL, stringValColumnLength VARCHAR(12), stringValEager VARCHAR(255), stringValLazy VARCHAR(255), stringValOptional VARCHAR(255), uniqueConstraintString VARCHAR(255) NOT NULL, uniqueString VARCHAR(255) NOT NULL, PRIMARY KEY (id), CONSTRAINT U_CFGFLDN_UNIQUESTRING UNIQUE (uniqueString), CONSTRAINT U_CFGFLDN_UNIQUECONSTRAINTSTRING UNIQUE (uniqueConstraintString));
CREATE TABLE jpaschema.ACfgFldEn (ID INTEGER NOT NULL, FLOATVALCOLUMNPRECISION FLOAT, FLOATVALCOLUMNSCALE FLOAT, intValColName INTEGER, NOTNULLABLE BYTEA NOT NULL, STRINGVALCOLUMNLENGTH VARCHAR(12), STRINGVALEAGER VARCHAR(255), STRINGVALLAZY VARCHAR(255), STRINGVALOPTIONAL VARCHAR(255), UNIQUECONSTRAINTSTRING VARCHAR(255) NOT NULL, UNIQUESTRING VARCHAR(255) NOT NULL UNIQUE, PRIMARY KEY (ID));
ALTER TABLE jpaschema.ACfgFldEn ADD CONSTRAINT UNQ_ACfgFldEn_0 UNIQUE (UNIQUECONSTRAINTSTRING);

CREATE TABLE jpaschema.AltColumnTable (ATTRCONFIGFIELDENTITY_ID INTEGER, id INTEGER, intValCol INTEGER);
#CREATE TABLE jpaschema.TableIDGen4Table (GEN_NAME VARCHAR(255) NOT NULL, GEN_VAL BIGINT, PRIMARY KEY (GEN_NAME));
#CREATE TABLE jpaschema.TableIDGenTable (GEN_NAME VARCHAR(255) NOT NULL, GEN_VAL BIGINT, PRIMARY KEY (GEN_NAME));
CREATE TABLE jpaschema.XACfgFldE (id INTEGER NOT NULL, floatValColumnPrecision NUMERIC, floatValColumnScale NUMERIC, intValColName INTEGER, notNullable BYTEA NOT NULL, stringValColumnLength VARCHAR(12), stringValEager VARCHAR(255), stringValLazy VARCHAR(255), stringValOptional VARCHAR(255), uniqueConstraintString VARCHAR(255) NOT NULL, uniqueString VARCHAR(255) NOT NULL, PRIMARY KEY (id), CONSTRAINT U_XCFGFLD_UNIQUESTRING UNIQUE (uniqueString), CONSTRAINT U_XCFGFLD_UNIQUECONSTRAINTSTRING UNIQUE (uniqueConstraintString));
CREATE TABLE jpaschema.XAltColumnTable (XMLATTRCONFIGFIELDENTITY_ID INTEGER, id INTEGER, XMLIntValCol INTEGER);
#CREATE TABLE jpaschema.XMLTableIDGen4Table (GEN_NAME VARCHAR(255) NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (GEN_NAME));
#CREATE TABLE jpaschema.XMLTableIDGenTable (GEN_NAME VARCHAR(255) NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (GEN_NAME));

CREATE TABLE jpaschema.OPENJPA_SEQUENCES_TABLE (ID VARCHAR(255) NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
CREATE TABLE jpaschema.OPENJPA_SEQUENCE_TABLE (ID SMALLINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));


CREATE INDEX I_SC_TBL1_ID ON SEC_TABLE1 (id);
CREATE INDEX I_SC_TMSC_ID ON SEC_TABLE2AMSC (id);
CREATE INDEX I_SC_TLMB_ID ON SEC_TABLEEMB (id);
CREATE INDEX I_XSC_BL1_ID ON XSEC_TABLE1 (id);
CREATE INDEX I_XSC_MSC_ID ON XSEC_TABLE2AMSC (id);
CREATE INDEX I_XSC_LMB_ID ON XSEC_TABLEEMB (id);
CREATE INDEX I_LTCLTBL_ATTRCONFIGFIELDENTITY_ID ON jpaschema.AltColumnTable (ATTRCONFIGFIELDENTITY_ID);
CREATE INDEX I_LTCLTBL_XMLATTRCONFIGFIELDENTITY_ID ON jpaschema.XAltColumnTable (XMLATTRCONFIGFIELDENTITY_ID);

CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN_TABLE', 0);
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('TableType2Generator', 0);
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('XMLTableType2Generator', 0);

CREATE TABLE TableIDGen4Table (GEN_NAME VARCHAR(50) NOT NULL, GEN_VAL DECIMAL(38), PRIMARY KEY (GEN_NAME));
CREATE TABLE XMLTableIDGen4Table (GEN_NAME VARCHAR(50) NOT NULL, GEN_VAL DECIMAL(38), PRIMARY KEY (GEN_NAME));
CREATE TABLE TableIDGenTable (GEN_NAME VARCHAR(50) NOT NULL, GEN_VAL DECIMAL(38), PRIMARY KEY (GEN_NAME));
CREATE TABLE XMLTableIDGenTable (GEN_NAME VARCHAR(50) NOT NULL, GEN_VAL DECIMAL(38), PRIMARY KEY (GEN_NAME));

INSERT INTO TableIDGen4Table(GEN_NAME, GEN_VAL) values ('TableType4Generator', 999);
INSERT INTO XMLTableIDGen4Table(GEN_NAME, GEN_VAL) values ('XMLTableType4Generator', 999);
INSERT INTO TableIDGenTable(GEN_NAME, GEN_VAL) values ('TableType3Generator', 0);
INSERT INTO XMLTableIDGenTable(GEN_NAME, GEN_VAL) values ('XMLTableType3Generator', 0);

#INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);
#INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN_TABLE', 0);
#INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('TableType2Generator', 0);
#INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('XMLTableType2Generator', 0);

#INSERT INTO TableIDGenTable(GEN_NAME, GEN_VAL) values ('TableType3Generator', 0);
#INSERT INTO XMLTableIDGenTable(GEN_NAME, GEN_VAL) values ('XMLTableType3Generator', 0);
#INSERT INTO TableIDGen4Table(GEN_NAME, GEN_VAL) values ('TableType4Generator', 0);
#INSERT INTO XMLTableIDGen4Table(GEN_NAME, GEN_VAL) values ('XMLTableType4Generator', 0);
