DELETE FROM jpaschema.ACfgFldEn;
DELETE FROM jpaschema.AltColumnTable;
DELETE FROM jpaschema.XACfgFldE;
DELETE FROM jpaschema.XAltColumnTable;
            
DELETE FROM ${schemaname}.AnnEmbedMultiTableEnt;
DELETE FROM ${schemaname}.AnnMSCMultiTableEnt;
DELETE FROM ${schemaname}.AnnMultiTableEnt;
DELETE FROM ${schemaname}.DatatypeSupPropTestEntity;
DELETE FROM ${schemaname}.DatatypeSupTestEntity;
DELETE FROM ${schemaname}.EmbeddableIdEntity;
DELETE FROM ${schemaname}.EmbeddedObjectAOEntity;
DELETE FROM ${schemaname}.EmbeddedObjectEntity;
DELETE FROM ${schemaname}.IdClassEntity;
DELETE FROM ${schemaname}.OPENJPA_SEQUENCES_TABLE;
DELETE FROM ${schemaname}.OPENJPA_SEQUENCE_TABLE;
DELETE FROM ${schemaname}.PKEntityByte;
DELETE FROM ${schemaname}.PKEntityByteWrapper;
DELETE FROM ${schemaname}.PKEntityChar;
DELETE FROM ${schemaname}.PKEntityCharacterWrapper;
DELETE FROM ${schemaname}.PKEntityInt;
DELETE FROM ${schemaname}.PKEntityIntWrapper;
DELETE FROM ${schemaname}.PKEntityJavaSqlDate;
DELETE FROM ${schemaname}.PKEntityJavaUtilDate;
DELETE FROM ${schemaname}.PKEntityLong;
DELETE FROM ${schemaname}.PKEntityLongWrapper;
DELETE FROM ${schemaname}.PKEntityShort;
DELETE FROM ${schemaname}.PKEntityShortWrapper;
DELETE FROM ${schemaname}.PKEntityString;
DELETE FROM ${schemaname}.PKGenAutoEntity;
DELETE FROM ${schemaname}.PKGenIdentityEntity;
DELETE FROM ${schemaname}.PKGenSequenceType1Entity;
DELETE FROM ${schemaname}.PKGenSequenceType2Entity;
DELETE FROM ${schemaname}.PKGenTableType1Entity;
DELETE FROM ${schemaname}.PKGenTableType2Entity;
DELETE FROM ${schemaname}.PKGenTableType3Entity;
DELETE FROM ${schemaname}.PKGenTableType4Entity;
DELETE FROM ${schemaname}.ReadOnlyEntity;
DELETE FROM ${schemaname}.SEC_TABLE1;
DELETE FROM ${schemaname}.SEC_TABLE2AMSC;
DELETE FROM ${schemaname}.SEC_TABLEEMB;
DELETE FROM ${schemaname}.SerialDatatypeSupPropTE;
DELETE FROM ${schemaname}.SerialDatatypeSupTE;
DELETE FROM ${schemaname}.TableIDGen4Table;
DELETE FROM ${schemaname}.TableIDGenTable;
DELETE FROM ${schemaname}.VersionedIntEntity;
DELETE FROM ${schemaname}.VersionedIntWrapperEntity;
DELETE FROM ${schemaname}.VersionedLongEntity;
DELETE FROM ${schemaname}.VersionedLongWrapperEntity;
DELETE FROM ${schemaname}.VersionedShortEntity;
DELETE FROM ${schemaname}.VersionedShortWrapperEntity;
DELETE FROM ${schemaname}.VersionedSqlTimestampEntity;
DELETE FROM ${schemaname}.XMLDatatypeSupPropTestEntity;
DELETE FROM ${schemaname}.XMLDatatypeSupTestEntity;
DELETE FROM ${schemaname}.XMLEmbeddableIdEntity;
DELETE FROM ${schemaname}.XMLEmbeddedObjectAOEntity;
DELETE FROM ${schemaname}.XMLEmbeddedObjectEntity;
DELETE FROM ${schemaname}.XMLEmbedMultiTableEnt;
DELETE FROM ${schemaname}.XMLIdClassEntity;
DELETE FROM ${schemaname}.XMLMSCMultiTableEnt;
DELETE FROM ${schemaname}.XMLMultiTableEnt;
DELETE FROM ${schemaname}.XMLPKEntityByte;
DELETE FROM ${schemaname}.XMLPKEntityByteWrapper;
DELETE FROM ${schemaname}.XMLPKEntityChar;
DELETE FROM ${schemaname}.XMLPKEntityCharacterWrapper;
DELETE FROM ${schemaname}.XMLPKEntityInt;
DELETE FROM ${schemaname}.XMLPKEntityIntWrapper;
DELETE FROM ${schemaname}.XMLPKEntityJavaSqlDate;
DELETE FROM ${schemaname}.XMLPKEntityJavaUtilDate;
DELETE FROM ${schemaname}.XMLPKEntityLong;
DELETE FROM ${schemaname}.XMLPKEntityLongWrapper;
DELETE FROM ${schemaname}.XMLPKEntityShort;
DELETE FROM ${schemaname}.XMLPKEntityShortWrapper;
DELETE FROM ${schemaname}.XMLPKEntityString;
DELETE FROM ${schemaname}.XMLPKGenAutoEntity;
DELETE FROM ${schemaname}.XMLPKGenIdentityEntity;
DELETE FROM ${schemaname}.XMLPKGenSequenceType1Entity;
DELETE FROM ${schemaname}.XMLPKGenSequenceType2Entity;
DELETE FROM ${schemaname}.XMLPKGenTableType1Entity;
DELETE FROM ${schemaname}.XMLPKGenTableType2Entity;
DELETE FROM ${schemaname}.XMLPKGenTableType3Entity;
DELETE FROM ${schemaname}.XMLPKGenTableType4Entity;
DELETE FROM ${schemaname}.XMLReadOnlyEntity;
DELETE FROM ${schemaname}.XMLSerialDatatypeSupPropTE;
DELETE FROM ${schemaname}.XMLSerialDatatypeSupTE;
DELETE FROM ${schemaname}.XMLTableIDGen4Table;
DELETE FROM ${schemaname}.XMLTableIDGenTable;
DELETE FROM ${schemaname}.XMLVersionedIntEntity;
DELETE FROM ${schemaname}.XMLVersionedIntWrapperEntity;
DELETE FROM ${schemaname}.XMLVersionedLongEntity;
DELETE FROM ${schemaname}.XMLVersionedLongWrapperEnt;
DELETE FROM ${schemaname}.XMLVersionedShortEntity;
DELETE FROM ${schemaname}.XMLVersionedShortWrapperEnt;
DELETE FROM ${schemaname}.XMLVersionedSqlTimestampEnt;
DELETE FROM ${schemaname}.XSEC_TABLE1;
DELETE FROM ${schemaname}.XSEC_TABLE2AMSC;
DELETE FROM ${schemaname}.XSEC_TABLEEMB;
            
              
DELETE FROM ${schemaname}.SEQUENCE;
DELETE FROM ${schemaname}.OPENJPA_SEQUENCES_TABLE;
DELETE FROM ${schemaname}.OPENJPA_SEQUENCE_TABLE;
DELETE FROM ${schemaname}.TableIDGenTable;
DELETE FROM ${schemaname}.TableIDGen4Table;
DELETE FROM ${schemaname}.XMLTableIDGen4Table;
DELETE FROM ${schemaname}.XMLTableIDGenTable;
            
INSERT INTO  ${schemaname}.SEQUENCE (SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN_SEQUENCE', 0);
INSERT INTO  ${schemaname}.SEQUENCE (SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);
INSERT INTO  ${schemaname}.SEQUENCE (SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN_TABLE', 0);
INSERT INTO  ${schemaname}.SEQUENCE (SEQ_NAME, SEQ_COUNT) values ('TableType2Generator', 0);
INSERT INTO  ${schemaname}.SEQUENCE (SEQ_NAME, SEQ_COUNT) values ('XMLTableType2Generator', 0);

INSERT INTO  ${schemaname}.TableIDGenTable  (GEN_NAME, GEN_VAL) values ('TableType3Generator', 0);
INSERT INTO  ${schemaname}.TableIDGen4Table (GEN_NAME, GEN_VAL) values ('TableType4Generator', 0);

INSERT INTO  ${schemaname}.XMLTableIDGenTable  (GEN_NAME, GEN_VAL) values ('XMLTableType3Generator', 0);
INSERT INTO  ${schemaname}.XMLTableIDGen4Table (GEN_NAME, GEN_VAL) values ('XMLTableType4Generator', 0);
