// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProducerStore.proto

package com.ibm.test.g3store.grpc;

public final class AppProducerProto {
  private AppProducerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_g3store_grpc_AppResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_g3store_grpc_AppResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_g3store_grpc_AppRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_g3store_grpc_AppRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_g3store_grpc_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_g3store_grpc_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_g3store_grpc_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_g3store_grpc_DeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_g3store_grpc_MultiCreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_g3store_grpc_MultiCreateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ProducerStore.proto\022\021test.g3store.grpc" +
      "\032\013Store.proto\032\033google/protobuf/empty.pro" +
      "to\"\031\n\013AppResponse\022\n\n\002id\030\001 \001(\t\"+\n\nAppRequ" +
      "est\022\035\n\tretailApp\030\001 \001(\0132\n.RetailApp\" \n\rDe" +
      "leteRequest\022\017\n\007appName\030\001 \001(\t\" \n\016DeleteRe" +
      "sponse\022\016\n\006result\030\001 \001(\t\"%\n\023MultiCreateRes" +
      "ponse\022\016\n\006result\030\001 \001(\t2\337\002\n\022AppProducerSer" +
      "vice\022L\n\tcreateApp\022\035.test.g3store.grpc.Ap" +
      "pRequest\032\036.test.g3store.grpc.AppResponse" +
      "\"\000\022R\n\tdeleteApp\022 .test.g3store.grpc.Dele" +
      "teRequest\032!.test.g3store.grpc.DeleteResp" +
      "onse\"\000\022N\n\rdeleteAllApps\022\026.google.protobu" +
      "f.Empty\032!.test.g3store.grpc.DeleteRespon" +
      "se\"\0000\001\022W\n\ncreateApps\022\035.test.g3store.grpc" +
      ".AppRequest\032&.test.g3store.grpc.MultiCre" +
      "ateResponse\"\000(\001B/\n\031com.ibm.test.g3store." +
      "grpcB\020AppProducerProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ibm.test.g3store.grpc.StoreProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_test_g3store_grpc_AppResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_g3store_grpc_AppResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_g3store_grpc_AppResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_test_g3store_grpc_AppRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_test_g3store_grpc_AppRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_g3store_grpc_AppRequest_descriptor,
        new java.lang.String[] { "RetailApp", });
    internal_static_test_g3store_grpc_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_test_g3store_grpc_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_g3store_grpc_DeleteRequest_descriptor,
        new java.lang.String[] { "AppName", });
    internal_static_test_g3store_grpc_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_test_g3store_grpc_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_g3store_grpc_DeleteResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_test_g3store_grpc_MultiCreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_test_g3store_grpc_MultiCreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_g3store_grpc_MultiCreateResponse_descriptor,
        new java.lang.String[] { "Result", });
    com.ibm.test.g3store.grpc.StoreProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
