// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Store.proto

package com.ibm.test.g3store.grpc;

public interface CreatorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Creator)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string companyName = 1;</code>
   * @return The companyName.
   */
  java.lang.String getCompanyName();
  /**
   * <code>string companyName = 1;</code>
   * @return The bytes for companyName.
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
