// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Store.proto

package com.ibm.test.g3store.grpc;

public interface PurchaseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PurchaseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.PurchaseType purchaseType = 2;</code>
   * @return The enum numeric value on the wire for purchaseType.
   */
  int getPurchaseTypeValue();
  /**
   * <code>.PurchaseType purchaseType = 2;</code>
   * @return The purchaseType.
   */
  com.ibm.test.g3store.grpc.PurchaseType getPurchaseType();
}
