type: pipeline_definition
product: Liberty
name: Open Liberty Delivery Requirements Verification
description: "Examines Open Liberty code changes for delivery standards compliance"
triggers:
- type: manual
  description: "Examines Open Liberty code changes for delivery standards compliance. Not a replacement for the Open Liberty Personal Build."
  triggerName: "libby"
  triggerRank: 50
  groups: ["LibertyDev"]
  propertyDefinitions:
    - name: githubPRNumber
      isRequired: true
      description: "PR number to perform delivery requirement verification against e.g. 30188"

steps:
- stepName: PR Changes
  workType: PRChangesDetection
  timeoutInMinutes: 30
  properties:
    githubPRApi: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${githubPRNumber}"

- stepGroup: Copyright Header Check
  properties:
    githubPRApi: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${githubPRNumber}"
  includeSteps:
    - file: steps/checks/copyrightHeaderCheck.yml

- stepGroup: Prohibited Terms Check
  properties:
    githubPRApi: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${githubPRNumber}"
  includeSteps:
    - file: steps/checks/prohibitedTermsCheck.yml

- stepGroup: GenAI Assistance Code Check
  properties:
    githubPRApi: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${githubPRNumber}"
  includeSteps:
    - file: steps/checks/genAICodeCheck.yml

- stepGroup: DHE Server Artifacts Check
  properties:
    githubPRApi: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${githubPRNumber}"
  includeSteps:
    - file: steps/checks/dheServerCheck.yml

- stepGroup: Code Checklist Creation
  properties:
    githubPRApi: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${githubPRNumber}"
  includeSteps:
    - file: steps/checks/codeChecklist.yml