type: pipeline_definition
product: Liberty
name: Open Liberty Delivery Requirements Verification
description: "Examines Open Liberty code changes for delivery standards compliance"
triggers:
- type: manual
  description: "Examines Open Liberty code changes for delivery standards compliance. Not a replacement for the Open Liberty Personal Build."
  triggerName: "libby"
  triggerRank: 50
  groups: ["LibertyDev"]
  propertyDefinitions:
    - name: githubPRNumber
      isRequired: true
      description: "PR number to perform delivery requirement verification against e.g. 30188"
    - name: githubPRBranch
      isRequired: false
      description: "Head branch of specified PR"
    - name: githubPRBranchOwner
      isRequired: false
      description: "PR head branch owner"

steps:
- stepName: Copyright Header Check
  workType: Jenkins
  projectName: copyrightHeaderCheck
  timeoutInMinutes: 1440
  properties:
    githubPRApi: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${githubPRNumber}"

- stepName: Detect Secrets Scan
  conditionalRun:
    - type: ifSet
      value: ${githubPRBranch}
    - type: ifSet
      value: ${githubPRBranchOwner}
  workType: Jenkins
  projectName: detectSecretsScan
  timeoutInMinutes: 1440
  properties:
    repoToScan: "open-liberty"
    repoSSHURL: "git@github.com:${githubPRBranchOwner}/open-liberty.git"
    branchToScan: ${githubPRBranch}
    githubPRApi: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${githubPRNumber}"

- stepName: Prohibited Terms Check
  workType: Jenkins
  projectName: prohibitedTermsCheck
  timeoutInMinutes: 1440
  properties:
    githubPRApi: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${githubPRNumber}"

- stepName: GenAI Assistance Code Check
  workType: Jenkins
  projectName: genAICodeCheck
  timeoutInMinutes: 1440
  properties:
    githubPRApi: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${githubPRNumber}"

- stepName: DHE Server Artifacts Check
  workType: Jenkins
  projectName: dheServerCheck
  timeoutInMinutes: 1440
  properties:
    githubPRApi: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${githubPRNumber}"
