type: pipeline_definition
product: Liberty
name: Open Liberty Detect Secrets Scan
description: "Runs the Detect Secrets tool on Open Liberty to find unaudited secrets"
triggers:
- type: github
  description: "Runs the Detect Secrets tool on Open Liberty to find unaudited secrets"
  triggerName: "detect-secrets"
  triggerRank: 50
  groups: ["LibertyDev"]
  keyword: "!detect-secrets"
  aliasKeywords:
    - "#detect-secrets"
    - "!run-detect-secrets"
    - "#run-detect-secrets"

- type: manual
  triggerName: "detect-secrets-manual"
  description: "Manually runs the Detect Secrets tool on Open Liberty to find unaudited secrets"
  triggerRank: 50
  groups: ["LibertyDev"]
  propertyDefinitions:
    - name: github_pr_user
      isRequired: true
      defaultValue: "Name of Open Liberty user or organization for checkout."
      description: "Name of Open Liberty user or organization for checkout."
    - name: github_pr_branch
      isRequired: true
      defaultValue: "Name of Open Liberty branch to checkout."
      description: "Name of Open Liberty branch to checkout."
    - name: github_pr_number
      isRequired: true
      defaultValue: "PR number in Open Liberty to checkout."
      description: "PR number in Open Liberty to checkout."
    - name: github_pr_api
      defaultValue: "https://api.github.com/repos/OpenLiberty/open-liberty/pulls/${github_pr_number}"

- stepName: Detect Secrets Scan
  workType: Jenkins
  projectName: detectSecretsScan
  timeoutInMinutes: 1440
  properties:
    repoToScan: "open-liberty"
    repoSSHURL: "git@github.com:${github_pr_user}/open-liberty.git"
    branchToScan: ${github_pr_branch}
    githubPRApi: ${github_pr_api}
