//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.20 at 10:40:54 AM CDT 
//


package org.apache.cxf.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.ibm.websphere.ras.annotation.Trivial;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.apache.cxf.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
@Trivial
public class ObjectFactory {

    private final static QName _Definitions_QNAME = new QName("http://schemas.xmlsoap.org/wsdl/", "definitions");
    private final static QName _TDefinitionsService_QNAME = new QName("http://schemas.xmlsoap.org/wsdl/", "service");
    private final static QName _TDefinitionsBinding_QNAME = new QName("http://schemas.xmlsoap.org/wsdl/", "binding");
    private final static QName _TDefinitionsImport_QNAME = new QName("http://schemas.xmlsoap.org/wsdl/", "import");
    private final static QName _TDefinitionsTypes_QNAME = new QName("http://schemas.xmlsoap.org/wsdl/", "types");
    private final static QName _TDefinitionsMessage_QNAME = new QName("http://schemas.xmlsoap.org/wsdl/", "message");
    private final static QName _TDefinitionsPortType_QNAME = new QName("http://schemas.xmlsoap.org/wsdl/", "portType");
    private final static QName _TOperationFault_QNAME = new QName("http://schemas.xmlsoap.org/wsdl/", "fault");
    private final static QName _TOperationOutput_QNAME = new QName("http://schemas.xmlsoap.org/wsdl/", "output");
    private final static QName _TOperationInput_QNAME = new QName("http://schemas.xmlsoap.org/wsdl/", "input");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.apache.cxf.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TBindingOperationMessage }
     * 
     */
    public TBindingOperationMessage createTBindingOperationMessage() {
        return new TBindingOperationMessage();
    }

    /**
     * Create an instance of {@link TOperation }
     * 
     */
    public TOperation createTOperation() {
        return new TOperation();
    }

    /**
     * Create an instance of {@link TPart }
     * 
     */
    public TPart createTPart() {
        return new TPart();
    }

    /**
     * Create an instance of {@link TDefinitions }
     * 
     */
    public TDefinitions createTDefinitions() {
        return new TDefinitions();
    }

    /**
     * Create an instance of {@link TDocumented }
     * 
     */
    public TDocumented createTDocumented() {
        return new TDocumented();
    }

    /**
     * Create an instance of {@link TFault }
     * 
     */
    public TFault createTFault() {
        return new TFault();
    }

    /**
     * Create an instance of {@link TPortType }
     * 
     */
    public TPortType createTPortType() {
        return new TPortType();
    }

    /**
     * Create an instance of {@link TImport }
     * 
     */
    public TImport createTImport() {
        return new TImport();
    }

    /**
     * Create an instance of {@link TParam }
     * 
     */
    public TParam createTParam() {
        return new TParam();
    }

    /**
     * Create an instance of {@link TService }
     * 
     */
    public TService createTService() {
        return new TService();
    }

    /**
     * Create an instance of {@link TMessage }
     * 
     */
    public TMessage createTMessage() {
        return new TMessage();
    }

    /**
     * Create an instance of {@link TBindingOperationFault }
     * 
     */
    public TBindingOperationFault createTBindingOperationFault() {
        return new TBindingOperationFault();
    }

    /**
     * Create an instance of {@link TDocumentation }
     * 
     */
    public TDocumentation createTDocumentation() {
        return new TDocumentation();
    }

    /**
     * Create an instance of {@link TBinding }
     * 
     */
    public TBinding createTBinding() {
        return new TBinding();
    }

    /**
     * Create an instance of {@link TBindingOperation }
     * 
     */
    public TBindingOperation createTBindingOperation() {
        return new TBindingOperation();
    }

    /**
     * Create an instance of {@link TPort }
     * 
     */
    public TPort createTPort() {
        return new TPort();
    }

    /**
     * Create an instance of {@link TTypes }
     * 
     */
    public TTypes createTTypes() {
        return new TTypes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDefinitions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/wsdl/", name = "definitions")
    public JAXBElement<TDefinitions> createDefinitions(TDefinitions value) {
        return new JAXBElement<TDefinitions>(_Definitions_QNAME, TDefinitions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/wsdl/", name = "service", scope = TDefinitions.class)
    public JAXBElement<TService> createTDefinitionsService(TService value) {
        return new JAXBElement<TService>(_TDefinitionsService_QNAME, TService.class, TDefinitions.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBinding }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/wsdl/", name = "binding", scope = TDefinitions.class)
    public JAXBElement<TBinding> createTDefinitionsBinding(TBinding value) {
        return new JAXBElement<TBinding>(_TDefinitionsBinding_QNAME, TBinding.class, TDefinitions.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TImport }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/wsdl/", name = "import", scope = TDefinitions.class)
    public JAXBElement<TImport> createTDefinitionsImport(TImport value) {
        return new JAXBElement<TImport>(_TDefinitionsImport_QNAME, TImport.class, TDefinitions.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/wsdl/", name = "types", scope = TDefinitions.class)
    public JAXBElement<TTypes> createTDefinitionsTypes(TTypes value) {
        return new JAXBElement<TTypes>(_TDefinitionsTypes_QNAME, TTypes.class, TDefinitions.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/wsdl/", name = "message", scope = TDefinitions.class)
    public JAXBElement<TMessage> createTDefinitionsMessage(TMessage value) {
        return new JAXBElement<TMessage>(_TDefinitionsMessage_QNAME, TMessage.class, TDefinitions.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPortType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/wsdl/", name = "portType", scope = TDefinitions.class)
    public JAXBElement<TPortType> createTDefinitionsPortType(TPortType value) {
        return new JAXBElement<TPortType>(_TDefinitionsPortType_QNAME, TPortType.class, TDefinitions.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/wsdl/", name = "fault", scope = TOperation.class)
    public JAXBElement<TFault> createTOperationFault(TFault value) {
        return new JAXBElement<TFault>(_TOperationFault_QNAME, TFault.class, TOperation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TParam }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/wsdl/", name = "output", scope = TOperation.class)
    public JAXBElement<TParam> createTOperationOutput(TParam value) {
        return new JAXBElement<TParam>(_TOperationOutput_QNAME, TParam.class, TOperation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TParam }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/wsdl/", name = "input", scope = TOperation.class)
    public JAXBElement<TParam> createTOperationInput(TParam value) {
        return new JAXBElement<TParam>(_TOperationInput_QNAME, TParam.class, TOperation.class, value);
    }

}
