CREATE TABLE ${schemaname}.EmbedIDOMEntityA (id INTEGER NOT NULL, password VARCHAR(254), userName VARCHAR(254), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.RELOM_EIDOMENTA (ENT_A_ID INTEGER, ENT_B_CTRY VARCHAR(255), ENT_B_ID INTEGER);
CREATE TABLE ${schemaname}.EmbedIDOMEntityA_EmbedIDOMEntityB (EmbedIDOMEntityA_id INTEGER, identity_country VARCHAR(254), identity_id VARCHAR(254));
CREATE TABLE ${schemaname}.EmbedIDOMEntityB (country VARCHAR(254) NOT NULL, id INTEGER NOT NULL, name VARCHAR(254), salary INTEGER, PRIMARY KEY (country, id));
CREATE TABLE ${schemaname}.IDClassOMEntityA (id INTEGER NOT NULL, password VARCHAR(254), userName VARCHAR(254), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.RELOM_IDCOMENTA (ENT_A_ID INTEGER, ENT_B_CTRY VARCHAR(255), ENT_B_ID INTEGER);
CREATE TABLE ${schemaname}.IDClassOMEntityA_IDClassOMEntityB (IDClassOMEntityA_id INTEGER, identity_country VARCHAR(254), identity_id INTEGER);
CREATE TABLE ${schemaname}.IDClassOMEntityB (country VARCHAR(255) NOT NULL, id INTEGER NOT NULL, name VARCHAR(255), salary INTEGER, PRIMARY KEY (country, id));
CREATE TABLE ${schemaname}.OMContainerTypeEntityA (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OMContainerTypeEntityB (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OMCTEA_GCT (OMContainerTypeEntityA_id INTEGER, genericizedCollectionType_id INTEGER);
CREATE TABLE ${schemaname}.OMCTEA_GLT (OMContainerTypeEntityA_id INTEGER, genericizedListType_id INTEGER);            
CREATE TABLE ${schemaname}.OMCTEA_GMKT (OMContainerTypeEntityA_id INTEGER, genericizedMapWithKeyType_ID INTEGER, element_id INTEGER);
CREATE TABLE ${schemaname}.OMCTEA_GMT (OMCONTAINERTYPEENTITYA_ID INTEGER, genericizedMapType_ID INTEGER, GENERICIZEDMAPTYPE_KEY INTEGER, KEY0 INTEGER, VALUE_ID INTEGER);            
CREATE TABLE ${schemaname}.OMCTEA_GST (OMContainerTypeEntityA_id INTEGER, genericizedSetType_id INTEGER);
CREATE TABLE ${schemaname}.OMCTEA_OLT (OMContainerTypeEntityA_id INTEGER, orderedListType_id INTEGER);
CREATE TABLE ${schemaname}.OMCTEA_UGCT (OMContainerTypeEntityA_id INTEGER, ungenericizedCollectionType_id INTEGER);
CREATE TABLE ${schemaname}.OMCTEA_UGLT (OMContainerTypeEntityA_id INTEGER, ungenericizedListType_id INTEGER);          
CREATE TABLE ${schemaname}.OMCTEA_UGMKT (OMContainerTypeEntityA_id INTEGER, ungenericizedMapWithKeyType_ID INTEGER, element_id INTEGER);            
CREATE TABLE ${schemaname}.OMCTEA_UGMT (OMContainerTypeEntityA_id INTEGER, ungenericizedMapType BLOB);
CREATE TABLE ${schemaname}.OMCTEA_UGST (OMContainerTypeEntityA_id INTEGER, ungenericizedSetType_id INTEGER);
CREATE TABLE ${schemaname}.OMEntA (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OMEntA_OMEntB_CA (OMEntA_id INTEGER, cascadeAll_id INTEGER);
CREATE TABLE ${schemaname}.OMEntA_OMEntB_CM (OMEntA_id INTEGER, cascadeMerge_id INTEGER);
CREATE TABLE ${schemaname}.OMEntA_OMEntB_CP (OMEntA_id INTEGER, cascadePersist_id INTEGER);
CREATE TABLE ${schemaname}.OMEntA_OMEntB_CRF (OMEntA_id INTEGER, cascadeRefresh_id INTEGER);
CREATE TABLE ${schemaname}.OMEntA_OMEntB_CRM (OMEntA_id INTEGER, cascadeRemove_id INTEGER);
CREATE TABLE ${schemaname}.OMEntB_CA (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OMEntB_CM (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OMEntB_CP (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OMEntB_CRF (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OMEntB_CRM (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OMEntB_DR (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OneXManyDRUniJoinTABLE(ENT_A INTEGER, ENT_B INTEGER NOT NULL, UNIQUE(ENT_B));
CREATE TABLE ${schemaname}.OPENJPA_SEQUENCE_TABLE (ID SMALLINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
CREATE TABLE ${schemaname}.XMLEmbedIDOMEntityA (id INTEGER NOT NULL, password VARCHAR(254), userName VARCHAR(254), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLRELOM_EIDOMENTA (ENT_A INTEGER, ENT_B_CTRY VARCHAR(255), ENT_B_ID INTEGER);
CREATE TABLE ${schemaname}.XMLEmbedIDOMEntityA_XMLEmbedIDOMEntityB (XMLEmbedIDOMEntityA_id INTEGER, identity_country VARCHAR(254), identity_id INTEGER);
CREATE TABLE ${schemaname}.XMLEmbedIDOMEntityB (country VARCHAR(255) NOT NULL, id INTEGER NOT NULL, name VARCHAR(255), salary INTEGER, PRIMARY KEY (country, id));
CREATE TABLE ${schemaname}.XMLIDClassOMEntityA (id INTEGER NOT NULL, password VARCHAR(254), userName VARCHAR(254), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLRELOM_IDCOMENTA (ENT_A INTEGER, ENT_B_CTRY VARCHAR(255), ENT_B_ID INTEGER);
CREATE TABLE ${schemaname}.XMLIDClassOMEntityA_XMLIDClassOMEntityB (XMLIDClassOMEntityA_id INTEGER, identity_country VARCHAR(254), identity_id INTEGER);
CREATE TABLE ${schemaname}.XMLIDClassOMEntityB (country VARCHAR(255) NOT NULL, id INTEGER NOT NULL, name VARCHAR(255), salary INTEGER, PRIMARY KEY (country, id));
CREATE TABLE ${schemaname}.XMLOMContainerTypeEntityA (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOMContainerTypeEntityB (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOMCTEA_GCT (XMLOMContainerTypeEntityA_id INTEGER, genericizedCollectionType_id INTEGER);
CREATE TABLE ${schemaname}.XMLOMCTEA_GLT (XMLOMContainerTypeEntityA_id INTEGER, genericizedListType_id INTEGER);          
CREATE TABLE ${schemaname}.XMLOMCTEA_GMKT (XMLOMContainerTypeEntityA_id INTEGER, genericizedMapWithKeyType_ID INTEGER, element_id INTEGER);
CREATE TABLE ${schemaname}.XMLOMCTEA_GMT (XMLOMCONTAINERTYPEENTITYA_ID INTEGER, genericizedMapType_ID INTEGER, GENERICIZEDMAPTYPE_KEY INTEGER, KEY0 INTEGER, VALUE_ID INTEGER);            
CREATE TABLE ${schemaname}.XMLOMCTEA_GST (XMLOMContainerTypeEntityA_id INTEGER, genericizedSetType_id INTEGER);
CREATE TABLE ${schemaname}.XMLOMCTEA_OLT (XMLOMContainerTypeEntityA_id INTEGER, orderedListType_id INTEGER);
CREATE TABLE ${schemaname}.XMLOMCTEA_UGCT (XMLOMContainerTypeEntityA_id INTEGER, ungenericizedCollectionType_id INTEGER);            
CREATE TABLE ${schemaname}.XMLOMCTEA_UGKMT (XMLOMContainerTypeEntityA_id INTEGER, ungenericizedMapWithKeyType_ID INTEGER, element_id INTEGER);            
CREATE TABLE ${schemaname}.XMLOMCTEA_UGLT (XMLOMContainerTypeEntityA_id INTEGER, ungenericizedListType_id INTEGER);
CREATE TABLE ${schemaname}.XMLOMCTEA_UGMT (XMLOMContainerTypeEntityA_id INTEGER, ungenericizedMapType BLOB);
CREATE TABLE ${schemaname}.XMLOMCTEA_UGST (XMLOMContainerTypeEntityA_id INTEGER, ungenericizedSetType_id INTEGER);
CREATE TABLE ${schemaname}.XMLOMEntA (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOMEntA_XMLOMEntB_CA (XMLOMEntA_id INTEGER, cascadeAll_id INTEGER);
CREATE TABLE ${schemaname}.XMLOMEntA_XMLOMEntB_CM (XMLOMEntA_id INTEGER, cascadeMerge_id INTEGER);
CREATE TABLE ${schemaname}.XMLOMEntA_XMLOMEntB_CP (XMLOMEntA_id INTEGER, cascadePersist_id INTEGER);
CREATE TABLE ${schemaname}.XMLOMEntA_XMLOMEntB_CRF (XMLOMEntA_id INTEGER, cascadeRefresh_id INTEGER);
CREATE TABLE ${schemaname}.XMLOMEntA_XMLOMEntB_CRM (XMLOMEntA_id INTEGER, cascadeRemove_id INTEGER);
CREATE TABLE ${schemaname}.XMLOMEntA_XMLOMEntB_DR (XMLOMEntA_id INTEGER, defaultRelationship_id INTEGER NOT NULL, UNIQUE(defaultRelationship_id));
CREATE TABLE ${schemaname}.XMLOMEntB_CA (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOMEntB_CM (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOMEntB_CP (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOMEntB_CRF (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOMEntB_CRM (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOMEntB_DR (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));

CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX001 ON ${schemaname}.RELOM_EIDOMENTA (ENT_B_CTRY, ENT_B_ID);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX002 ON ${schemaname}.RELOM_EIDOMENTA (ENT_A_ID);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX003 ON ${schemaname}.RELOM_IDCOMENTA (ENT_B_CTRY, ENT_B_ID);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX004 ON ${schemaname}.RELOM_IDCOMENTA (ENT_A_ID);
CREATE INDEX ${schemaname}.OM_I_MBDDTYB_ELEMENT ON ${schemaname}.EmbedIDOMEntityA_EmbedIDOMEntityB (identity_country, identity_id);
CREATE INDEX ${schemaname}.OM_I_MBDDTYB_EMBEDIDO ON ${schemaname}.EmbedIDOMEntityA_EmbedIDOMEntityB (EmbedIDOMEntityA_id);
CREATE INDEX ${schemaname}.OM_I_DCLSTYB_ELEMENT ON ${schemaname}.IDClassOMEntityA_IDClassOMEntityB (identity_country, identity_id);
CREATE INDEX ${schemaname}.OM_I_DCLSTYB_IDCLASSO ON ${schemaname}.IDClassOMEntityA_IDClassOMEntityB (IDClassOMEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX005 ON ${schemaname}.OMCTEA_GCT (genericizedCollectionType_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX006 ON ${schemaname}.OMCTEA_GCT (OMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX007 ON ${schemaname}.OMCTEA_GLT (genericizedListType_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX008 ON ${schemaname}.OMCTEA_GLT (OMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX009 ON ${schemaname}.OMCTEA_GMKT (element_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX010 ON ${schemaname}.OMCTEA_GMKT (OMContainerTypeEntityA_id);
CREATE INDEX I_RELOM_INDEX011 ON ${schemaname}.OMCTEA_GMT (OMCONTAINERTYPEENTITYA_ID);
CREATE INDEX I_RELOM_INDEX012 ON ${schemaname}.OMCTEA_GMT (VALUE_ID);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX013 ON ${schemaname}.OMCTEA_GST (genericizedSetType_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX014 ON ${schemaname}.OMCTEA_GST (OMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX015 ON ${schemaname}.OMCTEA_OLT (orderedListType_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX016 ON ${schemaname}.OMCTEA_OLT (OMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX017 ON ${schemaname}.OMCTEA_UGCT (ungenericizedCollectionType_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX018 ON ${schemaname}.OMCTEA_UGCT (OMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX019 ON ${schemaname}.OMCTEA_UGLT (ungenericizedListType_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX020 ON ${schemaname}.OMCTEA_UGLT (OMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX021 ON ${schemaname}.OMCTEA_UGMKT (element_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX022 ON ${schemaname}.OMCTEA_UGMKT (OMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX023 ON ${schemaname}.OMCTEA_UGMT (OMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX024 ON ${schemaname}.OMCTEA_UGST (ungenericizedSetType_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX025 ON ${schemaname}.OMCTEA_UGST (OMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX026 ON ${schemaname}.OMEntA_OMEntB_CA (cascadeAll_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX027 ON ${schemaname}.OMEntA_OMEntB_CA (OMEntA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX028 ON ${schemaname}.OMEntA_OMEntB_CM (cascadeMerge_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX029 ON ${schemaname}.OMEntA_OMEntB_CM (OMEntA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX030 ON ${schemaname}.OMEntA_OMEntB_CP (cascadePersist_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX031 ON ${schemaname}.OMEntA_OMEntB_CP (OMEntA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX032 ON ${schemaname}.OMEntA_OMEntB_CRF (cascadeRefresh_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX033 ON ${schemaname}.OMEntA_OMEntB_CRF (OMEntA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX033a ON ${schemaname}.OMEntA_OMEntB_CRM (cascadeRemove_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX035 ON ${schemaname}.OMEntA_OMEntB_CRM (OMEntA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX036 ON ${schemaname}.OneXManyDRUniJoinTABLE (ENT_A);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX038 ON ${schemaname}.XMLRELOM_EIDOMENTA (ENT_B_CTRY, ENT_B_ID);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX039 ON ${schemaname}.XMLRELOM_EIDOMENTA (ENT_A);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX040 ON ${schemaname}.XMLRELOM_IDCOMENTA (ENT_B_CTRY, ENT_B_ID);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX041 ON ${schemaname}.XMLRELOM_IDCOMENTA (ENT_A);
CREATE INDEX ${schemaname}.OM_I_XMLMTYB_ELEMENT ON ${schemaname}.XMLEmbedIDOMEntityA_XMLEmbedIDOMEntityB (identity_country, identity_id);
CREATE INDEX ${schemaname}.OM_I_XMLMTYB_XMLEMBED ON ${schemaname}.XMLEmbedIDOMEntityA_XMLEmbedIDOMEntityB (XMLEmbedIDOMEntityA_id);
CREATE INDEX ${schemaname}.OM_I_XMLDTYB_ELEMENT ON ${schemaname}.XMLIDClassOMEntityA_XMLIDClassOMEntityB (identity_country, identity_id);
CREATE INDEX ${schemaname}.OM_I_XMLDTYB_XMLIDCLA ON ${schemaname}.XMLIDClassOMEntityA_XMLIDClassOMEntityB (XMLIDClassOMEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX042 ON ${schemaname}.XMLOMCTEA_GCT (genericizedCollectionType_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX043 ON ${schemaname}.XMLOMCTEA_GCT (XMLOMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX044 ON ${schemaname}.XMLOMCTEA_GLT (genericizedListType_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX045 ON ${schemaname}.XMLOMCTEA_GLT (XMLOMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX046 ON ${schemaname}.XMLOMCTEA_GMKT (element_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX047 ON ${schemaname}.XMLOMCTEA_GMKT (XMLOMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX050 ON ${schemaname}.XMLOMCTEA_GST (genericizedSetType_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX051 ON ${schemaname}.XMLOMCTEA_GST (XMLOMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX052 ON ${schemaname}.XMLOMCTEA_OLT (orderedListType_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX053 ON ${schemaname}.XMLOMCTEA_OLT (XMLOMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX054 ON ${schemaname}.XMLOMCTEA_UGCT (ungenericizedCollectionType_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX055 ON ${schemaname}.XMLOMCTEA_UGCT (XMLOMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX056 ON ${schemaname}.XMLOMCTEA_UGKMT (element_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX057 ON ${schemaname}.XMLOMCTEA_UGKMT (XMLOMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX058 ON ${schemaname}.XMLOMCTEA_UGLT (ungenericizedListType_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX059 ON ${schemaname}.XMLOMCTEA_UGLT (XMLOMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX060 ON ${schemaname}.XMLOMCTEA_UGMT (XMLOMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX061 ON ${schemaname}.XMLOMCTEA_UGST (ungenericizedSetType_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX062 ON ${schemaname}.XMLOMCTEA_UGST (XMLOMContainerTypeEntityA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX063 ON ${schemaname}.XMLOMEntA_XMLOMEntB_CA (cascadeAll_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX064 ON ${schemaname}.XMLOMEntA_XMLOMEntB_CA (XMLOMEntA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX065 ON ${schemaname}.XMLOMEntA_XMLOMEntB_CM (cascadeMerge_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX066 ON ${schemaname}.XMLOMEntA_XMLOMEntB_CM (XMLOMEntA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX067 ON ${schemaname}.XMLOMEntA_XMLOMEntB_CP (cascadePersist_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX068 ON ${schemaname}.XMLOMEntA_XMLOMEntB_CP (XMLOMEntA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX069 ON ${schemaname}.XMLOMEntA_XMLOMEntB_CRF (cascadeRefresh_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX070 ON ${schemaname}.XMLOMEntA_XMLOMEntB_CRF (XMLOMEntA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX071 ON ${schemaname}.XMLOMEntA_XMLOMEntB_CRM (cascadeRemove_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX072 ON ${schemaname}.XMLOMEntA_XMLOMEntB_CRM (XMLOMEntA_id);
CREATE INDEX ${schemaname}.OM_I_RELOM_INDEX073 ON ${schemaname}.XMLOMEntA_XMLOMEntB_DR (XMLOMEntA_id);
 