/*******************************************************************************
 * Copyright (c) 2026 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
configurations {
  johnzon21 {transitive = false}
}

dependencies {
  johnzon21 'org.apache.johnzon:johnzon-core:2.1.0'
}

task addJohnzon21(type: Copy) {
  from configurations.johnzon21
  into "${buildDir}/autoFVT/publish/shared/resources/johnzon/2.1.0/"
  rename "johnzon-core-.*.jar", "johnzon-core.jar"
}

addRequiredLibraries {
  dependsOn addJohnzon21
}
