/*******************************************************************************
 * Copyright (c) 2017 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
/* Generated By:JavaCC: Do not edit this line. JSParserConstants.java */
package com.ibm.ws.sib.mfp.jmf.parser;

public interface JSParserConstants {

  int EOF = 0;
  int IDENTIFIER = 66;
  int LETTER = 67;
  int DIGIT = 68;
  int IDCHAR = 69;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\",\"",
    "\":\"",
    "\"*(\"",
    "\")*\"",
    "\"{\"",
    "\"|\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"Dynamic\"",
    "\"<\"",
    "\">\"",
    "\"string\"",
    "\"boolean\"",
    "\"decimal\"",
    "\"float\"",
    "\"double\"",
    "\"duration\"",
    "\"dateTime\"",
    "\"time\"",
    "\"date\"",
    "\"gYearMonth\"",
    "\"gYear\"",
    "\"gMonthDay\"",
    "\"gDay\"",
    "\"gMonth\"",
    "\"hexBinary\"",
    "\"base64Binary\"",
    "\"anyURI\"",
    "\"QName\"",
    "\"NOTATION\"",
    "\"normalizedString\"",
    "\"token\"",
    "\"language\"",
    "\"NMTOKEN\"",
    "\"NMTOKENS\"",
    "\"Name\"",
    "\"NCName\"",
    "\"ID\"",
    "\"IDREF\"",
    "\"IDREFS\"",
    "\"ENTITY\"",
    "\"ENTITIES\"",
    "\"integer\"",
    "\"nonPositiveInteger\"",
    "\"negativeInteger\"",
    "\"long\"",
    "\"int\"",
    "\"short\"",
    "\"byte\"",
    "\"nonNegativeInteger\"",
    "\"unsignedLong\"",
    "\"unsignedInt\"",
    "\"unsignedShort\"",
    "\"unsignedByte\"",
    "\"positiveInteger\"",
    "\"anySimpleType\"",
    "\"byte8\"",
    "\"byte12\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 64>",
    "<token of kind 65>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<IDCHAR>",
  };

}
