INSERT INTO ${schemaname}.EL10LockEntA (ID, STRDATA, VERSION) VALUES (1, 'EntityA-1', 1);

INSERT INTO ${schemaname}.EL10LockEntB (ID, STRDATA, VERSION) VALUES (1, 'EntityB-1', 1);
INSERT INTO ${schemaname}.EL10LockEntB (ID, STRDATA, VERSION) VALUES (2, 'EntityB-1', 2);
INSERT INTO ${schemaname}.EL10LockEntB (ID, STRDATA, VERSION) VALUES (3, 'EntityB-1', 3);
INSERT INTO ${schemaname}.EL10LockEntB (ID, STRDATA, VERSION) VALUES (4, 'EntityB-1', 4);
INSERT INTO ${schemaname}.EL10LockEntB (ID, STRDATA, VERSION) VALUES (5, 'EntityB-1', 5);
INSERT INTO ${schemaname}.EL10LockEntB (ID, STRDATA, VERSION) VALUES (6, 'EntityB-1', 6);
INSERT INTO ${schemaname}.EL10LockEntB (ID, STRDATA, VERSION) VALUES (7, 'EntityB-1', 7);
INSERT INTO ${schemaname}.EL10LockEntB (ID, STRDATA, VERSION) VALUES (8, 'EntityB-1', 8);
INSERT INTO ${schemaname}.EL10LockEntB (ID, STRDATA, VERSION) VALUES (9, 'EntityB-1', 9);
INSERT INTO ${schemaname}.EL10LockEntB (ID, STRDATA, VERSION) VALUES (10, 'EntityB-10', 1);

UPDATE ${schemaname}.EL10LockEntA SET ENTB_OTO = 1, ENTB_MTO = 1 WHERE ID = 1;

INSERT INTO ${schemaname}.EL10LEOMJT (ENTA, ENTB) VALUES (1, 1);
INSERT INTO ${schemaname}.EL10LEOMJT (ENTA, ENTB) VALUES (1, 2);
INSERT INTO ${schemaname}.EL10LEOMJT (ENTA, ENTB) VALUES (1, 3);
INSERT INTO ${schemaname}.EL10LEOMJT (ENTA, ENTB) VALUES (1, 4);
INSERT INTO ${schemaname}.EL10LEOMJT (ENTA, ENTB) VALUES (1, 5);
INSERT INTO ${schemaname}.EL10LEOMJT (ENTA, ENTB) VALUES (1, 6);
INSERT INTO ${schemaname}.EL10LEOMJT (ENTA, ENTB) VALUES (1, 7);
INSERT INTO ${schemaname}.EL10LEOMJT (ENTA, ENTB) VALUES (1, 8);
INSERT INTO ${schemaname}.EL10LEOMJT (ENTA, ENTB) VALUES (1, 9);
INSERT INTO ${schemaname}.EL10LEOMJT (ENTA, ENTB) VALUES (1, 10);

INSERT INTO ${schemaname}.EL10LEMMJT (ENTA, ENTB) VALUES (1, 1);
INSERT INTO ${schemaname}.EL10LEMMJT (ENTA, ENTB) VALUES (1, 2);
INSERT INTO ${schemaname}.EL10LEMMJT (ENTA, ENTB) VALUES (1, 3);
INSERT INTO ${schemaname}.EL10LEMMJT (ENTA, ENTB) VALUES (1, 4);
INSERT INTO ${schemaname}.EL10LEMMJT (ENTA, ENTB) VALUES (1, 5);
INSERT INTO ${schemaname}.EL10LEMMJT (ENTA, ENTB) VALUES (1, 6);
INSERT INTO ${schemaname}.EL10LEMMJT (ENTA, ENTB) VALUES (1, 7);
INSERT INTO ${schemaname}.EL10LEMMJT (ENTA, ENTB) VALUES (1, 8);
INSERT INTO ${schemaname}.EL10LEMMJT (ENTA, ENTB) VALUES (1, 9);
INSERT INTO ${schemaname}.EL10LEMMJT (ENTA, ENTB) VALUES (1, 10);
