otel.metrics.exporter=otlp
otel.exporter.otlp.protocol=http/protobuf
otel.sdk.disabled=false
otel.traces.exporter=none
otel.logs.exporter=none
otel.metric.export.interval=1000
otel.exporter.otlp.compression=gzip
