/*******************************************************************************
 * Copyright (c) 2020 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/

package test.wssecfvt.wsstemplates;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-02-17T23:15:10.747-06:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "WSSTemplatesService3", 
                  wsdlLocation = "file:/C:/Liberty/com.ibm.ws.wssecurity_fat/test-applications/wsstemplates/resources/WEB-INF/WSSTemplatesTest.wsdl",
                  targetNamespace = "http://wsstemplates.wssecfvt.test") 
public class WSSTemplatesService3 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wsstemplates.wssecfvt.test", "WSSTemplatesService3");
    public final static QName WSSTemplate3 = new QName("http://wsstemplates.wssecfvt.test", "WSSTemplate3");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Liberty/com.ibm.ws.wssecurity_fat/test-applications/wsstemplates/resources/WEB-INF/WSSTemplatesTest.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSSTemplatesService3.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Liberty/com.ibm.ws.wssecurity_fat/test-applications/wsstemplates/resources/WEB-INF/WSSTemplatesTest.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSSTemplatesService3(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSSTemplatesService3(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSSTemplatesService3() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    /**
     *
     * @return
     *     returns WSSTemplates
     */
    @WebEndpoint(name = "WSSTemplate3")
    public WSSTemplates getWSSTemplate3() {
        return super.getPort(WSSTemplate3, WSSTemplates.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSSTemplates
     */
    @WebEndpoint(name = "WSSTemplate3")
    public WSSTemplates getWSSTemplate3(WebServiceFeature... features) {
        return super.getPort(WSSTemplate3, WSSTemplates.class, features);
    }

}
