CREATE TABLE ${schemaname}.EventEntityOLGH14426 (id NUMERIC(38) NOT NULL, datef DATETIME NULL, JOB_ID NUMERIC(38) NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.JobEntityOLGH14426 (id NUMERIC(38) NOT NULL, DTYPE VARCHAR(255) NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));
CREATE INDEX I_VNTN426_JOB ON ${schemaname}.EventEntityOLGH14426 (JOB_ID);
CREATE INDEX I_JBNT426_DTYPE ON ${schemaname}.JobEntityOLGH14426 (DTYPE);