CREATE TABLE ${schemaname}.EventEntityOLGH14426 (id NUMERIC(32,0) NOT NULL, datef DATETIME YEAR TO FRACTION(3), JOB_ID NUMERIC(32,0), PRIMARY KEY (id)) LOCK MODE ROW;
CREATE TABLE ${schemaname}.JobEntityOLGH14426 (id NUMERIC(32,0) NOT NULL, DTYPE VARCHAR(255), PRIMARY KEY (id)) LOCK MODE ROW;
CREATE INDEX I_VNTN426_JOB ON ${schemaname}.EventEntityOLGH14426 (JOB_ID);
CREATE INDEX I_JBNT426_DTYPE ON ${schemaname}.JobEntityOLGH14426 (DTYPE);