/*******************************************************************************
 * Copyright (c) 2026 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
package io.openliberty.mcp.internal.fat.oidc.tests;

import java.io.File;
import java.io.FileInputStream;
import java.security.KeyStore;
import java.security.SecureRandom;
import java.security.cert.Certificate;
import java.util.Enumeration;

import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManagerFactory;

import componenttest.topology.impl.LibertyServer;

/**
 * Certificate helpers for HTTPS tests that involve both the Liberty server and Keycloak.
 *
 * <p>This class provides a single method:
 * <ul>
 * <li>{@link #buildCombinedSslContext} — builds an {@link SSLContext} that trusts both
 * the Keycloak self-signed certificate and the Liberty server's auto-generated TLS certificate,
 * suitable for passing to {@link io.openliberty.mcp.internal.fat.utils.McpClient}.</li>
 * </ul>
 *
 * <p><b>Certificate sources:</b>
 * <ul>
 * <li><b>Keycloak cert</b> — generated at container construction time and held in
 * {@link KeycloakContainer}'s truststore via {@link KeycloakContainer#getOrCreateTruststore()}.</li>
 * <li><b>Liberty cert</b> — auto-generated by Liberty on first start and stored at
 * {@code <serverRoot>/resources/security/key.p12} with password {@code "keypass"}
 * as declared in {@code server.xml}. Must be read <em>after</em> the server starts.</li>
 * </ul>
 *
 * <p>All methods in this class must be called after {@code server.startServer()} so that
 * {@code key.p12} exists on disk.
 */
public final class HttpsRequestHelper {

    /**
     * Builds an {@link SSLContext} that trusts both the Keycloak self-signed certificate
     * and the Liberty server's auto-generated TLS certificate.
     *
     * <p>Pass the returned context to
     * {@link io.openliberty.mcp.internal.fat.utils.McpClient#McpClient(LibertyServer, String, io.openliberty.mcp.internal.fat.utils.McpClient.StateMode, SSLContext)}
     * to create an HTTPS-capable client.
     *
     * <p>Must be called after the Liberty server has started.
     *
     * @param keycloakContainer the running Keycloak container
     * @param libertyServer the started Liberty server
     * @return an {@link SSLContext} trusting both certificates
     * @throws Exception if either keystore cannot be read or the SSL context cannot be built
     */
    public static SSLContext buildCombinedSslContext(KeycloakContainer keycloakContainer,
                                                     LibertyServer libertyServer)
                    throws Exception {
        KeyStore combinedTruststore = KeyStore.getInstance("pkcs12");
        combinedTruststore.load(null, null);

        // Add the Keycloak certificate(s)
        KeyStore keycloakTs = keycloakContainer.getOrCreateTruststore();
        Enumeration<String> keycloakAliases = keycloakTs.aliases();
        while (keycloakAliases.hasMoreElements()) {
            String alias = keycloakAliases.nextElement();
            combinedTruststore.setCertificateEntry("keycloak-" + alias, keycloakTs.getCertificate(alias));
        }

        // Add the Liberty server certificate(s) from its auto-generated key.p12
        KeyStore libertyKeystore = loadLibertyKeystore(libertyServer);
        Enumeration<String> libertyAliases = libertyKeystore.aliases();
        while (libertyAliases.hasMoreElements()) {
            String alias = libertyAliases.nextElement();
            Certificate cert = libertyKeystore.getCertificate(alias);
            if (cert != null) {
                combinedTruststore.setCertificateEntry("liberty-" + alias, cert);
            }
        }

        TrustManagerFactory tmf = TrustManagerFactory.getInstance("PKIX");
        tmf.init(combinedTruststore);

        SSLContext sslContext = SSLContext.getInstance("TLS");
        sslContext.init(null, tmf.getTrustManagers(), new SecureRandom());
        return sslContext;
    }

    /**
     * Loads Liberty's auto-generated PKCS12 keystore from
     * {@code <serverRoot>/resources/security/key.p12} using the password {@code "keypass"}
     * as declared in {@code server.xml}.
     */
    private static KeyStore loadLibertyKeystore(LibertyServer libertyServer) throws Exception {
        String keyStorePath = libertyServer.getServerRoot() + "/resources/security/key.p12";
        File keyStoreFile = new File(keyStorePath);
        if (!keyStoreFile.exists()) {
            throw new RuntimeException("Liberty keystore not found at: " + keyStorePath
                                       + " — ensure the server has started before calling this method.");
        }
        KeyStore keystore = KeyStore.getInstance("pkcs12");
        try (FileInputStream fis = new FileInputStream(keyStoreFile)) {
            keystore.load(fis, "keypass".toCharArray());
        }
        return keystore;
    }
}
