INSERT INTO SimpleEntityOLGH19185 (KEY_CHAR,ITEM_INTEGER1,ITEM_STRING1,ITEM_STRING2,ITEM_STRING3,ITEM_STRING4) VALUES ('Key20',9,'A',NULL,'C','D');
INSERT INTO SimpleEntityOLGH19185 (KEY_CHAR,ITEM_INTEGER1,ITEM_STRING1,ITEM_STRING2,ITEM_STRING3,ITEM_STRING4) VALUES ('Key21',8,'A','B','C',NULL);
INSERT INTO SimpleEntityOLGH19185 (KEY_CHAR,ITEM_INTEGER1,ITEM_STRING1,ITEM_STRING2,ITEM_STRING3,ITEM_STRING4) VALUES ('Key22',9,NULL,'B','C','D');
INSERT INTO SimpleEntityOLGH19185 (KEY_CHAR,ITEM_INTEGER1,ITEM_STRING1,ITEM_STRING2,ITEM_STRING3,ITEM_STRING4) VALUES ('Key13',4,'A','B','C',NULL);