<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="SamlTokenWebSvc" targetNamespace="http://wssec.basic.cxf.fats" 
    xmlns="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:tns="http://wssec.basic.cxf.fats"
    xmlns:x1="http://wssec.basic.cxf.fats/types"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
    xmlns:wsp="http://www.w3.org/ns/ws-policy"
    xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
    xmlns:sp13="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200802"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:jaxws="http://java.sun.com/xml/ns/jaxws">

    <!--                SAMLToken with plain text password               -->
    <wsp:Policy wsu:Id="SamlToken">
    <sp:SupportingTokens>
        <wsp:Policy>
          <sp:SamlToken
            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
            <wsp:Policy>
                <sp:WssSamlV20Token11/>
            </wsp:Policy>
          </sp:SamlToken>
        </wsp:Policy>
     </sp:SupportingTokens>
     </wsp:Policy>
     
    <wsp:Policy wsu:Id="SAMLTokenSecure">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                <wsp:Policy>
                                    <!-- sp:RequireClientCertificate / -->
                                </wsp:Policy>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <!-- sp:IncludeTimestamp/ -->
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SupportingTokens>
                    <wsp:Policy>
                        <sp:SamlToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV20Token11/>
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    
    <wsdl:types>
        <schema targetNamespace="http://wssec.basic.cxf.fats/types" 
            xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
            <element name="getVer">
                <complexType>
                    <sequence>
                        <element name="requestType" type="xsd:string"/>
                    </sequence>
                </complexType>
            </element>
            <element name="getVerResponse">
                <complexType>
                    <sequence>
                        <element name="responseType" type="xsd:string"/>
                    </sequence>
                </complexType>
            </element>
   	    <element name="faultDetail">
		<complexType>
			<sequence>
				<element name="minor" type="xsd:short"/>
				<element name="major" type="xsd:short"/>
			</sequence>
		</complexType>
	    </element>
        </schema>
    </wsdl:types>

    <wsdl:message name="getVerRequest">
        <wsdl:part element="x1:getVer" name="in"/>
    </wsdl:message>
    <wsdl:message name="getVerResponse">
        <wsdl:part element="x1:getVerResponse" name="out"/>
    </wsdl:message>

    <wsdl:portType name="SamlTokenType">
        <wsdl:operation name="invoke">
            <wsdl:input message="tns:getVerRequest" name="getVerRequest"/>
            <wsdl:output message="tns:getVerResponse" name="getVerResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="SamlToken_SOAPBinding" type="tns:SamlTokenType">
       <wsp:PolicyReference URI="#SamlToken" />
       <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <wsdl:operation name="invoke">
          <soap:operation soapAction="" style="document"/>
          <wsdl:input name="getVerRequest">
              <soap:body use="literal"/>
          </wsdl:input>
          <wsdl:output name="getVerResponse">
              <soap:body use="literal"/>
          </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:binding name="SamlToken_SecureBinding" type="tns:SamlTokenType">
      <wsp:PolicyReference URI="#SAMLTokenSecure" />
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <soap:operation soapAction=""/>
         <wsdl:input name="getVerRequest">
            <soap:body use="literal"/>
            <wsp:PolicyReference URI="#SAMLTokenSecure" />
         </wsdl:input>
         <wsdl:output name="getVerResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   
    <wsdl:service name="SAMLSOAPService2">
       <wsdl:port binding="tns:SamlToken_SOAPBinding" name="SAMLSoapPort2">
          <soap:address location="http://localhost:8010/samltoken/SAMLSOAPService2"/>
       </wsdl:port>
    </wsdl:service>

    <wsdl:service name="SAMLSOAPService5">
       <wsdl:port binding="tns:SamlToken_SOAPBinding" name="SAMLSoapPort5">
          <soap:address location="http://localhost:8010/samltoken/SAMLSOAPService5"/>
       </wsdl:port>
    </wsdl:service>

   <wsdl:service name="SamlTokenTransportSecure">
      <wsdl:port binding="tns:SamlToken_SecureBinding" name="SamlTokenTransportSecurePort">
         <soap:address location="https://localhost:8020/samlToken/SamlTokenTransportSecure"/>
      </wsdl:port>
   </wsdl:service>
   
   <!--                 Symmetric Sign                 -->
       <!-- SAMLToken with plain text password -->
    <wsp:Policy wsu:Id="SamlSymSign">

     <wsp:ExactlyOne>
            <wsp:All>
                <sp:SignedSupportingTokens>
                   <wsp:Policy>
                  	  <sp:SamlToken
                		sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">                		
                		<wsp:Policy>
                        	<sp:WssSamlV20Token11/>
                		</wsp:Policy>
          			  </sp:SamlToken>      
                   </wsp:Policy>
                </sp:SignedSupportingTokens>

				<sp:SymmetricBinding>
                     <wsp:Policy>
                         <sp:ProtectionToken>
                             <wsp:Policy>
                                 <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                                     <wsp:Policy>
                                         <sp:RequireThumbprintReference/>
                                         <sp:WssX509V3Token10/>
                                     </wsp:Policy>
                                 </sp:X509Token>
                             </wsp:Policy>
                         </sp:ProtectionToken>
                         <sp:AlgorithmSuite>
                             <wsp:Policy>
                                 <sp:Basic128/>
                             </wsp:Policy>
                         </sp:AlgorithmSuite>
                         <sp:Layout>
                             <wsp:Policy>
                                 <sp:Lax/>
                             </wsp:Policy>
                         </sp:Layout>
                         <sp:IncludeTimestamp/>
                         <sp:OnlySignEntireHeadersAndBody/>
                     </wsp:Policy>
                </sp:SymmetricBinding>
                <sp:Wss10>
                    <wsp:Policy>
                        <sp:MustSupportRefKeyIdentifier/>
                        <sp:MustSupportRefEncryptedKey/>
                        <sp:MustSupportRefThumbprint/>
                    </wsp:Policy>
                </sp:Wss10>
                <sp:SignedParts>
                    <sp:Body/>
                </sp:SignedParts>
               
            </wsp:All>
        </wsp:ExactlyOne>    
 
     </wsp:Policy>
     
     <wsdl:binding name="SamlToken_SymSignBinding" type="tns:SamlTokenType">
       <wsp:PolicyReference URI="#SamlSymSign" />
       <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <wsdl:operation name="invoke">
          <soap:operation soapAction="" style="document"/>
          <wsdl:input name="getVerRequest">
              <soap:body use="literal"/>
          </wsdl:input>
          <wsdl:output name="getVerResponse">
              <soap:body use="literal"/>
          </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>    
       
    <wsdl:service name="SAMLSymSignService">
       <wsdl:port binding="tns:SamlToken_SymSignBinding" name="SAMLSymSignPort">
          <soap:address location="http://localhost:8010/samltoken/SAMLSymSignService"/>
       </wsdl:port>
    </wsdl:service>
    <!--                 Symmetric Sign                 -->
     
    <!--                 Symmetric Encr                 -->
        <wsp:Policy wsu:Id="SamlSymEncr">
     <wsp:ExactlyOne>
            <wsp:All>
                <sp:EncryptedSupportingTokens>
                   <wsp:Policy>
                      <sp:SamlToken
                	    sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">                		
                		<wsp:Policy>
                           <sp:WssSamlV20Token11/>
                		</wsp:Policy>
          		      </sp:SamlToken>   
                   </wsp:Policy>
                </sp:EncryptedSupportingTokens>

                <sp:SymmetricBinding>
                     <wsp:Policy>
                         <sp:ProtectionToken>
                             <wsp:Policy>
                                 <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                                     <wsp:Policy>
                                         <sp:RequireThumbprintReference/>
                                         <sp:WssX509V3Token10/>
                                     </wsp:Policy>
                                 </sp:X509Token>
                             </wsp:Policy>
                         </sp:ProtectionToken>
                         <sp:AlgorithmSuite>
                             <wsp:Policy>
                                 <sp:Basic128/>
                             </wsp:Policy>
                         </sp:AlgorithmSuite>
                         <sp:Layout>
                             <wsp:Policy>
                                 <sp:Lax/>
                             </wsp:Policy>
                         </sp:Layout>
                         <sp:IncludeTimestamp/>
                         <sp:OnlySignEntireHeadersAndBody/>
                     </wsp:Policy>
                </sp:SymmetricBinding>               
               				
                <sp:SignedParts>
                    <sp:Body/>
                </sp:SignedParts>               
                                                              
            </wsp:All>
        </wsp:ExactlyOne>
   
     </wsp:Policy>

    <wsdl:binding name="SamlToken_SymEncrBinding" type="tns:SamlTokenType">
       <wsp:PolicyReference URI="#SamlSymEncr" />
       <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <wsdl:operation name="invoke">
          <soap:operation soapAction="" style="document"/>
          <wsdl:input name="getVerRequest">
              <soap:body use="literal"/>
          </wsdl:input>
          <wsdl:output name="getVerResponse">
              <soap:body use="literal"/>
          </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
        
    <wsdl:service name="SAMLSymEncrService">
       <wsdl:port binding="tns:SamlToken_SymEncrBinding" name="SAMLSymEncrPort">
          <soap:address location="http://localhost:8010/samltoken/SAMLSymEncrService"/>
       </wsdl:port>
    </wsdl:service>
    <!--                 Symmetric Encr                 -->
    
    <!--                 Symmetric Sign & Encr                 -->
    <wsp:Policy wsu:Id="SamlSymSignEncr">
     <wsp:ExactlyOne>
            <wsp:All>
                <sp:SignedEncryptedSupportingTokens>
                   <wsp:Policy>
                      <sp:SamlToken
                	    sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">                		
                		<wsp:Policy>
                           <sp:WssSamlV20Token11/>
                		</wsp:Policy>
          		      </sp:SamlToken>   
                   </wsp:Policy>
                </sp:SignedEncryptedSupportingTokens>

                <sp:SymmetricBinding>
                     <wsp:Policy>
                         <sp:ProtectionToken>
                             <wsp:Policy>
                                 <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                                     <wsp:Policy>
                                         <sp:RequireThumbprintReference/>
                                         <sp:WssX509V3Token10/>
                                     </wsp:Policy>
                                 </sp:X509Token>
                             </wsp:Policy>
                         </sp:ProtectionToken>
                         <sp:AlgorithmSuite>
                             <wsp:Policy>
                                 <sp:Basic128/>
                             </wsp:Policy>
                         </sp:AlgorithmSuite>
                         <sp:Layout>
                             <wsp:Policy>
                                 <sp:Lax/>
                             </wsp:Policy>
                         </sp:Layout>
                         <sp:IncludeTimestamp/>
                         <sp:OnlySignEntireHeadersAndBody/>
                     </wsp:Policy>
                </sp:SymmetricBinding>               
               				
                <sp:SignedParts>
                    <sp:Body/>
                </sp:SignedParts>               
                                                              
            </wsp:All>
        </wsp:ExactlyOne>
   
     </wsp:Policy>
    
    <wsdl:binding name="SamlToken_SymSignEncrBinding" type="tns:SamlTokenType">
       <wsp:PolicyReference URI="#SamlSymSignEncr" />
       <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <wsdl:operation name="invoke">
          <soap:operation soapAction="" style="document"/>
          <wsdl:input name="getVerRequest">
              <soap:body use="literal"/>
          </wsdl:input>
          <wsdl:output name="getVerResponse">
              <soap:body use="literal"/>
          </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
        
    <wsdl:service name="SAMLSymSignEncrService">
       <wsdl:port binding="tns:SamlToken_SymSignEncrBinding" name="SAMLSymSignEncrPort">
          <soap:address location="http://localhost:8010/samltoken/SAMLSymSignEncrService"/>
       </wsdl:port>
    </wsdl:service>    
    <!--                 Symmetric Sign & Encr                 -->

    <!--                 Asymmetric Sign                 -->
    
    <wsp:Policy wsu:Id="SamlAsymSign">
     <wsp:ExactlyOne>
            <wsp:All>
                <sp:SignedSupportingTokens>
                   <wsp:Policy>
                  	  <sp:SamlToken
                		sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">                		
                		<wsp:Policy>
                        	<sp:WssSamlV20Token11/>
                		</wsp:Policy>
          			  </sp:SamlToken>      
                   </wsp:Policy>
                </sp:SignedSupportingTokens>

                <sp:AsymmetricBinding >
                    <wsp:Policy>
                        <sp:InitiatorToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                                    <wsp:Policy>
                                        <sp:WssX509V3Token10/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:InitiatorToken>
                        <sp:RecipientToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                                    <wsp:Policy>
                                        <sp:WssX509V3Token10/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:RecipientToken>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:OnlySignEntireHeadersAndBody/>
                    </wsp:Policy>
                </sp:AsymmetricBinding>

                <sp:Wss10>
                    <wsp:Policy>
                        <sp:MustSupportRefKeyIdentifier/>
                    </wsp:Policy>
                </sp:Wss10>
                <sp:SignedParts>
                    <sp:Body/>
                </sp:SignedParts>
            </wsp:All>
        </wsp:ExactlyOne>    
   
    </wsp:Policy>    
    
     <wsdl:binding name="SamlToken_AsymSignBinding" type="tns:SamlTokenType">
       <wsp:PolicyReference URI="#SamlAsymSign" />
       <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <wsdl:operation name="invoke">
          <soap:operation soapAction="" style="document"/>
          <wsdl:input name="getVerRequest">
              <soap:body use="literal"/>
          </wsdl:input>
          <wsdl:output name="getVerResponse">
              <soap:body use="literal"/>
          </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>    
       
    <wsdl:service name="SAMLAsymSignService">
       <wsdl:port binding="tns:SamlToken_AsymSignBinding" name="SAMLAsymSignPort">
          <soap:address location="http://localhost:8010/samltoken/SAMLAsymSignService"/>
       </wsdl:port>
    </wsdl:service>    
    <!--                 Asymmetric Sign                 -->
    
    <!--                 Asymmetric Encr                 -->
    <wsp:Policy wsu:Id="SamlAsymEncr">
     <wsp:ExactlyOne>
            <wsp:All>
                <sp:EncryptedSupportingTokens>
                   <wsp:Policy>
                      <sp:SamlToken
                	    sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">                		
                		<wsp:Policy>
                           <sp:WssSamlV20Token11/>
                		</wsp:Policy>
          		      </sp:SamlToken>   
                   </wsp:Policy>
                </sp:EncryptedSupportingTokens>

                <sp:AsymmetricBinding>
                    <wsp:Policy>
                        <sp:InitiatorToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                                    <wsp:Policy>
                                        <sp:WssX509V3Token10/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:InitiatorToken>
                        <sp:RecipientToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                                    <wsp:Policy>
                                        <sp:WssX509V3Token10/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:RecipientToken>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:OnlySignEntireHeadersAndBody/>
                    </wsp:Policy>
                </sp:AsymmetricBinding>                
				
                <sp:SignedParts>
                    <sp:Body/>
                </sp:SignedParts>               
                                                              
            </wsp:All>
        </wsp:ExactlyOne>
   
     </wsp:Policy>

    <wsdl:binding name="SamlToken_AsymEncrBinding" type="tns:SamlTokenType">
       <wsp:PolicyReference URI="#SamlAsymEncr" />
       <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <wsdl:operation name="invoke">
          <soap:operation soapAction="" style="document"/>
          <wsdl:input name="getVerRequest">
              <soap:body use="literal"/>
          </wsdl:input>
          <wsdl:output name="getVerResponse">
              <soap:body use="literal"/>
          </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
        
    <wsdl:service name="SAMLAsymEncrService">
       <wsdl:port binding="tns:SamlToken_AsymEncrBinding" name="SAMLAsymEncrPort">
          <soap:address location="http://localhost:8010/samltoken/SAMLAsymEncrService"/>
       </wsdl:port>
    </wsdl:service>
    <!--                 Asymmetric Encr                 -->
    
    <!--                 Asymmetric Sign & Encr                 -->
    <wsp:Policy wsu:Id="SamlAsymSignEncr">
     <wsp:ExactlyOne>
            <wsp:All>
                <sp:SignedSupportingTokens>
                   <wsp:Policy>
                      <sp:SamlToken
                	    sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">                		
                		<wsp:Policy>
                           <sp:WssSamlV20Token11/>
                		</wsp:Policy>
          		      </sp:SamlToken>   
                   </wsp:Policy>
                </sp:SignedSupportingTokens>

                 <sp:AsymmetricBinding>
                    <wsp:Policy>
                        <sp:InitiatorToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                                    <wsp:Policy>
                                        <sp:WssX509V3Token10/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:InitiatorToken>
                        <sp:RecipientToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                                    <wsp:Policy>
                                        <sp:WssX509V3Token10/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:RecipientToken>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:OnlySignEntireHeadersAndBody/>
                    </wsp:Policy>
                </sp:AsymmetricBinding>               
                            
                <sp:SignedParts>
                    <sp:Body/>
                </sp:SignedParts>               
                                                              
            </wsp:All>
        </wsp:ExactlyOne>
   
     </wsp:Policy>
    
    <wsdl:binding name="SamlToken_AsymSignEncrBinding" type="tns:SamlTokenType">
       <wsp:PolicyReference URI="#SamlAsymSignEncr" />
       <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <wsdl:operation name="invoke">
          <soap:operation soapAction="" style="document"/>
          <wsdl:input name="getVerRequest">
              <soap:body use="literal"/>
          </wsdl:input>
          <wsdl:output name="getVerResponse">
              <soap:body use="literal"/>
          </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
        
    <wsdl:service name="SAMLAsymSignEncrService">
       <wsdl:port binding="tns:SamlToken_AsymSignEncrBinding" name="SAMLAsymSignEncrPort">
          <soap:address location="http://localhost:8010/samltoken/SAMLAsymSignEncrService"/>
       </wsdl:port>    
    </wsdl:service>
       <!--                 Asymmetric Sign & Encr                 -->
       
       
       <!--                 Asymmetric Sign, Encr & Timestamp                 -->
       <wsp:Policy wsu:Id="SignBodyTimeStampAndSamlPolicy">
    
       <sp:SupportingTokens>
          <wsp:Policy>
             <sp:SamlToken
                sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                <wsp:Policy>
                        <sp:WssSamlV20Token11/>
                </wsp:Policy>
             </sp:SamlToken>            
          </wsp:Policy>
       </sp:SupportingTokens>
        
       <sp:SignedElements>
          <sp:XPath>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd' and local-name()='Timestamp']</sp:XPath>
          <sp:XPath>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='urn:oasis:names:tc:SAML:2.0:assertion' and local-name()='Assertion']</sp:XPath>
       </sp:SignedElements>
    
       <sp:AsymmetricBinding>
          <wsp:Policy>
             <sp:InitiatorSignatureToken>
                <wsp:Policy>
                   <sp:X509Token
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                      <wsp:Policy>
                         <sp:WssX509V3Token10 />
                      </wsp:Policy>
                   </sp:X509Token>
                </wsp:Policy>
             </sp:InitiatorSignatureToken>
             <sp:RecipientSignatureToken>
                <wsp:Policy>
                   <sp:X509Token
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToInitiator">
                      <wsp:Policy>
                         <sp:WssX509V3Token10 />
                      </wsp:Policy>
                   </sp:X509Token>
                </wsp:Policy>
             </sp:RecipientSignatureToken>
             <sp:AlgorithmSuite>
                <wsp:Policy>
                   <sp:Basic128/>
                </wsp:Policy>
             </sp:AlgorithmSuite>
             <sp:Layout>
                <wsp:Policy>
                   <sp:Strict/>
                </wsp:Policy>
             </sp:Layout>
             <sp:IncludeTimestamp/>
             <!--sp:ProtectTokens/ -->
             <sp:OnlySignEntireHeadersAndBody/>
          </wsp:Policy>
       </sp:AsymmetricBinding>
                 
       <sp:SignedParts>
          <sp:Body/>
       </sp:SignedParts>
                               
    </wsp:Policy>
    
   <wsdl:portType name="SAMLX509AsyncType">
      <wsdl:operation name="invoke">
         <jaxws:bindings>
           <jaxws:enableAsyncMapping>true</jaxws:enableAsyncMapping>
         </jaxws:bindings>
         <wsdl:input message="tns:getVerRequest" name="getVerRequest"/>
         <wsdl:output message="tns:getVerResponse" name="getVerResponse"/>
      </wsdl:operation>
   </wsdl:portType>
    
    <wsdl:binding name="SamlToken_X509AsyncBinding" type="SAMLX509AsyncType">
       <wsp:PolicyReference URI="#SamlAsymSignEncr" />
       <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <wsdl:operation name="invoke">
          <soap:operation soapAction="" style="document"/>
          <wsdl:input name="getVerRequest">
              <soap:body use="literal"/>
          </wsdl:input>
          <wsdl:output name="getVerResponse">
              <soap:body use="literal"/>
          </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
        
    <wsdl:service name="SAMLAsyncX509Service">
       <wsdl:port binding="tns:SamlToken_AsymSignEncrBinding" name="SAMLAsyncX509Port">
          <soap:address location="http://localhost:8010/samltoken/SAMLAsyncX509Service"/>
       </wsdl:port>    
    </wsdl:service>
       <!--                 Asymmetric Sign, Encr & Timestamp                 -->
       
</wsdl:definitions>
