/*******************************************************************************
 * Copyright (c) 2017, 2025 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
repositories {
  ivy {
    url "../cnf/local"
    metadataSources {
      ivyDescriptor()
      artifact()
    }
  }
}

configurations {
  jaxrsValidator {
    transitive = false
  }
  jarA {
    transitive = false
  }
  jarB {
    transitive = false
  }
}

dependencies {
  jaxrsValidator 'com.sebastian-daschner:jaxrs-analyzer:0.9'
  jarA 'test:com.ibm.ws.cdi.visibility_fat.jarA:1.+'
  jarB 'test:com.ibm.ws.cdi.visibility_fat.jarB:1.+'
}

task addjaxrsValidator(type: Copy) {
  from configurations.jaxrsValidator
  into new File(autoFvtDir, 'lib/jaxrsvalidator')
}

task addTestBeanJarA() {
  dependsOn ':com.ibm.ws.cdi.visibility_fat.jarA:release'
  doLast {
    copy {
      from configurations.jarA
      into new File(autoFvtDir, 'beanJars')
      rename 'com.ibm.ws.cdi.visibility_fat.jarA-(.*).jar', 'jarA.jar'
    }
  }
}

task addTestBeanJarB() {
  dependsOn ':com.ibm.ws.cdi.visibility_fat.jarB:release'
  doLast {
    copy {
      from configurations.jarB
      into new File(autoFvtDir, 'beanJars')
      rename 'com.ibm.ws.cdi.visibility_fat.jarB-(.*).jar', 'jarB.jar'
    }
  }
}

//This task has a different output directory to the generic one in fat.gradle
task copyCDIFeatureBundles {
  dependsOn jar
  def projectName = project.name
  doLast {
    new File(buildDir, 'buildfiles').eachLine { String line ->
      if (!line.contains(projectName + '.jar')) {
        copy {
          from line
          into new File(autoFvtDir, 'publish/bundles')
        }
      }
    }
  }
}

addRequiredLibraries {
  dependsOn addjaxrsValidator
  dependsOn addTestBeanJarA
  dependsOn addTestBeanJarB
  dependsOn addJakartaTransformer
  dependsOn copyCDIFeatureBundles
}

