CREATE TABLE SimpleChildEntityOLGH11795 (BASE_CHILD_ID BIGINT NOT NULL, BASE_PARENT_ID BIGINT, PRIMARY KEY (BASE_CHILD_ID));
CREATE TABLE SimpleParentEntityOLGH11795 (BASE_PARENT_ID BIGINT NOT NULL, PRIMARY KEY (BASE_PARENT_ID));
CREATE INDEX I_SMPL795_PARENT ON SimpleChildEntityOLGH11795 (BASE_PARENT_ID);