INSERT INTO ${schemaname}.SimpleParentEntityOLGH11795 (BASE_PARENT_ID) VALUES (51);
INSERT INTO ${schemaname}.SimpleParentEntityOLGH11795 (BASE_PARENT_ID) VALUES (52);
INSERT INTO ${schemaname}.SimpleParentEntityOLGH11795 (BASE_PARENT_ID) VALUES (53);
INSERT INTO ${schemaname}.SimpleChildEntityOLGH11795 (BASE_CHILD_ID, BASE_PARENT_ID) VALUES (41, 51);
INSERT INTO ${schemaname}.SimpleChildEntityOLGH11795 (BASE_CHILD_ID, BASE_PARENT_ID) VALUES (42, 52);
INSERT INTO ${schemaname}.SimpleChildEntityOLGH11795 (BASE_CHILD_ID, BASE_PARENT_ID) VALUES (43, 53);