CREATE TABLE ${schemaname}.SimpleChildEntityOLGH11795 (BASE_CHILD_ID NUMERIC(32,0) NOT NULL, BASE_PARENT_ID NUMERIC(32,0), PRIMARY KEY (BASE_CHILD_ID)) LOCK MODE ROW;
CREATE TABLE ${schemaname}.SimpleParentEntityOLGH11795 (BASE_PARENT_ID NUMERIC(32,0) NOT NULL, PRIMARY KEY (BASE_PARENT_ID)) LOCK MODE ROW;
CREATE INDEX I_SMPL795_PARENT ON ${schemaname}.SimpleChildEntityOLGH11795 (BASE_PARENT_ID);