<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions 
        targetNamespace="http://wssec.basicssl.cxf.fats"
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        xmlns:apachesoap="http://xml.apache.org/xml-soap"
        xmlns:tsslns="http://wssec.basicssl.cxf.fats"
        xmlns:x1="http://wssec.basicssl.cxf.fats/types"
        xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
        xmlns:wsp="http://www.w3.org/ns/ws-policy"
        xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
        xmlns:sp13="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200802"
        xmlns:cxf="http://cxf.apache.org/core"
        xmlns:p="http://cxf.apache.org/policy"        
        xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!-- 2.1.1.1 UsernameToken with plain text password -->
    <wsp:Policy wsu:Id="UserNameToken1s">
        <sp:SupportingTokens>
            <wsp:Policy>
                <sp:UsernameToken
                    sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                    <wsp:Policy>
                       <sp:WssUsernameToken11/>
                       <!-- sp13:Created/ -->
                    </wsp:Policy>                                
                </sp:UsernameToken>
            </wsp:Policy>
        </sp:SupportingTokens>
    </wsp:Policy>
    
    <wsp:Policy wsu:Id="UserNameToken2s">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy/>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <!-- sp:IncludeTimestamp / -->
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SupportingTokens>
                    <wsp:Policy>
                        <sp:UsernameToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssUsernameToken11/>
                                <sp:HashPassword/>                                  
                                <!-- sp13:Created/>
                                <sp13:Nonce/ -->
                            </wsp:Policy>
                        </sp:UsernameToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    
        
    <wsp:Policy wsu:Id="UserNameToken3s">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy/>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SupportingTokens>
                    <wsp:Policy>
                        <sp:UsernameToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssUsernameToken10/>
                                <sp:HashPassword/>
                                <!-- Do not add sp13:Created and sp13:Nonce.
                                     otherwise, it throws exception
                                -->                                  
                                <!-- sp13:Created/>
                                <sp13:Nonce/ -->                              
                            </wsp:Policy>
                        </sp:UsernameToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>

    <wsp:Policy wsu:Id="UserNameToken4s">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                <wsp:Policy>
                                    <!--sp:RequireClientCertificate /-->
                                </wsp:Policy>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SupportingTokens>
                    <wsp:Policy>
                        <sp:UsernameToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssUsernameToken10/>
                                <sp13:Created/>
                                <sp13:Nonce/>
                            </wsp:Policy>
                        </sp:UsernameToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>

    <wsp:Policy wsu:Id="UserNameToken5s">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy/>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp />
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SupportingTokens>
                    <wsp:Policy>
                        <sp:UsernameToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssUsernameToken10/>
                                <sp13:Nonce/>
                            </wsp:Policy>
                        </sp:UsernameToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>

    <wsp:Policy wsu:Id="UserNameToken6s">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                <wsp:Policy>
                                    <!-- sp:RequireClientCertificate / -->
                                </wsp:Policy>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <!-- sp:IncludeTimestamp/ -->
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SupportingTokens>
                    <wsp:Policy>
                        <sp:UsernameToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssUsernameToken10/>
                                <sp13:Created/>
                            </wsp:Policy>
                        </sp:UsernameToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    
    <wsp:Policy wsu:Id="UserNameToken7s">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy/>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <!--sp:IncludeTimestamp /-->
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SupportingTokens>
                    <wsp:Policy>
                        <sp:UsernameToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssUsernameToken10/>
                                <sp13:Nonce/>
                            </wsp:Policy>
                        </sp:UsernameToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    
    <wsp:Policy wsu:Id="UserNameToken8s">
        <sp:SupportingTokens>
            <wsp:Policy>
                <sp:UsernameToken
                    sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                    <wsp:Policy>
                       <sp:WssUsernameToken11/>
                       <sp:NoPassword/>                       
                    </wsp:Policy>                                
                </sp:UsernameToken>
            </wsp:Policy>
        </sp:SupportingTokens>
    </wsp:Policy>
    
    <wsp:Policy wsu:Id="UserNameToken9s">
        <sp:SupportingTokens>
            <wsp:Policy>
                <sp:UsernameToken
                    sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                    <wsp:Policy>
                       <sp:WssUsernameToken11/>
                       <sp:HashPassword/>                       
                    </wsp:Policy>                                
                </sp:UsernameToken>
            </wsp:Policy>
        </sp:SupportingTokens>
    </wsp:Policy>
        
    <wsp:Policy wsu:Id="UserNameTokenbs">
        <sp:SupportingTokens>
            <wsp:Policy>
                <sp:UsernameToken
                    sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                    <wsp:Policy>
                       <sp:WssUsernameToken10/>
                       <sp13:Created/>
                    </wsp:Policy>                                
                </sp:UsernameToken>
            </wsp:Policy>
        </sp:SupportingTokens>
    </wsp:Policy>

    <wsp:Policy wsu:Id="UserNameTokencs">
        <sp:SupportingTokens>
            <wsp:Policy>
                <sp:UsernameToken
                    sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                    <wsp:Policy>
                       <sp:WssUsernameToken10/>
                       <sp13:Nonce/>
                    </wsp:Policy>                                
                </sp:UsernameToken>
            </wsp:Policy>
        </sp:SupportingTokens>
    </wsp:Policy>


    <wsp:Policy wsu:Id="UserNameTokends">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy/>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <!-- sp:IncludeTimestamp / -->
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SupportingTokens>
                    <wsp:Policy>
                        <sp:UsernameToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssUsernameToken10/>
                                <sp:NoPassword/>
                            </wsp:Policy>
                        </sp:UsernameToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    
   
    <wsdl:types>
        <xsd:schema targetNamespace="http://wssec.basicssl.cxf.fats/types">
                <xsd:element name="requestString">
                        <xsd:complexType>
                                <xsd:sequence>
                                        <xsd:element name="stringreq" type="xsd:string" />
                                </xsd:sequence>
                        </xsd:complexType>
                </xsd:element>
                <xsd:element name="responseString">
                        <xsd:complexType>
                                <xsd:sequence>
                                        <xsd:element name="stringres" type="xsd:string" />
                                </xsd:sequence>
                        </xsd:complexType>
                </xsd:element>
        </xsd:schema>
    </wsdl:types>

   <wsdl:message name="getVersionRequest">
      <wsdl:part element="x1:requestString" name="getVersion"/>
   </wsdl:message>
   <wsdl:message name="getVersionResponse">
      <wsdl:part element="x1:responseString" name="getVersionReturn" />
   </wsdl:message>

   <wsdl:portType name="FVTVersionBA">
      <wsdl:operation name="invoke">
         <wsdl:input message="tsslns:getVersionRequest" name="getVersionRequest"/>
         <wsdl:output message="tsslns:getVersionResponse" name="getVersionResponse"/>
      </wsdl:operation>
   </wsdl:portType>

   <wsdl:binding name="UrnBasicPlcyBASoapBinding" type="tsslns:FVTVersionBA">
      <wsp:PolicyReference URI="#UserNameToken1s" />
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <wsdlsoap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <wsdlsoap:body use="literal"/>
            <wsp:PolicyReference URI="#UserNameToken1s" />
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <wsdlsoap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="FVTVersionBAService">
      <wsdl:port name="UrnBasicPlcyBA" binding="tsslns:UrnBasicPlcyBASoapBinding">
         <wsdlsoap:address location="http://localhost:8010/untoken/FVTVersionBAService"/>
      </wsdl:port>
   </wsdl:service>

   <wsdl:binding name="UrnBasicPlcyBA2SoapBinding" type="tsslns:FVTVersionBA">
      <wsp:PolicyReference URI="#UserNameToken2s" />
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <wsdlsoap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <wsdlsoap:body use="literal"/>
            <wsp:PolicyReference URI="#UserNameToken2s" />
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <wsdlsoap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   
   <wsdl:service name="FVTVersionBA2Service">
      <wsdl:port name="UrnBasicPlcyBA2" binding="tsslns:UrnBasicPlcyBA2SoapBinding">
         <wsdlsoap:address location="https://localhost:8020/untoken/FVTVersionBA2Service"/>
      </wsdl:port>
   </wsdl:service>   

   <wsdl:binding name="UrnBasicPlcyBA3SoapBinding" type="tsslns:FVTVersionBA">
      <wsp:PolicyReference URI="#UserNameToken3s" />
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <wsdlsoap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <wsdlsoap:body use="literal"/>
            <wsp:PolicyReference URI="#UserNameToken3s" />
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <wsdlsoap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   
   <wsdl:service name="FVTVersionBA3Service">
      <wsdl:port name="UrnBasicPlcyBA3" binding="tsslns:UrnBasicPlcyBA3SoapBinding">
         <wsdlsoap:address location="https://localhost:8020/untoken/FVTVersionBA3Service"/>
      </wsdl:port>
   </wsdl:service>   

   <wsdl:binding name="UrnBasicPlcyBA4SoapBinding" type="tsslns:FVTVersionBA">
      <wsp:PolicyReference URI="#UserNameToken4s" />
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <wsdlsoap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <wsdlsoap:body use="literal"/>
            <wsp:PolicyReference URI="#UserNameToken4s" />
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <wsdlsoap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   
   <wsdl:service name="FVTVersionBA4Service">
      <wsdl:port name="UrnBasicPlcyBA4" binding="tsslns:UrnBasicPlcyBA4SoapBinding">
         <wsdlsoap:address location="https://localhost:8020/untoken/FVTVersionBA4Service"/>
      </wsdl:port>
   </wsdl:service>
   
   <wsdl:binding name="UrnBasicPlcyBA5SoapBinding" type="tsslns:FVTVersionBA">
      <wsp:PolicyReference URI="#UserNameToken5s" />
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <wsdlsoap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <wsdlsoap:body use="literal"/>
            <wsp:PolicyReference URI="#UserNameToken5s" />
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <wsdlsoap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   
   <wsdl:service name="FVTVersionBA5Service">
      <wsdl:port name="UrnBasicPlcyBA5" binding="tsslns:UrnBasicPlcyBA5SoapBinding">
         <wsdlsoap:address location="https://localhost:8020/untoken/FVTVersionBA5Service"/>
      </wsdl:port>
   </wsdl:service>      

   <wsdl:binding name="UrnBasicPlcyBA6SoapBinding" type="tsslns:FVTVersionBA">
      <wsp:PolicyReference URI="#UserNameToken6s" />
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <wsdlsoap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <wsdlsoap:body use="literal"/>
            <wsp:PolicyReference URI="#UserNameToken6s" />
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <wsdlsoap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   
   <wsdl:service name="FVTVersionBA6Service">
      <wsdl:port name="UrnBasicPlcyBA6" binding="tsslns:UrnBasicPlcyBA6SoapBinding">
         <wsdlsoap:address location="https://localhost:8020/untoken/FVTVersionBA6Service"/>
      </wsdl:port>
   </wsdl:service>
   
   <wsdl:binding name="UrnBasicPlcyBA7SoapBinding" type="tsslns:FVTVersionBA">
      <wsp:PolicyReference URI="#UserNameToken7s" />
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <wsdlsoap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <wsdlsoap:body use="literal"/>
            <wsp:PolicyReference URI="#UserNameToken7s" />
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <wsdlsoap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   
   <wsdl:service name="FVTVersionBA7Service">
      <wsdl:port name="UrnBasicPlcyBA7" binding="tsslns:UrnBasicPlcyBA7SoapBinding">
         <wsdlsoap:address location="https://localhost:8020/untoken/FVTVersionBA7Service"/>
      </wsdl:port>
   </wsdl:service>   
            
   <wsdl:binding name="UrnBasicPlcyBA8SoapBinding" type="tsslns:FVTVersionBA">
      <wsp:PolicyReference URI="#UserNameToken8s" />
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <wsdlsoap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <wsdlsoap:body use="literal"/>
            <wsp:PolicyReference URI="#UserNameToken8s" />
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <wsdlsoap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   
   <wsdl:service name="FVTVersionBA8Service">
      <wsdl:port name="UrnBasicPlcyBA8" binding="tsslns:UrnBasicPlcyBA8SoapBinding">
         <wsdlsoap:address location="http://localhost:8010/untoken/FVTVersionBA8Service"/>
      </wsdl:port>
   </wsdl:service>       
   
   <wsdl:binding name="UrnBasicPlcyBA9SoapBinding" type="tsslns:FVTVersionBA">
      <wsp:PolicyReference URI="#UserNameToken9s" />
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <wsdlsoap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <wsdlsoap:body use="literal"/>
            <wsp:PolicyReference URI="#UserNameToken9s" />
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <wsdlsoap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   
   <wsdl:service name="FVTVersionBA9Service">
      <wsdl:port name="UrnBasicPlcyBA9" binding="tsslns:UrnBasicPlcyBA9SoapBinding">
         <wsdlsoap:address location="http://localhost:8010/untoken/FVTVersionBA9Service"/>
      </wsdl:port>
   </wsdl:service>      

   <wsdl:binding name="UrnBasicPlcyBAbSoapBinding" type="tsslns:FVTVersionBA">
      <wsp:PolicyReference URI="#UserNameTokenbs" />
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <wsdlsoap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <wsdlsoap:body use="literal"/>
            <wsp:PolicyReference URI="#UserNameTokenbs" />
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <wsdlsoap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   
   <wsdl:service name="FVTVersionBAbService">
      <wsdl:port name="UrnBasicPlcyBAb" binding="tsslns:UrnBasicPlcyBAbSoapBinding">
         <wsdlsoap:address location="http://localhost:8010/untoken/FVTVersionBAbService"/>
      </wsdl:port>
   </wsdl:service>      

   <wsdl:binding name="UrnBasicPlcyBAcSoapBinding" type="tsslns:FVTVersionBA">
      <wsp:PolicyReference URI="#UserNameTokencs" />
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <wsdlsoap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <wsdlsoap:body use="literal"/>
            <wsp:PolicyReference URI="#UserNameTokencs" />
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <wsdlsoap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   
   <wsdl:service name="FVTVersionBAcService">
      <wsdl:port name="UrnBasicPlcyBAc" binding="tsslns:UrnBasicPlcyBAcSoapBinding">
         <wsdlsoap:address location="http://localhost:8010/untoken/FVTVersionBAcService"/>
      </wsdl:port>
   </wsdl:service>      

   <wsdl:binding name="UrnBasicPlcyBAdSoapBinding" type="tsslns:FVTVersionBA">
      <wsp:PolicyReference URI="#UserNameTokends" />
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <wsdlsoap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <wsdlsoap:body use="literal"/>
            <wsp:PolicyReference URI="#UserNameTokends" />
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <wsdlsoap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   
   <wsdl:service name="FVTVersionBAdService">
      <wsdl:port name="UrnBasicPlcyBAd" binding="tsslns:UrnBasicPlcyBAdSoapBinding">
         <wsdlsoap:address location="http://localhost:8010/untoken/FVTVersionBAdService"/>
      </wsdl:port>
   </wsdl:service>      

</wsdl:definitions>


