CREATE TABLE ${schemaname}.JPA31ENTITY (ID BIGINT NOT NULL, INTVAL1 INTEGER, INTVAL2 INTEGER, STRVAL1 VARCHAR(255), STRVAL2 VARCHAR(255), PRIMARY KEY (ID)) CCSID UNICODE;
CREATE TABLE ${schemaname}.COLTABLE1 (ent_id BIGINT, COLVAL1 VARCHAR(255)) CCSID UNICODE;
ALTER TABLE ${schemaname}.COLTABLE1 ADD CONSTRAINT COLTABLE1_ent_id FOREIGN KEY (ent_id) REFERENCES ${schemaname}.JPA31ENTITY (ID);