CREATE TABLE ElementCollectionEntityOLGH16686 (id INTEGER NOT NULL, PRIMARY KEY (id));
CREATE TABLE EntMapDateTemporal (ELEMENTCOLLECTIONENTITYOLGH16686_ID INTEGER, mykey DATE NOT NULL, temporalValue DATE);
CREATE INDEX I_NTMPPRL_ELEMENTCOLLECTIONENTITYOLGH16686_ID ON EntMapDateTemporal (ELEMENTCOLLECTIONENTITYOLGH16686_ID);