CREATE TABLE ${schemaname}.ElementCollectionEntityOLGH16686 (id INTEGER NOT NULL, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.EntMapDateTemporal (ELEMENTCOLLECTIONENTITYOLGH16686_ID INTEGER, mykey DATE NOT NULL, temporalValue DATE);
CREATE INDEX ${schemaname}.I_NTMPPRL_ELEMENTCOLLECTIONENTITYOLGH16686_ID ON ${schemaname}.EntMapDateTemporal (ELEMENTCOLLECTIONENTITYOLGH16686_ID);