<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="callertoken" targetNamespace="http://caller.libertyfat.test/contract"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:tns="http://caller.libertyfat.test/contract"
        xmlns:wsp="http://www.w3.org/ns/ws-policy"
        xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
        xmlns:wsaws="http://www.w3.org/2005/08/addressing" 
        xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
        xmlns:sp13="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200802"
        xmlns:x1="http://caller.libertyfat.test/types" >


<!--  CHC remove HasPassword -->
    <!-- bac01 Caller HTTP but encrypted UNT  -->
	<wsp:Policy wsu:Id="CallerHttpPolicy">
		<sp:SupportingTokens>
			<wsp:Policy>
				<sp:SamlToken
					sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
					<wsp:Policy>
						<sp:WssSamlV20Token11 />
					</wsp:Policy>
				</sp:SamlToken>
			</wsp:Policy>
		</sp:SupportingTokens>

	</wsp:Policy>

<!--  CHC remove Nonce & Created -->
    <!-- bac02 https protected plain UNT -->
    <wsp:Policy wsu:Id="CallerHttpsPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy/>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <!-- sp:IncludeTimestamp / -->
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SupportingTokens>
                    <wsp:Policy>
                        <sp:SamlToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV20Token11/>
                                <sp13:Created/>
                                <sp13:Nonce/>
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>

    <wsdl:types>
        <xsd:schema targetNamespace="http://caller.libertyfat.test/types">
                <xsd:element name="requestString">
                        <xsd:complexType>
                                <xsd:sequence>
                                        <xsd:element name="stringreq" type="xsd:string"/>
                                </xsd:sequence>
                        </xsd:complexType>
                </xsd:element>
                <xsd:element name="responseString">
                        <xsd:complexType>
                                <xsd:sequence>
                                        <xsd:element name="stringres" type="xsd:string"/>
                                </xsd:sequence>
                        </xsd:complexType>
                </xsd:element>
        </xsd:schema>
    </wsdl:types>

   <wsdl:message name="getVersionRequest">
      <wsdl:part element="x1:requestString" name="getVersion"/>
   </wsdl:message>
   <wsdl:message name="getVersionResponse">
      <wsdl:part element="x1:responseString" name="getVersionReturn"/>
   </wsdl:message>

   <wsdl:portType name="FVTVersionSamlC">
      <wsdl:operation name="invoke">
         <wsdl:input message="tns:getVersionRequest" name="getVersionRequest"/>
         <wsdl:output message="tns:getVersionResponse" name="getVersionResponse"/>
      </wsdl:operation>
   </wsdl:portType>

   <wsdl:binding name="SamlTokenCallerSoapBinding01" type="tns:FVTVersionSamlC">
      <wsp:PolicyReference URI="#CallerHttpPolicy"/>
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <soap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   
   <wsdl:binding name="SamlTokenCallerSoapBinding02" type="tns:FVTVersionSamlC">
      <wsp:PolicyReference URI="#CallerHttpsPolicy"/>
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <soap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="FatSamlC01Service">
      <wsdl:port name="SamlCallerToken01" binding="tns:SamlTokenCallerSoapBinding01">
         <soap:address location="http://localhost:8010/callertoken/FatSamlC01Service"/>
      </wsdl:port>
   </wsdl:service>
   
    <wsdl:service name="FatSamlC02Service">
      <wsdl:port name="SamlCallerToken02" binding="tns:SamlTokenCallerSoapBinding02">
         <soap:address location="http://localhost:8010/callertoken/FatSamlC02Service"/>
      </wsdl:port>
   </wsdl:service>

   <wsdl:service name="FatSamlC02aService">
     <wsdl:port name="SamlCallerToken02a" binding="tns:SamlTokenCallerSoapBinding02">
        <soap:address location="http://localhost:8010/callertoken/FatSamlC02aService"/>
     </wsdl:port>
  </wsdl:service>

   <!--                 Symmetric Sign                 -->
       <!-- SamlTokenCaller with plain text password -->
    <wsp:Policy wsu:Id="SamlCallerSymSign">

     <wsp:ExactlyOne>
            <wsp:All>
                <sp:SignedSupportingTokens>
                   <wsp:Policy>
                  	  <sp:SamlToken
                		sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">                		
                		<wsp:Policy>
                        	<sp:WssSamlV20Token11/>
                		</wsp:Policy>
          			  </sp:SamlToken>      
                   </wsp:Policy>
                </sp:SignedSupportingTokens>

				<sp:SymmetricBinding>
                     <wsp:Policy>
                         <sp:ProtectionToken>
                             <wsp:Policy>
                                 <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                                     <wsp:Policy>
                                         <sp:RequireThumbprintReference/>
                                         <sp:WssX509V3Token10/>
                                     </wsp:Policy>
                                 </sp:X509Token>
                             </wsp:Policy>
                         </sp:ProtectionToken>
                         <sp:AlgorithmSuite>
                             <wsp:Policy>
                                 <sp:Basic128/>
                             </wsp:Policy>
                         </sp:AlgorithmSuite>
                         <sp:Layout>
                             <wsp:Policy>
                                 <sp:Lax/>
                             </wsp:Policy>
                         </sp:Layout>
                         <sp:IncludeTimestamp/>
                         <sp:OnlySignEntireHeadersAndBody/>
                     </wsp:Policy>
                </sp:SymmetricBinding>
                <sp:Wss10>
                    <wsp:Policy>
                        <sp:MustSupportRefKeyIdentifier/>
                        <sp:MustSupportRefEncryptedKey/>
                        <sp:MustSupportRefThumbprint/>
                    </wsp:Policy>
                </sp:Wss10>
                <sp:SignedParts>
                    <sp:Body/>
                </sp:SignedParts>
               
            </wsp:All>
        </wsp:ExactlyOne>    
 
     </wsp:Policy>
     
     <wsdl:binding name="SamlTokenCaller_SymSignBinding" type="tns:FVTVersionSamlC">
       <wsp:PolicyReference URI="#SamlCallerSymSign" />
       <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <wsdl:operation name="invoke">
          <soap:operation soapAction="" style="document"/>
          <wsdl:input name="getVersionRequest">
              <soap:body use="literal"/>
          </wsdl:input>
          <wsdl:output name="getVersionResponse">
              <soap:body use="literal"/>
          </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>    
       
    <wsdl:service name="SamlCallerSymSignService">
       <wsdl:port binding="tns:SamlTokenCaller_SymSignBinding" name="SamlCallerSymSignPort">
          <soap:address location="http://localhost:8010/callertoken/SAMLCallerSymSignService"/>
       </wsdl:port>
    </wsdl:service>
    <!--                 Symmetric Sign                 -->
     
    <!--                 Symmetric Encr                 -->
        <wsp:Policy wsu:Id="SamlCallerSymEncr">
     <wsp:ExactlyOne>
            <wsp:All>
                <sp:EncryptedSupportingTokens>
                   <wsp:Policy>
                      <sp:SamlToken
                	    sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">                		
                		<wsp:Policy>
                           <sp:WssSamlV20Token11/>
                		</wsp:Policy>
          		      </sp:SamlToken>   
                   </wsp:Policy>
                </sp:EncryptedSupportingTokens>

                <sp:SymmetricBinding>
                     <wsp:Policy>
                         <sp:ProtectionToken>
                             <wsp:Policy>
                                 <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                                     <wsp:Policy>
                                         <sp:RequireThumbprintReference/>
                                         <sp:WssX509V3Token10/>
                                     </wsp:Policy>
                                 </sp:X509Token>
                             </wsp:Policy>
                         </sp:ProtectionToken>
                         <sp:AlgorithmSuite>
                             <wsp:Policy>
                                 <sp:Basic128/>
                             </wsp:Policy>
                         </sp:AlgorithmSuite>
                         <sp:Layout>
                             <wsp:Policy>
                                 <sp:Lax/>
                             </wsp:Policy>
                         </sp:Layout>
                         <sp:IncludeTimestamp/>
                         <sp:OnlySignEntireHeadersAndBody/>
                     </wsp:Policy>
                </sp:SymmetricBinding>               
               				
                <sp:SignedParts>
                    <sp:Body/>
                </sp:SignedParts>               
                                                              
            </wsp:All>
        </wsp:ExactlyOne>
   
     </wsp:Policy>

    <wsdl:binding name="SamlTokenCaller_SymEncrBinding" type="tns:FVTVersionSamlC">
       <wsp:PolicyReference URI="#SamlCallerSymEncr" />
       <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <wsdl:operation name="invoke">
          <soap:operation soapAction="" style="document"/>
          <wsdl:input name="getVersionRequest">
              <soap:body use="literal"/>
          </wsdl:input>
          <wsdl:output name="getVersionResponse">
              <soap:body use="literal"/>
          </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
        
    <wsdl:service name="SAMLCallerSymEncrService">
       <wsdl:port binding="tns:SamlTokenCaller_SymEncrBinding" name="SAMLCallerSymEncrPort">
          <soap:address location="http://localhost:8010/callertoken/SAMLCallerSymEncrService"/>
       </wsdl:port>
    </wsdl:service>
    <!--                 Symmetric Encr                 -->
    
    <!--                 Symmetric Sign & Encr                 -->
    <wsp:Policy wsu:Id="SamlCallerSymSignEncr">
     <wsp:ExactlyOne>
            <wsp:All>
                <sp:SignedEncryptedSupportingTokens>
                   <wsp:Policy>
                      <sp:SamlToken
                	    sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">                		
                		<wsp:Policy>
                           <sp:WssSamlV20Token11/>
                		</wsp:Policy>
          		      </sp:SamlToken>   
                   </wsp:Policy>
                </sp:SignedEncryptedSupportingTokens>

                <sp:SymmetricBinding>
                     <wsp:Policy>
                         <sp:ProtectionToken>
                             <wsp:Policy>
                                 <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                                     <wsp:Policy>
                                         <sp:RequireThumbprintReference/>
                                         <sp:WssX509V3Token10/>
                                     </wsp:Policy>
                                 </sp:X509Token>
                             </wsp:Policy>
                         </sp:ProtectionToken>
                         <sp:AlgorithmSuite>
                             <wsp:Policy>
                                 <sp:Basic128/>
                             </wsp:Policy>
                         </sp:AlgorithmSuite>
                         <sp:Layout>
                             <wsp:Policy>
                                 <sp:Lax/>
                             </wsp:Policy>
                         </sp:Layout>
                         <sp:IncludeTimestamp/>
                         <sp:OnlySignEntireHeadersAndBody/>
                     </wsp:Policy>
                </sp:SymmetricBinding>               
               				
                <sp:SignedParts>
                    <sp:Body/>
                </sp:SignedParts>               
                                                              
            </wsp:All>
        </wsp:ExactlyOne>
   
     </wsp:Policy>
    
    <wsdl:binding name="SamlTokenCaller_SymSignEncrBinding" type="tns:FVTVersionSamlC">
       <wsp:PolicyReference URI="#SamlCallerSymSignEncr" />
       <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <wsdl:operation name="invoke">
          <soap:operation soapAction="" style="document"/>
          <wsdl:input name="getVersionRequest">
              <soap:body use="literal"/>
          </wsdl:input>
          <wsdl:output name="getVersionResponse">
              <soap:body use="literal"/>
          </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
        
    <wsdl:service name="SAMLCallerSymSignEncrService">
       <wsdl:port binding="tns:SamlTokenCaller_SymSignEncrBinding" name="SAMLCallerSymSignEncrPort">
          <soap:address location="http://localhost:8010/callertoken/SAMLCallerSymSignEncrService"/>
       </wsdl:port>
    </wsdl:service>    
    <!--                 Symmetric Sign & Encr                 -->

    <!--                 Asymmetric Sign                 -->
    
    <wsp:Policy wsu:Id="SamlCallerAsymSign">
     <wsp:ExactlyOne>
            <wsp:All>
                <sp:SignedSupportingTokens>
                   <wsp:Policy>
                  	  <sp:SamlToken
                		sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">                		
                		<wsp:Policy>
                        	<sp:WssSamlV20Token11/>
                		</wsp:Policy>
          			  </sp:SamlToken>      
                   </wsp:Policy>
                </sp:SignedSupportingTokens>

                <sp:AsymmetricBinding >
                    <wsp:Policy>
                        <sp:InitiatorToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                                    <wsp:Policy>
                                        <sp:WssX509V3Token10/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:InitiatorToken>
                        <sp:RecipientToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                                    <wsp:Policy>
                                        <sp:WssX509V3Token10/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:RecipientToken>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:OnlySignEntireHeadersAndBody/>
                    </wsp:Policy>
                </sp:AsymmetricBinding>

                <sp:Wss10>
                    <wsp:Policy>
                        <sp:MustSupportRefKeyIdentifier/>
                    </wsp:Policy>
                </sp:Wss10>
                <sp:SignedParts>
                    <sp:Body/>
                </sp:SignedParts>
            </wsp:All>
        </wsp:ExactlyOne>    
   
    </wsp:Policy>    
    
     <wsdl:binding name="SamlTokenCaller_AsymSignBinding" type="tns:FVTVersionSamlC">
       <wsp:PolicyReference URI="#SamlCallerAsymSign" />
       <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <wsdl:operation name="invoke">
          <soap:operation soapAction="" style="document"/>
          <wsdl:input name="getVersionRequest">
              <soap:body use="literal"/>
          </wsdl:input>
          <wsdl:output name="getVersionResponse">
              <soap:body use="literal"/>
          </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>    
       
    <wsdl:service name="SAMLCallerAsymSignService">
       <wsdl:port binding="tns:SamlTokenCaller_AsymSignBinding" name="SAMLCallerAsymSignPort">
          <soap:address location="http://localhost:8010/callertoken/SAMLCallerAsymSignService"/>
       </wsdl:port>
    </wsdl:service>    
    <!--                 Asymmetric Sign                 -->
    
    <!--                 Asymmetric Encr                 -->
    <wsp:Policy wsu:Id="SamlCallerAsymEncr">
     <wsp:ExactlyOne>
            <wsp:All>
                <sp:EncryptedSupportingTokens>
                   <wsp:Policy>
                      <sp:SamlToken
                	    sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">                		
                		<wsp:Policy>
                           <sp:WssSamlV20Token11/>
                		</wsp:Policy>
          		      </sp:SamlToken>   
                   </wsp:Policy>
                </sp:EncryptedSupportingTokens>

                <sp:AsymmetricBinding>
                    <wsp:Policy>
                        <sp:InitiatorToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                                    <wsp:Policy>
                                        <sp:WssX509V3Token10/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:InitiatorToken>
                        <sp:RecipientToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                                    <wsp:Policy>
                                        <sp:WssX509V3Token10/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:RecipientToken>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:OnlySignEntireHeadersAndBody/>
                    </wsp:Policy>
                </sp:AsymmetricBinding>                
				
                <sp:SignedParts>
                    <sp:Body/>
                </sp:SignedParts>               
                                                              
            </wsp:All>
        </wsp:ExactlyOne>
   
     </wsp:Policy>

    <wsdl:binding name="SamlTokenCaller_AsymEncrBinding" type="tns:FVTVersionSamlC">
       <wsp:PolicyReference URI="#SamlCallerAsymEncr" />
       <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <wsdl:operation name="invoke">
          <soap:operation soapAction="" style="document"/>
          <wsdl:input name="getVersionRequest">
              <soap:body use="literal"/>
          </wsdl:input>
          <wsdl:output name="getVersionResponse">
              <soap:body use="literal"/>
          </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
        
    <wsdl:service name="SAMLCallerAsymEncrService">
       <wsdl:port binding="tns:SamlTokenCaller_AsymEncrBinding" name="SAMLCallerAsymEncrPort">
          <soap:address location="http://localhost:8010/callertoken/SAMLCallerAsymEncrService"/>
       </wsdl:port>
    </wsdl:service>
    <!--                 Asymmetric Encr                 -->
    
    <!--                 Asymmetric Sign & Encr                 -->
    <wsp:Policy wsu:Id="SamlCallerAsymSignEncr">
     <wsp:ExactlyOne>
            <wsp:All>
                <sp:SignedEncryptedSupportingTokens>
                   <wsp:Policy>
                      <sp:SamlToken
                	    sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">                		
                		<wsp:Policy>
                           <sp:WssSamlV20Token11/>
                		</wsp:Policy>
          		      </sp:SamlToken>   
                   </wsp:Policy>
                </sp:SignedEncryptedSupportingTokens>

                 <sp:AsymmetricBinding>
                    <wsp:Policy>
                        <sp:InitiatorToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                                    <wsp:Policy>
                                        <sp:WssX509V3Token10/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:InitiatorToken>
                        <sp:RecipientToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                                    <wsp:Policy>
                                        <sp:WssX509V3Token10/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:RecipientToken>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:OnlySignEntireHeadersAndBody/>
                    </wsp:Policy>
                </sp:AsymmetricBinding>               
                            
                <sp:SignedParts>
                    <sp:Body/>
                </sp:SignedParts>               
                                                              
            </wsp:All>
        </wsp:ExactlyOne>
   
     </wsp:Policy>
    
    <wsdl:binding name="SamlTokenCaller_AsymSignEncrBinding" type="tns:FVTVersionSamlC">
       <wsp:PolicyReference URI="#SamlCallerAsymSignEncr" />
       <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <wsdl:operation name="invoke">
          <soap:operation soapAction="" style="document"/>
          <wsdl:input name="getVersionRequest">
              <soap:body use="literal"/>
          </wsdl:input>
          <wsdl:output name="getVersionResponse">
              <soap:body use="literal"/>
          </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
        
    <wsdl:service name="FatSamlC03Service">
      <wsdl:port name="SamlCallerToken03" binding="tns:SamlTokenCaller_AsymSignEncrBinding">
         <soap:address location="http://localhost:8010/callertoken/FatSamlC03Service"/>
      </wsdl:port>
   </wsdl:service>
   
   <wsdl:service name="FatSamlC04Service">
      <wsdl:port name="SamlCallerToken04" binding="tns:SamlTokenCaller_AsymSignEncrBinding">
         <soap:address location="http://localhost:8010/callertoken/FatSamlC04Service"/>
      </wsdl:port>
   </wsdl:service>
   
    <wsdl:service name="SAMLCallerAsymSignEncrService">
       <wsdl:port binding="tns:SamlTokenCaller_AsymSignEncrBinding" name="SAMLCallerAsymSignEncrPort">
          <soap:address location="http://localhost:8010/callertoken/SAMLCallerAsymSignEncrService"/>
       </wsdl:port>    
    </wsdl:service>
       <!--                 Asymmetric Sign & Encr                 -->
       
             
    <wsp:Policy wsu:Id="SAMLTokenCallerSignEncrSecure">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                <wsp:Policy>
                                    <!-- sp:RequireClientCertificate / -->
                                </wsp:Policy>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <!-- sp:IncludeTimestamp/ -->
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SupportingTokens>
                    <wsp:Policy>
                        <sp:SamlToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV20Token11/>
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
                <sp:SymmetricBinding>
                     <wsp:Policy>
                         <sp:ProtectionToken>
                             <wsp:Policy>
                                 <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                                     <wsp:Policy>
                                         <sp:RequireThumbprintReference/>
                                         <sp:WssX509V3Token10/>
                                     </wsp:Policy>
                                 </sp:X509Token>
                             </wsp:Policy>
                         </sp:ProtectionToken>
                         <sp:AlgorithmSuite>
                             <wsp:Policy>
                                 <sp:Basic128/>
                             </wsp:Policy>
                         </sp:AlgorithmSuite>
                         <sp:Layout>
                             <wsp:Policy>
                                 <sp:Lax/>
                             </wsp:Policy>
                         </sp:Layout>
                         <sp:IncludeTimestamp/>
                         <sp:OnlySignEntireHeadersAndBody/>
                     </wsp:Policy>
                </sp:SymmetricBinding>               
               				
                <sp:SignedParts>
                    <sp:Body/>
                </sp:SignedParts>               
                                                              
          </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
             
    <wsdl:binding name="SamlTokenCaller_SymSignEncrSecureBinding" type="tns:FVTVersionSamlC">
       <wsp:PolicyReference URI="#SAMLTokenCallerSignEncrSecure" />
       <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
       <wsdl:operation name="invoke">
          <soap:operation soapAction="" style="document"/>
          <wsdl:input name="getVersionRequest">
              <soap:body use="literal"/>
          </wsdl:input>
          <wsdl:output name="getVersionResponse">
              <soap:body use="literal"/>
          </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
        
    <wsdl:service name="SAMLCallerSymSignEncrSecureService">
       <wsdl:port binding="tns:SamlTokenCaller_SymSignEncrSecureBinding" name="SAMLCallerSymSignSecureEncrPort">
          <soap:address location="https://localhost:8020/callertoken/SAMLCallerSymSignEncrSecureService"/>
       </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
