<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://echo.properties.jaxws.ibm.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="SimpleEchoService" targetNamespace="http://echo.properties.jaxws.ibm.com/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://echo.properties.jaxws.ibm.com/" elementFormDefault="unqualified" targetNamespace="http://echo.properties.jaxws.ibm.com/" version="1.0">
<xs:element name="echo" type="tns:echo"></xs:element>
<xs:element name="echoResponse" type="tns:echoResponse"></xs:element>
<xs:complexType name="echo">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:string"></xs:element>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="echoResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"></xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="echoResponse">
    <wsdl:part element="tns:echoResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="echo">
    <wsdl:part element="tns:echo" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="SimpleEcho">
    <wsdl:operation name="echo">
      <wsdl:input message="tns:echo" name="echo">
    </wsdl:input>
      <wsdl:output message="tns:echoResponse" name="echoResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SimpleEchoServiceSoapBinding" type="tns:SimpleEcho">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"></soap:binding>
    <wsdl:operation name="echo">
      <soap:operation soapAction="" style="document"></soap:operation>
      <wsdl:input name="echo">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="echoResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SimpleEchoService">
    <wsdl:port binding="tns:SimpleEchoServiceSoapBinding" name="SimpleEchoPort">
      <soap:address location="http://localhost:8010/httpConduitProperties/SimpleEchoService"></soap:address>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>