<?xml version="1.0" encoding="UTF-8"?><!--
	* This program may be used, executed, copied, modified and distributed
	* without royalty for the purpose of developing, using, marketing, or distributing.
--><wsdl:definitions name="PingService12" targetNamespace="http://com/ibm/was/wssample/sei/ping/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://com/ibm/was/wssample/sei/ping/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<xsd:schema targetNamespace="http://com/ibm/was/wssample/sei/ping/">


			<xsd:element name="pingStringInput">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="pingInput" type="xsd:string"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="pingOperationRequest">
		<wsdl:part element="tns:pingStringInput" name="parameter"/>
	</wsdl:message>
	<wsdl:portType name="PingService12PortType">
		<wsdl:operation name="pingOperation">
			<wsdl:input message="tns:pingOperationRequest"/>

		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="PingSOAP12" type="tns:PingService12PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="pingOperation">
			<soap:operation soapAction="pingOperation" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="PingService12">
		<wsdl:port binding="tns:PingSOAP12" name="PingService12Port">
			<soap:address location="http://wsi6.rtp.raleigh.ibm.com:9080/InteropService/PingService12"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>