CREATE TABLE WLPPART (ID NUMBER(19) NOT NULL, EXECUTOR NVARCHAR2(100) NOT NULL, EXPIRY NUMBER(19) NOT NULL, HOSTNAME NVARCHAR2(100) NOT NULL, LSERVER NVARCHAR2(100) NOT NULL, STATES NUMBER(19) NOT NULL, USERDIR NVARCHAR2(254) NOT NULL, PRIMARY KEY (ID))
CREATE TABLE WLPTASK (ID NUMBER(19) NOT NULL, INAME NVARCHAR2(254) NOT NULL, LOADER NVARCHAR2(254) NOT NULL, MBITS NUMBER(5) NOT NULL, NEXTEXEC NUMBER(19) NOT NULL, ORIGSUBMT NUMBER(19) NOT NULL, OWNR NVARCHAR2(120) NOT NULL, PARTN NUMBER(19) NOT NULL, PREVSCHED NUMBER(19) NULL, PREVSTART NUMBER(19) NULL, PREVSTOP NUMBER(19) NULL, RESLT BLOB NULL, RFAILS NUMBER(5) NOT NULL, STATES NUMBER(5) NOT NULL, TASKB BLOB NULL, TASKINFO BLOB NOT NULL, TRIG BLOB NULL, TXTIMEOUT NUMBER(10) NOT NULL, VERSION NUMBER(10) NOT NULL, PRIMARY KEY (ID))
CREATE TABLE WLPPROP (ID NVARCHAR2(254) NOT NULL, VAL NVARCHAR2(254) NOT NULL, PRIMARY KEY (ID))
ALTER TABLE WLPPART ADD CONSTRAINT UNQ_WLPPART_0 UNIQUE (EXECUTOR, HOSTNAME, LSERVER, USERDIR)
CREATE SEQUENCE WLPSEQ INCREMENT BY 50 START WITH 50

EXIT;