CREATE TABLE WLPPersistenceUnitEntity (ID NVARCHAR2(255) NOT NULL, VALUE NUMBER(10) NULL, PRIMARY KEY (ID))
CREATE TABLE WLPDefDSEntity (ID NUMBER(19) NOT NULL, VALUE NVARCHAR2(255) NULL, PRIMARY KEY (ID))

EXIT;