receivers:
 otlp:
   protocols:
     grpc:
      endpoint: 0.0.0.0:4317
      tls:
        cert_file: /etc/certificate.crt
        key_file: /etc/private.key
     http:

exporters:
  debug:
  otlp:
    endpoint: "jaeger-all-in-one:4317"
    tls:
      insecure: false
      insecure_skip_verify: true
      cert_file: /etc/certificate.crt
      key_file: /etc/private.key
processors:
 batch:
   timeout: 0s

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,otlp]
