receivers:
 otlp:
   protocols:
     grpc:
     http:

exporters:
 debug:
 otlp/jaeger:
   endpoint: "jaeger-all-in-one:4317" 
   tls:
      insecure: true

processors:
 batch:
   timeout: 0s

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,otlp/jaeger]