CREATE TABLE PersistenceUnitEntity (ID VARCHAR(255) NOT NULL, VALUE INTEGER, PRIMARY KEY (ID))
CREATE TABLE DefDSEntity2 (ID BIGINT NOT NULL, VALUE VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE DefDSEntity (ID BIGINT NOT NULL, VALUE VARCHAR(255), PRIMARY KEY (ID))
