CREATE TABLE PersistenceUnitEntity (ID VARCHAR NOT NULL, VAL INTEGER, PRIMARY KEY (ID));
CREATE TABLE DefDSEntity2 (ID BIGINT NOT NULL, VAL VARCHAR, PRIMARY KEY (ID));
CREATE TABLE DefDSEntity (ID BIGINT NOT NULL, VAL VARCHAR, PRIMARY KEY (ID));
