#!/bin/sh
set -e

case "$1" in
    remove|upgrade)
        echo "Removing leftover license and run directories"
        if [ -d "/usr/share/doc/openliberty" ]; then
            rm -rf /usr/share/doc/openliberty
        fi
        if [ -d "/var/run/openliberty" ]; then
            rm -rf /var/run/openliberty
        fi
        echo "Reloading systemctl services after uninstall of openliberty"
        systemctl daemon-reload
        ;;
    abort-install|abort-upgrade|purge)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        ;;
esac

#DEBHELPER#
exit 0

