/*******************************************************************************
 * Copyright (c) 2020 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/

package test.wssecfvt.derivekey;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-02-01T15:32:53.111-06:00
 * Generated source version: 2.6.2
 *
 */
@WebServiceClient(name = "DeriveKeyService7",
                  wsdlLocation = "DeriveKey.wsdl",
                  targetNamespace = "http://derivekey.wssecfvt.test")
public class DeriveKeyService7 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://derivekey.wssecfvt.test", "DeriveKeyService7");
    public final static QName DeriveKeySymmetricSignedEndorsingEncryptedPort = new QName("http://derivekey.wssecfvt.test", "DeriveKeySymmetricSignedEndorsingEncryptedPort");
    static {
        URL url = DeriveKeyService7.class.getResource("DeriveKey.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(DeriveKeyService7.class.getName()).log(java.util.logging.Level.INFO,
                                                                                      "Can not initialize the default wsdl from {0}", "DeriveKey.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DeriveKeyService7(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeriveKeyService7(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeriveKeyService7() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *         returns DeriveKeyPortType
     */
    @WebEndpoint(name = "DeriveKeySymmetricSignedEndorsingEncryptedPort")
    public DeriveKeyPortType getDeriveKeySymmetricSignedEndorsingEncryptedPort() {
        return super.getPort(DeriveKeySymmetricSignedEndorsingEncryptedPort, DeriveKeyPortType.class);
    }

    /**
     *
     * @param features
     *                     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will have their
     *                     default values.
     * @return
     *         returns DeriveKeyPortType
     */
    @WebEndpoint(name = "DeriveKeySymmetricSignedEndorsingEncryptedPort")
    public DeriveKeyPortType getDeriveKeySymmetricSignedEndorsingEncryptedPort(WebServiceFeature... features) {
        return super.getPort(DeriveKeySymmetricSignedEndorsingEncryptedPort, DeriveKeyPortType.class, features);
    }

}
