package com.ibm.samples.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "SecuredSayHelloService", targetNamespace = "http://jaxws.samples.ibm.com", wsdlLocation = "WEB-INF/wsdl/SecuredSayHelloService.wsdl")
public class SecuredSayHelloService extends Service {

	private final static URL SECUREDSAYHELLOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ibm.samples.jaxws.SecuredSayHelloService.class.getName());

	static {
		URL url = null;
		try {
			url = new URL("file://WEB-INF/wsdl/SecuredSayHelloService.wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'SecuredSayHelloService.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SECUREDSAYHELLOSERVICE_WSDL_LOCATION = url;
	}

	public SecuredSayHelloService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SecuredSayHelloService() {
		super(SECUREDSAYHELLOSERVICE_WSDL_LOCATION,
				new QName("http://jaxws.samples.ibm.com", "SecuredSayHelloService"));
	}

	/**
	 * 
	 * @return returns SayHello
	 */
	@WebEndpoint(name = "SayHelloStalelessPort")
	public SayHello getSayHelloStalelessPort() {
		return super.getPort(new QName("http://jaxws.samples.ibm.com", "SayHelloStalelessPort"), SayHello.class);
	}

	/**
	 * 
	 * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *                 on the proxy. Supported features not in the
	 *                 <code>features</code> parameter will have their default
	 *                 values.
	 * @return returns SayHello
	 */
	@WebEndpoint(name = "SayHelloStalelessPort")
	public SayHello getSayHelloStalelessPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://jaxws.samples.ibm.com", "SayHelloStalelessPort"), SayHello.class,
				features);
	}

}
