/*******************************************************************************
 * Copyright (c) 2022 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package jaxb.web.utils;

/**
 *
 */
public class JAXBXMLSchemaConstants {

    public static final String EXPECTED_PURCHASEORDERTYPE_MARSHALLED_RESULT = "<PurchaseOrderType xmlns=\"https://jaxb.web.dataobjects/\" xmlns:ns0=\"http://jaxb.web.dataobjects/\" orderDate=\"2018-09-09-05:00\">\n"
                                                                              + "   <shipTo country=\"United States\">\n"
                                                                              + "      <name>Test Name</name>\n"
                                                                              + "      <street>505 E Maple</street>\n"
                                                                              + "      <city>Austin</city>\n"
                                                                              + "      <state>Texas</state>\n"
                                                                              + "      <zip>77777</zip>\n"
                                                                              + "   </shipTo>\n"
                                                                              + "   <billTo country=\"United States\">\n"
                                                                              + "      <name>Test Name</name>\n"
                                                                              + "      <street>505 E Maple</street>\n"
                                                                              + "      <city>Austin</city>\n"
                                                                              + "      <state>Texas</state>\n"
                                                                              + "      <zip>77777</zip>\n"
                                                                              + "   </billTo>\n"
                                                                              + "   <comment>New Order</comment>\n"
                                                                              + "   <items>\n"
                                                                              + "      <item>\n"
                                                                              + "         <productName>Test Product</productName>\n"
                                                                              + "         <quantity>15</quantity>\n"
                                                                              + "         <Price>59872326</Price>\n"
                                                                              + "         <comment>I'm a test product</comment>\n"
                                                                              + "         <shipDate>2018-09-09-05:00</shipDate>\n"
                                                                              + "      </item>\n"
                                                                              + "      <item>\n"
                                                                              + "         <productName>Test Product 2</productName>\n"
                                                                              + "         <quantity>1251</quantity>\n"
                                                                              + "         <Price>135165.999999999883584678173065185546875</Price>\n"
                                                                              + "         <comment>I'm another test product</comment>\n"
                                                                              + "         <shipDate>2018-09-09-05:00</shipDate>\n"
                                                                              + "      </item>\n"
                                                                              + "      <itemNames>Test Product Test Product 2</itemNames>\n"
                                                                              + "   </items>\n"
                                                                              + "</PurchaseOrderType>";

    public static final String EXPECTED_ITEM_MARSHALLED_RESULT = "<ns0:items xmlns:ns0=\"https://jaxb.web.dataobjects/\">\n"
                                                                 + "   <ns0:item>\n"
                                                                 + "      <ns0:productName>Test Product</ns0:productName>\n"
                                                                 + "      <ns0:quantity>15</ns0:quantity>\n"
                                                                 + "      <ns0:Price>59872326</ns0:Price>\n"
                                                                 + "      <ns0:comment>I'm a test product</ns0:comment>\n"
                                                                 + "      <ns0:shipDate>2018-09-09-05:00</ns0:shipDate>\n"
                                                                 + "   </ns0:item>\n"
                                                                 + "   <ns0:item>\n"
                                                                 + "      <ns0:productName>Test Product 2</ns0:productName>\n"
                                                                 + "      <ns0:quantity>1251</ns0:quantity>\n"
                                                                 + "      <ns0:Price>135165.999999999883584678173065185546875</ns0:Price>\n"
                                                                 + "      <ns0:comment>I'm another test product</ns0:comment>\n"
                                                                 + "      <ns0:shipDate>2018-09-09-05:00</ns0:shipDate>\n"
                                                                 + "   </ns0:item>\n"
                                                                 + "</ns0:items>";

    public static final String EXPECTED_SHIPPINGADDRESS_MARSHALLED_RESULT = "<ns0:ShippingAddress xmlns:ns0=\"https://jaxb.web.dataobjects/\" country=\"United States\">\n"
                                                                            + "   <ns0:name>Test Name</ns0:name>\n"
                                                                            + "   <ns0:street>505 E Maple</ns0:street>\n"
                                                                            + "   <ns0:city>Austin</ns0:city>\n"
                                                                            + "   <ns0:state>Texas</ns0:state>\n"
                                                                            + "   <ns0:zip>77777</ns0:zip>\n"
                                                                            + "</ns0:ShippingAddress>";

    public final static String EXPECTED_MOXY_SCHEMA_VALUE = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                                                            + "<xsd:schema xmlns:ns0=\"http://jaxb.web.dataobjects/\" xmlns:ns1=\"https://jaxb.web.dataobjects/\" xmlns:ref=\"http://ws-i.org/profiles/basic/1.1/xsd\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" targetNamespace=\"https://jaxb.web.dataobjects/\" elementFormDefault=\"qualified\">\n"
                                                            + "   <xsd:import schemaLocation=\"http://ws-i.org/profiles/basic/1.1/swaref.xsd\" namespace=\"http://ws-i.org/profiles/basic/1.1/xsd\"/>\n"
                                                            + "   <xsd:complexType name=\"Image\">\n"
                                                            + "      <xsd:sequence>\n"
                                                            + "         <xsd:element name=\"name\" type=\"xsd:string\" minOccurs=\"0\"/>\n"
                                                            + "         <xsd:element name=\"imageHandler\" type=\"ref:swaRef\" minOccurs=\"0\" xmlns:ns2=\"http://www.w3.org/2005/05/xmlmime\" ns2:expectedContentTypes=\"application/octet-stream\"/>\n"
                                                            + "         <xsd:element name=\"imageBytes\" type=\"xsd:string\" minOccurs=\"0\"/>\n"
                                                            + "      </xsd:sequence>\n"
                                                            + "   </xsd:complexType>\n"
                                                            + "   <xsd:complexType name=\"Items\">\n"
                                                            + "      <xsd:sequence>\n"
                                                            + "         <xsd:element name=\"item\" maxOccurs=\"unbounded\">\n"
                                                            + "            <xsd:complexType>\n"
                                                            + "               <xsd:sequence>\n"
                                                            + "                  <xsd:element name=\"productName\" type=\"xsd:string\"/>\n"
                                                            + "                  <xsd:element name=\"quantity\" type=\"xsd:int\"/>\n"
                                                            + "                  <xsd:element name=\"Price\" type=\"xsd:decimal\"/>\n"
                                                            + "                  <xsd:element name=\"comment\" type=\"xsd:string\" minOccurs=\"0\"/>\n"
                                                            + "                  <xsd:element name=\"shipDate\" type=\"xsd:date\" minOccurs=\"0\"/>\n"
                                                            + "               </xsd:sequence>\n"
                                                            + "               <xsd:attribute name=\"partNum\" type=\"xsd:string\" use=\"required\"/>\n"
                                                            + "            </xsd:complexType>\n"
                                                            + "         </xsd:element>\n"
                                                            + "         <xsd:element name=\"itemNames\" minOccurs=\"0\">\n"
                                                            + "            <xsd:simpleType>\n"
                                                            + "               <xsd:list itemType=\"xsd:string\"/>\n"
                                                            + "            </xsd:simpleType>\n"
                                                            + "         </xsd:element>\n"
                                                            + "      </xsd:sequence>\n"
                                                            + "   </xsd:complexType>\n"
                                                            + "   <xsd:complexType name=\"PurchaseOrderType\">\n"
                                                            + "      <xsd:sequence>\n"
                                                            + "         <xsd:element name=\"shipTo\" type=\"ns1:ShippingAddress\"/>\n"
                                                            + "         <xsd:element name=\"billTo\" type=\"ns1:ShippingAddress\"/>\n"
                                                            + "         <xsd:element name=\"comment\" type=\"xsd:string\" minOccurs=\"0\"/>\n"
                                                            + "         <xsd:element name=\"items\" type=\"ns1:Items\"/>\n"
                                                            + "      </xsd:sequence>\n"
                                                            + "      <xsd:attribute name=\"orderDate\" type=\"xsd:date\"/>\n"
                                                            + "   </xsd:complexType>\n"
                                                            + "   <xsd:complexType name=\"ShippingAddress\">\n"
                                                            + "      <xsd:sequence>\n"
                                                            + "         <xsd:element name=\"name\" type=\"xsd:string\"/>\n"
                                                            + "         <xsd:element name=\"street\" type=\"xsd:string\"/>\n"
                                                            + "         <xsd:element name=\"city\" type=\"xsd:string\"/>\n"
                                                            + "         <xsd:element name=\"state\" type=\"xsd:string\"/>\n"
                                                            + "         <xsd:element name=\"zip\" type=\"xsd:decimal\"/>\n"
                                                            + "      </xsd:sequence>\n"
                                                            + "      <xsd:attribute name=\"country\" type=\"xsd:NMTOKEN\"/>\n"
                                                            + "   </xsd:complexType>\n"
                                                            + "   <xsd:element name=\"items\" type=\"ns1:Items\"/>\n"
                                                            + "   <xsd:element name=\"PurchaseOrderType\" type=\"ns1:PurchaseOrderType\"/>\n"
                                                            + "   <xsd:element name=\"ShippingAddress\" type=\"ns1:ShippingAddress\"/>\n"
                                                            + "   <xsd:element name=\"Items\" type=\"ns1:Items\"/>\n"
                                                            + "   <xsd:element name=\"Image\" type=\"ns1:Image\"/>\n"
                                                            + "</xsd:schema>";

    public final static String EXPECTED_RI_SCHEMA_VALUE = "<?xml version=\"1.0\" standalone=\"yes\"?>\n"
                                                          + "<xs:schema elementFormDefault=\"qualified\" version=\"1.0\" targetNamespace=\"https://jaxb.web.dataobjects/\" xmlns:swaRef=\"http://ws-i.org/profiles/basic/1.1/xsd\" xmlns:xmime=\"http://www.w3.org/2005/05/xmlmime\" xmlns:tns=\"https://jaxb.web.dataobjects/\" xmlns:ns0=\"http://jaxb.web.dataobjects/\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\n"
                                                          + "\n"
                                                          + "  <xs:import namespace=\"http://ws-i.org/profiles/basic/1.1/xsd\" schemaLocation=\"http://ws-i.org/profiles/basic/1.1/swaref.xsd\"/>\n"
                                                          + "  <xs:import namespace=\"http://www.w3.org/2005/05/xmlmime\" schemaLocation=\"http://www.w3.org/2005/05/xmlmime\"/>\n"
                                                          + "  <xs:element name=\"Image\" type=\"tns:Image\"/>\n"
                                                          + "\n"
                                                          + "  <xs:element name=\"Items\" type=\"tns:Items\"/>\n"
                                                          + "\n"
                                                          + "  <xs:element name=\"PurchaseOrderType\" type=\"tns:PurchaseOrderType\"/>\n"
                                                          + "\n"
                                                          + "  <xs:element name=\"ShippingAddress\" type=\"tns:ShippingAddress\"/>\n"
                                                          + "\n"
                                                          + "  <xs:element name=\"items\" type=\"tns:Items\"/>\n"
                                                          + "\n"
                                                          + "  <xs:complexType name=\"Image\">\n"
                                                          + "    <xs:sequence>\n"
                                                          + "      <xs:element name=\"name\" type=\"xs:string\" minOccurs=\"0\"/>\n"
                                                          + "      <xs:element name=\"imageHandler\" xmime:expectedContentTypes=\"application/octet-stream\" type=\"swaRef:swaRef\" minOccurs=\"0\"/>\n"
                                                          + "      <xs:element name=\"imageBytes\" type=\"xs:string\" minOccurs=\"0\"/>\n"
                                                          + "    </xs:sequence>\n"
                                                          + "  </xs:complexType>\n"
                                                          + "\n"
                                                          + "  <xs:complexType name=\"Items\">\n"
                                                          + "    <xs:sequence>\n"
                                                          + "      <xs:element name=\"item\" maxOccurs=\"unbounded\">\n"
                                                          + "        <xs:complexType>\n"
                                                          + "          <xs:sequence>\n"
                                                          + "            <xs:element name=\"productName\" type=\"xs:string\"/>\n"
                                                          + "            <xs:element name=\"quantity\" type=\"xs:int\"/>\n"
                                                          + "            <xs:element name=\"Price\" type=\"xs:decimal\"/>\n"
                                                          + "            <xs:element name=\"comment\" type=\"xs:string\" minOccurs=\"0\"/>\n"
                                                          + "            <xs:element name=\"shipDate\" type=\"xs:date\" minOccurs=\"0\"/>\n"
                                                          + "          </xs:sequence>\n"
                                                          + "          <xs:attribute name=\"partNum\" type=\"xs:string\" use=\"required\"/>\n"
                                                          + "        </xs:complexType>\n"
                                                          + "      </xs:element>\n"
                                                          + "      <xs:element name=\"itemNames\" minOccurs=\"0\">\n"
                                                          + "        <xs:simpleType>\n"
                                                          + "          <xs:list itemType=\"xs:string\"/>\n"
                                                          + "        </xs:simpleType>\n"
                                                          + "      </xs:element>\n"
                                                          + "    </xs:sequence>\n"
                                                          + "  </xs:complexType>\n"
                                                          + "\n"
                                                          + "  <xs:complexType name=\"PurchaseOrderType\">\n"
                                                          + "    <xs:sequence>\n"
                                                          + "      <xs:element name=\"shipTo\" type=\"tns:ShippingAddress\"/>\n"
                                                          + "      <xs:element name=\"billTo\" type=\"tns:ShippingAddress\"/>\n"
                                                          + "      <xs:element name=\"comment\" type=\"xs:string\" minOccurs=\"0\"/>\n"
                                                          + "      <xs:element ref=\"tns:items\"/>\n"
                                                          + "    </xs:sequence>\n"
                                                          + "    <xs:attribute name=\"orderDate\" type=\"xs:date\"/>\n"
                                                          + "  </xs:complexType>\n"
                                                          + "\n"
                                                          + "  <xs:complexType name=\"ShippingAddress\">\n"
                                                          + "    <xs:sequence>\n"
                                                          + "      <xs:element name=\"name\" type=\"xs:string\"/>\n"
                                                          + "      <xs:element name=\"street\" type=\"xs:string\"/>\n"
                                                          + "      <xs:element name=\"city\" type=\"xs:string\"/>\n"
                                                          + "      <xs:element name=\"state\" type=\"xs:string\"/>\n"
                                                          + "      <xs:element name=\"zip\" type=\"xs:decimal\"/>\n"
                                                          + "    </xs:sequence>\n"
                                                          + "    <xs:attribute name=\"country\" type=\"xs:NMTOKEN\"/>\n"
                                                          + "  </xs:complexType>\n"
                                                          + "</xs:schema>\n";

    public static final String EXPECTED_RI_PURCHASEORDERTYPE_MARSHALLED_RESULT = "<ns0:PurchaseOrderType orderDate=\"1969-12-31-06:00\" xmlns:ns0=\"https://jaxb.web.dataobjects/\">\n"
                                                                                 + "    <ns0:shipTo country=\"United States\">\n"
                                                                                 + "        <ns0:name>Test Name</ns0:name>\n"
                                                                                 + "        <ns0:street>505 E Maple</ns0:street>\n"
                                                                                 + "        <ns0:city>Austin</ns0:city>\n"
                                                                                 + "        <ns0:state>Texas</ns0:state>\n"
                                                                                 + "        <ns0:zip>77777</ns0:zip>\n"
                                                                                 + "    </ns0:shipTo>\n"
                                                                                 + "    <ns0:billTo country=\"United States\">\n"
                                                                                 + "        <ns0:name>Test Name</ns0:name>\n"
                                                                                 + "        <ns0:street>505 E Maple</ns0:street>\n"
                                                                                 + "        <ns0:city>Austin</ns0:city>\n"
                                                                                 + "        <ns0:state>Texas</ns0:state>\n"
                                                                                 + "        <ns0:zip>77777</ns0:zip>\n"
                                                                                 + "    </ns0:billTo>\n"
                                                                                 + "    <ns0:comment>New Order</ns0:comment>\n"
                                                                                 + "    <ns0:items>\n"
                                                                                 + "        <ns0:item>\n"
                                                                                 + "            <ns0:productName>Test Product</ns0:productName>\n"
                                                                                 + "            <ns0:quantity>15</ns0:quantity>\n"
                                                                                 + "            <ns0:Price>59872326</ns0:Price>\n"
                                                                                 + "            <ns0:comment>I'm a test product</ns0:comment>\n"
                                                                                 + "            <ns0:shipDate>2018-09-09-05:00</ns0:shipDate>\n"
                                                                                 + "        </ns0:item>\n"
                                                                                 + "        <ns0:item>\n"
                                                                                 + "            <ns0:productName>Test Product 2</ns0:productName>\n"
                                                                                 + "            <ns0:quantity>1251</ns0:quantity>\n"
                                                                                 + "            <ns0:Price>135165.999999999883584678173065185546875</ns0:Price>\n"
                                                                                 + "            <ns0:comment>I'm another test product</ns0:comment>\n"
                                                                                 + "            <ns0:shipDate>2018-09-09-05:00</ns0:shipDate>\n"
                                                                                 + "        </ns0:item>\n"
                                                                                 + "        <ns0:itemNames>Test Product Test Product 2</ns0:itemNames>\n"
                                                                                 + "    </ns0:items>\n"
                                                                                 + "</ns0:PurchaseOrderType>";

}
