/*******************************************************************************
 * Copyright (c) 2022 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package jaxb.web.utils;

/**
 *
 */
public class JAXBXMLSchemaConstants {

    public static final String EXPECTED_PURCHASEORDERTYPE_MARSHALLED_RESULT = "<ns0:PurchaseOrderType xmlns:ns0=\"http://jaxb.web.dataobjects/\" orderDate=\"2018-09-09\">\n"
                                                                              + "   <ns0:shipTo country=\"United States\">\n"
                                                                              + "      <ns0:name>Test Name</ns0:name>\n"
                                                                              + "      <ns0:street>505 E Maple</ns0:street>\n"
                                                                              + "      <ns0:city>Austin</ns0:city>\n"
                                                                              + "      <ns0:state>Texas</ns0:state>\n"
                                                                              + "      <ns0:zip>77777</ns0:zip>\n"
                                                                              + "   </ns0:shipTo>\n"
                                                                              + "   <ns0:billTo country=\"United States\">\n"
                                                                              + "      <ns0:name>Test Name</ns0:name>\n"
                                                                              + "      <ns0:street>505 E Maple</ns0:street>\n"
                                                                              + "      <ns0:city>Austin</ns0:city>\n"
                                                                              + "      <ns0:state>Texas</ns0:state>\n"
                                                                              + "      <ns0:zip>77777</ns0:zip>\n"
                                                                              + "   </ns0:billTo>\n"
                                                                              + "   <ns0:comment>New Order</ns0:comment>\n"
                                                                              + "   <ns0:items>\n"
                                                                              + "      <ns0:item>\n"
                                                                              + "         <ns0:productName>Test Product</ns0:productName>\n"
                                                                              + "         <ns0:quantity>15</ns0:quantity>\n"
                                                                              + "         <ns0:Price>59872326</ns0:Price>\n"
                                                                              + "         <ns0:comment>I'm a test product</ns0:comment>\n"
                                                                              + "         <ns0:shipDate>2018-09-09</ns0:shipDate>\n"
                                                                              + "      </ns0:item>\n"
                                                                              + "      <ns0:item>\n"
                                                                              + "         <ns0:productName>Test Product 2</ns0:productName>\n"
                                                                              + "         <ns0:quantity>1251</ns0:quantity>\n"
                                                                              + "         <ns0:Price>135165.999999999883584678173065185546875</ns0:Price>\n"
                                                                              + "         <ns0:comment>I'm another test product</ns0:comment>\n"
                                                                              + "         <ns0:shipDate>2018-09-09</ns0:shipDate>\n"
                                                                              + "      </ns0:item>\n"
                                                                              + "      <ns0:itemNames>Test Product Test Product 2</ns0:itemNames>\n"
                                                                              + "   </ns0:items>\n"
                                                                              + "</ns0:PurchaseOrderType>";

    public static final String EXPECTED_ITEM_MARSHALLED_RESULT = "<ns0:items xmlns:ns0=\"http://jaxb.web.dataobjects/\">\n"
                                                                 + "   <ns0:item>\n"
                                                                 + "      <ns0:productName>Test Product</ns0:productName>\n"
                                                                 + "      <ns0:quantity>15</ns0:quantity>\n"
                                                                 + "      <ns0:Price>59872326</ns0:Price>\n"
                                                                 + "      <ns0:comment>I'm a test product</ns0:comment>\n"
                                                                 + "      <ns0:shipDate>2018-09-09-05:00</ns0:shipDate>\n"
                                                                 + "   </ns0:item>\n"
                                                                 + "   <ns0:item>\n"
                                                                 + "      <ns0:productName>Test Product 2</ns0:productName>\n"
                                                                 + "      <ns0:quantity>1251</ns0:quantity>\n"
                                                                 + "      <ns0:Price>135165.999999999883584678173065185546875</ns0:Price>\n"
                                                                 + "      <ns0:comment>I'm another test product</ns0:comment>\n"
                                                                 + "      <ns0:shipDate>2018-09-09-05:00</ns0:shipDate>\n"
                                                                 + "   </ns0:item>\n"
                                                                 + "</ns0:items>";

    public static final String EXPECTED_SHIPPINGADDRESS_MARSHALLED_RESULT = "<ns0:ShippingAddress xmlns:ns0=\"http://jaxb.web.dataobjects/\" country=\"United States\">\n"
                                                                            + "   <ns0:name>Test Name</ns0:name>\n"
                                                                            + "   <ns0:street>505 E Maple</ns0:street>\n"
                                                                            + "   <ns0:city>Austin</ns0:city>\n"
                                                                            + "   <ns0:state>Texas</ns0:state>\n"
                                                                            + "   <ns0:zip>77777</ns0:zip>\n"
                                                                            + "</ns0:ShippingAddress>";

    public final static String EXPECTED_MOXY_SCHEMA_VALUE = "<xsd:schema xmlns:ns0=\"http://jaxb.web.dataobjects/\" xmlns:ref=\"http://ws-i.org/profiles/basic/1.1/xsd\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" targetNamespace=\"http://jaxb.web.dataobjects/\" elementFormDefault=\"qualified\">\n"
                                                            + "   <xsd:import schemaLocation=\"http://ws-i.org/profiles/basic/1.1/swaref.xsd\" namespace=\"http://ws-i.org/profiles/basic/1.1/xsd\"/>\n"
                                                            + "   <xsd:complexType name=\"Image\">\n"
                                                            + "      <xsd:sequence>\n"
                                                            + "         <xsd:element name=\"name\" type=\"xsd:string\" minOccurs=\"0\"/>\n"
                                                            + "         <xsd:element name=\"imageHandler\" type=\"ref:swaRef\" minOccurs=\"0\" xmlns:ns1=\"http://www.w3.org/2005/05/xmlmime\" ns1:expectedContentTypes=\"application/octet-stream\"/>\n"
                                                            + "         <xsd:element name=\"imageBytes\" type=\"xsd:string\" minOccurs=\"0\"/>\n"
                                                            + "      </xsd:sequence>\n"
                                                            + "   </xsd:complexType>\n"
                                                            + "   <xsd:complexType name=\"Items\">\n"
                                                            + "      <xsd:sequence>\n"
                                                            + "         <xsd:element name=\"item\" maxOccurs=\"unbounded\">\n"
                                                            + "            <xsd:complexType>\n"
                                                            + "               <xsd:sequence>\n"
                                                            + "                  <xsd:element name=\"productName\" type=\"xsd:string\"/>\n"
                                                            + "                  <xsd:element name=\"quantity\" type=\"xsd:int\"/>\n"
                                                            + "                  <xsd:element name=\"Price\" type=\"xsd:decimal\"/>\n"
                                                            + "                  <xsd:element name=\"comment\" type=\"xsd:string\" minOccurs=\"0\"/>\n"
                                                            + "                  <xsd:element name=\"shipDate\" type=\"xsd:date\" minOccurs=\"0\"/>\n"
                                                            + "               </xsd:sequence>\n"
                                                            + "               <xsd:attribute name=\"partNum\" type=\"xsd:string\" use=\"required\"/>\n"
                                                            + "            </xsd:complexType>\n"
                                                            + "         </xsd:element>\n"
                                                            + "         <xsd:element name=\"itemNames\" minOccurs=\"0\">\n"
                                                            + "            <xsd:simpleType>\n"
                                                            + "               <xsd:list itemType=\"xsd:string\"/>\n"
                                                            + "            </xsd:simpleType>\n"
                                                            + "         </xsd:element>\n"
                                                            + "      </xsd:sequence>\n"
                                                            + "   </xsd:complexType>\n"
                                                            + "   <xsd:complexType name=\"PurchaseOrderType\">\n"
                                                            + "      <xsd:sequence>\n"
                                                            + "         <xsd:element name=\"shipTo\" type=\"ns0:ShippingAddress\"/>\n"
                                                            + "         <xsd:element name=\"billTo\" type=\"ns0:ShippingAddress\"/>\n"
                                                            + "         <xsd:element name=\"comment\" type=\"xsd:string\" minOccurs=\"0\"/>\n"
                                                            + "         <xsd:element name=\"items\" type=\"ns0:Items\"/>\n"
                                                            + "      </xsd:sequence>\n"
                                                            + "      <xsd:attribute name=\"orderDate\" type=\"xsd:date\"/>\n"
                                                            + "   </xsd:complexType>\n"
                                                            + "   <xsd:complexType name=\"ShippingAddress\">\n"
                                                            + "      <xsd:sequence>\n"
                                                            + "         <xsd:element name=\"name\" type=\"xsd:string\"/>\n"
                                                            + "         <xsd:element name=\"street\" type=\"xsd:string\"/>\n"
                                                            + "         <xsd:element name=\"city\" type=\"xsd:string\"/>\n"
                                                            + "         <xsd:element name=\"state\" type=\"xsd:string\"/>\n"
                                                            + "         <xsd:element name=\"zip\" type=\"xsd:decimal\"/>\n"
                                                            + "      </xsd:sequence>\n"
                                                            + "      <xsd:attribute name=\"country\" type=\"xsd:NMTOKEN\"/>\n"
                                                            + "   </xsd:complexType>\n"
                                                            + "   <xsd:element name=\"items\" type=\"ns0:Items\"/>\n"
                                                            + "   <xsd:element name=\"Items\" type=\"ns0:Items\"/>\n"
                                                            + "   <xsd:element name=\"Image\" type=\"ns0:Image\"/>\n"
                                                            + "   <xsd:element name=\"PurchaseOrderType\" type=\"ns0:PurchaseOrderType\"/>\n"
                                                            + "   <xsd:element name=\"ShippingAddress\" type=\"ns0:ShippingAddress\"/>\n"
                                                            + "</xsd:schema>";

    public final static String EXPECTED_RI_SCHEMA_VALUE = "<xsd:schema xmlns:ns0=\"http://jaxb.web.dataobjects/\" xmlns:ref=\"http://ws-i.org/profiles/basic/1.1/xsd\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" targetNamespace=\"http://jaxb.web.dataobjects/\" elementFormDefault=\"qualified\">\n"
                                                          + "   <xsd:import schemaLocation=\"http://ws-i.org/profiles/basic/1.1/swaref.xsd\" namespace=\"http://ws-i.org/profiles/basic/1.1/xsd\"/>\n"
                                                          + "   <xsd:complexType name=\"Image\">\n"
                                                          + "      <xsd:sequence>\n"
                                                          + "         <xsd:element name=\"name\" type=\"xsd:string\" minOccurs=\"0\"/>\n"
                                                          + "         <xsd:element name=\"imageHandler\" type=\"ref:swaRef\" minOccurs=\"0\" xmlns:ns1=\"http://www.w3.org/2005/05/xmlmime\" ns1:expectedContentTypes=\"application/octet-stream\"/>\n"
                                                          + "         <xsd:element name=\"imageBytes\" type=\"xsd:string\" minOccurs=\"0\"/>\n"
                                                          + "      </xsd:sequence>\n"
                                                          + "   </xsd:complexType>\n"
                                                          + "   <xsd:complexType name=\"Items\">\n"
                                                          + "      <xsd:sequence>\n"
                                                          + "         <xsd:element name=\"item\" maxOccurs=\"unbounded\">\n"
                                                          + "            <xsd:complexType>\n"
                                                          + "               <xsd:sequence>\n"
                                                          + "                  <xsd:element name=\"productName\" type=\"xsd:string\"/>\n"
                                                          + "                  <xsd:element name=\"quantity\" type=\"xsd:int\"/>\n"
                                                          + "                  <xsd:element name=\"Price\" type=\"xsd:decimal\"/>\n"
                                                          + "                  <xsd:element name=\"comment\" type=\"xsd:string\" minOccurs=\"0\"/>\n"
                                                          + "                  <xsd:element name=\"shipDate\" type=\"xsd:date\" minOccurs=\"0\"/>\n"
                                                          + "               </xsd:sequence>\n"
                                                          + "               <xsd:attribute name=\"partNum\" type=\"xsd:string\" use=\"required\"/>\n"
                                                          + "            </xsd:complexType>\n"
                                                          + "         </xsd:element>\n"
                                                          + "         <xsd:element name=\"itemNames\" minOccurs=\"0\">\n"
                                                          + "            <xsd:simpleType>\n"
                                                          + "               <xsd:list itemType=\"xsd:string\"/>\n"
                                                          + "            </xsd:simpleType>\n"
                                                          + "         </xsd:element>\n"
                                                          + "      </xsd:sequence>\n"
                                                          + "   </xsd:complexType>\n"
                                                          + "   <xsd:complexType name=\"PurchaseOrderType\">\n"
                                                          + "      <xsd:sequence>\n"
                                                          + "         <xsd:element name=\"shipTo\" type=\"ns0:ShippingAddress\"/>\n"
                                                          + "         <xsd:element name=\"billTo\" type=\"ns0:ShippingAddress\"/>\n"
                                                          + "         <xsd:element name=\"comment\" type=\"xsd:string\" minOccurs=\"0\"/>\n"
                                                          + "         <xsd:element name=\"items\" type=\"ns0:Items\"/>\n"
                                                          + "      </xsd:sequence>\n"
                                                          + "      <xsd:attribute name=\"orderDate\" type=\"xsd:date\"/>\n"
                                                          + "   </xsd:complexType>\n"
                                                          + "   <xsd:complexType name=\"ShippingAddress\">\n"
                                                          + "      <xsd:sequence>\n"
                                                          + "         <xsd:element name=\"name\" type=\"xsd:string\"/>\n"
                                                          + "         <xsd:element name=\"street\" type=\"xsd:string\"/>\n"
                                                          + "         <xsd:element name=\"city\" type=\"xsd:string\"/>\n"
                                                          + "         <xsd:element name=\"state\" type=\"xsd:string\"/>\n"
                                                          + "         <xsd:element name=\"zip\" type=\"xsd:decimal\"/>\n"
                                                          + "      </xsd:sequence>\n"
                                                          + "      <xsd:attribute name=\"country\" type=\"xsd:NMTOKEN\"/>\n"
                                                          + "   </xsd:complexType>\n"
                                                          + "   <xsd:element name=\"items\" type=\"ns0:Items\"/>\n"
                                                          + "   <xsd:element name=\"Items\" type=\"ns0:Items\"/>\n"
                                                          + "   <xsd:element name=\"Image\" type=\"ns0:Image\"/>\n"
                                                          + "   <xsd:element name=\"PurchaseOrderType\" type=\"ns0:PurchaseOrderType\"/>\n"
                                                          + "   <xsd:element name=\"ShippingAddress\" type=\"ns0:ShippingAddress\"/>\n"
                                                          + "</xsd:schema>";

    public static final String EXPECTED_RI_PURCHASEORDERTYPE_MARSHALLED_RESULT = "<ns0:PurchaseOrderType xmlns:ns0=\"http://jaxb.web.dataobjects/\" orderDate=\"2018-09-09\">\n"
                                                                                 + "   <ns0:shipTo country=\"United States\">\n"
                                                                                 + "      <ns0:name>Test Name</ns0:name>\n"
                                                                                 + "      <ns0:street>505 E Maple</ns0:street>\n"
                                                                                 + "      <ns0:city>Austin</ns0:city>\n"
                                                                                 + "      <ns0:state>Texas</ns0:state>\n"
                                                                                 + "      <ns0:zip>77777</ns0:zip>\n"
                                                                                 + "   </ns0:shipTo>\n"
                                                                                 + "   <ns0:billTo country=\"United States\">\n"
                                                                                 + "      <ns0:name>Test Name</ns0:name>\n"
                                                                                 + "      <ns0:street>505 E Maple</ns0:street>\n"
                                                                                 + "      <ns0:city>Austin</ns0:city>\n"
                                                                                 + "      <ns0:state>Texas</ns0:state>\n"
                                                                                 + "      <ns0:zip>77777</ns0:zip>\n"
                                                                                 + "   </ns0:billTo>\n"
                                                                                 + "   <ns0:comment>New Order</ns0:comment>\n"
                                                                                 + "   <ns0:items>\n"
                                                                                 + "      <ns0:item>\n"
                                                                                 + "         <ns0:productName>Test Product</ns0:productName>\n"
                                                                                 + "         <ns0:quantity>15</ns0:quantity>\n"
                                                                                 + "         <ns0:Price>59872326</ns0:Price>\n"
                                                                                 + "         <ns0:comment>I'm a test product</ns0:comment>\n"
                                                                                 + "         <ns0:shipDate>2018-09-09</ns0:shipDate>\n"
                                                                                 + "      </ns0:item>\n"
                                                                                 + "      <ns0:item>\n"
                                                                                 + "         <ns0:productName>Test Product 2</ns0:productName>\n"
                                                                                 + "         <ns0:quantity>1251</ns0:quantity>\n"
                                                                                 + "         <ns0:Price>135165.999999999883584678173065185546875</ns0:Price>\n"
                                                                                 + "         <ns0:comment>I'm another test product</ns0:comment>\n"
                                                                                 + "         <ns0:shipDate>2018-09-09</ns0:shipDate>\n"
                                                                                 + "      </ns0:item>\n"
                                                                                 + "      <ns0:itemNames>Test Product Test Product 2</ns0:itemNames>\n"
                                                                                 + "   </ns0:items>\n"
                                                                                 + "</ns0:PurchaseOrderType>";

}
