//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://provider.jaxws.ws.ibm.com/")
package com.ibm.ws.jaxws.client;
