CREATE TABLE ${schemaname}.EmbedIDOOEntA (id INTEGER NOT NULL, password VARCHAR(255), userName VARCHAR(255), identity_country VARCHAR(255), identity_id INTEGER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.EmbedIDOOEntB (country VARCHAR(255) NOT NULL, id INTEGER NOT NULL, name VARCHAR(255), salary INTEGER, PRIMARY KEY (country, id));
CREATE TABLE ${schemaname}.IDClassOOEntityA (id INTEGER NOT NULL, password VARCHAR(255), userName VARCHAR(255), identity_country VARCHAR(255), identity_id INTEGER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.IDClassOOEntityB (country VARCHAR(255) NOT NULL, id INTEGER NOT NULL, name VARCHAR(255), salary INTEGER, PRIMARY KEY (country, id));
CREATE TABLE ${schemaname}.OOBiCardEntA (id INTEGER NOT NULL, name VARCHAR(255), b_id INTEGER NOT NULL, PRIMARY KEY (id), UNIQUE(b_id));
CREATE TABLE ${schemaname}.OOBiCardEntB (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntA (id INTEGER NOT NULL, name VARCHAR(255), BIENT_B1 INTEGER, b2_id INTEGER, BIENT_B4 INTEGER, BIENT_B1CA INTEGER, BIENT_B1CM INTEGER, BIENT_B1CP INTEGER, BIENT_B1RF INTEGER, BIENT_B1RM INTEGER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B1 (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B2 (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B4 (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B5CA (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B5CM (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B5CP (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B5RF (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B5RM (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOCardEntA (id INTEGER NOT NULL, name VARCHAR(255), b_id INTEGER NOT NULL, PRIMARY KEY (id), UNIQUE(b_id));
CREATE TABLE ${schemaname}.OOCardEntB (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OONoOptBiEntityA (id INTEGER NOT NULL, name VARCHAR(255), b_id INTEGER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OONoOptBiEntityB (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OONoOptEntityA (id INTEGER NOT NULL, name VARCHAR(255), b_id INTEGER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OONoOptEntityB (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOUniEntA (id INTEGER NOT NULL, name VARCHAR(255), UNIENT_B1 INTEGER, b2_id INTEGER, b4_id INTEGER, b5ca_id INTEGER, b5cm_id INTEGER, b5cp_id INTEGER, b5rf_id INTEGER, b5rm_id INTEGER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOUniEntB (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OPENJPA_SEQUENCE_TABLE (ID SMALLINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
CREATE TABLE ${schemaname}.PKJoinOOEntityA (id INTEGER NOT NULL, strVal VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.PKJoinOOEntityB (id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLEmbedIDOOEntA (id INTEGER NOT NULL, password VARCHAR(255), userName VARCHAR(255), identity_country VARCHAR(255), identity_id INTEGER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLEmbedIDOOEntB (country VARCHAR(255) NOT NULL, id INTEGER NOT NULL, name VARCHAR(255), salary INTEGER, PRIMARY KEY (country, id));
CREATE TABLE ${schemaname}.XMLIDClassOOEntityA (id INTEGER NOT NULL, password VARCHAR(255), userName VARCHAR(255), identity_country VARCHAR(255), identity_id INTEGER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLIDClassOOEntityB (country VARCHAR(255) NOT NULL, id INTEGER NOT NULL, name VARCHAR(255), salary INTEGER, PRIMARY KEY (country, id));
CREATE TABLE ${schemaname}.XMLOOBiCardEntA (id INTEGER NOT NULL, name VARCHAR(255), b_id INTEGER NOT NULL, PRIMARY KEY (id), UNIQUE(b_id));
CREATE TABLE ${schemaname}.XMLOOBiCardEntB (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntA (id INTEGER NOT NULL, name VARCHAR(255), b5cp_id INTEGER, XMLBIENT_B1 INTEGER, b2_id INTEGER, b4_id INTEGER, b5ca_id INTEGER, b5cm_id INTEGER, b5rf_id INTEGER, b5rm_id INTEGER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B1 (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B2 (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B4 (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B5CA (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B5CM (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B5CP (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B5RF (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B5RM (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOCardEntA (id INTEGER NOT NULL, name VARCHAR(255), b_id INTEGER NOT NULL, PRIMARY KEY (id), UNIQUE(b_id));
CREATE TABLE ${schemaname}.XMLOOCardEntB (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOONoOptBiEntityA (id INTEGER NOT NULL, name VARCHAR(255), b_id INTEGER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOONoOptBiEntityB (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOONoOptEntityA (id INTEGER NOT NULL, name VARCHAR(255), b_id INTEGER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOONoOptEntityB (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOUniEntA (id INTEGER NOT NULL, name VARCHAR(255), UNIENT_B1 INTEGER, b2_id INTEGER, b4_id INTEGER, b5ca_id INTEGER, b5cm_id INTEGER, b5cp_id INTEGER, b5rf_id INTEGER, b5rm_id INTEGER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOUniEntB (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLPKJoinOOEnA (id INTEGER NOT NULL, strVal VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLPKJoinOOEnB (id INTEGER NOT NULL, intVal INTEGER, PRIMARY KEY (id));

CREATE INDEX ${schemaname}.I_MBDDONT_IDENTITY ON ${schemaname}.EmbedIDOOEntA (identity_country, identity_id);
CREATE INDEX ${schemaname}.I_DCLSTTY_IDENTITY2 ON ${schemaname}.IDClassOOEntityA (identity_country, identity_id);
CREATE INDEX ${schemaname}.I_OBCRDNT_B        ON ${schemaname}.OOBiCardEntA (b_id);
CREATE INDEX ${schemaname}.I_OOBIENT_B1       ON ${schemaname}.OOBiEntA (BIENT_B1);
CREATE INDEX ${schemaname}.I_OOBIENT_B2       ON ${schemaname}.OOBiEntA (b2_id);
CREATE INDEX ${schemaname}.I_OOBIENT_B4       ON ${schemaname}.OOBiEntA (BIENT_B4);
CREATE INDEX ${schemaname}.I_OOBIENT_B5CA     ON ${schemaname}.OOBiEntA (BIENT_B1CA);
CREATE INDEX ${schemaname}.I_OOBIENT_B5CM     ON ${schemaname}.OOBiEntA (BIENT_B1CM);
CREATE INDEX ${schemaname}.I_OOBIENT_B5CP     ON ${schemaname}.OOBiEntA (BIENT_B1CP);
CREATE INDEX ${schemaname}.I_OOBIENT_B5RF     ON ${schemaname}.OOBiEntA (BIENT_B1RF);
CREATE INDEX ${schemaname}.I_OOBIENT_B5RM     ON ${schemaname}.OOBiEntA (BIENT_B1RM);
CREATE INDEX ${schemaname}.I_OOCRDNT_B        ON ${schemaname}.OOCardEntA (b_id);
CREATE INDEX ${schemaname}.I_NPTBTTY_B        ON ${schemaname}.OONoOptBiEntityA (b_id);
CREATE INDEX ${schemaname}.I_NPTNTTY_B        ON ${schemaname}.OONoOptEntityA (b_id);
CREATE INDEX ${schemaname}.I_OOUNINT_B1       ON ${schemaname}.OOUniEntA (UNIENT_B1);
CREATE INDEX ${schemaname}.I_OOUNINT_B2       ON ${schemaname}.OOUniEntA (b2_id);
CREATE INDEX ${schemaname}.I_OOUNINT_B4       ON ${schemaname}.OOUniEntA (b4_id);
CREATE INDEX ${schemaname}.I_OOUNINT_B5CA     ON ${schemaname}.OOUniEntA (b5ca_id);
CREATE INDEX ${schemaname}.I_OOUNINT_B5CM     ON ${schemaname}.OOUniEntA (b5cm_id);
CREATE INDEX ${schemaname}.I_OOUNINT_B5CP     ON ${schemaname}.OOUniEntA (b5cp_id);
CREATE INDEX ${schemaname}.I_OOUNINT_B5RF     ON ${schemaname}.OOUniEntA (b5rf_id);
CREATE INDEX ${schemaname}.I_OOUNINT_B5RM     ON ${schemaname}.OOUniEntA (b5rm_id);
CREATE INDEX ${schemaname}.I_XMLMDNT_IDENTITY ON ${schemaname}.XMLEmbedIDOOEntA (identity_country, identity_id);
CREATE INDEX ${schemaname}.I_XMLDTTY_IDENTITY2 ON ${schemaname}.XMLIDClassOOEntityA (identity_country, identity_id);
CREATE INDEX ${schemaname}.I_XMLBDNT_B        ON ${schemaname}.XMLOOBiCardEntA (b_id);
CREATE INDEX ${schemaname}.I_XMLOBNT_B1       ON ${schemaname}.XMLOOBiEntA (XMLBIENT_B1);
CREATE INDEX ${schemaname}.I_XMLOBNT_B2       ON ${schemaname}.XMLOOBiEntA (b2_id);
CREATE INDEX ${schemaname}.I_XMLOBNT_B4       ON ${schemaname}.XMLOOBiEntA (b4_id);
CREATE INDEX ${schemaname}.I_XMLOBNT_B5CA     ON ${schemaname}.XMLOOBiEntA (b5ca_id);
CREATE INDEX ${schemaname}.I_XMLOBNT_B5CM     ON ${schemaname}.XMLOOBiEntA (b5cm_id);
CREATE INDEX ${schemaname}.I_XMLOBNT_B5CP     ON ${schemaname}.XMLOOBiEntA (b5cp_id);
CREATE INDEX ${schemaname}.I_XMLOBNT_B5RF     ON ${schemaname}.XMLOOBiEntA (b5rf_id);
CREATE INDEX ${schemaname}.I_XMLOBNT_B5RM     ON ${schemaname}.XMLOOBiEntA (b5rm_id);
CREATE INDEX ${schemaname}.I_XMLCDNT_B        ON ${schemaname}.XMLOOCardEntA (b_id);
CREATE INDEX ${schemaname}.I_XMLNTTY_B1       ON ${schemaname}.XMLOONoOptBiEntityA (b_id);
CREATE INDEX ${schemaname}.I_XMLNTTY_B        ON ${schemaname}.XMLOONoOptEntityA (b_id);
CREATE INDEX ${schemaname}.I_XMLUNNT_B1       ON ${schemaname}.XMLOOUniEntA (UNIENT_B1);
CREATE INDEX ${schemaname}.I_XMLUNNT_B2       ON ${schemaname}.XMLOOUniEntA (b2_id);
CREATE INDEX ${schemaname}.I_XMLUNNT_B4       ON ${schemaname}.XMLOOUniEntA (b4_id);
CREATE INDEX ${schemaname}.I_XMLUNNT_B5CA     ON ${schemaname}.XMLOOUniEntA (b5ca_id);
CREATE INDEX ${schemaname}.I_XMLUNNT_B5CM     ON ${schemaname}.XMLOOUniEntA (b5cm_id);
CREATE INDEX ${schemaname}.I_XMLUNNT_B5CP     ON ${schemaname}.XMLOOUniEntA (b5cp_id);
CREATE INDEX ${schemaname}.I_XMLUNNT_B5RF     ON ${schemaname}.XMLOOUniEntA (b5rf_id);
CREATE INDEX ${schemaname}.I_XMLUNNT_B5RM     ON ${schemaname}.XMLOOUniEntA (b5rm_id);