DROP TABLE IF EXISTS  UUIDUUIDGENENTITY CASCADE;
DROP TABLE IF EXISTS  UUIDIDCLASSENTITY CASCADE;
DROP TABLE IF EXISTS  UUIDAUTOGENENTITY CASCADE;
DROP TABLE IF EXISTS  UUIDENTITY CASCADE;
DROP TABLE IF EXISTS  UUIDEMBEDDABLEIDENTITY CASCADE;

DROP TABLE IF EXISTS  XMLUUIDUUIDGENENTITY CASCADE;
DROP TABLE IF EXISTS  XMLUUIDIDCLASSENTITY CASCADE;
DROP TABLE IF EXISTS  XMLUUIDAUTOGENENTITY CASCADE;
DROP TABLE IF EXISTS  XMLUUIDENTITY CASCADE;
DROP TABLE IF EXISTS  XMLUUIDEMBEDDABLEIDENTITY CASCADE;

DROP TABLE IF EXISTS  QUERYDATETIMEENTITY CASCADE;
DROP TABLE IF EXISTS  QUERYENTITY CASCADE;

DROP TABLE CaseEntity;
DROP TABLE Case2Entity;
DROP TABLE COLTABLE1;
DROP TABLE Case3Entity;