CREATE TABLE IF NOT EXISTS UUIDUUIDGENENTITY (ID UUID NOT NULL, STRDATA VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS UUIDIDCLASSENTITY (UUID_ID UUID NOT NULL, L_ID BIGINT NOT NULL, STRDATA VARCHAR(255), PRIMARY KEY (UUID_ID, L_ID));
CREATE TABLE IF NOT EXISTS UUIDAUTOGENENTITY (ID UUID NOT NULL, STRDATA VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS UUIDENTITY (ID UUID NOT NULL, STRDATA VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS UUIDEMBEDDABLEIDENTITY (STRDATA VARCHAR(255), ID UUID NOT NULL, PRIMARY KEY (ID));

CREATE TABLE IF NOT EXISTS XMLUUIDUUIDGENENTITY (ID UUID NOT NULL, STRDATA VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS XMLUUIDIDCLASSENTITY (UUID_ID UUID NOT NULL, L_ID BIGINT NOT NULL, STRDATA VARCHAR(255), PRIMARY KEY (UUID_ID, L_ID));
CREATE TABLE IF NOT EXISTS XMLUUIDAUTOGENENTITY (ID UUID NOT NULL, STRDATA VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS XMLUUIDENTITY (ID UUID NOT NULL, STRDATA VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS XMLUUIDEMBEDDABLEIDENTITY (STRDATA VARCHAR(255), EID UUID NOT NULL, PRIMARY KEY (EID));

CREATE TABLE IF NOT EXISTS QUERYDATETIMEENTITY (ID INTEGER NOT NULL, LOCALDATEDATA DATE, LOCALDATETIMEDATA TIMESTAMP, LOCALTIMEDATA TIME, PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS QUERYENTITY (ID INTEGER NOT NULL, DOUBLEVAL FLOAT, FLOATVAL FLOAT, INTVAL INTEGER, LONGVAL BIGINT, STRVAL VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE CaseEntity (KEY_CHAR VARCHAR(255) NOT NULL, ITEM_INTEGER1 INTEGER, ITEM_INTEGER2 INTEGER, ITEM_STRING1 VARCHAR(255), ITEM_STRING2 VARCHAR(255), ITEM_STRING3 VARCHAR(255), ITEM_STRING4 VARCHAR(255), PRIMARY KEY (KEY_CHAR));
CREATE TABLE Case2Entity (ID BIGINT NOT NULL, INTVAL1 INTEGER, INTVAL2 INTEGER, STRVAL1 VARCHAR(255), STRVAL2 VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE COLTABLE1 (ent_id BIGINT, COLVAL1 VARCHAR(255));
ALTER TABLE COLTABLE1 ADD CONSTRAINT COLTABLE1_ent_id FOREIGN KEY (ent_id) REFERENCES Case2Entity (ID);
CREATE TABLE Case3Entity (KEY_CHAR VARCHAR(255) NOT NULL, ITEM_INTEGER1 INTEGER, ITEM_STRING1 VARCHAR(255), ITEM_STRING2 VARCHAR(255), ITEM_STRING3 VARCHAR(255), ITEM_STRING4 VARCHAR(255), PRIMARY KEY (KEY_CHAR));