CREATE TABLE UUIDUUIDGENENTITY (ID VARCHAR(255) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (ID));
CREATE TABLE UUIDIDCLASSENTITY (UUID_ID VARCHAR(255) NOT NULL, L_ID NUMERIC(19) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (UUID_ID, L_ID));
CREATE TABLE UUIDAUTOGENENTITY (ID VARCHAR(255) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (ID));
CREATE TABLE UUIDENTITY (ID VARCHAR(255) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (ID));
CREATE TABLE UUIDEMBEDDABLEIDENTITY (STRDATA VARCHAR(255) NULL, ID VARCHAR(255) NOT NULL, PRIMARY KEY (ID));

CREATE TABLE XMLUUIDUUIDGENENTITY (ID VARCHAR(255) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (ID));
CREATE TABLE XMLUUIDIDCLASSENTITY (UUID_ID VARCHAR(255) NOT NULL, L_ID NUMERIC(19) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (UUID_ID, L_ID));
CREATE TABLE XMLUUIDAUTOGENENTITY (ID VARCHAR(255) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (ID));
CREATE TABLE XMLUUIDENTITY (ID VARCHAR(255) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (ID));
CREATE TABLE XMLUUIDEMBEDDABLEIDENTITY (STRDATA VARCHAR(255) NULL, EID VARCHAR(255) NOT NULL, PRIMARY KEY (EID));

CREATE TABLE QUERYDATETIMEENTITY (ID INTEGER NOT NULL, LOCALDATEDATA DATE NULL, LOCALDATETIMEDATA DATETIME2 NULL, LOCALTIMEDATA TIME NULL, PRIMARY KEY (ID));
CREATE TABLE QUERYENTITY (ID INTEGER NOT NULL, DOUBLEVAL FLOAT(32) NULL, FLOATVAL FLOAT(16) NULL, INTVAL INTEGER NULL, LONGVAL NUMERIC(19) NULL, STRVAL VARCHAR(255) NULL, PRIMARY KEY (ID));

INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);

CREATE TABLE CaseEntity (KEY_CHAR VARCHAR(255) NOT NULL, ITEM_INTEGER1 INT, ITEM_INTEGER2 INT, ITEM_STRING1 VARCHAR(255), ITEM_STRING2 VARCHAR(255), ITEM_STRING3 VARCHAR(255), ITEM_STRING4 VARCHAR(255), PRIMARY KEY (KEY_CHAR));
CREATE TABLE Case2Entity (ID BIGINT NOT NULL, INTVAL1 INTEGER, INTVAL2 INTEGER, STRVAL1 VARCHAR(255), STRVAL2 VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE COLTABLE1 (ent_id BIGINT, COLVAL1 VARCHAR(255));
ALTER TABLE COLTABLE1 ADD CONSTRAINT COLTABLE1_ent_id FOREIGN KEY (ent_id) REFERENCES Case2Entity (ID);
CREATE TABLE Case3Entity (KEY_CHAR VARCHAR(255) NOT NULL, ITEM_INTEGER1 INT, ITEM_STRING1 VARCHAR(255), ITEM_STRING2 VARCHAR(255), ITEM_STRING3 VARCHAR(255), ITEM_STRING4 VARCHAR(255), PRIMARY KEY (KEY_CHAR));