DROP TABLE UUIDUUIDGENENTITY;
DROP TABLE UUIDIDCLASSENTITY;
DROP TABLE UUIDAUTOGENENTITY;
DROP TABLE UUIDENTITY;
DROP TABLE UUIDEMBEDDABLEIDENTITY;

DROP TABLE XMLUUIDUUIDGENENTITY;
DROP TABLE XMLUUIDIDCLASSENTITY;
DROP TABLE XMLUUIDAUTOGENENTITY;
DROP TABLE XMLUUIDENTITY;
DROP TABLE XMLUUIDEMBEDDABLEIDENTITY;

DROP TABLE QUERYDATETIMEENTITY;
DROP TABLE QUERYENTITY;

DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN';
