CREATE TABLE UUIDUUIDGENENTITY (ID VARCHAR(255) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (ID));
CREATE TABLE UUIDIDCLASSENTITY (UUID_ID VARCHAR(255) NOT NULL, L_ID NUMERIC(19) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (UUID_ID, L_ID));
CREATE TABLE UUIDAUTOGENENTITY (ID VARCHAR(255) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (ID));
CREATE TABLE UUIDENTITY (ID VARCHAR(255) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (ID));
CREATE TABLE UUIDEMBEDDABLEIDENTITY (STRDATA VARCHAR(255) NULL, ID VARCHAR(255) NOT NULL, PRIMARY KEY (ID));

CREATE TABLE XMLUUIDUUIDGENENTITY (ID VARCHAR(255) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (ID));
CREATE TABLE XMLUUIDIDCLASSENTITY (UUID_ID VARCHAR(255) NOT NULL, L_ID NUMERIC(19) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (UUID_ID, L_ID));
CREATE TABLE XMLUUIDAUTOGENENTITY (ID VARCHAR(255) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (ID));
CREATE TABLE XMLUUIDENTITY (ID VARCHAR(255) NOT NULL, STRDATA VARCHAR(255) NULL, PRIMARY KEY (ID));
CREATE TABLE XMLUUIDEMBEDDABLEIDENTITY (STRDATA VARCHAR(255) NULL, EID VARCHAR(255) NOT NULL, PRIMARY KEY (EID));


CREATE TABLE QUERYDATETIMEENTITY (ID INTEGER NOT NULL, LOCALDATEDATA DATE NULL, LOCALDATETIMEDATA DATETIME2 NULL, LOCALTIMEDATA TIME NULL, PRIMARY KEY (ID));
CREATE TABLE QUERYENTITY (ID INTEGER NOT NULL, DOUBLEVAL FLOAT(32) NULL, FLOATVAL FLOAT(16) NULL, INTVAL INTEGER NULL, LONGVAL NUMERIC(19) NULL, STRVAL VARCHAR(255) NULL, PRIMARY KEY (ID));

INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);

