INSERT INTO CaseEntity (KEY_CHAR,ITEM_INTEGER1,ITEM_INTEGER2) VALUES ('SimpleEntityOLGH14457_1',1,2);
INSERT INTO CaseEntity (KEY_CHAR,ITEM_INTEGER1,ITEM_INTEGER2) VALUES ('SimpleEntityOLGH14457_2',3,4);

INSERT INTO Case2Entity (ID,INTVAL1,INTVAL2,STRVAL1,STRVAL2) VALUES (1,99,5,'Test1','Test2');
INSERT INTO Case2Entity (ID,INTVAL1,INTVAL2,STRVAL1,STRVAL2) VALUES (2,99,15,'Test3','Test4');
INSERT INTO Case2Entity (ID,INTVAL1,INTVAL2,STRVAL1,STRVAL2) VALUES (3,6,5,'Test5','Test6');
INSERT INTO Case2Entity (ID,INTVAL1,INTVAL2,STRVAL1,STRVAL2) VALUES (4,26,11,'Test7','Test8');

INSERT INTO Case3Entity (KEY_CHAR,ITEM_INTEGER1,ITEM_STRING1,ITEM_STRING2,ITEM_STRING3,ITEM_STRING4) VALUES ('Key01',1,'A','B','C','D');
INSERT INTO Case3Entity (KEY_CHAR,ITEM_INTEGER1,ITEM_STRING1,ITEM_STRING2,ITEM_STRING3,ITEM_STRING4) VALUES ('Key02',2,'A','B','C','D');