<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions name="callertoken"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:tns="http://caller.libertyfat.test/contract"
        targetNamespace="http://caller.libertyfat.test/contract"
        xmlns:wsp="http://www.w3.org/ns/ws-policy"
        xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
        xmlns:wsaws="http://www.w3.org/2005/08/addressing" 
        xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
        xmlns:sp13="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200802"
        xmlns:x1="http://caller.libertyfat.test/types" >


    <!-- bac01 Caller HTTP but encrypted UNT  -->
    <wsp:Policy wsu:Id="CallerHttpPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:EncryptedSupportingTokens>
                   <wsp:Policy>
                      <sp:UsernameToken
                         sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                         <wsp:Policy>                 
                            <sp:HashPassword/>
                            <sp:WssUsernameToken11/>
                         </wsp:Policy>
                      </sp:UsernameToken>
                   </wsp:Policy>
                </sp:EncryptedSupportingTokens>

                <sp:AsymmetricBinding >
                    <wsp:Policy>
                        <sp:InitiatorToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                                    <wsp:Policy>
                                        <sp:WssX509V3Token10/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:InitiatorToken>
                        <sp:RecipientToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                                    <wsp:Policy>
                                        <sp:WssX509V3Token10/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:RecipientToken>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:EncryptSignature /> <!--Somehow with EncryptBeforeSigning, we have to add this EncryptSignature  -->
                        <sp:EncryptBeforeSigning />
                        <sp:OnlySignEntireHeadersAndBody/>
                    </wsp:Policy>
                </sp:AsymmetricBinding>
                <sp:Wss10>
                    <wsp:Policy>
                        <sp:MustSupportRefKeyIdentifier/>
                        <sp:MustSupportRefIssuerSerial/>
                    </wsp:Policy>
                </sp:Wss10>
                <sp:SignedParts>
                    <sp:Body/>
                </sp:SignedParts>
                <sp:EncryptedParts>
                    <sp:Body/>
                </sp:EncryptedParts>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>

    <!-- bac02 https protected plain UNT -->
    <wsp:Policy wsu:Id="CallerHttpsPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy/>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <!-- sp:IncludeTimestamp / -->
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SupportingTokens>
                    <wsp:Policy>
                        <sp:UsernameToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssUsernameToken11/>
                                <sp13:Created/>
                                <sp13:Nonce/>
                            </wsp:Policy>
                        </sp:UsernameToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    

    <!-- bac03 not used... http plain UNT -->
    <wsp:Policy wsu:Id="CallerHttpUNTPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:SupportingTokens>
                    <wsp:Policy>
                        <sp:UsernameToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssUsernameToken11/>
                                <sp13:Created/>
                                <sp13:Nonce/>
                            </wsp:Policy>
                        </sp:UsernameToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    


    <!-- bac04 Https but no userNametoken-->
    <wsp:Policy wsu:Id="CallerHttpsNoUntPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy/>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <!-- sp:IncludeTimestamp / -->
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>


    <!-- bac05 x509 Asymmetric -->
    <wsp:Policy wsu:Id="X509TokenPolicy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:AsymmetricBinding>
               <wsp:Policy>
                  <sp:InitiatorToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10/>
                              <sp:RequireIssuerSerialReference/>
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:InitiatorToken>
                  <sp:RecipientToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10/>
                              <sp:RequireIssuerSerialReference/>
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:RecipientToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic128Sha256/> 
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:AsymmetricBinding>
            <sp:EncryptedParts>
                <sp:Body/>
            </sp:EncryptedParts>            
            <sp:SignedParts>
                 <sp:Body/>
            </sp:SignedParts>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>

     <!-- bax06. transport endorsing -->
    <wsp:Policy wsu:Id="X509TransportEndorsingPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy/>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:EndorsingSupportingTokens>
                   <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                           <wsp:Policy>
                              <sp:WssX509V3Token10/>
                           </wsp:Policy>
                        </sp:X509Token>
                        <sp:SignedParts>
                            <sp:Body/>
                        </sp:SignedParts>
                    </wsp:Policy>
                </sp:EndorsingSupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>


    <!-- bac07 Symmetric x509 endorsing -->
    <wsp:Policy wsu:Id="SymmetricEndorsingPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:SymmetricBinding>
                  <wsp:Policy>
                    <sp:ProtectionToken>
                       <wsp:Policy>
                          <sp:X509Token
                             sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                             <wsp:Policy>
                                <sp:RequireDerivedKeys/>
                                <sp:RequireThumbprintReference/>
                                <sp:WssX509V3Token11/>
                             </wsp:Policy>
                          </sp:X509Token>
                       </wsp:Policy>
                    </sp:ProtectionToken>
                    <sp:AlgorithmSuite>
                       <wsp:Policy>
                          <sp:Basic128/>
                       </wsp:Policy>
                    </sp:AlgorithmSuite>
                    <sp:Layout>
                       <wsp:Policy>
                          <sp:Strict/>
                       </wsp:Policy>
                    </sp:Layout>
                    <sp:IncludeTimestamp/>
                    <sp:OnlySignEntireHeadersAndBody/>
                    <!-- sp:EncryptBeforeSigning / --> 
                 </wsp:Policy>
              </sp:SymmetricBinding>
              <sp:EndorsingSupportingTokens xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
                 <wsp:Policy>
                      <sp:X509Token
                         sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                         <wsp:Policy>
                            <sp:RequireThumbprintReference/>
                            <sp:WssX509V3Token11/>
                         </wsp:Policy>
                      </sp:X509Token>
                  </wsp:Policy>
              </sp:EndorsingSupportingTokens>         
              <sp:Wss11>
                  <wsp:Policy>
                      <sp:MustSupportRefKeyIdentifier/>
                      <sp:MustSupportRefIssuerSerial/>
                      <sp:MustSupportRefThumbprint/>
                      <sp:MustSupportRefEncryptedKey/>
                      <sp:RequireSignatureConfirmation/>
                  </wsp:Policy>
              </sp:Wss11>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>


    <!-- bac08 Symmetric x509 endorsing TLS -->
    <wsp:Policy wsu:Id="SymmetricEndorsingTLSPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy/>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SymmetricBinding>
                  <wsp:Policy>
                    <sp:ProtectionToken>
                       <wsp:Policy>
                          <sp:X509Token
                             sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                             <wsp:Policy>
                                <sp:RequireDerivedKeys/>
                                <sp:RequireThumbprintReference/>
                                <sp:WssX509V3Token11/>
                             </wsp:Policy>
                          </sp:X509Token>
                       </wsp:Policy>
                    </sp:ProtectionToken>
                    <sp:AlgorithmSuite>
                       <wsp:Policy>
                          <sp:Basic128/>
                       </wsp:Policy>
                    </sp:AlgorithmSuite>
                    <sp:Layout>
                       <wsp:Policy>
                          <sp:Strict/>
                       </wsp:Policy>
                    </sp:Layout>
                    <sp:IncludeTimestamp/>
                    <sp:OnlySignEntireHeadersAndBody/>
                    <!-- sp:EncryptBeforeSigning / --> 
                 </wsp:Policy>
              </sp:SymmetricBinding>
              <sp:EndorsingSupportingTokens xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
                 <wsp:Policy>
                      <sp:X509Token
                         sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                         <wsp:Policy>
                            <sp:RequireThumbprintReference/>
                            <sp:WssX509V3Token11/>
                         </wsp:Policy>
                      </sp:X509Token>
                  </wsp:Policy>
              </sp:EndorsingSupportingTokens>         
              <sp:Wss11>
                  <wsp:Policy>
                      <sp:MustSupportRefKeyIdentifier/>
                      <sp:MustSupportRefIssuerSerial/>
                      <sp:MustSupportRefThumbprint/>
                      <sp:MustSupportRefEncryptedKey/>
                      <sp:RequireSignatureConfirmation/>
                  </wsp:Policy>
              </sp:Wss11>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>


    <!-- bac09 migsym -->
    <wsp:Policy wsu:Id="CallerSymmetricProtectTokensPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:SymmetricBinding>
                  <wsp:Policy>
                    <sp:ProtectionToken>
                       <wsp:Policy>
                          <sp:X509Token
                             sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                             <wsp:Policy>
                                <sp:WssX509V3Token11/>
                             </wsp:Policy>
                          </sp:X509Token>
                       </wsp:Policy>
                    </sp:ProtectionToken>
                    <sp:Layout>
                       <wsp:Policy>
                          <sp:Lax/>
                       </wsp:Policy>
                    </sp:Layout>
                    <sp:IncludeTimestamp/>
                    <sp:OnlySignEntireHeadersAndBody/>
                    <sp:ProtectTokens/>
                    <sp:SignBeforeEncrypting/>
                    <sp:AlgorithmSuite>
                       <wsp:Policy>
                          <sp:Basic128/>
                       </wsp:Policy>
                    </sp:AlgorithmSuite>
                 </wsp:Policy>
              </sp:SymmetricBinding>
              <sp:EncryptedParts>
                <sp:Body/>
              </sp:EncryptedParts>            
              <sp:SignedParts>
                 <sp:Body/>
              </sp:SignedParts>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>


    <!-- bac10.https mig -->
    <wsp:Policy wsu:Id="CallerTransportEndorsingPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy/>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:EndorsingSupportingTokens xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
                   <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                           <wsp:Policy>
                              <sp:WssX509V3Token10/>
                           </wsp:Policy>
                        </sp:X509Token>
                    </wsp:Policy>
                </sp:EndorsingSupportingTokens>         
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>


    <wsdl:types>
        <xsd:schema targetNamespace="http://caller.libertyfat.test/types">
                <xsd:element name="requestString">
                        <xsd:complexType>
                                <xsd:sequence>
                                        <xsd:element name="stringreq" type="xsd:string"/>
                                </xsd:sequence>
                        </xsd:complexType>
                </xsd:element>
                <xsd:element name="responseString">
                        <xsd:complexType>
                                <xsd:sequence>
                                        <xsd:element name="stringres" type="xsd:string"/>
                                </xsd:sequence>
                        </xsd:complexType>
                </xsd:element>
        </xsd:schema>
    </wsdl:types>

   <wsdl:message name="getVersionRequest">
      <wsdl:part element="x1:requestString" name="getVersion"/>
   </wsdl:message>
   <wsdl:message name="getVersionResponse">
      <wsdl:part element="x1:responseString" name="getVersionReturn"/>
   </wsdl:message>

   <wsdl:portType name="FVTVersionBAC">
      <wsdl:operation name="invoke">
         <wsdl:input message="tns:getVersionRequest" name="getVersionRequest"/>
         <wsdl:output message="tns:getVersionResponse" name="getVersionResponse"/>
      </wsdl:operation>
   </wsdl:portType>

   <wsdl:binding name="UrnCallerTokenSoapBinding01" type="tns:FVTVersionBAC">
      <wsp:PolicyReference URI="#CallerHttpPolicy"/>
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <soap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="FatBAC01Service">
      <wsdl:port name="UrnCallerToken01" binding="tns:UrnCallerTokenSoapBinding01">
         <soap:address location="http://localhost:8010/callertoken/FatBAC01Service"/>
      </wsdl:port>
   </wsdl:service>

   <wsdl:binding name="UrnCallerTokenSoapBinding02" type="tns:FVTVersionBAC">
      <wsp:PolicyReference URI="#CallerHttpsPolicy"/>
                                 
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <soap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="FatBAC02Service">
      <wsdl:port name="UrnCallerToken02" binding="tns:UrnCallerTokenSoapBinding02">
         <soap:address location="http://localhost:8010/callertoken/FatBAC02Service"/>
      </wsdl:port>
   </wsdl:service>

   <wsdl:binding name="UrnCallerTokenSoapBinding03" type="tns:FVTVersionBAC">
      <!-- wsp:PolicyReference URI="#CallerHttpUNTPolicy"/ -->
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <soap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="FatBAC03Service">
      <wsdl:port name="UrnCallerToken03" binding="tns:UrnCallerTokenSoapBinding03">
         <soap:address location="http://localhost:8010/callertoken/FatBAC03Service"/>
      </wsdl:port>
   </wsdl:service>

   <wsdl:binding name="UrnCallerTokenSoapBinding04" type="tns:FVTVersionBAC">
      <wsp:PolicyReference URI="#CallerHttpsNoUntPolicy"/>
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <soap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="FatBAC04Service">
      <wsdl:port name="UrnCallerToken04" binding="tns:UrnCallerTokenSoapBinding04">
         <soap:address location="http://localhost:8010/callertoken/FatBAC04Service"/>
      </wsdl:port>
   </wsdl:service>

   <wsdl:binding name="UrnCallerTokenSoapBinding05" type="tns:FVTVersionBAC">
      <wsp:PolicyReference URI="#X509TokenPolicy"/>
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <soap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="FatBAC05Service">
      <wsdl:port name="UrnCallerToken05" binding="tns:UrnCallerTokenSoapBinding05">
         <soap:address location="http://localhost:8010/callertoken/FatBAC05Service"/>
      </wsdl:port>
   </wsdl:service>

   <wsdl:binding name="UrnCallerTokenSoapBinding06" type="tns:FVTVersionBAC">
      <wsp:PolicyReference URI="#X509TransportEndorsingPolicy"/>
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <soap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="FatBAC06Service">
      <wsdl:port name="UrnCallerToken06" binding="tns:UrnCallerTokenSoapBinding06">
         <soap:address location="http://localhost:8010/callertoken/FatBAC06Service"/>
      </wsdl:port>
   </wsdl:service>

   <wsdl:binding name="UrnCallerTokenSoapBinding07" type="tns:FVTVersionBAC">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsp:PolicyReference URI="#SymmetricEndorsingPolicy"/>
      <wsdl:operation name="invoke">
         <soap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="FatBAC07Service">
      <wsdl:port name="UrnCallerToken07" binding="tns:UrnCallerTokenSoapBinding07">
         <soap:address location="http://localhost:8010/callertoken/FatBAC07Service"/>
      </wsdl:port>
   </wsdl:service>

   <wsdl:binding name="UrnCallerTokenSoapBinding08" type="tns:FVTVersionBAC">
      <wsp:PolicyReference URI="#SymmetricEndorsingTLSPolicy"/>
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <soap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="FatBAC08Service">
      <wsdl:port name="UrnCallerToken08" binding="tns:UrnCallerTokenSoapBinding08">
         <soap:address location="http://localhost:8010/callertoken/FatBAC08Service"/>
      </wsdl:port>
   </wsdl:service>

   <wsdl:binding name="UrnCallerTokenSoapBinding09" type="tns:FVTVersionBAC">
      <wsp:PolicyReference URI="#CallerSymmetricProtectTokensPolicy"/>
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <soap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="FatBAC09Service">
      <wsdl:port name="UrnCallerToken09" binding="tns:UrnCallerTokenSoapBinding09">
         <soap:address location="http://localhost:8010/callertoken/FatBAC09Service"/>
      </wsdl:port>
   </wsdl:service>

   <wsdl:binding name="UrnCallerTokenSoapBinding10" type="tns:FVTVersionBAC">
      <wsp:PolicyReference URI="#CallerTransportEndorsingPolicy"/>
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="invoke">
         <soap:operation soapAction=""/>
         <wsdl:input name="getVersionRequest">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="getVersionResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="FatBAC10Service">
      <wsdl:port name="UrnCallerToken10" binding="tns:UrnCallerTokenSoapBinding10">
         <soap:address location="http://localhost:8010/callertoken/FatBAC10Service"/>
      </wsdl:port>
   </wsdl:service>


</wsdl:definitions>


