<?xml version="1.0" encoding="UTF-8"?>
<definitions name="MTOMDDOverrideService" targetNamespace="http://server.mtom.jaxws22.cxf.fats/" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:tns="http://server.mtom.jaxws22.cxf.fats/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://server.mtom.jaxws22.cxf.fats/" schemaLocation="mtom.xsd"/>
    </xsd:schema>
  </types>
  <message name="echobyte">
    <part name="parameters" element="tns:echobyte">
    </part>
  </message>
  <message name="echobyteResponse">
    <part name="parameters" element="tns:echobyteResponse">
    </part>
  </message>
  <portType name="MTOMDDOverride">
    <operation name="echobyte">
      <input message="tns:echobyte" wsam:Action="http://server.mtom.jaxws22.cxf.fats/MTOMDDOverride/echobyteRequest">
    </input>
      <output message="tns:echobyteResponse" wsam:Action="http://server.mtom.jaxws22.cxf.fats/MTOMDDOverride/echobyteResponse">
    </output>
    </operation>
  </portType>
  <binding name="MTOMDDOverridePortBinding" type="tns:MTOMDDOverride">
    <wsp:PolicyReference URI="#MTOMDDOverridePortBinding_MTOM_Policy"/>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="echobyte">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="MTOMDDOverrideService">
    <port name="MTOMDDOverridePort" binding="tns:MTOMDDOverridePortBinding">
      <soap:address location="http://localhost:9080/webservicefeaturetests/MTOMDDOverrideService"/>
    </port>
  </service>
    <wsp:Policy wsu:Id="MTOMDDOverridePortBinding_MTOM_Policy">
    <ns1:OptimizedMimeSerialization wsp:Optional="true" xmlns:ns1="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization"/>
  </wsp:Policy>
</definitions>
