#!/bin/bash
echo ------------------
echo Launcher called: $@  | tee /opt/ol/wlp/launcher.log
echo -------------------
COMMAND=$1
SERVER=$2
PHASE=$3
if [ $1 == "checkpoint" ]; then
  /opt/ol/fat/scripts/checkpoint $SERVER $PHASE  | tee -a /opt/ol/wlp/launcher.log
  echo Checkpoint action completed | tee -a /opt/ol/wlp/launcher.log
else
   /opt/ol/wlp/bin/server start $SERVER | tee -a /opt/ol/wlp/launcher.log
   echo server start with checkpoint completed | tee -a /opt/ol/wlp/launcher.log
fi
# Write ~20K to stdout. Otherwise "Checkpoint action completed" audit message will not always get flushed out
# to the testcontainers harness prior to the sleep below.
x=0 
while [ $x -lt 10000 ]; 
do   
    echo -n o
    let x++
done; 
echo
# sleep for 24 hours. This is to keep the container from terminating until 
# the test harness stops it.
sleep 86400
 