<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
    name  = "MainService"
    targetNamespace = "http://com/ibm/ws/jaxws/wsdl/MainService.wsdl"
    xmlns:tns = "http://com/ibm/ws/jaxws/wsdl/MainService.wsdl"
    xmlns:msg = "http://com/ibm/ws/jaxws/wsdl/MainServiceSchema.xsd"
    xmlns:wsdl = "http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdlsoap = "http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:customwsdl = "http://com/ibm/ws/jaxws/wsdl/ImportedService.wsdl"
    xmlns:xs = "http://www.w3.org/2001/XMLSchema"
    >

    <wsdl:import namespace="http://com/ibm/ws/jaxws/wsdl/ImportedService.wsdl" location="ImportedService.wsdl"/>

    <wsdl:types>
      <xs:schema elementFormDefault="qualified" targetNamespace="urn:tns" xmlns:msg="http://com/ibm/ws/jaxws/wsdl/MainServiceSchema.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <xs:import namespace="http://com/ibm/ws/jaxws/wsdl/MainServiceSchema.xsd" schemaLocation="MainServiceSchema.xsd"/>
      </xs:schema>
    </wsdl:types>

    <wsdl:message name="NameSpaceCheck">
      <wsdl:part element="msg:NameSpaceCheck" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="NameSpaceCheckResponse">
      <wsdl:part element="msg:NameSpaceCheckResponse" name="result"/>
    </wsdl:message>

    <wsdl:portType name="NameSpaceCheckPortType">
      <wsdl:operation name="NameSpaceCheck">
        <wsdl:input message="tns:NameSpaceCheck"/>
        <wsdl:output message="tns:NameSpaceCheckResponse"/>
        <wsdl:fault message="customwsdl:CustomFaultDetail" name="faultdetail"/>
      </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="NameSpaceCheck_SoapHttpBinding" type="tns:NameSpaceCheckPortType">
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="NameSpaceCheck">
        <wsdlsoap:operation soapAction="tns:NameSpaceCheck" style="document"/>
        <wsdl:input>
          <wsdlsoap:header message="customwsdl:CustomHeader" part="person" use="literal"/>
          <wsdlsoap:body parts="parameters" use="literal"/>
        </wsdl:input>
        <wsdl:output>
          <wsdlsoap:header message="customwsdl:CustomHeader" part="person" use="literal"/>
          <wsdlsoap:body parts="result" use="literal"/>
        </wsdl:output>
        <wsdl:fault name="faultdetail">
          <wsdlsoap:fault name="faultdetail" use="literal"/>
        </wsdl:fault>
      </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="NameSpaceCheckService">
      <wsdl:port binding="tns:NameSpaceCheck_SoapHttpBinding" name="NameSpaceCheckServicePortHttp">
        <wsdlsoap:address location="http://com/ibm/ws/jaxws/NameSpaceCheck"/>
      </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
