
package hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 *
 */
@WebService(name = "HelloIF", targetNamespace = "http://hello")
@XmlSeeAlso({
              ObjectFactory.class
})
public interface HelloIF {

    /**
     *
     * @param address
     * @param address2
     */
    @WebMethod
    @RequestWrapper(localName = "updateAddress", targetNamespace = "http://hello", className = "hello.UpdateAddress")
    @ResponseWrapper(localName = "updateAddress", targetNamespace = "http://hello", className = "hello.UpdateAddress")
    public void updateAddress(
                              @WebParam(name = "Address", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<Address> address,
                              @WebParam(name = "Address2", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<Address> address2);

    /**
     *
     * @param address
     * @param address2
     */
    @WebMethod
    @RequestWrapper(localName = "sayHelloHeader", targetNamespace = "http://hello", className = "hello.SayHelloHeader")
    @ResponseWrapper(localName = "sayHelloHeader", targetNamespace = "http://hello", className = "hello.SayHelloHeader")
    public void sayHelloHeader(
                               @WebParam(name = "Address", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<Address> address,
                               @WebParam(name = "Header", targetNamespace = "", header = true, mode = WebParam.Mode.INOUT) Holder<Header> header);

}
