/*******************************************************************************
 * Copyright (c) 2023, 2026 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
	
configurations {
	  prometheusRegistry
	  micrometerCore
	  hdrHistogram
	  simpleClientCommon
	  simpleClientTracerCommon
	  simpleClientTracerOtelAgent
	  simpleClientTracerOtel
	  simpleClient
	  // 1.15.12 configurations
	  prometheusRegistry1512
	  prometheusSimpleClientRegistry
	  micrometerCorev1512
	  micrometerCommons
	  SimpleClientv11512Common
	  SimpleClientv11512TracerCommon
	  SimpleClientv11512TracerOtelAgent
	  SimpleClientv11512TracerOtel
	  SimpleClientv11512
}
	
dependencies {
  prometheusRegistry 'io.micrometer:micrometer-registry-prometheus:1.9.3'
  micrometerCore 'io.micrometer:micrometer-core:1.9.3'
  hdrHistogram 'org.hdrhistogram:HdrHistogram:2.1.12'
  simpleClientCommon 'io.prometheus:simpleclient_common:0.15.0'
  simpleClientTracerCommon 'io.prometheus:simpleclient_tracer_common:0.15.0'
  simpleClientTracerOtelAgent 'io.prometheus:simpleclient_tracer_otel_agent:0.15.0'
  simpleClientTracerOtel 'io.prometheus:simpleclient_tracer_otel:0.15.0'
  simpleClient 'io.prometheus:simpleclient:0.15.0'
  // 1.15.12 dependencies
  prometheusRegistry1512 'io.micrometer:micrometer-registry-prometheus:1.15.12'
  prometheusSimpleClientRegistry 'io.micrometer:micrometer-registry-prometheus-simpleclient:1.15.12'
  micrometerCorev1512 'io.micrometer:micrometer-core:1.15.12'
  micrometerCommons 'io.micrometer:micrometer-commons:1.15.12'
  SimpleClientv11512Common 'io.prometheus:simpleclient_common:0.16.0'
  SimpleClientv11512TracerCommon 'io.prometheus:simpleclient_tracer_common:0.16.0'
  SimpleClientv11512TracerOtelAgent 'io.prometheus:simpleclient_tracer_otel_agent:0.16.0'
  SimpleClientv11512TracerOtel 'io.prometheus:simpleclient_tracer_otel:0.16.0'
  SimpleClientv11512 'io.prometheus:simpleclient:0.16.0'
}

task copyPrometheus(type: Copy) {
  shouldRunAfter jar
  from configurations.prometheusRegistry
  into new File(autoFvtDir, 'publish/shared/resources/prometheuslib/')
}

task copyHdrHistogramPrometheus(type: Copy) {
  shouldRunAfter jar
  from configurations.hdrHistogram
  into new File(autoFvtDir, 'publish/shared/resources/prometheuslib/')
}

task copyHdrHistogramUseless(type: Copy) {
  shouldRunAfter jar
  from configurations.hdrHistogram
  into new File(autoFvtDir, 'publish/shared/resources/uselessLib/')
}

task copyMicrometerCore(type: Copy) {
  shouldRunAfter jar
  from configurations.micrometerCore
  into new File(autoFvtDir, 'publish/shared/resources/micrometercore/')
}

task copySimpleClientCommon(type: Copy) {
  shouldRunAfter jar
  from configurations.simpleClientCommon
  into new File(autoFvtDir, 'publish/shared/resources/prometheuslib/')
}

task copySimpleClientTracerCommon(type: Copy) {
  shouldRunAfter jar
  from configurations.simpleClientTracerCommon
  into new File(autoFvtDir, 'publish/shared/resources/prometheuslib/')
}
task copySimpleClientTracerOtelAgent(type: Copy) {
  shouldRunAfter jar
  from configurations.simpleClientTracerOtelAgent
  into new File(autoFvtDir, 'publish/shared/resources/prometheuslib/')
}

task copySimpleClientTracerOtel(type: Copy) {
  shouldRunAfter jar
  from configurations.simpleClientTracerOtel
  into new File(autoFvtDir, 'publish/shared/resources/prometheuslib/')
}

task copySimpleClient(type: Copy) {
  shouldRunAfter jar
  from configurations.simpleClient
  into new File(autoFvtDir, 'publish/shared/resources/prometheuslib/')
}

task copyHdrHistogramPrometheuslib1512(type: Copy) {
  shouldRunAfter jar
  from configurations.hdrHistogram
  into new File(autoFvtDir, 'publish/shared/resources/prometheuslib1512/')
}

task copyPrometheusRegistry1512(type: Copy) {
  shouldRunAfter jar
  from configurations.prometheusRegistry1512
  into new File(autoFvtDir, 'publish/shared/resources/prometheuslib1512/')
}

task copyHdrHistogramPrometheusSimpleClient(type: Copy) {
  shouldRunAfter jar
  from configurations.hdrHistogram
  into new File(autoFvtDir, 'publish/shared/resources/prometheusSimpleClientLib/')
}

task copyPrometheusSimpleClientRegistry(type: Copy) {
  shouldRunAfter jar
  from configurations.prometheusSimpleClientRegistry
  into new File(autoFvtDir, 'publish/shared/resources/prometheusSimpleClientLib/')
}

task copyMicrometerCorev1512(type: Copy) {
  shouldRunAfter jar
  from configurations.micrometerCorev1512
  into new File(autoFvtDir, 'publish/shared/resources/micrometercorev1512/')
}

task copyMicrometerCommons(type: Copy) {
  shouldRunAfter jar
  from configurations.micrometerCommons
  into new File(autoFvtDir, 'publish/shared/resources/micrometercorev1512/')
}

task copySimpleClientv11512Common(type: Copy) {
  shouldRunAfter jar
  from configurations.SimpleClientv11512Common
  into new File(autoFvtDir, 'publish/shared/resources/prometheusSimpleClientLib/')
}

task copySimpleClientv11512TracerCommon(type: Copy) {
  shouldRunAfter jar
  from configurations.SimpleClientv11512TracerCommon
  into new File(autoFvtDir, 'publish/shared/resources/prometheusSimpleClientLib/')
}

task copySimpleClientv11512TracerOtelAgent(type: Copy) {
  shouldRunAfter jar
  from configurations.SimpleClientv11512TracerOtelAgent
  into new File(autoFvtDir, 'publish/shared/resources/prometheusSimpleClientLib/')
}

task copySimpleClientv11512TracerOtel(type: Copy) {
  shouldRunAfter jar
  from configurations.SimpleClientv11512TracerOtel
  into new File(autoFvtDir, 'publish/shared/resources/prometheusSimpleClientLib/')
}

task copySimpleClientv11512(type: Copy) {
  shouldRunAfter jar
  from configurations.SimpleClientv11512
  into new File(autoFvtDir, 'publish/shared/resources/prometheusSimpleClientLib/')
}

 addRequiredLibraries {
  dependsOn copyMicrometerCore
  dependsOn copyPrometheus
  dependsOn copyHdrHistogramPrometheus
  dependsOn copyHdrHistogramUseless
  dependsOn copySimpleClientCommon
  dependsOn copySimpleClientTracerCommon
  dependsOn copySimpleClientTracerOtelAgent
  dependsOn copySimpleClientTracerOtel
  dependsOn copySimpleClient
  dependsOn copyHdrHistogramPrometheuslib1512
  dependsOn copyPrometheusRegistry1512
  dependsOn copyHdrHistogramPrometheusSimpleClient
  dependsOn copyPrometheusSimpleClientRegistry
  dependsOn copyMicrometerCorev1512
  dependsOn copyMicrometerCommons
  dependsOn copySimpleClientv11512Common
  dependsOn copySimpleClientv11512TracerCommon
  dependsOn copySimpleClientv11512TracerOtelAgent
  dependsOn copySimpleClientv11512TracerOtel
  dependsOn copySimpleClientv11512
}