CREATE TABLE ${schemaname}.EventEntityOLGH14426 (id BIGINT NOT NULL, datef DATETIME, JOB_ID BIGINT, PRIMARY KEY (id)) ENGINE = innodb;
CREATE TABLE ${schemaname}.JobEntityOLGH14426 (id BIGINT NOT NULL, DTYPE VARCHAR(255), PRIMARY KEY (id)) ENGINE = innodb;
CREATE INDEX I_VNTN426_JOB ON ${schemaname}.EventEntityOLGH14426 (JOB_ID);
CREATE INDEX I_JBNT426_DTYPE ON ${schemaname}.JobEntityOLGH14426 (DTYPE);