CREATE TABLE ${schemaname}.EventEntityOLGH14426 (id NUMBER NOT NULL, datef TIMESTAMP, JOB_ID NUMBER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.JobEntityOLGH14426 (id NUMBER NOT NULL, DTYPE VARCHAR2(255), PRIMARY KEY (id));
CREATE INDEX I_VNTN426_JOB ON ${schemaname}.EventEntityOLGH14426 (JOB_ID);
CREATE INDEX I_JBNT426_DTYPE ON ${schemaname}.JobEntityOLGH14426 (DTYPE);