#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Dec 25 11:35:59 GMT 2024
maven-metadata-apache.snapshots.xml.error=
maven-metadata-apache.snapshots.xml.lastUpdated=1735126559971
