//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:52 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:54 PM(foreman)-)
//


package com.ibm.ws.policyattachments.service1.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "helloWithPolicy", namespace = "http://service1.policyattachments.ws.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "helloWithPolicy", namespace = "http://service1.policyattachments.ws.ibm.com/")
public class HelloWithPolicy {


}
