-- Ignore pluggable databases
alter session set "_ORACLE_SCRIPT"=true;

-- Create oracle user
CREATE USER "ORACLEUSR@EXAMPLE.COM" IDENTIFIED EXTERNALLY;
GRANT CONNECT TO "ORACLEUSR@EXAMPLE.COM";
GRANT CREATE SESSION TO "ORACLEUSR@EXAMPLE.COM";

