/*******************************************************************************
 * Copyright (c) 2018 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package http2.test.war.servlets;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * HTTP/2 test servlet. The server.xml for this test uses compression. After the response is compressed, that
 * max frame size should still be respected.
 *
 * Per 6.5.2, the SETTINGS_MAX_FRAME_SIZE initial AND minumum value is 16384.
 */
@WebServlet("/H2Compression")
public class H2Compression extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        response.setHeader("Content-Type", "application/xml");

        PrintWriter pw = response.getWriter();

        char c = 'c';
        // need a string that won't easily deflate down to less than 16344
        StringBuilder sb = new StringBuilder(30000);
        for (int i = 0; i < 29000; i++) {
            sb.append(c);
        }
        // A very big body to make sure compression works
        pw.print("Chapter 1\n"
                 + "Marseilles — The Arrival.\n"
                 + "\n"
                 + "On the 24th of February, 1815, the look-out at Notre-Dame de la Garde signalled the three-master, the Pharaon from Smyrna, Trieste, and Naples.\n"
                 + "\n"
                 + "As usual, a pilot put off immediately, and rounding the Chateau d’If, got on board the vessel between Cape Morgion and Rion island.\n"
                 + "\n"
                 + "Immediately, and according to custom, the ramparts of Fort Saint-Jean were covered with spectators; it is always an event at Marseilles for a ship to come into port, especially when this ship, like the Pharaon, has been built, rigged, and laden at the old Phocee docks, and belongs to an owner of the city.\n"
                 + "\n"
                 + "The ship drew on and had safely passed the strait, which some volcanic shock has made between the Calasareigne and Jaros islands; had doubled Pomegue, and approached the harbor under topsails, jib, and spanker, but so slowly and sedately that the idlers, with that instinct which is the forerunner of evil, asked one another what misfortune could have happened on board. However, those experienced in navigation saw plainly that if any accident had occurred, it was not to the vessel herself, for she bore down with all the evidence of being skilfully handled, the anchor a-cockbill, the jib-boom guys already eased off, and standing by the side of the pilot, who was steering the Pharaon towards the narrow entrance of the inner port, was a young man, who, with activity and vigilant eye, watched every motion of the ship, and repeated each direction of the pilot.\n"
                 + "\n"
                 + "The vague disquietude which prevailed among the spectators had so much affected one of the crowd that he did not await the arrival of the vessel in harbor, but jumping into a small skiff, desired to be pulled alongside the Pharaon, which he reached as she rounded into La Reserve basin.\n"
                 + "\n"
                 + "When the young man on board saw this person approach, he left his station by the pilot, and, hat in hand, leaned over the ship’s bulwarks.\n"
                 + "\n"
                 + "He was a fine, tall, slim young fellow of eighteen or twenty, with black eyes, and hair as dark as a raven’s wing; and his whole appearance bespoke that calmness and resolution peculiar to men accustomed from their cradle to contend with danger.\n"
                 + "\n"
                 + "“Ah, is it you, Dantes?” cried the man in the skiff. “What’s the matter? and why have you such an air of sadness aboard?”\n"
                 + "\n"
                 + "“A great misfortune, M. Morrel,” replied the young man, — “a great misfortune, for me especially! Off Civita Vecchia we lost our brave Captain Leclere.”\n"
                 + "\n"
                 + "“And the cargo?” inquired the owner, eagerly.\n"
                 + "\n"
                 + "“Is all safe, M. Morrel; and I think you will be satisfied on that head. But poor Captain Leclere — “\n"
                 + "\n"
                 + "“What happened to him?” asked the owner, with an air of considerable resignation. “What happened to the worthy captain?”\n"
                 + "\n"
                 + "“He died.”\n"
                 + "\n"
                 + "“Fell into the sea?”\n"
                 + "\n"
                 + "“No, sir, he died of brain-fever in dreadful agony.” Then turning to the crew, he said, “Bear a hand there, to take in sail!”\n"
                 + "\n"
                 + "All hands obeyed, and at once the eight or ten seamen who composed the crew, sprang to their respective stations at the spanker brails and outhaul, topsail sheets and halyards, the jib downhaul, and the topsail clewlines and buntlines. The young sailor gave a look to see that his orders were promptly and accurately obeyed, and then turned again to the owner.\n"
                 + "\n"
                 + "“And how did this misfortune occur?” inquired the latter, resuming the interrupted conversation.\n"
                 + "\n"
                 + "“Alas, sir, in the most unexpected manner. After a long talk with the harbor-master, Captain Leclere left Naples greatly disturbed in mind. In twenty-four hours he was attacked by a fever, and died three days afterwards. We performed the usual burial service, and he is at his rest, sewn up in his hammock with a thirty-six pound shot at his head and his heels, off El Giglio island. We bring to his widow his sword and cross of honor. It was worth while, truly,” added the young man with a melancholy smile, “to make war against the English for ten years, and to die in his bed at last, like everybody else.”\n"
                 + "\n"
                 + "“Why, you see, Edmond,” replied the owner, who appeared more comforted at every moment, “we are all mortal, and the old must make way for the young. If not, why, there would be no promotion; and since you assure me that the cargo — “\n"
                 + "\n"
                 + "“Is all safe and sound, M. Morrel, take my word for it; and I advise you not to take 25,000 francs for the profits of the voyage.”\n"
                 + "\n"
                 + "Then, as they were just passing the Round Tower, the young man shouted: “Stand by there to lower the topsails and jib; brail up the spanker!”\n"
                 + "\n"
                 + "The order was executed as promptly as it would have been on board a man-of-war.\n"
                 + "\n"
                 + "“Let go — and clue up!” At this last command all the sails were lowered, and the vessel moved almost imperceptibly onwards.\n"
                 + "\n"
                 + "“Now, if you will come on board, M. Morrel,” said Dantes, observing the owner’s impatience, “here is your supercargo, M. Danglars, coming out of his cabin, who will furnish you with every particular. As for me, I must look after the anchoring, and dress the ship in mourning.”\n"
                 + "\n"
                 + "The owner did not wait for a second invitation. He seized a rope which Dantes flung to him, and with an activity that would have done credit to a sailor, climbed up the side of the ship, while the young man, going to his task, left the conversation to Danglars, who now came towards the owner. He was a man of twenty-five or twenty-six years of age, of unprepossessing countenance, obsequious to his superiors, insolent to his subordinates; and this, in addition to his position as responsible agent on board, which is always obnoxious to the sailors, made him as much disliked by the crew as Edmond Dantes was beloved by them.\n"
                 + "\n"
                 + "“Well, M. Morrel,” said Danglars, “you have heard of the misfortune that has befallen us?”\n"
                 + "\n"
                 + "“Yes — yes: poor Captain Leclere! He was a brave and an honest man.”\n"
                 + "\n"
                 + "“And a first-rate seaman, one who had seen long and honorable service, as became a man charged with the interests of a house so important as that of Morrel & Son,” replied Danglars.\n"
                 + "\n"
                 + "“But,” replied the owner, glancing after Dantes, who was watching the anchoring of his vessel, “it seems to me that a sailor needs not be so old as you say, Danglars, to understand his business, for our friend Edmond seems to understand it thoroughly, and not to require instruction from any one.”\n"
                 + "\n"
                 + "“Yes,” said Danglars, darting at Edmond a look gleaming with hate. “Yes, he is young, and youth is invariably self-confident. Scarcely was the captain’s breath out of his body when he assumed the command without consulting any one, and he caused us to lose a day and a half at the Island of Elba, instead of making for Marseilles direct.”\n"
                 + "\n"
                 + "“As to taking command of the vessel,” replied Morrel, “that was his duty as captain’s mate; as to losing a day and a half off the Island of Elba, he was wrong, unless the vessel needed repairs.”\n"
                 + "\n"
                 + "“The vessel was in as good condition as I am, and as, I hope you are, M. Morrel, and this day and a half was lost from pure whim, for the pleasure of going ashore, and nothing else.”\n"
                 + "\n"
                 + "“Dantes,” said the shipowner, turning towards the young man, “come this way!”\n"
                 + "\n"
                 + "“In a moment, sir,” answered Dantes, “and I’m with you.” Then calling to the crew, he said — “Let go!”\n"
                 + "\n"
                 + "The anchor was instantly dropped, and the chain ran rattling through the port-hole. Dantes continued at his post in spite of the presence of the pilot, until this manoeuvre was completed, and then he added, “Half-mast the colors, and square the yards!”\n"
                 + "\n"
                 + "“You see,” said Danglars, “he fancies himself captain already, upon my word.”\n"
                 + "\n"
                 + "“And so, in fact, he is,” said the owner.\n"
                 + "\n"
                 + "“Except your signature and your partner’s, M. Morrel.”\n"
                 + "\n"
                 + "“And why should he not have this?” asked the owner; “he is young, it is true, but he seems to me a thorough seaman, and of full experience.”\n"
                 + "\n"
                 + "A cloud passed over Danglars’ brow. “Your pardon, M. Morrel,” said Dantes, approaching, “the vessel now rides at anchor, and I am at your service. You hailed me, I think?”\n"
                 + "\n"
                 + "Danglars retreated a step or two. “I wished to inquire why you stopped at the Island of Elba?”\n"
                 + "\n"
                 + "“I do not know, sir; it was to fulfil the last instructions of Captain Leclere, who, when dying, gave me a packet for Marshal Bertrand.”\n"
                 + "\n"
                 + "“Then did you see him, Edmond?”\n"
                 + "\n"
                 + "“Who?”\n"
                 + "\n"
                 + "“The marshal.”\n"
                 + "\n"
                 + "“Yes.”\n"
                 + "\n"
                 + "Morrel looked around him, and then, drawing Dantes on one side, he said suddenly — “And how is the emperor?”\n"
                 + "\n"
                 + "“Very well, as far as I could judge from the sight of him.”\n"
                 + "\n"
                 + "“You saw the emperor, then?”\n"
                 + "\n"
                 + "“He entered the marshal’s apartment while I was there.”\n"
                 + "\n"
                 + "“And you spoke to him?”\n"
                 + "\n"
                 + "“Why, it was he who spoke to me, sir,” said Dantes, with a smile.\n"
                 + "\n"
                 + "“And what did he say to you?”\n"
                 + "\n"
                 + "“Asked me questions about the vessel, the time she left Marseilles, the course she had taken, and what was her cargo. I believe, if she had not been laden, and I had been her master, he would have bought her. But I told him I was only mate, and that she belonged to the firm of Morrel & Son. `Ah, yes,’ he said, `I know them. The Morrels have been shipowners from father to son; and there was a Morrel who served in the same regiment with me when I was in garrison at Valence.'”\n"
                 + "\n"
                 + "“Pardieu, and that is true!” cried the owner, greatly delighted. “And that was Policar Morrel, my uncle, who was afterwards a captain. Dantes, you must tell my uncle that the emperor remembered him, and you will see it will bring tears into the old soldier’s eyes. Come, come,” continued he, patting Edmond’s shoulder kindly, “you did very right, Dantes, to follow Captain Leclere’s instructions, and touch at Elba, although if it were known that you had conveyed a packet to the marshal, and had conversed with the emperor, it might bring you into trouble.”\n"
                 + "\n"
                 + "“How could that bring me into trouble, sir?” asked Dantes; “for I did not even know of what I was the bearer; and the emperor merely made such inquiries as he would of the first comer. But, pardon me, here are the health officers and the customs inspectors coming alongside.” And the young man went to the gangway. As he departed, Danglars approached, and said, —\n"
                 + "\n"
                 + "“Well, it appears that he has given you satisfactory reasons for his landing at Porto-Ferrajo?”\n"
                 + "\n"
                 + "“Yes, most satisfactory, my dear Danglars.”\n"
                 + "\n"
                 + "“Well, so much the better,” said the supercargo; “for it is not pleasant to think that a comrade has not done his duty.”\n"
                 + "\n"
                 + "“Dantes has done his,” replied the owner, “and that is not saying much. It was Captain Leclere who gave orders for this delay.”\n"
                 + "\n"
                 + "“Talking of Captain Leclere, has not Dantes given you a letter from him?”\n"
                 + "\n"
                 + "“To me? — no — was there one?”\n"
                 + "\n"
                 + "“I believe that, besides the packet, Captain Leclere confided a letter to his care.”\n"
                 + "\n"
                 + "“Of what packet are you speaking, Danglars?”\n"
                 + "\n"
                 + "“Why, that which Dantes left at Porto-Ferrajo.”\n"
                 + "\n"
                 + "“How do you know he had a packet to leave at Porto-Ferrajo?”\n"
                 + "\n"
                 + "Danglars turned very red.\n"
                 + "\n"
                 + "“I was passing close to the door of the captain’s cabin, which was half open, and I saw him give the packet and letter to Dantes.”\n"
                 + "\n"
                 + "“He did not speak to me of it,” replied the shipowner; “but if there be any letter he will give it to me.”\n"
                 + "\n"
                 + "Danglars reflected for a moment. “Then, M. Morrel, I beg of you,” said he, “not to say a word to Dantes on the subject. I may have been mistaken.”\n"
                 + "\n"
                 + "At this moment the young man returned; Danglars withdrew.\n"
                 + "\n"
                 + "“Well, my dear Dantes, are you now free?” inquired the owner.\n"
                 + "\n"
                 + "“Yes, sir.”\n"
                 + "\n"
                 + "“You have not been long detained.”\n"
                 + "\n"
                 + "“No. I gave the custom-house officers a copy of our bill of lading; and as to the other papers, they sent a man off with the pilot, to whom I gave them.”\n"
                 + "\n"
                 + "“Then you have nothing more to do here?”\n"
                 + "\n"
                 + "“No — everything is all right now.”\n"
                 + "\n"
                 + "“Then you can come and dine with me?”\n"
                 + "\n"
                 + "“I really must ask you to excuse me, M. Morrel. My first visit is due to my father, though I am not the less grateful for the honor you have done me.”\n"
                 + "\n"
                 + "“Right, Dantes, quite right. I always knew you were a good son.”\n"
                 + "\n"
                 + "“And,” inquired Dantes, with some hesitation, “do you know how my father is?”\n"
                 + "\n"
                 + "“Well, I believe, my dear Edmond, though I have not seen him lately.”\n"
                 + "\n"
                 + "“Yes, he likes to keep himself shut up in his little room.”\n"
                 + "\n"
                 + "“That proves, at least, that he has wanted for nothing during your absence.”\n"
                 + "\n"
                 + "Dantes smiled. “My father is proud, sir, and if he had not a meal left, I doubt if he would have asked anything from anyone, except from Heaven.”\n"
                 + "\n"
                 + "“Well, then, after this first visit has been made we shall count on you.”\n"
                 + "\n"
                 + "“I must again excuse myself, M. Morrel, for after this first visit has been paid I have another which I am most anxious to pay.”\n"
                 + "\n"
                 + "“True, Dantes, I forgot that there was at the Catalans some one who expects you no less impatiently than your father — the lovely Mercedes.”\n"
                 + "\n"
                 + "Dantes blushed.\n"
                 + "\n"
                 + "“Ah, ha,” said the shipowner, “I am not in the least surprised, for she has been to me three times, inquiring if there were any news of the Pharaon. Peste, Edmond, you have a very handsome mistress!”\n"
                 + "\n"
                 + "“She is not my mistress,” replied the young sailor, gravely; “she is my betrothed.”\n"
                 + "\n"
                 + "“Sometimes one and the same thing,” said Morrel, with a smile.\n"
                 + "\n"
                 + "“Not with us, sir,” replied Dantes.\n"
                 + "\n"
                 + "“Well, well, my dear Edmond,” continued the owner, “don’t let me detain you. You have managed my affairs so well that I ought to allow you all the time you require for your own. Do you want any money?”\n"
                 + "\n"
                 + "“No, sir; I have all my pay to take — nearly three months’ wages.”\n"
                 + "\n"
                 + "“You are a careful fellow, Edmond.”\n"
                 + "\n"
                 + "“Say I have a poor father, sir.”\n"
                 + "\n"
                 + "“Yes, yes, I know how good a son you are, so now hasten away to see your father. I have a son too, and I should be very wroth with those who detained him from me after a three months’ voyage.”\n"
                 + "\n"
                 + "“Then I have your leave, sir?”\n"
                 + "\n"
                 + "“Yes, if you have nothing more to say to me.”\n"
                 + "\n"
                 + "“Nothing.”\n"
                 + "\n"
                 + "“Captain Leclere did not, before he died, give you a letter for me?”\n"
                 + "\n"
                 + "“He was unable to write, sir. But that reminds me that I must ask your leave of absence for some days.”\n"
                 + "\n"
                 + "“To get married?”\n"
                 + "\n"
                 + "“Yes, first, and then to go to Paris.”\n"
                 + "\n"
                 + "“Very good; have what time you require, Dantes. It will take quite six weeks to unload the cargo, and we cannot get you ready for sea until three months after that; only be back again in three months, for the Pharaon,” added the owner, patting the young sailor on the back, “cannot sail without her captain.”\n"
                 + "\n"
                 + "“Without her captain!” cried Dantes, his eyes sparkling with animation; “pray mind what you say, for you are touching on the most secret wishes of my heart. Is it really your intention to make me captain of the Pharaon?”\n"
                 + "\n"
                 + "“If I were sole owner we’d shake hands on it now, my dear Dantes, and call it settled; but I have a partner, and you know the Italian proverb — Chi ha compagno ha padrone — `He who has a partner has a master.’ But the thing is at least half done, as you have one out of two votes. Rely on me to procure you the other; I will do my best.”\n"
                 + "\n"
                 + "“Ah, M. Morrel,” exclaimed the young seaman, with tears in his eyes, and grasping the owner’s hand, “M. Morrel, I thank you in the name of my father and of Mercedes.”\n"
                 + "\n"
                 + "“That’s all right, Edmond. There’s a providence that watches over the deserving. Go to your father: go and see Mercedes, and afterwards come to me.”\n"
                 + "\n"
                 + "“Shall I row you ashore?”\n"
                 + "\n"
                 + "“No, thank you; I shall remain and look over the accounts with Danglars. Have you been satisfied with him this voyage?”\n"
                 + "\n"
                 + "“That is according to the sense you attach to the question, sir. Do you mean is he a good comrade? No, for I think he never liked me since the day when I was silly enough, after a little quarrel we had, to propose to him to stop for ten minutes at the island of Monte Cristo to settle the dispute — a proposition which I was wrong to suggest, and he quite right to refuse. If you mean as responsible agent when you ask me the question, I believe there is nothing to say against him, and that you will be content with the way in which he has performed his duty.”\n"
                 + "\n"
                 + "“But tell me, Dantes, if you had command of the Pharaon should you be glad to see Danglars remain?”\n"
                 + "\n"
                 + "“Captain or mate, M. Morrel, I shall always have the greatest respect for those who possess the owners’ confidence.”\n"
                 + "\n"
                 + "“That’s right, that’s right, Dantes! I see you are a thoroughly good fellow, and will detain you no longer. Go, for I see how impatient you are.”\n"
                 + "\n"
                 + "“Then I have leave?”\n"
                 + "\n"
                 + "“Go, I tell you.”\n"
                 + "\n"
                 + "“May I have the use of your skiff?”\n"
                 + "\n"
                 + "“Certainly.”\n"
                 + "\n"
                 + "“Then, for the present, M. Morrel, farewell, and a thousand thanks!”\n"
                 + "\n"
                 + "“I hope soon to see you again, my dear Edmond. Good luck to you.”\n"
                 + "\n"
                 + "The young sailor jumped into the skiff, and sat down in the stern sheets, with the order that he be put ashore at La Canebiere. The two oarsmen bent to their work, and the little boat glided away as rapidly as possible in the midst of the thousand vessels which choke up the narrow way which leads between the two rows of ships from the mouth of the harbor to the Quai d’Orleans.\n"
                 + "\n"
                 + "The shipowner, smiling, followed him with his eyes until he saw him spring out on the quay and disappear in the midst of the throng, which from five o’clock in the morning until nine o’clock at night, swarms in the famous street of La Canebiere, — a street of which the modern Phocaeans are so proud that they say with all the gravity in the world, and with that accent which gives so much character to what is said, “If Paris had La Canebiere, Paris would be a second Marseilles.” On turning round the owner saw Danglars behind him, apparently awaiting orders, but in reality also watching the young sailor, — but there was a great difference in the expression of the two men who thus followed the movements of Edmond Dantes.\n"
                 + "\n"
                 + "Chapter 2\n"
                 + "Father and Son.\n"
                 + "\n"
                 + "We will leave Danglars struggling with the demon of hatred, and endeavoring to insinuate in the ear of the shipowner some evil suspicions against his comrade, and follow Dantes, who, after having traversed La Canebiere, took the Rue de Noailles, and entering a small house, on the left of the Allees de Meillan, rapidly ascended four flights of a dark staircase, holding the baluster with one hand, while with the other he repressed the beatings of his heart, and paused before a half-open door, from which he could see the whole of a small room.\n"
                 + "\n"
                 + "This room was occupied by Dantes’ father. The news of the arrival of the Pharaon had not yet reached the old man, who, mounted on a chair, was amusing himself by training with trembling hand the nasturtiums and sprays of clematis that clambered over the trellis at his window. Suddenly, he felt an arm thrown around his body, and a well-known voice behind him exclaimed, “Father — dear father!”\n"
                 + "\n"
                 + "The old man uttered a cry, and turned round; then, seeing his son, he fell into his arms, pale and trembling.\n"
                 + "\n"
                 + "“What ails you, my dearest father? Are you ill?” inquired the young man, much alarmed.\n"
                 + "\n"
                 + "“No, no, my dear Edmond — my boy — my son! — no; but I did not expect you; and joy, the surprise of seeing you so suddenly — Ah, I feel as if I were going to die.”\n"
                 + "\n"
                 + "“Come, come, cheer up, my dear father! ‘Tis I — really I! They say joy never hurts, and so I came to you without any warning. Come now, do smile, instead of looking at me so solemnly. Here I am back again, and we are going to be happy.”\n"
                 + "\n"
                 + "“Yes, yes, my boy, so we will — so we will,” replied the old man; “but how shall we be happy? Shall you never leave me again? Come, tell me all the good fortune that has befallen you.”\n"
                 + "\n"
                 + "“God forgive me,” said the young man, “for rejoicing at happiness derived from the misery of others, but, Heaven knows, I did not seek this good fortune; it has happened, and I really cannot pretend to lament it. The good Captain Leclere is dead, father, and it is probable that, with the aid of M. Morrel, I shall have his place. Do you understand, father? Only imagine me a captain at twenty, with a hundred louis pay, and a share in the profits! Is this not more than a poor sailor like me could have hoped for?”\n"
                 + "\n"
                 + "“Yes, my dear boy,” replied the old man, “it is very fortunate.”\n"
                 + "\n"
                 + "“Well, then, with the first money I touch, I mean you to have a small house, with a garden in which to plant clematis, nasturtiums, and honeysuckle. But what ails you, father? Are you not well?”\n"
                 + "\n"
                 + "“‘Tis nothing, nothing; it will soon pass away” — and as he said so the old man’s strength failed him, and he fell backwards.\n"
                 + "\n"
                 + "“Come, come,” said the young man, “a glass of wine, father, will revive you. Where do you keep your wine?”\n"
                 + "\n"
                 + "“No, no; thanks. You need not look for it; I do not want it,” said the old man.\n"
                 + "\n"
                 + "“Yes, yes, father, tell me where it is,” and he opened two or three cupboards.\n"
                 + "\n"
                 + "“It is no use,” said the old man, “there is no wine.”\n"
                 + "\n"
                 + "“What, no wine?” said Dantes, turning pale, and looking alternately at the hollow cheeks of the old man and the empty cupboards. “What, no wine? Have you wanted money, father?”\n"
                 + "\n");
        pw.print("“I want nothing now that I have you,” said the old man.\n"
                 + "\n"
                 + "“Yet,” stammered Dantes, wiping the perspiration from his brow, — “yet I gave you two hundred francs when I left, three months ago.”\n"
                 + "\n"
                 + "“Yes, yes, Edmond, that is true, but you forgot at that time a little debt to our neighbor, Caderousse. He reminded me of it, telling me if I did not pay for you, he would be paid by M. Morrel; and so, you see, lest he might do you an injury” —\n"
                 + "\n"
                 + "“Well?”\n"
                 + "\n"
                 + "“Why, I paid him.”\n"
                 + "\n"
                 + "“But,” cried Dantes, “it was a hundred and forty francs I owed Caderousse.”\n"
                 + "\n"
                 + "“Yes,” stammered the old man.\n"
                 + "\n"
                 + "“And you paid him out of the two hundred francs I left you?”\n"
                 + "\n"
                 + "The old man nodded.\n"
                 + "\n"
                 + "“So that you have lived for three months on sixty francs,” muttered Edmond.\n"
                 + "\n"
                 + "“You know how little I require,” said the old man.\n"
                 + "\n"
                 + "“Heaven pardon me,” cried Edmond, falling on his knees before his father.\n"
                 + "\n"
                 + "“What are you doing?”\n"
                 + "\n"
                 + "“You have wounded me to the heart.”\n"
                 + "\n"
                 + "“Never mind it, for I see you once more,” said the old man; “and now it’s all over — everything is all right again.”\n"
                 + "\n"
                 + "“Yes, here I am,” said the young man, “with a promising future and a little money. Here, father, here!” he said, “take this — take it, and send for something immediately.” And he emptied his pockets on the table, the contents consisting of a dozen gold pieces, five or six five-franc pieces, and some smaller coin. The countenance of old Dantes brightened.\n"
                 + "\n"
                 + "“Whom does this belong to?” he inquired.\n"
                 + "\n"
                 + "“To me, to you, to us! Take it; buy some provisions; be happy, and to-morrow we shall have more.”\n"
                 + "\n"
                 + "“Gently, gently,” said the old man, with a smile; “and by your leave I will use your purse moderately, for they would say, if they saw me buy too many things at a time, that I had been obliged to await your return, in order to be able to purchase them.”\n"
                 + "\n"
                 + "“Do as you please; but, first of all, pray have a servant, father. I will not have you left alone so long. I have some smuggled coffee and most capital tobacco, in a small chest in the hold, which you shall have to-morrow. But, hush, here comes somebody.”\n"
                 + "\n"
                 + "“‘Tis Caderousse, who has heard of your arrival, and no doubt comes to congratulate you on your fortunate return.”\n"
                 + "\n"
                 + "“Ah, lips that say one thing, while the heart thinks another,” murmured Edmond. “But, never mind, he is a neighbor who has done us a service on a time, so he’s welcome.”\n"
                 + "\n"
                 + "As Edmond paused, the black and bearded head of Caderousse appeared at the door. He was a man of twenty-five or six, and held a piece of cloth, which, being a tailor, he was about to make into a coat-lining.\n"
                 + "\n"
                 + "“What, is it you, Edmond, back again?” said he, with a broad Marseillaise accent, and a grin that displayed his ivory-white teeth.\n"
                 + "\n"
                 + "“Yes, as you see, neighbor Caderousse; and ready to be agreeable to you in any and every way,” replied Dantes, but ill-concealing his coldness under this cloak of civility.\n"
                 + "\n"
                 + "“Thanks — thanks; but, fortunately, I do not want for anything; and it chances that at times there are others who have need of me.” Dantes made a gesture. “I do not allude to you, my boy. No! — no! I lent you money, and you returned it; that’s like good neighbors, and we are quits.”\n"
                 + "\n"
                 + "“We are never quits with those who oblige us,” was Dantes’ reply; “for when we do not owe them money, we owe them gratitude.”\n"
                 + "\n"
                 + "“What’s the use of mentioning that? What is done is done. Let us talk of your happy return, my boy. I had gone on the quay to match a piece of mulberry cloth, when I met friend Danglars. `You at Marseilles?’ — `Yes,’ says he.\n"
                 + "\n"
                 + "“`I thought you were at Smyrna.’ — `I was; but am now back again.’\n"
                 + "\n"
                 + "“`And where is the dear boy, our little Edmond?’\n"
                 + "\n"
                 + "“`Why, with his father, no doubt,’ replied Danglars. And so I came,” added Caderousse, “as fast as I could to have the pleasure of shaking hands with a friend.”\n"
                 + "\n"
                 + "“Worthy Caderousse!” said the old man, “he is so much attached to us.”\n"
                 + "\n"
                 + "“Yes, to be sure I am. I love and esteem you, because honest folks are so rare. But it seems you have come back rich, my boy,” continued the tailor, looking askance at the handful of gold and silver which Dantes had thrown on the table.\n"
                 + "\n"
                 + "The young man remarked the greedy glance which shone in the dark eyes of his neighbor. “Eh,” he said, negligently. “this money is not mine. I was expressing to my father my fears that he had wanted many things in my absence, and to convince me he emptied his purse on the table. Come, father” added Dantes, “put this money back in your box — unless neighbor Caderousse wants anything, and in that case it is at his service.”\n"
                 + "\n"
                 + "“No, my boy, no,” said Caderousse. “I am not in any want, thank God, my living is suited to my means. Keep your money — keep it, I say; — one never has too much; — but, at the same time, my boy, I am as much obliged by your offer as if I took advantage of it.”\n"
                 + "\n"
                 + "“It was offered with good will,” said Dantes.\n"
                 + "\n"
                 + "“No doubt, my boy; no doubt. Well, you stand well with M. Morrel I hear, — you insinuating dog, you!”\n"
                 + "\n"
                 + "“M. Morrel has always been exceedingly kind to me,” replied Dantes.\n"
                 + "\n"
                 + "“Then you were wrong to refuse to dine with him.”\n"
                 + "\n"
                 + "“What, did you refuse to dine with him?” said old Dantes; “and did he invite you to dine?”\n"
                 + "\n"
                 + "“Yes, my dear father,” replied Edmond, smiling at his father’s astonishment at the excessive honor paid to his son.\n"
                 + "\n"
                 + "“And why did you refuse, my son?” inquired the old man.\n"
                 + "\n"
                 + "“That I might the sooner see you again, my dear father,” replied the young man. “I was most anxious to see you.”\n"
                 + "\n"
                 + "“But it must have vexed M. Morrel, good, worthy man,” said Caderousse. “And when you are looking forward to be captain, it was wrong to annoy the owner.”\n"
                 + "\n"
                 + "“But I explained to him the cause of my refusal,” replied Dantes, “and I hope he fully understood it.”\n"
                 + "\n"
                 + "“Yes, but to be captain one must do a little flattery to one’s patrons.”\n"
                 + "\n"
                 + "“I hope to be captain without that,” said Dantes.\n"
                 + "\n"
                 + "“So much the better — so much the better! Nothing will give greater pleasure to all your old friends; and I know one down there behind the Saint Nicolas citadel who will not be sorry to hear it.”\n"
                 + "\n"
                 + "“Mercedes?” said the old man.\n"
                 + "\n"
                 + "“Yes, my dear father, and with your permission, now I have seen you, and know you are well and have all you require, I will ask your consent to go and pay a visit to the Catalans.”\n"
                 + "\n"
                 + "“Go, my dear boy,” said old Dantes: “and heaven bless you in your wife, as it has blessed me in my son!”\n"
                 + "\n"
                 + "“His wife!” said Caderousse; “why, how fast you go on, father Dantes; she is not his wife yet, as it seems to me.”\n"
                 + "\n"
                 + "“So, but according to all probability she soon will be,” replied Edmond.\n"
                 + "\n"
                 + "“Yes — yes,” said Caderousse; “but you were right to return as soon as possible, my boy.”\n"
                 + "\n"
                 + "“And why?”\n"
                 + "\n"
                 + "“Because Mercedes is a very fine girl, and fine girls never lack followers; she particularly has them by dozens.”\n"
                 + "\n"
                 + "“Really?” answered Edmond, with a smile which had in it traces of slight uneasiness.\n"
                 + "\n"
                 + "“Ah, yes,” continued Caderousse, “and capital offers, too; but you know, you will be captain, and who could refuse you then?”\n"
                 + "\n"
                 + "“Meaning to say,” replied Dantes, with a smile which but ill-concealed his trouble, “that if I were not a captain” —\n"
                 + "\n"
                 + "“Eh — eh!” said Caderousse, shaking his head.\n"
                 + "\n"
                 + "“Come, come,” said the sailor, “I have a better opinion than you of women in general, and of Mercedes in particular; and I am certain that, captain or not, she will remain ever faithful to me.”\n"
                 + "\n"
                 + "“So much the better — so much the better,” said Caderousse. “When one is going to be married, there is nothing like implicit confidence; but never mind that, my boy, — go and announce your arrival, and let her know all your hopes and prospects.”\n"
                 + "\n"
                 + "“I will go directly,” was Edmond’s reply; and, embracing his father, and nodding to Caderousse, he left the apartment.\n"
                 + "\n"
                 + "Caderousse lingered for a moment, then taking leave of old Dantes, he went downstairs to rejoin Danglars, who awaited him at the corner of the Rue Senac.\n"
                 + "\n"
                 + "“Well,” said Danglars, “did you see him?”\n"
                 + "\n"
                 + "“I have just left him,” answered Caderousse.\n"
                 + "\n"
                 + "“Did he allude to his hope of being captain?”\n"
                 + "\n"
                 + "“He spoke of it as a thing already decided.”\n"
                 + "\n"
                 + "“Indeed!” said Danglars, “he is in too much hurry, it appears to me.”\n"
                 + "\n"
                 + "“Why, it seems M. Morrel has promised him the thing.”\n"
                 + "\n"
                 + "“So that he is quite elated about it?”\n"
                 + "\n"
                 + "“Why, yes, he is actually insolent over the matter — has already offered me his patronage, as if he were a grand personage, and proffered me a loan of money, as though he were a banker.”\n"
                 + "\n"
                 + "“Which you refused?”\n"
                 + "\n"
                 + "“Most assuredly; although I might easily have accepted it, for it was I who put into his hands the first silver he ever earned; but now M. Dantes has no longer any occasion for assistance — he is about to become a captain.”\n"
                 + "\n"
                 + "“Pooh!” said Danglars, “he is not one yet.”\n"
                 + "\n"
                 + "“Ma foi, it will be as well if he is not,” answered Caderousse; “for if he should be, there will be really no speaking to him.”\n"
                 + "\n"
                 + "“If we choose,” replied Danglars, “he will remain what he is; and perhaps become even less than he is.”\n"
                 + "\n"
                 + "“What do you mean?”\n"
                 + "\n"
                 + "“Nothing — I was speaking to myself. And is he still in love with the Catalane?”\n"
                 + "\n"
                 + "“Over head and ears; but, unless I am much mistaken, there will be a storm in that quarter.”\n"
                 + "\n"
                 + "“Explain yourself.”\n"
                 + "\n"
                 + "“Why should I?”\n"
                 + "\n"
                 + "“It is more important than you think, perhaps. You do not like Dantes?”\n"
                 + "\n"
                 + "“I never like upstarts.”\n"
                 + "\n"
                 + "“Then tell me all you know about the Catalane.”\n"
                 + "\n"
                 + "“I know nothing for certain; only I have seen things which induce me to believe, as I told you, that the future captain will find some annoyance in the vicinity of the Vieilles Infirmeries.”\n"
                 + "\n"
                 + "“What have you seen? — come, tell me!”\n"
                 + "\n"
                 + "“Well, every time I have seen Mercedes come into the city she has been accompanied by a tall, strapping, black-eyed Catalan, with a red complexion, brown skin, and fierce air, whom she calls cousin.”\n"
                 + "\n"
                 + "“Really; and you think this cousin pays her attentions?”\n"
                 + "\n"
                 + "“I only suppose so. What else can a strapping chap of twenty-one mean with a fine wench of seventeen?”\n"
                 + "\n"
                 + "“And you say that Dantes has gone to the Catalans?”\n"
                 + "\n"
                 + "“He went before I came down.”\n"
                 + "\n"
                 + "“Let us go the same way; we will stop at La Reserve, and we can drink a glass of La Malgue, whilst we wait for news.”\n"
                 + "\n"
                 + "“Come along,” said Caderousse; “but you pay the score.”\n"
                 + "\n"
                 + "“Of course,” replied Danglars; and going quickly to the designated place, they called for a bottle of wine, and two glasses.\n"
                 + "\n"
                 + "Pere Pamphile had seen Dantes pass not ten minutes before; and assured that he was at the Catalans, they sat down under the budding foliage of the planes and sycamores, in the branches of which the birds were singing their welcome to one of the first days of spring.\n"
                 + "\n"
                 + "Chapter 3\n"
                 + "The Catalans.\n"
                 + "\n"
                 + "Beyond a bare, weather-worn wall, about a hundred paces from the spot where the two friends sat looking and listening as they drank their wine, was the village of the Catalans. Long ago this mysterious colony quitted Spain, and settled on the tongue of land on which it is to this day. Whence it came no one knew, and it spoke an unknown tongue. One of its chiefs, who understood Provencal, begged the commune of Marseilles to give them this bare and barren promontory, where, like the sailors of old, they had run their boats ashore. The request was granted; and three months afterwards, around the twelve or fifteen small vessels which had brought these gypsies of the sea, a small village sprang up. This village, constructed in a singular and picturesque manner, half Moorish, half Spanish, still remains, and is inhabited by descendants of the first comers, who speak the language of their fathers. For three or four centuries they have remained upon this small promontory, on which they had settled like a flight of seabirds, without mixing with the Marseillaise population, intermarrying, and preserving their original customs and the costume of their mother-country as they have preserved its language.\n"
                 + "\n"
                 + "Our readers will follow us along the only street of this little village, and enter with us one of the houses, which is sunburned to the beautiful dead-leaf color peculiar to the buildings of the country, and within coated with whitewash, like a Spanish posada. A young and beautiful girl, with hair as black as jet, her eyes as velvety as the gazelle’s, was leaning with her back against the wainscot, rubbing in her slender delicately moulded fingers a bunch of heath blossoms, the flowers of which she was picking off and strewing on the floor; her arms, bare to the elbow, brown, and modelled after those of the Arlesian Venus, moved with a kind of restless impatience, and she tapped the earth with her arched and supple foot, so as to display the pure and full shape of her well-turned leg, in its red cotton, gray and blue clocked, stocking. At three paces from her, seated in a chair which he balanced on two legs, leaning his elbow on an old worm-eaten table, was a tall young man of twenty, or two-and-twenty, who was looking at her with an air in which vexation and uneasiness were mingled. He questioned her with his eyes, but the firm and steady gaze of the young girl controlled his look.\n"
                 + "\n"
                 + "“You see, Mercedes,” said the young man, “here is Easter come round again; tell me, is this the moment for a wedding?”\n"
                 + "\n"
                 + "“I have answered you a hundred times, Fernand, and really you must be very stupid to ask me again.”\n"
                 + "\n"
                 + "“Well, repeat it, — repeat it, I beg of you, that I may at last believe it! Tell me for the hundredth time that you refuse my love, which had your mother’s sanction. Make me understand once for all that you are trifling with my happiness, that my life or death are nothing to you. Ah, to have dreamed for ten years of being your husband, Mercedes, and to lose that hope, which was the only stay of my existence!”\n"
                 + "\n"
                 + "“At least it was not I who ever encouraged you in that hope, Fernand,” replied Mercedes; “you cannot reproach me with the slightest coquetry. I have always said to you, `I love you as a brother; but do not ask from me more than sisterly affection, for my heart is another’s.’ Is not this true, Fernand?”\n"
                 + "\n"
                 + "“Yes, that is very true, Mercedes,” replied the young man, “Yes, you have been cruelly frank with me; but do you forget that it is among the Catalans a sacred law to intermarry?”\n"
                 + "\n"
                 + "“You mistake, Fernand; it is not a law, but merely a custom, and, I pray of you, do not cite this custom in your favor. You are included in the conscription, Fernand, and are only at liberty on sufferance, liable at any moment to be called upon to take up arms. Once a soldier, what would you do with me, a poor orphan, forlorn, without fortune, with nothing but a half-ruined hut and a few ragged nets, the miserable inheritance left by my father to my mother, and by my mother to me? She has been dead a year, and you know, Fernand, I have subsisted almost entirely on public charity. Sometimes you pretend I am useful to you, and that is an excuse to share with me the produce of your fishing, and I accept it, Fernand, because you are the son of my father’s brother, because we were brought up together, and still more because it would give you so much pain if I refuse. But I feel very deeply that this fish which I go and sell, and with the produce of which I buy the flax I spin, — I feel very keenly, Fernand, that this is charity.”\n"
                 + "\n"
                 + "“And if it were, Mercedes, poor and lone as you are, you suit me as well as the daughter of the first shipowner or the richest banker of Marseilles! What do such as we desire but a good wife and careful housekeeper, and where can I look for these better than in you?”\n"
                 + "\n"
                 + "“Fernand,” answered Mercedes, shaking her head, “a woman becomes a bad manager, and who shall say she will remain an honest woman, when she loves another man better than her husband? Rest content with my friendship, for I say once more that is all I can promise, and I will promise no more than I can bestow.”\n"
                 + "\n"
                 + "“I understand,” replied Fernand, “you can endure your own wretchedness patiently, but you are afraid to share mine. Well, Mercedes, beloved by you, I would tempt fortune; you would bring me good luck, and I should become rich. I could extend my occupation as a fisherman, might get a place as clerk in a warehouse, and become in time a dealer myself.”\n"
                 + "\n"
                 + "“You could do no such thing, Fernand; you are a soldier, and if you remain at the Catalans it is because there is no war; so remain a fisherman, and contented with my friendship, as I cannot give you more.”\n"
                 + "\n"
                 + "“Well, I will do better, Mercedes. I will be a sailor; instead of the costume of our fathers, which you despise, I will wear a varnished hat, a striped shirt, and a blue jacket, with an anchor on the buttons. Would not that dress please you?”\n"
                 + "\n"
                 + "“What do you mean?” asked Mercedes, with an angry glance, — “what do you mean? I do not understand you?”\n"
                 + "\n"
                 + "“I mean, Mercedes, that you are thus harsh and cruel with me, because you are expecting some one who is thus attired; but perhaps he whom you await is inconstant, or if he is not, the sea is so to him.”\n"
                 + "\n"
                 + "“Fernand,” cried Mercedes, “I believed you were good-hearted, and I was mistaken! Fernand, you are wicked to call to your aid jealousy and the anger of God! Yes, I will not deny it, I do await, and I do love him of whom you speak; and, if he does not return, instead of accusing him of the inconstancy which you insinuate, I will tell you that he died loving me and me only.” The young girl made a gesture of rage. “I understand you, Fernand; you would be revenged on him because I do not love you; you would cross your Catalan knife with his dirk. What end would that answer? To lose you my friendship if he were conquered, and see that friendship changed into hate if you were victor. Believe me, to seek a quarrel with a man is a bad method of pleasing the woman who loves that man. No, Fernand, you will not thus give way to evil thoughts. Unable to have me for your wife, you will content yourself with having me for your friend and sister; and besides,” she added, her eyes troubled and moistened with tears, “wait, wait, Fernand; you said just now that the sea was treacherous, and he has been gone four months, and during these four months there have been some terrible storms.”\n"
                 + "\n"
                 + "Fernand made no reply, nor did he attempt to check the tears which flowed down the cheeks of Mercedes, although for each of these tears he would have shed his heart’s blood; but these tears flowed for another. He arose, paced a while up and down the hut, and then, suddenly stopping before Mercedes, with his eyes glowing and his hands clinched, — “Say, Mercedes,” he said, “once for all, is this your final determination?”\n"
                 + "\n"
                 + "“I love Edmond Dantes,” the young girl calmly replied, “and none but Edmond shall ever be my husband.”\n"
                 + "\n"
                 + "“And you will always love him?”\n"
                 + "\n"
                 + "“As long as I live.”\n"
                 + "\n"
                 + "Fernand let fall his head like a defeated man, heaved a sigh that was like a groan, and then suddenly looking her full in the face, with clinched teeth and expanded nostrils, said, — “But if he is dead” —\n"
                 + "\n"
                 + "“If he is dead, I shall die too.”\n"
                 + "\n"
                 + "“If he has forgotten you” —\n"
                 + "\n"
                 + "“Mercedes!” called a joyous voice from without, — “Mercedes!”\n"
                 + "\n"
                 + "“Ah,” exclaimed the young girl, blushing with delight, and fairly leaping in excess of love, “you see he has not forgotten me, for here he is!” And rushing towards the door, she opened it, saying, “Here, Edmond, here I am!”\n"
                 + "\n"
                 + "Fernand, pale and trembling, drew back, like a traveller at the sight of a serpent, and fell into a chair beside him. Edmond and Mercedes were clasped in each other’s arms. The burning Marseilles sun, which shot into the room through the open door, covered them with a flood of light. At first they saw nothing around them. Their intense happiness isolated them from all the rest of the world, and they only spoke in broken words, which are the tokens of a joy so extreme that they seem rather the expression of sorrow. Suddenly Edmond saw the gloomy, pale, and threatening countenance of Fernand, as it was defined in the shadow. By a movement for which he could scarcely account to himself, the young Catalan placed his hand on the knife at his belt.\n"
                 + "\n"
                 + "“Ah, your pardon,” said Dantes, frowning in his turn; “I did not perceive that there were three of us.” Then, turning to Mercedes, he inquired, “Who is this gentleman?”\n"
                 + "\n"
                 + "“One who will be your best friend, Dantes, for he is my friend, my cousin, my brother; it is Fernand — the man whom, after you, Edmond, I love the best in the world. Do you not remember him?”\n"
                 + "\n"
                 + "“Yes!” said Dantes, and without relinquishing Mercedes hand clasped in one of his own, he extended the other to the Catalan with a cordial air. But Fernand, instead of responding to this amiable gesture, remained mute and trembling. Edmond then cast his eyes scrutinizingly at the agitated and embarrassed Mercedes, and then again on the gloomy and menacing Fernand. This look told him all, and his anger waxed hot.\n"
                 + "\n"
                 + "“I did not know, when I came with such haste to you, that I was to meet an enemy here.”\n"
                 + "\n"
                 + "“An enemy!” cried Mercedes, with an angry look at her cousin. “An enemy in my house, do you say, Edmond! If I believed that, I would place my arm under yours and go with you to Marseilles, leaving the house to return to it no more.”\n"
                 + "\n"
                 + "Fernand’s eye darted lightning. “And should any misfortune occur to you, dear Edmond,” she continued with the same calmness which proved to Fernand that the young girl had read the very innermost depths of his sinister thought, “if misfortune should occur to you, I would ascend the highest point of the Cape de Morgion and cast myself headlong from it.”\n"
                 + "\n"
                 + "Fernand became deadly pale. “But you are deceived, Edmond,” she continued. “You have no enemy here — there is no one but Fernand, my brother, who will grasp your hand as a devoted friend.”\n"
                 + "\n"
                 + "And at these words the young girl fixed her imperious look on the Catalan, who, as if fascinated by it, came slowly towards Edmond, and offered him his hand. His hatred, like a powerless though furious wave, was broken against the strong ascendancy which Mercedes exercised over him. Scarcely, however, had he touched Edmond’s hand than he felt he had done all he could do, and rushed hastily out of the house.\n"
                 + "\n"
                 + "“Oh,” he exclaimed, running furiously and tearing his hair — “Oh, who will deliver me from this man? Wretched — wretched that I am!”\n"
                 + "\n"
                 + "“Hallo, Catalan! Hallo, Fernand! where are you running to?” exclaimed a voice.\n"
                 + "\n"
                 + "The young man stopped suddenly, looked around him, and perceived Caderousse sitting at table with Danglars, under an arbor.\n"
                 + "\n"
                 + "“Well”, said Caderousse, “why don’t you come? Are you really in such a hurry that you have no time to pass the time of day with your friends?”\n"
                 + "\n"
                 + "“Particularly when they have still a full bottle before them,” added Danglars. Fernand looked at them both with a stupefied air, but did not say a word.\n"
                 + "\n"
                 + "“He seems besotted,” said Danglars, pushing Caderousse with his knee. “Are we mistaken, and is Dantes triumphant in spite of all we have believed?”\n"
                 + "\n"
                 + "“Why, we must inquire into that,” was Caderousse’s reply; and turning towards the young man, said, “Well, Catalan, can’t you make up your mind?”\n"
                 + "\n"
                 + "Fernand wiped away the perspiration steaming from his brow, and slowly entered the arbor, whose shade seemed to restore somewhat of calmness to his senses, and whose coolness somewhat of refreshment to his exhausted body.\n"
                 + "\n"
                 + "“Good-day,” said he. “You called me, didn’t you?” And he fell, rather than sat down, on one of the seats which surrounded the table.\n"
                 + "\n"
                 + "“I called you because you were running like a madman, and I was afraid you would throw yourself into the sea,” said Caderousse, laughing. “Why, when a man has friends, they are not only to offer him a glass of wine, but, moreover, to prevent his swallowing three or four pints of water unnecessarily!”\n"
                 + "\n"
                 + "Fernand gave a groan, which resembled a sob, and dropped his head into his hands, his elbows leaning on the table.\n"
                 + "\n"
                 + "“Well, Fernand, I must say,” said Caderousse, beginning the conversation, with that brutality of the common people in which curiosity destroys all diplomacy, “you look uncommonly like a rejected lover;” and he burst into a hoarse laugh.\n"
                 + "\n"
                 + "“Bah!” said Danglars, “a lad of his make was not born to be unhappy in love. You are laughing at him, Caderousse.”\n"
                 + "\n"
                 + "“No,” he replied, “only hark how he sighs! Come, come, Fernand,” said Caderousse, “hold up your head, and answer us. It’s not polite not to reply to friends who ask news of your health.”\n"
                 + "\n"
                 + "“My health is well enough,” said Fernand, clinching his hands without raising his head.\n"
                 + "\n"
                 + "“Ah, you see, Danglars,” said Caderousse, winking at his friend, “this is how it is; Fernand, whom you see here, is a good and brave Catalan, one of the best fishermen in Marseilles, and he is in love with a very fine girl, named Mercedes; but it appears, unfortunately, that the fine girl is in love with the mate of the Pharaon; and as the Pharaon arrived to-day — why, you understand!”\n"
                 + "\n"
                 + "“No; I do not understand,” said Danglars.\n"
                 + "\n"
                 + "“Poor Fernand has been dismissed,” continued Caderousse.\n"
                 + "\n"
                 + "“Well, and what then?” said Fernand, lifting up his head, and looking at Caderousse like a man who looks for some one on whom to vent his anger; “Mercedes is not accountable to any person, is she? Is she not free to love whomsoever she will?”\n"
                 + "\n"
                 + "“Oh, if you take it in that sense,” said Caderousse, “it is another thing. But I thought you were a Catalan, and they told me the Catalans were not men to allow themselves to be supplanted by a rival. It was even told me that Fernand, especially, was terrible in his vengeance.”\n"
                 + "\n"
                 + "Fernand smiled piteously. “A lover is never terrible,” he said.\n"
                 + "\n"
                 + "“Poor fellow!” remarked Danglars, affecting to pity the young man from the bottom of his heart. “Why, you see, he did not expect to see Dantes return so suddenly — he thought he was dead, perhaps; or perchance faithless! These things always come on us more severely when they come suddenly.”\n"
                 + "\n"
                 + "“Ah, ma foi, under any circumstances,” said Caderousse, who drank as he spoke, and on whom the fumes of the wine began to take effect, — “under any circumstances Fernand is not the only person put out by the fortunate arrival of Dantes; is he, Danglars?”\n"
                 + "\n"
                 + "“No, you are right — and I should say that would bring him ill-luck.”\n"
                 + "\n"
                 + "“Well, never mind,” answered Caderousse, pouring out a glass of wine for Fernand, and filling his own for the eighth or ninth time, while Danglars had merely sipped his. “Never mind — in the meantime he marries Mercedes — the lovely Mercedes — at least he returns to do that.”\n"
                 + "\n"
                 + "During this time Danglars fixed his piercing glance on the young man, on whose heart Caderousse’s words fell like molten lead.\n"
                 + "\n"
                 + "“And when is the wedding to be?” he asked.\n"
                 + "\n"
                 + "“Oh, it is not yet fixed!” murmured Fernand.\n"
                 + "\n"
                 + "“No, but it will be,” said Caderousse, “as surely as Dantes will be captain of the Pharaon — eh, Danglars?”\n"
                 + "\n"
                 + "Danglars shuddered at this unexpected attack, and turned to Caderousse, whose countenance he scrutinized, to try and detect whether the blow was premeditated; but he read nothing but envy in a countenance already rendered brutal and stupid by drunkenness.\n"
                 + "\n"
                 + "“Well,” said he, filling the glasses, “let us drink to Captain Edmond Dantes, husband of the beautiful Catalane!”\n"
                 + "\n"
                 + "Caderousse raised his glass to his mouth with unsteady hand, and swallowed the contents at a gulp. Fernand dashed his on the ground.\n"
                 + "\n"
                 + "“Eh, eh, eh!” stammered Caderousse. “What do I see down there by the wall, in the direction of the Catalans? Look, Fernand, your eyes are better than mine. I believe I see double. You know wine is a deceiver; but I should say it was two lovers walking side by side, and hand in hand. Heaven forgive me, they do not know that we can see them, and they are actually embracing!”\n"
                 + "\n"
                 + "Danglars did not lose one pang that Fernand endured.\n"
                 + "\n"
                 + "“Do you know them, Fernand?” he said.\n"
                 + "\n"
                 + "“Yes,” was the reply, in a low voice. “It is Edmond and Mercedes!”\n"
                 + "\n"
                 + "“Ah, see there, now!” said Caderousse; “and I did not recognize them! Hallo, Dantes! hello, lovely damsel! Come this way, and let us know when the wedding is to be, for Fernand here is so obstinate he will not tell us.”\n"
                 + "\n"
                 + "“Hold your tongue, will you?” said Danglars, pretending to restrain Caderousse, who, with the tenacity of drunkards, leaned out of the arbor. “Try to stand upright, and let the lovers make love without interruption. See, look at Fernand, and follow his example; he is well-behaved!”\n"
                 + "\n"
                 + "Fernand, probably excited beyond bearing, pricked by Danglars, as the bull is by the bandilleros, was about to rush out; for he had risen from his seat, and seemed to be collecting himself to dash headlong upon his rival, when Mercedes, smiling and graceful, lifted up her lovely head, and looked at them with her clear and bright eyes. At this Fernand recollected her threat of dying if Edmond died, and dropped again heavily on his seat. Danglars looked at the two men, one after the other, the one brutalized by liquor, the other overwhelmed with love.\n"
                 + "\n"
                 + "“I shall get nothing from these fools,” he muttered; “and I am very much afraid of being here between a drunkard and a coward. Here’s an envious fellow making himself boozy on wine when he ought to be nursing his wrath, and here is a fool who sees the woman he loves stolen from under his nose and takes on like a big baby. Yet this Catalan has eyes that glisten like those of the vengeful Spaniards, Sicilians, and Calabrians, and the other has fists big enough to crush an ox at one blow. Unquestionably, Edmond’s star is in the ascendant, and he will marry the splendid girl — he will be captain, too, and laugh at us all, unless” — a sinister smile passed over Danglars’ lips — “unless I take a hand in the affair,” he added.\n"
                 + "\n");
        pw.print("“Hallo!” continued Caderousse, half-rising, and with his fist on the table, “hallo, Edmond! do you not see your friends, or are you too proud to speak to them?”\n"
                 + "\n"
                 + "“No, my dear fellow!” replied Dantes, “I am not proud, but I am happy, and happiness blinds, I think, more than pride.”\n"
                 + "\n"
                 + "“Ah, very well, that’s an explanation!” said Caderousse. “How do you do, Madame Dantes?”\n"
                 + "\n"
                 + "Mercedes courtesied gravely, and said — “That is not my name, and in my country it bodes ill fortune, they say, to call a young girl by the name of her betrothed before he becomes her husband. So call me Mercedes, if you please.”\n"
                 + "\n"
                 + "“We must excuse our worthy neighbor, Caderousse,” said Dantes, “he is so easily mistaken.”\n"
                 + "\n"
                 + "“So, then, the wedding is to take place immediately, M. Dantes,” said Danglars, bowing to the young couple.\n"
                 + "\n"
                 + "“As soon as possible, M. Danglars; to-day all preliminaries will be arranged at my father’s, and to-morrow, or next day at latest, the wedding festival here at La Reserve. My friends will be there, I hope; that is to say, you are invited, M. Danglars, and you, Caderousse.”\n"
                 + "\n"
                 + "“And Fernand,” said Caderousse with a chuckle; “Fernand, too, is invited!”\n"
                 + "\n"
                 + "“My wife’s brother is my brother,” said Edmond; “and we, Mercedes and I, should be very sorry if he were absent at such a time.”\n"
                 + "\n"
                 + "Fernand opened his mouth to reply, but his voice died on his lips, and he could not utter a word.\n"
                 + "\n"
                 + "“To-day the preliminaries, to-morrow or next day the ceremony! You are in a hurry, captain!”\n"
                 + "\n"
                 + "“Danglars,” said Edmond, smiling, “I will say to you as Mercedes said just now to Caderousse, `Do not give me a title which does not belong to me’; that may bring me bad luck.”\n"
                 + "\n"
                 + "“Your pardon,” replied Danglars, “I merely said you seemed in a hurry, and we have lots of time; the Pharaon cannot be under weigh again in less than three months.”\n"
                 + "\n"
                 + "“We are always in a hurry to be happy, M. Danglars; for when we have suffered a long time, we have great difficulty in believing in good fortune. But it is not selfishness alone that makes me thus in haste; I must go to Paris.”\n"
                 + "\n"
                 + "“Ah, really? — to Paris! and will it be the first time you have ever been there, Dantes?”\n"
                 + "\n"
                 + "“Yes.”\n"
                 + "\n"
                 + "“Have you business there?”\n"
                 + "\n"
                 + "“Not of my own; the last commission of poor Captain Leclere; you know to what I allude, Danglars — it is sacred. Besides, I shall only take the time to go and return.”\n"
                 + "\n"
                 + "“Yes, yes, I understand,” said Danglars, and then in a low tone, he added, “To Paris, no doubt to deliver the letter which the grand marshal gave him. Ah, this letter gives me an idea — a capital idea! Ah; Dantes, my friend, you are not yet registered number one on board the good ship Pharaon;” then turning towards Edmond, who was walking away, “A pleasant journey,” he cried.\n"
                 + "\n"
                 + "“Thank you,” said Edmond with a friendly nod, and the two lovers continued on their way, as calm and joyous as if they were the very elect of heaven.\n"
                 + "\n"
                 + "Chapter 4\n"
                 + "Conspiracy.\n"
                 + "\n"
                 + "Danglars followed Edmond and Mercedes with his eyes until the two lovers disappeared behind one of the angles of Fort Saint Nicolas, then turning round, he perceived Fernand, who had fallen, pale and trembling, into his chair, while Caderousse stammered out the words of a drinking-song.\n"
                 + "\n"
                 + "“Well, my dear sir,” said Danglars to Fernand, “here is a marriage which does not appear to make everybody happy.”\n"
                 + "\n"
                 + "“It drives me to despair,” said Fernand.\n"
                 + "\n"
                 + "“Do you, then, love Mercedes?”\n"
                 + "\n"
                 + "“I adore her!”\n"
                 + "\n"
                 + "“For long?”\n"
                 + "\n"
                 + "“As long as I have known her — always.”\n"
                 + "\n"
                 + "“And you sit there, tearing your hair, instead of seeking to remedy your condition; I did not think that was the way of your people.”\n"
                 + "\n"
                 + "“What would you have me do?” said Fernand.\n"
                 + "\n"
                 + "“How do I know? Is it my affair? I am not in love with Mademoiselle Mercedes; but for you — in the words of the gospel, seek, and you shall find.”\n"
                 + "\n"
                 + "“I have found already.”\n"
                 + "\n"
                 + "“What?”\n"
                 + "\n"
                 + "“I would stab the man, but the woman told me that if any misfortune happened to her betrothed, she would kill herself.”\n"
                 + "\n"
                 + "“Pooh! Women say those things, but never do them.”\n"
                 + "\n"
                 + "“You do not know Mercedes; what she threatens she will do.”\n"
                 + "\n"
                 + "“Idiot!” muttered Danglars; “whether she kill herself or not, what matter, provided Dantes is not captain?”\n"
                 + "\n"
                 + "“Before Mercedes should die,” replied Fernand, with the accents of unshaken resolution, “I would die myself!”\n"
                 + "\n"
                 + "“That’s what I call love!” said Caderousse with a voice more tipsy than ever. “That’s love, or I don’t know what love is.”\n"
                 + "\n"
                 + "“Come,” said Danglars, “you appear to me a good sort of fellow, and hang me, I should like to help you, but” —\n"
                 + "\n"
                 + "“Yes,” said Caderousse, “but how?”\n"
                 + "\n"
                 + "“My dear fellow,” replied Danglars, “you are three parts drunk; finish the bottle, and you will be completely so. Drink then, and do not meddle with what we are discussing, for that requires all one’s wit and cool judgment.”\n"
                 + "\n"
                 + "“I — drunk!” said Caderousse; “well that’s a good one! I could drink four more such bottles; they are no bigger than cologne flasks. Pere Pamphile, more wine!” and Caderousse rattled his glass upon the table.\n"
                 + "\n"
                 + "“You were saying, sir” — said Fernand, awaiting with great anxiety the end of this interrupted remark.\n"
                 + "\n"
                 + "“What was I saying? I forget. This drunken Caderousse has made me lose the thread of my sentence.”\n"
                 + "\n"
                 + "“Drunk, if you like; so much the worse for those who fear wine, for it is because they have bad thoughts which they are afraid the liquor will extract from their hearts;” and Caderousse began to sing the two last lines of a song very popular at the time, —\n"
                 + "\n"
                 + "`Tous les mechants sont beuveurs d’eau; C’est bien prouve par le deluge.’*\n"
                 + "\n"
                 + "* “The wicked are great drinkers of water As the flood proved once for all.”\n"
                 + "\n"
                 + "“You said, sir, you would like to help me, but” —\n"
                 + "\n"
                 + "“Yes; but I added, to help you it would be sufficient that Dantes did not marry her you love; and the marriage may easily be thwarted, methinks, and yet Dantes need not die.”\n"
                 + "\n"
                 + "“Death alone can separate them,” remarked Fernand.\n"
                 + "\n"
                 + "“You talk like a noodle, my friend,” said Caderousse; “and here is Danglars, who is a wide-awake, clever, deep fellow, who will prove to you that you are wrong. Prove it, Danglars. I have answered for you. Say there is no need why Dantes should die; it would, indeed, be a pity he should. Dantes is a good fellow; I like Dantes. Dantes, your health.”\n"
                 + "\n"
                 + "Fernand rose impatiently. “Let him run on,” said Danglars, restraining the young man; “drunk as he is, he is not much out in what he says. Absence severs as well as death, and if the walls of a prison were between Edmond and Mercedes they would be as effectually separated as if he lay under a tombstone.”\n"
                 + "\n"
                 + "“Yes; but one gets out of prison,” said Caderousse, who, with what sense was left him, listened eagerly to the conversation, “and when one gets out and one’s name is Edmond Dantes, one seeks revenge” —\n"
                 + "\n"
                 + "“What matters that?” muttered Fernand.\n"
                 + "\n"
                 + "“And why, I should like to know,” persisted Caderousse, “should they put Dantes in prison? he has not robbed or killed or murdered.”\n"
                 + "\n"
                 + "“Hold your tongue!” said Danglars.\n"
                 + "\n"
                 + "“I won’t hold my tongue!” replied Caderousse; “I say I want to know why they should put Dantes in prison; I like Dantes; Dantes, your health!” and he swallowed another glass of wine.\n"
                 + "\n"
                 + "Danglars saw in the muddled look of the tailor the progress of his intoxication, and turning towards Fernand, said, “Well, you understand there is no need to kill him.”\n"
                 + "\n"
                 + "“Certainly not, if, as you said just now, you have the means of having Dantes arrested. Have you that means?”\n"
                 + "\n"
                 + "“It is to be found for the searching. But why should I meddle in the matter? it is no affair of mine.”\n"
                 + "\n"
                 + "“I know not why you meddle,” said Fernand, seizing his arm; “but this I know, you have some motive of personal hatred against Dantes, for he who himself hates is never mistaken in the sentiments of others.”\n"
                 + "\n"
                 + "“I! — motives of hatred against Dantes? None, on my word! I saw you were unhappy, and your unhappiness interested me; that’s all; but since you believe I act for my own account, adieu, my dear friend, get out of the affair as best you may;” and Danglars rose as if he meant to depart.\n"
                 + "\n"
                 + "“No, no,” said Fernand, restraining him, “stay! It is of very little consequence to me at the end of the matter whether you have any angry feeling or not against Dantes. I hate him! I confess it openly. Do you find the means, I will execute it, provided it is not to kill the man, for Mercedes has declared she will kill herself if Dantes is killed.”\n"
                 + "\n"
                 + "Caderousse, who had let his head drop on the table, now raised it, and looking at Fernand with his dull and fishy eyes, he said, — “Kill Dantes! who talks of killing Dantes? I won’t have him killed — I won’t! He’s my friend, and this morning offered to share his money with me, as I shared mine with him. I won’t have Dantes killed — I won’t!”\n"
                 + "\n"
                 + "“And who has said a word about killing him, muddlehead?” replied Danglars. “We were merely joking; drink to his health,” he added, filling Caderousse’s glass, “and do not interfere with us.”\n"
                 + "\n"
                 + "“Yes, yes, Dantes’ good health!” said Caderousse, emptying his glass, “here’s to his health! his health — hurrah!”\n"
                 + "\n"
                 + "“But the means — the means?” said Fernand.\n"
                 + "\n"
                 + "“Have you not hit upon any?” asked Danglars.\n"
                 + "\n"
                 + "“No! — you undertook to do so.”\n"
                 + "\n"
                 + "“True,” replied Danglars; “the French have the superiority over the Spaniards, that the Spaniards ruminate, while the French invent.”\n"
                 + "\n"
                 + "“Do you invent, then,” said Fernand impatiently.\n"
                 + "\n"
                 + "“Waiter,” said Danglars, “pen, ink, and paper.”\n"
                 + "\n"
                 + "“Pen, ink, and paper,” muttered Fernand.\n"
                 + "\n"
                 + "“Yes; I am a supercargo; pen, ink, and paper are my tools, and without my tools I am fit for nothing.”\n"
                 + "\n"
                 + "“Pen, ink, and paper, then,” called Fernand loudly.\n"
                 + "\n"
                 + "“There’s what you want on that table,” said the waiter.\n"
                 + "\n"
                 + "“Bring them here.” The waiter did as he was desired.\n"
                 + "\n"
                 + "“When one thinks,” said Caderousse, letting his hand drop on the paper, “there is here wherewithal to kill a man more sure than if we waited at the corner of a wood to assassinate him! I have always had more dread of a pen, a bottle of ink, and a sheet of paper, than of a sword or pistol.”\n"
                 + "\n"
                 + "“The fellow is not so drunk as he appears to be,” said Danglars. “Give him some more wine, Fernand.” Fernand filled Caderousse’s glass, who, like the confirmed toper he was, lifted his hand from the paper and seized the glass.\n"
                 + "\n"
                 + "The Catalan watched him until Caderousse, almost overcome by this fresh assault on his senses, rested, or rather dropped, his glass upon the table.\n"
                 + "\n"
                 + "“Well!” resumed the Catalan, as he saw the final glimmer of Caderousse’s reason vanishing before the last glass of wine.\n"
                 + "\n"
                 + "“Well, then, I should say, for instance,” resumed Danglars, “that if after a voyage such as Dantes has just made, in which he touched at the Island of Elba, some one were to denounce him to the king’s procureur as a Bonapartist agent” —\n"
                 + "\n"
                 + "“I will denounce him!” exclaimed the young man hastily.\n"
                 + "\n"
                 + "“Yes, but they will make you then sign your declaration, and confront you with him you have denounced; I will supply you with the means of supporting your accusation, for I know the fact well. But Dantes cannot remain forever in prison, and one day or other he will leave it, and the day when he comes out, woe betide him who was the cause of his incarceration!”\n"
                 + "\n"
                 + "“Oh, I should wish nothing better than that he would come and seek a quarrel with me.”\n"
                 + "\n"
                 + "“Yes, and Mercedes! Mercedes, who will detest you if you have only the misfortune to scratch the skin of her dearly beloved Edmond!”\n"
                 + "\n"
                 + "“True!” said Fernand.\n"
                 + "\n"
                 + "“No, no,” continued Danglars; “if we resolve on such a step, it would be much better to take, as I now do, this pen, dip it into this ink, and write with the left hand (that the writing may not be recognized) the denunciation we propose.” And Danglars, uniting practice with theory, wrote with his left hand, and in a writing reversed from his usual style, and totally unlike it, the following lines, which he handed to Fernand, and which Fernand read in an undertone: —\n"
                 + "\n"
                 + "“The honorable, the king’s attorney, is informed by a friend of the throne and religion, that one Edmond Dantes, mate of the ship Pharaon, arrived this morning from Smyrna, after having touched at Naples and Porto-Ferrajo, has been intrusted by Murat with a letter for the usurper, and by the usurper with a letter for the Bonapartist committee in Paris. Proof of this crime will be found on arresting him, for the letter will be found upon him, or at his father’s, or in his cabin on board the Pharaon.”\n"
                 + "\n"
                 + "“Very good,” resumed Danglars; “now your revenge looks like common-sense, for in no way can it revert to yourself, and the matter will thus work its own way; there is nothing to do now but fold the letter as I am doing, and write upon it, `To the king’s attorney,’ and that’s all settled.” And Danglars wrote the address as he spoke.\n"
                 + "\n"
                 + "“Yes, and that’s all settled!” exclaimed Caderousse, who, by a last effort of intellect, had followed the reading of the letter, and instinctively comprehended all the misery which such a denunciation must entail. “Yes, and that’s all settled; only it will be an infamous shame;” and he stretched out his hand to reach the letter.\n"
                 + "\n"
                 + "“Yes,” said Danglars, taking it from beyond his reach; “and as what I say and do is merely in jest, and I, amongst the first and foremost, should be sorry if anything happened to Dantes — the worthy Dantes — look here!” And taking the letter, he squeezed it up in his hands and threw it into a corner of the arbor.\n"
                 + "\n"
                 + "“All right!” said Caderousse. “Dantes is my friend, and I won’t have him ill-used.”\n"
                 + "\n"
                 + "“And who thinks of using him ill? Certainly neither I nor Fernand,” said Danglars, rising and looking at the young man, who still remained seated, but whose eye was fixed on the denunciatory sheet of paper flung into the corner.\n"
                 + "\n"
                 + "“In this case,” replied Caderousse, “let’s have some more wine. I wish to drink to the health of Edmond and the lovely Mercedes.”\n"
                 + "\n"
                 + "“You have had too much already, drunkard,” said Danglars; “and if you continue, you will be compelled to sleep here, because unable to stand on your legs.”\n"
                 + "\n"
                 + "“I?” said Caderousse, rising with all the offended dignity of a drunken man, “I can’t keep on my legs? Why, I’ll wager I can go up into the belfry of the Accoules, and without staggering, too!”\n"
                 + "\n"
                 + "“Done!” said Danglars, “I’ll take your bet; but to-morrow — to-day it is time to return. Give me your arm, and let us go.”\n"
                 + "\n"
                 + "“Very well, let us go,” said Caderousse; “but I don’t want your arm at all. Come, Fernand, won’t you return to Marseilles with us?”\n"
                 + "\n"
                 + "“No,” said Fernand; “I shall return to the Catalans.”\n"
                 + "\n"
                 + "“You’re wrong. Come with us to Marseilles — come along.”\n"
                 + "\n"
                 + "“I will not.”\n"
                 + "\n"
                 + "“What do you mean? you will not? Well, just as you like, my prince; there’s liberty for all the world. Come along, Danglars, and let the young gentleman return to the Catalans if he chooses.”\n"
                 + "\n"
                 + "Danglars took advantage of Caderousse’s temper at the moment, to take him off towards Marseilles by the Porte Saint-Victor, staggering as he went.\n"
                 + "\n"
                 + "When they had advanced about twenty yards, Danglars looked back and saw Fernand stoop, pick up the crumpled paper, and putting it into his pocket then rush out of the arbor towards Pillon.\n"
                 + "\n"
                 + "“Well,” said Caderousse, “why, what a lie he told! He said he was going to the Catalans, and he is going to the city. Hallo, Fernand!”\n"
                 + "\n"
                 + "“Oh, you don’t see straight,” said Danglars; “he’s gone right enough.”\n"
                 + "\n"
                 + "“Well,” said Caderousse, “I should have said not — how treacherous wine is!”\n"
                 + "\n"
                 + "“Come, come,” said Danglars to himself, “now the thing is at work and it will effect its purpose unassisted.”\n"
                 + "\n"
                 + "Chapter 5\n"
                 + "The Marriage-Feast.\n"
                 + "\n"
                 + "The morning’s sun rose clear and resplendent, touching the foamy waves into a network of ruby-tinted light.\n"
                 + "\n"
                 + "The feast had been made ready on the second floor at La Reserve, with whose arbor the reader is already familiar. The apartment destined for the purpose was spacious and lighted by a number of windows, over each of which was written in golden letters for some inexplicable reason the name of one of the principal cities of France; beneath these windows a wooden balcony extended the entire length of the house. And although the entertainment was fixed for twelve o’clock, an hour previous to that time the balcony was filled with impatient and expectant guests, consisting of the favored part of the crew of the Pharaon, and other personal friends of the bride-groom, the whole of whom had arrayed themselves in their choicest costumes, in order to do greater honor to the occasion.\n"
                 + "\n"
                 + "Various rumors were afloat to the effect that the owners of the Pharaon had promised to attend the nuptial feast; but all seemed unanimous in doubting that an act of such rare and exceeding condescension could possibly be intended.\n"
                 + "\n"
                 + "Danglars, however, who now made his appearance, accompanied by Caderousse, effectually confirmed the report, stating that he had recently conversed with M. Morrel, who had himself assured him of his intention to dine at La Reserve.\n"
                 + "\n"
                 + "In fact, a moment later M. Morrel appeared and was saluted with an enthusiastic burst of applause from the crew of the Pharaon, who hailed the visit of the shipowner as a sure indication that the man whose wedding feast he thus delighted to honor would ere long be first in command of the ship; and as Dantes was universally beloved on board his vessel, the sailors put no restraint on their tumultuous joy at finding that the opinion and choice of their superiors so exactly coincided with their own.\n"
                 + "\n"
                 + "With the entrance of M. Morrel, Danglars and Caderousse were despatched in search of the bride-groom to convey to him the intelligence of the arrival of the important personage whose coming had created such a lively sensation, and to beseech him to make haste.\n"
                 + "\n"
                 + "Danglars and Caderousse set off upon their errand at full speed; but ere they had gone many steps they perceived a group advancing towards them, composed of the betrothed pair, a party of young girls in attendance on the bride, by whose side walked Dantes’ father; the whole brought up by Fernand, whose lips wore their usual sinister smile.\n"
                 + "\n"
                 + "Neither Mercedes nor Edmond observed the strange expression of his countenance; they were so happy that they were conscious only of the sunshine and the presence of each other.\n"
                 + "\n"
                 + "Having acquitted themselves of their errand, and exchanged a hearty shake of the hand with Edmond, Danglars and Caderousse took their places beside Fernand and old Dantes, — the latter of whom attracted universal notice. The old man was attired in a suit of glistening watered silk, trimmed with steel buttons, beautifully cut and polished. His thin but wiry legs were arrayed in a pair of richly embroidered clocked stockings, evidently of English manufacture, while from his three-cornered hat depended a long streaming knot of white and blue ribbons. Thus he came along, supporting himself on a curiously carved stick, his aged countenance lit up with happiness, looking for all the world like one of the aged dandies of 1796, parading the newly opened gardens of the Tuileries and Luxembourg. Beside him glided Caderousse, whose desire to partake of the good things provided for the wedding-party had induced him to become reconciled to the Dantes, father and son, although there still lingered in his mind a faint and unperfect recollection of the events of the preceding night; just as the brain retains on waking in the morning the dim and misty outline of a dream.\n"
                 + "\n"
                 + "As Danglars approached the disappointed lover, he cast on him a look of deep meaning, while Fernand, as he slowly paced behind the happy pair, who seemed, in their own unmixed content, to have entirely forgotten that such a being as himself existed, was pale and abstracted; occasionally, however, a deep flush would overspread his countenance, and a nervous contraction distort his features, while, with an agitated and restless gaze, he would glance in the direction of Marseilles, like one who either anticipated or foresaw some great and important event.\n"
                 + "\n"
                 + "Dantes himself was simply, but becomingly, clad in the dress peculiar to the merchant service — a costume somewhat between a military and a civil garb; and with his fine countenance, radiant with joy and happiness, a more perfect specimen of manly beauty could scarcely be imagined.\n"
                 + "\n"
                 + "Lovely as the Greek girls of Cyprus or Chios, Mercedes boasted the same bright flashing eyes of jet, and ripe, round, coral lips. She moved with the light, free step of an Arlesienne or an Andalusian. One more practiced in the arts of great cities would have hid her blushes beneath a veil, or, at least, have cast down her thickly fringed lashes, so as to have concealed the liquid lustre of her animated eyes; but, on the contrary, the delighted girl looked around her with a smile that seemed to say: “If you are my friends, rejoice with me, for I am very happy.”\n"
                 + "\n"
                 + "As soon as the bridal party came in sight of La Reserve, M. Morrel descended and came forth to meet it, followed by the soldiers and sailors there assembled, to whom he had repeated the promise already given, that Dantes should be the successor to the late Captain Leclere. Edmond, at the approach of his patron, respectfully placed the arm of his affianced bride within that of M. Morrel, who, forthwith conducting her up the flight of wooden steps leading to the chamber in which the feast was prepared, was gayly followed by the guests, beneath whose heavy tread the slight structure creaked and groaned for the space of several minutes.\n"
                 + "\n"
                 + "“Father,” said Mercedes, stopping when she had reached the centre of the table, “sit, I pray you, on my right hand; on my left I will place him who has ever been as a brother to me,” pointing with a soft and gentle smile to Fernand; but her words and look seemed to inflict the direst torture on him, for his lips became ghastly pale, and even beneath the dark hue of his complexion the blood might be seen retreating as though some sudden pang drove it back to the heart.\n"
                 + "\n"
                 + "During this time, Dantes, at the opposite side of the table, had been occupied in similarly placing his most honored guests. M. Morrel was seated at his right hand, Danglars at his left; while, at a sign from Edmond, the rest of the company ranged themselves as they found it most agreeable.\n"
                 + "\n"
                 + "Then they began to pass around the dusky, piquant, Arlesian sausages, and lobsters in their dazzling red cuirasses, prawns of large size and brilliant color, the echinus with its prickly outside and dainty morsel within, the clovis, esteemed by the epicures of the South as more than rivalling the exquisite flavor of the oyster, — all the delicacies, in fact, that are cast up by the wash of waters on the sandy beach, and styled by the grateful fishermen “fruits of the sea.”\n"
                 + "\n"
                 + "“A pretty silence truly!” said the old father of the bride-groom, as he carried to his lips a glass of wine of the hue and brightness of the topaz, and which had just been placed before Mercedes herself. “Now, would anybody think that this room contained a happy, merry party, who desire nothing better than to laugh and dance the hours away?”\n"
                 + "\n"
                 + "“Ah,” sighed Caderousse, “a man cannot always feel happy because he is about to be married.”\n"
                 + "\n"
                 + "“The truth is,” replied Dantes, “that I am too happy for noisy mirth; if that is what you meant by your observation, my worthy friend, you are right; joy takes a strange effect at times, it seems to oppress us almost the same as sorrow.”\n"
                 + "\n"
                 + "Danglars looked towards Fernand, whose excitable nature received and betrayed each fresh impression.\n"
                 + "\n"
                 + "“Why, what ails you?” asked he of Edmond. “Do you fear any approaching evil? I should say that you were the happiest man alive at this instant.”\n"
                 + "\n"
                 + "“And that is the very thing that alarms me,” returned Dantes. “Man does not appear to me to be intended to enjoy felicity so unmixed; happiness is like the enchanted palaces we read of in our childhood, where fierce, fiery dragons defend the entrance and approach; and monsters of all shapes and kinds, requiring to be overcome ere victory is ours. I own that I am lost in wonder to find myself promoted to an honor of which I feel myself unworthy — that of being the husband of Mercedes.”\n"
                 + "\n"
                 + "“Nay, nay!” cried Caderousse, smiling, “you have not attained that honor yet. Mercedes is not yet your wife. Just assume the tone and manner of a husband, and see how she will remind you that your hour is not yet come!”\n"
                 + "\n"
                 + "The bride blushed, while Fernand, restless and uneasy, seemed to start at every fresh sound, and from time to time wiped away the large drops of perspiration that gathered on his brow.\n"
                 + "\n"
                 + "“Well, never mind that, neighbor Caderousse; it is not worth while to contradict me for such a trifle as that. ‘Tis true that Mercedes is not actually my wife; but,” added he, drawing out his watch, “in an hour and a half she will be.”\n"
                 + "\n"
                 + "A general exclamation of surprise ran round the table, with the exception of the elder Dantes, whose laugh displayed the still perfect beauty of his large white teeth. Mercedes looked pleased and gratified, while Fernand grasped the handle of his knife with a convulsive clutch.\n"
                 + "\n"
                 + "“In an hour?” inquired Danglars, turning pale. “How is that, my friend?”\n"
                 + "\n"
                 + "“Why, thus it is,” replied Dantes. “Thanks to the influence of M. Morrel, to whom, next to my father, I owe every blessing I enjoy, every difficulty his been removed. We have purchased permission to waive the usual delay; and at half-past two o’clock the mayor of Marseilles will be waiting for us at the city hall. Now, as a quarter-past one has already struck, I do not consider I have asserted too much in saying, that, in another hour and thirty minutes Mercedes will have become Madame Dantes.”\n"
                 + "\n"
                 + "Fernand closed his eyes, a burning sensation passed across his brow, and he was compelled to support himself by the table to prevent his falling from his chair; but in spite of all his efforts, he could not refrain from uttering a deep groan, which, however, was lost amid the noisy felicitations of the company.\n"
                 + "\n"
                 + "“Upon my word,” cried the old man, “you make short work of this kind of affair. Arrived here only yesterday morning, and married to-day at three o’clock! Commend me to a sailor for going the quick way to work!”\n"
                 + "\n"
                 + "“But,” asked Danglars, in a timid tone, “how did you manage about the other formalities — the contract — the settlement?”\n"
                 + "\n"
                 + "“The contract,” answered Dantes, laughingly, “it didn’t take long to fix that. Mercedes has no fortune; I have none to settle on her. So, you see, our papers were quickly written out, and certainly do not come very expensive.” This joke elicited a fresh burst of applause.\n"
                 + "\n"
                 + "“So that what we presumed to be merely the betrothal feast turns out to be the actual wedding dinner!” said Danglars.");

    }

    @Override
    public void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        doGet(request, response);
    }

}
