DROP TABLE HelmetEntityOLGH19182;
DROP TABLE JPA10EntityManagerEntityA;
DROP TABLE JPA10ENTITYMANAGERENTITYA_JPA1;
DROP TABLE JPA10EntityManagerEntityB;
DROP TABLE JPA10EntityManagerEntityC;
DROP TABLE JPA_HELMET_PROPERTIES;
DROP TABLE ShelfEntityOLGH19182;