CREATE TABLE NUMBERS (
item INT,
quantity INT
);

CREATE TABLE ORDERS (
orderID INT NOT NULL PRIMARY KEY,
itemID INT,
quantity INT
);

CREATE TABLE INVENTORY (
itemID INT NOT NULL PRIMARY KEY,
quantity INT NOT NULL
);

CREATE SEQUENCE order_seq MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;

	CREATE or REPLACE trigger order_trigger
	BEFORE INSERT ON ORDERS
	FOR EACH ROW
	BEGIN
		IF (:new.orderID IS NULL) THEN
			SELECT order_seq.nextval INTO :new.orderID FROM DUAL;
		END IF;
	END;
	/

INSERT INTO INVENTORY VALUES (1, 100);

INSERT INTO NUMBERS VALUES (1, 10);

INSERT INTO NUMBERS VALUES (2, 10);

INSERT INTO NUMBERS VALUES (3, 10);

INSERT INTO NUMBERS VALUES (4, 10);

INSERT INTO NUMBERS VALUES (5, 10);

INSERT INTO NUMBERS VALUES (6, 10);

INSERT INTO NUMBERS VALUES (7, 10);

INSERT INTO NUMBERS VALUES (8, 10);

INSERT INTO NUMBERS VALUES (9, 10);

INSERT INTO NUMBERS VALUES (10, 10);

INSERT INTO NUMBERS VALUES (11, 10);

INSERT INTO NUMBERS VALUES (12, 10);

INSERT INTO NUMBERS VALUES (13, 10);

INSERT INTO NUMBERS VALUES (14, 10);

INSERT INTO NUMBERS VALUES (15, 10);

INSERT INTO NUMBERS VALUES (16, 10);

INSERT INTO NUMBERS VALUES (17, 10);

INSERT INTO NUMBERS VALUES (18, 10);

INSERT INTO NUMBERS VALUES (19, 10);

INSERT INTO NUMBERS VALUES (20, 10);

COMMIT WORK;
EXIT;