/*******************************************************************************
 * Copyright (c) 2020 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/

package test.wssecfvt.endsuptokens;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-02-15T08:47:39.481-06:00
 * Generated source version: 2.6.2
 *
 */
@WebServiceClient(name = "EndSupTokensService2",
                  wsdlLocation = "EndSupTokens.wsdl",
                  targetNamespace = "http://endsuptokens.wssecfvt.test")
public class EndSupTokensService2 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endsuptokens.wssecfvt.test", "EndSupTokensService2");
    public final static QName EndSupTokensX509EndorsingEncryptedPort = new QName("http://endsuptokens.wssecfvt.test", "EndSupTokensX509EndorsingEncryptedPort");
    static {
        URL url = EndSupTokensService2.class.getResource("EndSupTokens.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(EndSupTokensService2.class.getName()).log(java.util.logging.Level.INFO,
                                                                                         "Can not initialize the default wsdl from {0}", "EndSupTokens.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EndSupTokensService2(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EndSupTokensService2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EndSupTokensService2() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *         returns EndSupTokensPortType
     */
    @WebEndpoint(name = "EndSupTokensX509EndorsingEncryptedPort")
    public EndSupTokensPortType getEndSupTokensX509EndorsingEncryptedPort() {
        return super.getPort(EndSupTokensX509EndorsingEncryptedPort, EndSupTokensPortType.class);
    }

    /**
     *
     * @param features
     *                     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will have their
     *                     default values.
     * @return
     *         returns EndSupTokensPortType
     */
    @WebEndpoint(name = "EndSupTokensX509EndorsingEncryptedPort")
    public EndSupTokensPortType getEndSupTokensX509EndorsingEncryptedPort(WebServiceFeature... features) {
        return super.getPort(EndSupTokensX509EndorsingEncryptedPort, EndSupTokensPortType.class, features);
    }

}
