<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Wss11SigWebSvc1" targetNamespace="http://wss11sig.wssecfvt.test" 
    xmlns="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:tns="http://wss11sig.wssecfvt.test"
    xmlns:x1="http://wss11sig.wssecfvt.test/types"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
    xmlns:wsp="http://www.w3.org/ns/ws-policy"
    xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
    xmlns:sp13="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200802"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    
    <wsp:Policy wsu:Id="BasicSigConfirmPolicy">
        
     <wsp:ExactlyOne>
        <wsp:All>
           <sp:AsymmetricBinding>
             <wsp:Policy>
               <sp:InitiatorSignatureToken>
                 <wsp:Policy>
                   <sp:X509Token
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                      <wsp:Policy>
                         <sp:WssX509V3Token10 />
                      </wsp:Policy>
                   </sp:X509Token>
                 </wsp:Policy>
               </sp:InitiatorSignatureToken>
               <sp:RecipientSignatureToken>
                 <wsp:Policy>
                   <sp:X509Token
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToInitiator">
                      <wsp:Policy>
                         <sp:WssX509V3Token10 />
                      </wsp:Policy>
                   </sp:X509Token>
                 </wsp:Policy>
               </sp:RecipientSignatureToken>
               <sp:AlgorithmSuite>
                 <wsp:Policy>
                   <sp:Basic128/>
                 </wsp:Policy>
               </sp:AlgorithmSuite>
               <sp:Layout>
                 <wsp:Policy>
                   <sp:Strict/>
                 </wsp:Policy>
               </sp:Layout>
             </wsp:Policy>
           </sp:AsymmetricBinding>
           <!--
           <sp:Wss11>
              <wsp:Policy>
                 <sp:RequireSignatureConfirmation/>
              </wsp:Policy>
           </sp:Wss11>
           -->
           <sp:SignedParts>
             <sp:Body/>
           </sp:SignedParts>
         </wsp:All>
      </wsp:ExactlyOne>
      
    </wsp:Policy>
              
    <wsp:Policy wsu:Id="BasicSigConfirmPolicyNoSig">
        
     <wsp:ExactlyOne>
        <wsp:All>
           <sp:AsymmetricBinding>
             <wsp:Policy>
               <sp:InitiatorSignatureToken>
                 <wsp:Policy>
                   <sp:X509Token
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                      <wsp:Policy>
                         <sp:WssX509V3Token10 />
                      </wsp:Policy>
                   </sp:X509Token>
                 </wsp:Policy>
               </sp:InitiatorSignatureToken>
               <sp:RecipientSignatureToken>
                 <wsp:Policy>
                   <sp:X509Token
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToInitiator">
                      <wsp:Policy>
                         <sp:WssX509V3Token10 />
                      </wsp:Policy>
                   </sp:X509Token>
                 </wsp:Policy>
               </sp:RecipientSignatureToken>
               <sp:AlgorithmSuite>
                 <wsp:Policy>
                   <sp:Basic128/>
                 </wsp:Policy>
               </sp:AlgorithmSuite>
               <sp:Layout>
                 <wsp:Policy>
                   <sp:Strict/>
                 </wsp:Policy>
               </sp:Layout>
             </wsp:Policy>
           </sp:AsymmetricBinding>
           <sp:Wss11>
              <wsp:Policy>
                 <sp:RequireSignatureConfirmation/>
              </wsp:Policy>
           </sp:Wss11>
           <!--
           <sp:SignedParts>
             <sp:Body/>
           </sp:SignedParts>
           -->
         </wsp:All>
      </wsp:ExactlyOne>
      
    </wsp:Policy>
    
    <wsp:Policy wsu:Id="BasicSigNoConfirmPolicy">
        
     <wsp:ExactlyOne>
        <wsp:All>
           <sp:AsymmetricBinding>
             <wsp:Policy>
               <sp:InitiatorSignatureToken>
                 <wsp:Policy>
                   <sp:X509Token
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                      <wsp:Policy>
                         <sp:WssX509V3Token10 />
                      </wsp:Policy>
                   </sp:X509Token>
                 </wsp:Policy>
               </sp:InitiatorSignatureToken>
               <sp:RecipientSignatureToken>
                 <wsp:Policy>
                   <sp:X509Token
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToInitiator">
                      <wsp:Policy>
                         <sp:WssX509V3Token10 />
                      </wsp:Policy>
                   </sp:X509Token>
                 </wsp:Policy>
               </sp:RecipientSignatureToken>
               <sp:AlgorithmSuite>
                 <wsp:Policy>
                   <sp:Basic128/>
                 </wsp:Policy>
               </sp:AlgorithmSuite>
               <sp:Layout>
                 <wsp:Policy>
                   <sp:Strict/>
                 </wsp:Policy>
               </sp:Layout>
             </wsp:Policy>
           </sp:AsymmetricBinding>
           <sp:Wss11>
              <wsp:Policy>
                 <sp:RequireSignatureConfirmation/>
              </wsp:Policy>
           </sp:Wss11>
           <sp:SignedParts>
             <sp:Body/>
           </sp:SignedParts>
         </wsp:All>
      </wsp:ExactlyOne>
      
    </wsp:Policy>
              
    <!-- not used policies... -->                         
    <wsp:Policy wsu:Id="BasicSigConfirmPolicy2">
    
       <sp:EncryptedSupportingTokens>
          <wsp:Policy>
             <sp:UsernameToken
                sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                <wsp:Policy>
                   <sp:WssUsernameToken11/>
                </wsp:Policy>
             </sp:UsernameToken>
          </wsp:Policy>
       </sp:EncryptedSupportingTokens>
                
       <sp:AsymmetricBinding>
          <wsp:Policy>
             <sp:InitiatorEncryptionToken>
                <wsp:Policy>
                   <sp:X509Token
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                      <wsp:Policy>
                         <sp:WssX509V3Token10 />
                      </wsp:Policy>
                   </sp:X509Token>
                </wsp:Policy>
             </sp:InitiatorEncryptionToken>
             <sp:RecipientEncryptionToken>
                <wsp:Policy>
                   <sp:X509Token
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                      <wsp:Policy>
                         <sp:WssX509V3Token10 />
                      </wsp:Policy>
                   </sp:X509Token>
                </wsp:Policy>
             </sp:RecipientEncryptionToken>
             <sp:AlgorithmSuite>
                <wsp:Policy>
                   <sp:Basic128Rsa15/>
                </wsp:Policy>
             </sp:AlgorithmSuite>
             <sp:Layout>
                <wsp:Policy>
                   <sp:Strict/>
                </wsp:Policy>
             </sp:Layout>
             <sp:ProtectTokens/>
          </wsp:Policy>
       </sp:AsymmetricBinding>
                                                     
    </wsp:Policy>
    
    <wsp:Policy wsu:Id="EncryptedHeaderNSPolicy">
        
     <wsp:ExactlyOne>
        <wsp:All>
           <sp:AsymmetricBinding>
             <wsp:Policy>
               <sp:InitiatorEncryptionToken>
                 <wsp:Policy>
                   <sp:X509Token
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                      <wsp:Policy>
                         <sp:WssX509V3Token10 />
                      </wsp:Policy>
                   </sp:X509Token>
                 </wsp:Policy>
               </sp:InitiatorEncryptionToken>
               <sp:RecipientEncryptionToken>
                 <wsp:Policy>
                   <sp:X509Token
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                      <wsp:Policy>
                         <sp:WssX509V3Token10 />
                      </wsp:Policy>
                   </sp:X509Token>
                 </wsp:Policy>
               </sp:RecipientEncryptionToken>
               <sp:AlgorithmSuite>
                 <wsp:Policy>
                   <sp:Basic128/>
                 </wsp:Policy>
               </sp:AlgorithmSuite>
               <sp:Layout>
                 <wsp:Policy>
                   <sp:Strict/>
                 </wsp:Policy>
               </sp:Layout>
             </wsp:Policy>
           </sp:AsymmetricBinding>
           
           <!--
           <sp:EncryptedParts>
              <sp:Header  Namespace="http://sylonglin/I7/FVT"/>
           </sp:EncryptedParts>
           -->
           <sp:EncryptedParts>
              <sp:Body/>
           </sp:EncryptedParts>
                          
         </wsp:All>
      </wsp:ExactlyOne>
      
    </wsp:Policy>
                             
    <wsp:Policy wsu:Id="BasicSigConfirmPolicy2">
    
       <sp:EncryptedSupportingTokens>
          <wsp:Policy>
             <sp:UsernameToken
                sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                <wsp:Policy>
                   <sp:WssUsernameToken11/>
                </wsp:Policy>
             </sp:UsernameToken>
          </wsp:Policy>
       </sp:EncryptedSupportingTokens>
                
       <sp:AsymmetricBinding>
          <wsp:Policy>
             <sp:InitiatorEncryptionToken>
                <wsp:Policy>
                   <sp:X509Token
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                      <wsp:Policy>
                         <sp:WssX509V3Token10 />
                      </wsp:Policy>
                   </sp:X509Token>
                </wsp:Policy>
             </sp:InitiatorEncryptionToken>
             <sp:RecipientEncryptionToken>
                <wsp:Policy>
                   <sp:X509Token
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                      <wsp:Policy>
                         <sp:WssX509V3Token10 />
                      </wsp:Policy>
                   </sp:X509Token>
                </wsp:Policy>
             </sp:RecipientEncryptionToken>
             <sp:AlgorithmSuite>
                <wsp:Policy>
                   <sp:Basic128Rsa15/>
                </wsp:Policy>
             </sp:AlgorithmSuite>
             <sp:Layout>
                <wsp:Policy>
                   <sp:Strict/>
                </wsp:Policy>
             </sp:Layout>
             <sp:ProtectTokens/>
          </wsp:Policy>
       </sp:AsymmetricBinding>
                                                     
    </wsp:Policy>
                             
    <wsdl:types>
        <schema targetNamespace="http://wss11sig.wssecfvt.test/types" 
            xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
            <element name="getVer">
                <complexType>
                    <sequence>
                        <element name="requestType" type="xsd:string"/>
                    </sequence>
                </complexType>
            </element>
            <element name="getVerResponse">
                <complexType>
                    <sequence>
                        <element name="responseType" type="xsd:string"/>
                    </sequence>
                </complexType>
            </element>
   	    <element name="faultDetail">
		<complexType>
			<sequence>
				<element name="minor" type="xsd:short"/>
				<element name="major" type="xsd:short"/>
			</sequence>
		</complexType>
	    </element>
        </schema>
    </wsdl:types>

    <wsdl:message name="getVerRequest">
        <wsdl:part element="x1:getVer" name="in"/>
    </wsdl:message>
    <wsdl:message name="getVerResponse">
        <wsdl:part element="x1:getVerResponse" name="out"/>
    </wsdl:message>

    <wsdl:portType name="WSS11Sig">
        <wsdl:operation name="invoke">
            <wsdl:input message="tns:getVerRequest" name="getVerRequest"/>
            <wsdl:output message="tns:getVerResponse" name="getVerResponse"/>
        </wsdl:operation>
    </wsdl:portType>
             
    <wsdl:binding name="UrnWss11SigSoapBinding1" type="tns:WSS11Sig">
        <wsp:PolicyReference URI="#BasicSigConfirmPolicy" />
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="invoke">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="getVerRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="getVerResponse">
               <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        
    </wsdl:binding>
    
    <wsdl:binding name="UrnWss11SigSoapBinding2" type="tns:WSS11Sig">
        <wsp:PolicyReference URI="#BasicSigConfirmPolicyNoSig" />
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="invoke">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="getVerRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="getVerResponse">
               <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        
    </wsdl:binding>
    
    <wsdl:binding name="UrnWss11SigSoapBinding4" type="tns:WSS11Sig">
        <wsp:PolicyReference URI="#BasicSigNoConfirmPolicy" />
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="invoke">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="getVerRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="getVerResponse">
               <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        
    </wsdl:binding>
    
        <wsdl:binding name="UrnWss11SigSoapBinding5" type="tns:WSS11Sig">
        <wsp:PolicyReference URI="#BasicSigConfirmPolicy" />
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="invoke">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="getVerRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="getVerResponse">
               <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        
    </wsdl:binding>
    <!--
    <wsdl:binding name="UrnWss11SigSoapBinding2" type="tns:WSS11Sig">
        <wsp:PolicyReference URI="#EncryptedHeaderNSPolicy" />
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="invoke">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="getVerRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="getVerResponse">
               <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        
    </wsdl:binding>
    -->
    
    <wsdl:service name="WSS11SigService1">
        <wsdl:port binding="tns:UrnWss11SigSoapBinding1" name="WSS11Sig1">
            <soap:address location="http://localhost:8010/wss11sig/WSS11SigService1"/>
        </wsdl:port>
    </wsdl:service>
    
    <wsdl:service name="WSS11SigService2">
        <wsdl:port binding="tns:UrnWss11SigSoapBinding2" name="WSS11Sig2">
            <soap:address location="http://localhost:8010/wss11sig/WSS11SigService2"/>
        </wsdl:port>
    </wsdl:service>
    
    <wsdl:service name="WSS11SigService4">
        <wsdl:port binding="tns:UrnWss11SigSoapBinding4" name="WSS11Sig4">
            <soap:address location="http://localhost:8010/wss11sig/WSS11SigService4"/>
        </wsdl:port>
    </wsdl:service>
    
    <wsdl:service name="WSS11SigService5">
        <wsdl:port binding="tns:UrnWss11SigSoapBinding5" name="WSS11Sig5">
            <soap:address location="http://localhost:8010/wss11sig/WSS11SigService5"/>
        </wsdl:port>
    </wsdl:service>        
    <!--
    <wsdl:service name="WSS11SigService2">
        <wsdl:port binding="tns:UrnWss11SigSoapBinding2" name="WSS11Sig2">
            <soap:address location="http://localhost:8010/wss11sig/WSS11SigService2"/>
        </wsdl:port>
    </wsdl:service>
   -->
           
</wsdl:definitions>
