CREATE TABLE ${schemaname}.EmbedIDOOEntA (id NUMBER NOT NULL, password VARCHAR2(255), userName VARCHAR2(255), identity_id NUMBER, identity_country VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.EmbedIDOOEntB (country VARCHAR2(255) NOT NULL, id NUMBER NOT NULL, name VARCHAR2(255), salary NUMBER, PRIMARY KEY (country, id));
CREATE TABLE ${schemaname}.IDClassOOEntityA (id NUMBER NOT NULL, password VARCHAR2(255), userName VARCHAR2(255), identity_id NUMBER, identity_country VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.IDClassOOEntityB (country VARCHAR2(255) NOT NULL, id NUMBER NOT NULL, name VARCHAR2(255), salary NUMBER, PRIMARY KEY (country, id));
CREATE TABLE ${schemaname}.OOBiCardEntA (id NUMBER NOT NULL, name VARCHAR2(255), B_ID NUMBER, PRIMARY KEY (id), UNIQUE(B_ID));
CREATE TABLE ${schemaname}.OOBiCardEntB (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntA (id NUMBER NOT NULL, name VARCHAR2(255), BIENT_B1CP NUMBER, BIENT_B1 NUMBER, B2_ID NUMBER, BIENT_B4 NUMBER, BIENT_B1CA NUMBER, BIENT_B1CM NUMBER, BIENT_B1RF NUMBER, BIENT_B1RM NUMBER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B1 (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B2 (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B4 (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B5CA (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B5CM (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B5CP (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B5RF (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOBiEntB_B5RM (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOCardEntA (id NUMBER NOT NULL, name VARCHAR2(255), B_ID NUMBER, PRIMARY KEY (id), UNIQUE(B_ID));
CREATE TABLE ${schemaname}.OOCardEntB (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OONoOptBiEntityA (id NUMBER NOT NULL, name VARCHAR2(255), B_ID NUMBER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OONoOptBiEntityB (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OONoOptEntityA (id NUMBER NOT NULL, name VARCHAR2(255), B_ID NUMBER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OONoOptEntityB (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOUniEntA (id NUMBER NOT NULL, name VARCHAR2(255), UNIENT_B1 NUMBER, B2_ID NUMBER, B4_ID NUMBER, B5CA_ID NUMBER, B5CM_ID NUMBER, B5CP_ID NUMBER, B5RF_ID NUMBER, B5RM_ID NUMBER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OOUniEntB (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.PKJoinOOEntityA (id NUMBER NOT NULL, strVal VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.PKJoinOOEntityB (id NUMBER NOT NULL, intVal NUMBER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLEmbedIDOOEntA (id NUMBER NOT NULL, password VARCHAR2(255), userName VARCHAR2(255), identity_id NUMBER, identity_country VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLEmbedIDOOEntB (country VARCHAR2(255) NOT NULL, id NUMBER NOT NULL, name VARCHAR2(255), salary NUMBER, PRIMARY KEY (country, id));
CREATE TABLE ${schemaname}.XMLIDClassOOEntityA (id NUMBER NOT NULL, password VARCHAR2(255), userName VARCHAR2(255), identity_id NUMBER, identity_country VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLIDClassOOEntityB (country VARCHAR2(255) NOT NULL, id NUMBER NOT NULL, name VARCHAR2(255), salary NUMBER, PRIMARY KEY (country, id));
CREATE TABLE ${schemaname}.XMLOOBiCardEntA (id NUMBER NOT NULL, name VARCHAR2(255), B_ID NUMBER, PRIMARY KEY (id), UNIQUE(B_ID));
CREATE TABLE ${schemaname}.XMLOOBiCardEntB (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntA (id NUMBER NOT NULL, name VARCHAR2(255), B5CM_ID NUMBER, XMLBIENT_B1 NUMBER, B2_ID NUMBER, B4_ID NUMBER, B5CA_ID NUMBER, B5CP_ID NUMBER, B5RF_ID NUMBER, B5RM_ID NUMBER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B1 (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B2 (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B4 (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B5CA (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B5CM (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B5CP (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B5RF (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOBiEntB_B5RM (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOCardEntA (id NUMBER NOT NULL, name VARCHAR2(255), B_ID NUMBER, PRIMARY KEY (id), UNIQUE(B_ID));
CREATE TABLE ${schemaname}.XMLOOCardEntB (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOONoOptBiEntityA (id NUMBER NOT NULL, name VARCHAR2(255), B_ID NUMBER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOONoOptBiEntityB (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOONoOptEntityA (id NUMBER NOT NULL, name VARCHAR2(255), B_ID NUMBER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOONoOptEntityB (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOUniEntA (id NUMBER NOT NULL, name VARCHAR2(255), UNIENT_B1 NUMBER, B2_ID NUMBER, B4_ID NUMBER, B5CA_ID NUMBER, B5CM_ID NUMBER, B5CP_ID NUMBER, B5RF_ID NUMBER, B5RM_ID NUMBER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLOOUniEntB (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLPKJoinOOEnA (id NUMBER NOT NULL, strVal VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLPKJoinOOEnB (id NUMBER NOT NULL, intVal NUMBER, PRIMARY KEY (id));
CREATE INDEX ${schemaname}.I_MBDDONT_IDENTITY ON ${schemaname}.EmbedIDOOEntA (identity_id, identity_country);
CREATE INDEX ${schemaname}.I_DCLSTTY_IDENTITY ON ${schemaname}.IDClassOOEntityA (identity_id, identity_country);
CREATE INDEX ${schemaname}.I_OBCRDNT_B ON ${schemaname}.OOBiCardEntA (B_ID);
CREATE INDEX ${schemaname}.I_OOBIENT_B1 ON ${schemaname}.OOBiEntA (BIENT_B1);
CREATE INDEX ${schemaname}.I_OOBIENT_B2 ON ${schemaname}.OOBiEntA (B2_ID);
CREATE INDEX ${schemaname}.I_OOBIENT_B4 ON ${schemaname}.OOBiEntA (BIENT_B4);
CREATE INDEX ${schemaname}.I_OOBIENT_B5CA ON ${schemaname}.OOBiEntA (BIENT_B1CA);
CREATE INDEX ${schemaname}.I_OOBIENT_B5CM ON ${schemaname}.OOBiEntA (BIENT_B1CM);
CREATE INDEX ${schemaname}.I_OOBIENT_B5CP ON ${schemaname}.OOBiEntA (BIENT_B1CP);
CREATE INDEX ${schemaname}.I_OOBIENT_B5RF ON ${schemaname}.OOBiEntA (BIENT_B1RF);
CREATE INDEX ${schemaname}.I_OOBIENT_B5RM ON ${schemaname}.OOBiEntA (BIENT_B1RM);
CREATE INDEX ${schemaname}.I_OOCRDNT_B ON ${schemaname}.OOCardEntA (B_ID);
CREATE INDEX ${schemaname}.I_NPTBTTY_B ON ${schemaname}.OONoOptBiEntityA (B_ID);
CREATE INDEX ${schemaname}.I_NPTNTTY_B ON ${schemaname}.OONoOptEntityA (B_ID);
CREATE INDEX ${schemaname}.I_OOUNINT_B1 ON ${schemaname}.OOUniEntA (UNIENT_B1);
CREATE INDEX ${schemaname}.I_OOUNINT_B2 ON ${schemaname}.OOUniEntA (B2_ID);
CREATE INDEX ${schemaname}.I_OOUNINT_B4 ON ${schemaname}.OOUniEntA (B4_ID);
CREATE INDEX ${schemaname}.I_OOUNINT_B5CA ON ${schemaname}.OOUniEntA (B5CA_ID);
CREATE INDEX ${schemaname}.I_OOUNINT_B5CM ON ${schemaname}.OOUniEntA (B5CM_ID);
CREATE INDEX ${schemaname}.I_OOUNINT_B5CP ON ${schemaname}.OOUniEntA (B5CP_ID);
CREATE INDEX ${schemaname}.I_OOUNINT_B5RF ON ${schemaname}.OOUniEntA (B5RF_ID);
CREATE INDEX ${schemaname}.I_OOUNINT_B5RM ON ${schemaname}.OOUniEntA (B5RM_ID);
CREATE INDEX ${schemaname}.I_XMLMDNT_IDENTITY ON ${schemaname}.XMLEmbedIDOOEntA (identity_id, identity_country);
CREATE INDEX ${schemaname}.I_XMLDTTY_IDENTITY ON ${schemaname}.XMLIDClassOOEntityA (identity_id, identity_country);
CREATE INDEX ${schemaname}.I_XMLBDNT_B ON ${schemaname}.XMLOOBiCardEntA (B_ID);
CREATE INDEX ${schemaname}.I_XMLOBNT_B1 ON ${schemaname}.XMLOOBiEntA (XMLBIENT_B1);
CREATE INDEX ${schemaname}.I_XMLOBNT_B2 ON ${schemaname}.XMLOOBiEntA (B2_ID);
CREATE INDEX ${schemaname}.I_XMLOBNT_B4 ON ${schemaname}.XMLOOBiEntA (B4_ID);
CREATE INDEX ${schemaname}.I_XMLOBNT_B5CA ON ${schemaname}.XMLOOBiEntA (B5CA_ID);
CREATE INDEX ${schemaname}.I_XMLOBNT_B5CM ON ${schemaname}.XMLOOBiEntA (B5CM_ID);
CREATE INDEX ${schemaname}.I_XMLOBNT_B5CP ON ${schemaname}.XMLOOBiEntA (B5CP_ID);
CREATE INDEX ${schemaname}.I_XMLOBNT_B5RF ON ${schemaname}.XMLOOBiEntA (B5RF_ID);
CREATE INDEX ${schemaname}.I_XMLOBNT_B5RM ON ${schemaname}.XMLOOBiEntA (B5RM_ID);
CREATE INDEX ${schemaname}.I_XMLCDNT_B ON ${schemaname}.XMLOOCardEntA (B_ID);
CREATE INDEX ${schemaname}.I_XMLNTTY_B ON ${schemaname}.XMLOONoOptBiEntityA (B_ID);
CREATE INDEX ${schemaname}.I_XMLNTTY_B1 ON ${schemaname}.XMLOONoOptEntityA (B_ID);
CREATE INDEX ${schemaname}.I_XMLUNNT_B1 ON ${schemaname}.XMLOOUniEntA (UNIENT_B1);
CREATE INDEX ${schemaname}.I_XMLUNNT_B2 ON ${schemaname}.XMLOOUniEntA (B2_ID);
CREATE INDEX ${schemaname}.I_XMLUNNT_B4 ON ${schemaname}.XMLOOUniEntA (B4_ID);
CREATE INDEX ${schemaname}.I_XMLUNNT_B5CA ON ${schemaname}.XMLOOUniEntA (B5CA_ID);
CREATE INDEX ${schemaname}.I_XMLUNNT_B5CM ON ${schemaname}.XMLOOUniEntA (B5CM_ID);
CREATE INDEX ${schemaname}.I_XMLUNNT_B5CP ON ${schemaname}.XMLOOUniEntA (B5CP_ID);
CREATE INDEX ${schemaname}.I_XMLUNNT_B5RF ON ${schemaname}.XMLOOUniEntA (B5RF_ID);
CREATE INDEX ${schemaname}.I_XMLUNNT_B5RM ON ${schemaname}.XMLOOUniEntA (B5RM_ID);