CREATE TABLE ${schemaname}.JPA10EntityManagerEntityA (id NUMBER NOT NULL, strData VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.JPA10ENTITYMANAGERENTITYA_JPA2 (ENTITYALIST_ID NUMBER, ENTITYBLIST_ID NUMBER);
CREATE TABLE ${schemaname}.JPA10EntityManagerEntityB (id NUMBER NOT NULL, strData VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.JPA10EntityManagerEntityC (id NUMBER NOT NULL, strData VARCHAR2(255), ENTITYA_ID NUMBER, ENTITYALAZY_ID NUMBER, PRIMARY KEY (id));
CREATE INDEX I_JP20JP2_ELEMENT ON ${schemaname}.JPA10ENTITYMANAGERENTITYA_JPA2 (ENTITYBLIST_ID);
CREATE INDEX I_JP20JP2_ENTITYALIST_ID ON ${schemaname}.JPA10ENTITYMANAGERENTITYA_JPA2 (ENTITYALIST_ID);
CREATE INDEX I_JP20TYC_ENTITYA ON ${schemaname}.JPA10EntityManagerEntityC (ENTITYA_ID);
CREATE INDEX I_JP20TYC_ENTITYALAZY ON ${schemaname}.JPA10EntityManagerEntityC (ENTITYALAZY_ID);