CREATE TABLE ${schemaname}.JPA10EntityManagerEntityA (id INT NOT NULL, strData VARCHAR(255) NULL NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.JPA10ENTITYMANAGERENTITYA_JPA2 (ENTITYALIST_ID INT NULL, ENTITYBLIST_ID INT NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE);
CREATE TABLE ${schemaname}.JPA10EntityManagerEntityB (id INT NOT NULL, strData VARCHAR(255) NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.JPA10EntityManagerEntityC (id INT NOT NULL, strData VARCHAR(255) NULL, ENTITYA_ID INT NULL, ENTITYALAZY_ID INT NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));
CREATE INDEX I_JP20JP2_ELEMENT ON ${schemaname}.JPA10ENTITYMANAGERENTITYA_JPA2 (ENTITYBLIST_ID);
CREATE INDEX I_JP20JP2_ENTITYALIST_ID ON ${schemaname}.JPA10ENTITYMANAGERENTITYA_JPA2 (ENTITYALIST_ID);
CREATE INDEX I_JP20TYC_ENTITYA ON ${schemaname}.JPA10EntityManagerEntityC (ENTITYA_ID);
CREATE INDEX I_JP20TYC_ENTITYALAZY ON ${schemaname}.JPA10EntityManagerEntityC (ENTITYALAZY_ID);