CREATE TABLE ${schemaname}.JPA10EntityManagerEntityA (id NUMBER NOT NULL, strData VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.JPA10EntityManagerEntityA_JPA10EntityManagerEntityB (ENTITYALIST_ID NUMBER, ENTITYBLIST_ID NUMBER);
CREATE TABLE ${schemaname}.JPA10EntityManagerEntityB (id NUMBER NOT NULL, strData VARCHAR2(255), PRIMARY KEY (id));
CREATE TABLE ${schemaname}.JPA10EntityManagerEntityC (id NUMBER NOT NULL, strData VARCHAR2(255), ENTITYA_ID NUMBER, ENTITYALAZY_ID NUMBER, PRIMARY KEY (id));
CREATE INDEX I_JP10JP1_ELEMENT ON ${schemaname}.JPA10EntityManagerEntityA_JPA10EntityManagerEntityB (ENTITYBLIST_ID);
CREATE INDEX I_JP10JP1_ENTITYALIST_ID ON ${schemaname}.JPA10EntityManagerEntityA_JPA10EntityManagerEntityB (ENTITYALIST_ID);
CREATE INDEX I_JP10TYC_ENTITYA ON ${schemaname}.JPA10EntityManagerEntityC (ENTITYA_ID);
CREATE INDEX I_JP10TYC_ENTITYALAZY ON ${schemaname}.JPA10EntityManagerEntityC (ENTITYALAZY_ID);