DROP TABLE ${schemaname}.PREV_ADDRESSES;
DROP TABLE ${schemaname}.SpecEmployeeOLGH16588;
DROP TABLE ${schemaname}.SPECEMPLOYEEOLGH16588_SPECPHON;
DROP TABLE ${schemaname}.SpecPhoneOLGH16588;
DROP TABLE ${schemaname}.SPECPHONEOLGH16588_SPECPHONEOL;