-- EclipseLink
CREATE TABLE ${schemaname}.PREV_ADDRESSES (SpecEmployeeOLGH16588_ID INT NULL, city VARCHAR(255) NULL, state VARCHAR(255) NULL, street VARCHAR(255) NULL, zipcode VARCHAR(255) NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE);
CREATE TABLE ${schemaname}.SpecEmployeeOLGH16588 (id INT NOT NULL, city VARCHAR(255) NULL, state VARCHAR(255) NULL, street VARCHAR(255) NULL, zipcode VARCHAR(255) NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.SPECEMPLOYEEOLGH16588_SPECPHON (SpecEmployeeOLGH16588_ID INT NULL, phones_ID INT NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE);
CREATE TABLE ${schemaname}.SpecPhoneOLGH16588 (id INT NOT NULL, vendor VARCHAR(255) NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));
CREATE INDEX ${schemaname}.I_PRV_SSS_SPECCONTACTINFOOLGH1 ON ${schemaname}.PREV_ADDRESSES (SpecEmployeeOLGH16588_ID);
CREATE INDEX ${schemaname}.I_SPCMPHN_ELEMENT ON ${schemaname}.SPECEMPLOYEEOLGH16588_SPECPHON (phones_ID);
CREATE INDEX ${schemaname}.I_SPCMPHN_SPECCONTACTINFOOLGH1 ON ${schemaname}.SPECEMPLOYEEOLGH16588_SPECPHON (SpecEmployeeOLGH16588_ID);