//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:52 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:54 PM(foreman)-)
//

package com.ibm.ws.wsat.webservice.client;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "RegistrationService", targetNamespace = "http://webservice.wsat.ws.ibm.com", wsdlLocation = "/META-INF/wsdl/wscoor-liberty.wsdl")
public class RegistrationService
                extends Service
{

    private final static URL REGISTRATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException REGISTRATIONSERVICE_EXCEPTION;
    private final static QName REGISTRATIONSERVICE_QNAME = new QName("http://webservice.wsat.ws.ibm.com", "RegistrationService");

    static {
        REGISTRATIONSERVICE_WSDL_LOCATION = RegistrationService.class.getResource("/META-INF/wsdl/wscoor-liberty.wsdl");
        WebServiceException e = null;
        if (REGISTRATIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/META-INF/wsdl/wscoor-liberty.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        REGISTRATIONSERVICE_EXCEPTION = e;
    }

    public RegistrationService() {
        super(__getWsdlLocation(), REGISTRATIONSERVICE_QNAME);
    }

    public RegistrationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTRATIONSERVICE_QNAME, features);
    }

    public RegistrationService(URL wsdlLocation) {
        super(wsdlLocation, REGISTRATIONSERVICE_QNAME);
    }

    public RegistrationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTRATIONSERVICE_QNAME, features);
    }

    public RegistrationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *         returns RegistrationPortType
     */
    @WebEndpoint(name = "RegistrationPort")
    public RegistrationPortType getRegistrationPort() {
        return super.getPort(new QName("http://webservice.wsat.ws.ibm.com", "RegistrationPort"), RegistrationPortType.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will have their default
     *            values.
     * @return
     *         returns RegistrationPortType
     */
    @WebEndpoint(name = "RegistrationPort")
    public RegistrationPortType getRegistrationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.wsat.ws.ibm.com", "RegistrationPort"), RegistrationPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTRATIONSERVICE_EXCEPTION != null) {
            throw REGISTRATIONSERVICE_EXCEPTION;
        }
        return REGISTRATIONSERVICE_WSDL_LOCATION;
    }

}
