CREATE TABLE DefDSEntity2 (ID BIGINT NOT NULL, VALUE VARCHAR(255) FOR MIXED DATA, PRIMARY KEY (ID));
CREATE TABLE DefDSEntity (ID BIGINT NOT NULL, VALUE VARCHAR(255) FOR MIXED DATA, PRIMARY KEY (ID));
