CREATE TABLE WLPPersistenceUnitEntity (ID VARCHAR(255) FOR MIXED DATA NOT NULL, VALUE INTEGER, PRIMARY KEY (ID));
CREATE TABLE WLPDefDSEntity (ID BIGINT NOT NULL, VALUE VARCHAR(255) FOR MIXED DATA, PRIMARY KEY (ID));
