//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//

package com.ibm.ws.jaxws.ejbinterceptor.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "SayHelloService", targetNamespace = "http://ejbinterceptor.jaxws.ws.ibm.com/", wsdlLocation = "WEB-INF/wsdl/SayHelloService.wsdl")
public class SayHelloService
                extends Service
{

    private final static URL SAYHELLOSERVICE_WSDL_LOCATION;
    private final static WebServiceException SAYHELLOSERVICE_EXCEPTION;
    private final static QName SAYHELLOSERVICE_QNAME = new QName("http://ejbinterceptor.jaxws.ws.ibm.com/", "SayHelloService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("WEB-INF/wsdl/SayHelloService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAYHELLOSERVICE_WSDL_LOCATION = url;
        SAYHELLOSERVICE_EXCEPTION = e;
    }

    public SayHelloService() {
        super(__getWsdlLocation(), SAYHELLOSERVICE_QNAME);
    }

    public SayHelloService(URL wsdlLocation) {
        super(wsdlLocation, SAYHELLOSERVICE_QNAME);
    }

    public SayHelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *         returns SayHello
     */
    @WebEndpoint(name = "SayHelloPort")
    public SayHello getSayHelloPort() {
        return super.getPort(new QName("http://ejbinterceptor.jaxws.ws.ibm.com/", "SayHelloPort"), SayHello.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will have their default
     *            values.
     * @return
     *         returns SayHello
     */
    @WebEndpoint(name = "SayHelloPort")
    public SayHello getSayHelloPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ejbinterceptor.jaxws.ws.ibm.com/", "SayHelloPort"), SayHello.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAYHELLOSERVICE_EXCEPTION != null) {
            throw SAYHELLOSERVICE_EXCEPTION;
        }
        return SAYHELLOSERVICE_WSDL_LOCATION;
    }

}
