{
	"date" : { "year" : 2018, "month" : "January", "day" : 16, "dayOfWeek" : "Tuesday" },
	"location" : { "state" : "Minnesota", "zip" : 55901, "county" : "Olmsted", "city" : "Rochester" },
	"hourlyForecast" : [
		{ "temp" :  3, "windchill" : -12, "chanceOfSnow" : 0.31 },
		{ "temp" :  3, "windchill" : -10, "chanceOfSnow" : 0.29 },
		{ "temp" :  3, "windchill" : -11, "chanceOfSnow" : 0.27 },
		{ "temp" :  3, "windchill" : -12, "chanceOfSnow" : 0.25 },
		{ "temp" :  3, "windchill" : -12, "chanceOfSnow" : 0.20 },
		{ "temp" :  2, "windchill" : -13, "chanceOfSnow" : 0.09 },
		{ "temp" :  1, "windchill" : -13, "chanceOfSnow" : 0.05 },
		{ "temp" : -1, "windchill" : -15, "chanceOfSnow" : 0.05 },
		{ "temp" : -1, "windchill" : -15, "chanceOfSnow" : 0.05 },
		{ "temp" : -1, "windchill" : -15, "chanceOfSnow" : 0.05 },
		{ "temp" :  1, "windchill" : -13, "chanceOfSnow" : 0.05 },
		{ "temp" :  3, "windchill" :  -9, "chanceOfSnow" : 0.05 },
		{ "temp" :  5, "windchill" :  -8, "chanceOfSnow" : 0.01 },
		{ "temp" :  6, "windchill" :  -7, "chanceOfSnow" : 0.01 },
		{ "temp" :  7, "windchill" :  -6, "chanceOfSnow" : 0.01 },
		{ "temp" :  7, "windchill" :  -6, "chanceOfSnow" : 0.01 },
		{ "temp" :  5, "windchill" :  -7, "chanceOfSnow" : 0.01 },
		{ "temp" :  3, "windchill" :  -9, "chanceOfSnow" : 0.01 },
		{ "temp" :  1, "windchill" : -10, "chanceOfSnow" : 0.01 },
		{ "temp" : -1, "windchill" : -13, "chanceOfSnow" : 0.01 },
		{ "temp" : -2, "windchill" : -14, "chanceOfSnow" : 0.01 },
		{ "temp" : -3, "windchill" : -15, "chanceOfSnow" : 0.01 },
		{ "temp" : -4, "windchill" : -16, "chanceOfSnow" : 0.01 },
		{ "temp" : -5, "windchill" : -16, "chanceOfSnow" : 0.01 }
	]
}