CREATE TABLE Event (eventId INTEGER NOT NULL, eventLocation VARCHAR(255), eventName VARCHAR(255), eventTime VARCHAR(255), PRIMARY KEY (eventId))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
