//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.20 at 10:40:55 AM CDT 
//


package org.apache.cxf.configuration.security;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.ibm.websphere.ras.annotation.Trivial;


/**
 * 
 *         This structure contains the specification of JSSE TrustManagers for
 *         a single Keystore used for trusted certificates.
 *         
 * 
 * <p>Java class for TrustManagersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrustManagersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="keyStore" type="{http://cxf.apache.org/configuration/security}KeyStoreType" minOccurs="0"/>
 *         &lt;element name="certStore" type="{http://cxf.apache.org/configuration/security}CertStoreType" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="provider" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="factoryAlgorithm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrustManagersType", propOrder = {
    "keyStore",
    "certStore"
})
@Trivial
public class TrustManagersType {

    protected KeyStoreType keyStore;
    protected CertStoreType certStore;
    @XmlAttribute(name = "provider")
    protected String provider;
    @XmlAttribute(name = "factoryAlgorithm")
    protected String factoryAlgorithm;
    @XmlAttribute(name = "ref")
    protected String ref;

    /**
     * Gets the value of the keyStore property.
     * 
     * @return
     *     possible object is
     *     {@link KeyStoreType }
     *     
     */
    public KeyStoreType getKeyStore() {
        return keyStore;
    }

    /**
     * Sets the value of the keyStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyStoreType }
     *     
     */
    public void setKeyStore(KeyStoreType value) {
        this.keyStore = value;
    }

    public boolean isSetKeyStore() {
        return (this.keyStore!= null);
    }

    /**
     * Gets the value of the certStore property.
     * 
     * @return
     *     possible object is
     *     {@link CertStoreType }
     *     
     */
    public CertStoreType getCertStore() {
        return certStore;
    }

    /**
     * Sets the value of the certStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertStoreType }
     *     
     */
    public void setCertStore(CertStoreType value) {
        this.certStore = value;
    }

    public boolean isSetCertStore() {
        return (this.certStore!= null);
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvider(String value) {
        this.provider = value;
    }

    public boolean isSetProvider() {
        return (this.provider!= null);
    }

    /**
     * Gets the value of the factoryAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFactoryAlgorithm() {
        return factoryAlgorithm;
    }

    /**
     * Sets the value of the factoryAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFactoryAlgorithm(String value) {
        this.factoryAlgorithm = value;
    }

    public boolean isSetFactoryAlgorithm() {
        return (this.factoryAlgorithm!= null);
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRef(String value) {
        this.ref = value;
    }

    public boolean isSetRef() {
        return (this.ref!= null);
    }

}
