CREATE TABLE ${schemaname}.CALLBACKENTITY (id INT NOT NULL, name VARCHAR(255) NULL, protectionType VARCHAR(31) NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));
CREATE INDEX ${schemaname}.I_CLLBTTY_DTYPE ON ${schemaname}.CALLBACKENTITY (protectionType);
CREATE TABLE ${schemaname}.OOIRootEntity (id INT NOT NULL, name VARCHAR(255) NULL, leafType VARCHAR(31) NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));
CREATE INDEX ${schemaname}.I_OOIRTTY_DTYPE ON ${schemaname}.OOIRootEntity (leafType);
CREATE TABLE ${schemaname}.CallbkEntNSptDefCbk (id INT NOT NULL, name VARCHAR(255) NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.CallbkEntSptDefCbk (id INT NOT NULL, name VARCHAR(255) NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLCallbkEntNSptDefCbk (id INT NOT NULL, name VARCHAR(255) NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XMLCallbkEntSptDefCbk (id INT NOT NULL, name VARCHAR(255) NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (id));