DROP TABLE ${schemaname}.SIMPLEENTITYOLGH21204;
DROP TABLE ${schemaname}.STEPEXECUTIONENTITYOLGH21204;
DROP TABLE ${schemaname}.SIMPLEENTITYOLGH21204_AUDIT;
DROP TRIGGER ${schemaname}.SIMPLEENTITYOLGH21204_TRIGGER;