INSERT INTO ${schemaname}.SIMPLEENTITYOLGH21204_AUDIT (ENTITY_ID, NAME, PRICE) VALUES (1, 'COFFEE1', 11.1);
INSERT INTO ${schemaname}.SIMPLEENTITYOLGH21204_AUDIT (ENTITY_ID, NAME, PRICE) VALUES (2, 'COFFEE2', 22.2);
INSERT INTO ${schemaname}.SIMPLEENTITYOLGH21204_AUDIT (ENTITY_ID, NAME, PRICE) VALUES (3, 'COFFEE3', 33.3);