CREATE TABLE ASMTestServiceEntity (ID INTEGER NOT NULL, STRDATA VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(255) NOT NULL, SEQ_COUNT INTEGER);
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);
