CREATE TABLE ${schemaname}.criteria_car_origin (CAR_ID VARCHAR(255), CAR_VER INTEGER, component VARCHAR(255) NOT NULL, origin VARCHAR(255));
CREATE TABLE ${schemaname}.SimpleEntityOLGH10515 (CAR_ID VARCHAR(255) NOT NULL, CAR_VER INT NOT NULL, UNQ_INDEX NUMERIC IDENTITY UNIQUE, PRIMARY KEY (CAR_ID, CAR_VER));
CREATE INDEX I_CRTRRGN_CAR_ID ON ${schemaname}.criteria_car_origin (CAR_ID, CAR_VER);