CREATE TABLE WLPPersistenceUnitEntity (ID NVARCHAR(255) NOT NULL, VALUE INTEGER NULL, PRIMARY KEY (ID));
CREATE TABLE WLPDefDSEntity (ID NUMERIC(19) NOT NULL, VALUE NVARCHAR(255) NULL, PRIMARY KEY (ID));
