CREATE TABLE ElemCollEntityOLGH16686 (id INTEGER NOT NULL, PRIMARY KEY (id));
CREATE TABLE EntMapDateTemporal (ELEMCOLLENTITYOLGH16686_ID INTEGER, mykey DATE NOT NULL, temporalValue DATE);
CREATE INDEX I_NTMPPRL_ELEMCOLLENTITYOLGH16686_ID ON EntMapDateTemporal (ELEMCOLLENTITYOLGH16686_ID);