CREATE TABLE ElemCollEntityOLGH16686 (id INT NOT NULL, PRIMARY KEY (id));
CREATE TABLE EntMapDateTemporal (ELEMCOLLENTITYOLGH16686_ID INT, mykey DATETIME NOT NULL, temporalValue DATETIME);
CREATE INDEX I_NTMPPRL_ELEMCOLLENTITYOLGH16686_ID ON EntMapDateTemporal (ELEMCOLLENTITYOLGH16686_ID);