CREATE TABLE ${schemaname}.ElemCollEntityOLGH16686 (id INTEGER NOT NULL, PRIMARY KEY (id)) ENGINE = innodb;
CREATE TABLE ${schemaname}.EntMapDateTemporal (ELEMCOLLENTITYOLGH16686_ID INTEGER, mykey DATE NOT NULL, temporalValue DATE) ENGINE = innodb;
CREATE INDEX ${schemaname}.I_NTMPPRL_ELEMCOLLENTITYOLGH16686_ID ON ${schemaname}.EntMapDateTemporal (ELEMCOLLENTITYOLGH16686_ID);