mcpServer.name=Model Context Protocol (MCP) Server
mcpServer.description=Configure the MCP Server feature.

stateless.name=Stateless mode
stateless.description=Stateless mode disables MCP session tracking by the server. This mode removes the need for session affinity in a clustered environment. Otherwise, the same server handles requests from the same MCP session. Because no session data is stored on the servers, any server instance can handle any request, which simplifies load balancing and horizontal scaling. However, the stateless mode also disables MCP features that rely on session tracking or linking separate HTTP requests together, such as canceling a tool call.

moduleName.name=Module name
moduleName.description=The name of the module in an EAR. Selects the module to which the configuration applies.

path.name=Endpoint path
path.description=The URL path for this MCP endpoint, relative to the module context root. Sets the MCP endpoint path within that module.
