CREATE TABLE ${schemaname}.AttrOColE (ID INTEGER NOT NULL, NAME VARCHAR(255), NONINSERTABLEXMLELEMENTS BLOB(2147483647), NONNULLABLEXMLELEMENTS BLOB(2147483647), NONUPDABLEXMLELEMENTS BLOB(2147483647), PRIMARY KEY (ID));
CREATE TABLE ${schemaname}.AttrOColE_nonInsertAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), NONINSERTABLE_ORDER INTEGER);
CREATE TABLE ${schemaname}.AttrOColE_nonNullAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), NONNULLABLE_ORDER INTEGER NOT NULL);
CREATE TABLE ${schemaname}.AttrOColE_nonUpdateAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), NONUPDATABLE_ORDER INTEGER);
CREATE TABLE ${schemaname}.AttrOColE_oNameTypeElem (ATTRIBUTEORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), orderNameTypeElements_ORDER INTEGER);

CREATE TABLE ${schemaname}.BONameE (id INTEGER NOT NULL, name VARCHAR(255), COLUMN_ID INTEGER, bo2mNames_ORDER INTEGER, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.BONameXE (id INTEGER NOT NULL, name VARCHAR(255), XMLCOLUMN_ID INTEGER, bo2mNames_ORDER INTEGER, PRIMARY KEY (id));

CREATE TABLE ${schemaname}.DefOColE (ID INTEGER NOT NULL, NAME VARCHAR(255), XMLORDERCOLUMNDEFINITIONELEMENTS BLOB(2147483647), XMLOVERRIDEORDERCOLUMNDEFINITIONELEMENTS BLOB(2147483647), PRIMARY KEY (ID));
CREATE TABLE ${schemaname}.DefOColE_oColDefElem (DEFINITIONORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), OCDefElements_ODR INTEGER, ORDERCOLUMNDEFINITIONELEMENTS VARCHAR(255));
CREATE TABLE ${schemaname}.DefOColE_ovrOColDefElem (DEFINITIONORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), OVROCDefElements_ODR SMALLINT, OVERRIDEORDERCOLUMNDEFINITIONELEMENTS VARCHAR(255));

CREATE TABLE ${schemaname}.Diff_Table_Name (NAMETABLEORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), Diff_OrderColumn_Name INTEGER, OVERRIDEORDERCOLUMNNAMEELEMENTS VARCHAR(255));

CREATE TABLE ${schemaname}.NTblOColE (ID INTEGER NOT NULL, NAME VARCHAR(255), XMLORDERNAMETYPEELEMENTS BLOB(2147483647), XMLOVERRIDEORDERCOLUMNNAMEELEMENTS BLOB(2147483647), PRIMARY KEY (ID));
CREATE TABLE ${schemaname}.NTblOColE_oNameTypeElem (NAMETABLEORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), orderNameTypeElements_ORDER INTEGER, ORDERNAMETYPEELEMENTS VARCHAR(255));

CREATE TABLE ${schemaname}.OColE (id INTEGER NOT NULL, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.OColE_BONameE (bm2mNames_ID INTEGER, columns_ID INTEGER, columns_ORDER INTEGER, bm2mNames_ORDER INTEGER);
CREATE TABLE ${schemaname}.OColE_listElements (ORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), OVRELEMENTS_ORDER INTEGER, LISTELEMENTS VARCHAR(255));
CREATE TABLE ${schemaname}.OColE_UONameE (ORDERCOLUMNENTITY_ID INTEGER, UM2MNAMES_ID INTEGER, um2mNames_ORDER INTEGER, UO2MNAMES_ID INTEGER, uo2mNames_ORDER INTEGER);

CREATE TABLE ${schemaname}.UONameE (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));

CREATE TABLE ${schemaname}.XOColE (id INTEGER NOT NULL, PRIMARY KEY (id));
CREATE TABLE ${schemaname}.XOColE_BONameXE (xmlColumns_ID INTEGER, bm2mNames_ID INTEGER, bm2mNames_ORDER INTEGER, xmlColumns_ORDER INTEGER);
CREATE TABLE ${schemaname}.XOColE_listElements (XMLORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), OVRELEMENTS_ORDER INTEGER, LISTELEMENTS VARCHAR(255));
CREATE TABLE ${schemaname}.XOColE_UONameE (XMLOrderColumnEntity_ID INTEGER, um2mNames_ID INTEGER, um2mNames_ORDER INTEGER, uo2mNames_ID INTEGER, uo2mNames_ORDER INTEGER);

CREATE INDEX I_TTRCNLM_ATTRIBUTEORDERCOLUMNENTITY_ID ON ${schemaname}.AttrOColE_nonInsertAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID);
CREATE INDEX I_TTRCNLM_ATTRIBUTEORDERCOLUMNENTITY_ID1 ON ${schemaname}.AttrOColE_nonNullAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID);
CREATE INDEX I_TTRCNLM_ATTRIBUTEORDERCOLUMNENTITY_ID2 ON ${schemaname}.AttrOColE_nonUpdateAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID);
CREATE INDEX I_TTRCPLM_ATTRIBUTEORDERCOLUMNENTITY_ID ON ${schemaname}.AttrOColE_oNameTypeElem (ATTRIBUTEORDERCOLUMNENTITY_ID);
CREATE INDEX I_BONAMEE_COLUMN ON ${schemaname}.BONameE (COLUMN_ID);
CREATE INDEX I_BONMEXE_XMLCOLUMN ON ${schemaname}.BONameXE (XMLCOLUMN_ID);
CREATE INDEX I_DFCLFLM_DEFINITIONORDERCOLUMNENTITY_ID ON ${schemaname}.DefOColE_oColDefElem (DEFINITIONORDERCOLUMNENTITY_ID);
CREATE INDEX I_DFCLFLM_DEFINITIONORDERCOLUMNENTITY_ID1 ON ${schemaname}.DefOColE_ovrOColDefElem (DEFINITIONORDERCOLUMNENTITY_ID);
CREATE INDEX I_DFF__NM_NAMETABLEORDERCOLUMNENTITY_ID ON ${schemaname}.Diff_Table_Name (NAMETABLEORDERCOLUMNENTITY_ID);
CREATE INDEX I_NTBLPLM_NAMETABLEORDERCOLUMNENTITY_ID ON ${schemaname}.NTblOColE_oNameTypeElem (NAMETABLEORDERCOLUMNENTITY_ID);
CREATE INDEX I_CL_BONM_COLUMNS_ID ON ${schemaname}.OColE_BONameE (COLUMNS_ID);
CREATE INDEX I_CL_BONM_ELEMENT ON ${schemaname}.OColE_BONameE (BM2MNAMES_ID);
CREATE INDEX I_CL_LNTS_ORDERCOLUMNENTITY_ID ON ${schemaname}.OColE_listElements (ORDERCOLUMNENTITY_ID);
CREATE INDEX I_CL_UONM_ELEMENT ON ${schemaname}.OColE_UONameE (UM2MNAMES_ID);
CREATE INDEX I_CL_UONM_ELEMENT1 ON ${schemaname}.OColE_UONameE (UO2MNAMES_ID);
CREATE INDEX I_CL_UONM_ORDERCOLUMNENTITY_ID ON ${schemaname}.OColE_UONameE (ORDERCOLUMNENTITY_ID);
CREATE INDEX I_XCL_NMX_ELEMENT ON ${schemaname}.XOColE_BONameXE (BM2MNAMES_ID);
CREATE INDEX I_XCL_NMX_XMLCOLUMNS_ID ON ${schemaname}.XOColE_BONameXE (XMLCOLUMNS_ID);
CREATE INDEX I_XCL_NTS_XMLORDERCOLUMNENTITY_ID ON ${schemaname}.XOColE_listElements (XMLORDERCOLUMNENTITY_ID);
CREATE INDEX I_XCL_UNM_ELEMENT ON ${schemaname}.XOColE_UONameE (UM2MNAMES_ID);
CREATE INDEX I_XCL_UNM_ELEMENT1 ON ${schemaname}.XOColE_UONameE (UO2MNAMES_ID);
CREATE INDEX I_XCL_UNM_XMLORDERCOLUMNENTITY_ID ON ${schemaname}.XOColE_UONameE (XMLORDERCOLUMNENTITY_ID);
