CREATE TABLE AttrOColE (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));

CREATE TABLE AttrOColE_nonInsertAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255),NONINSERTABLE_ORDER INTEGER);
CREATE INDEX I_TTRBNTS_ATTRIBUT ON AttrOColE_nonInsertAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID);

CREATE TABLE AttrOColE_nonInsertXmlElem (ATTRIBUTEORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), NONINSERTABLE_ORDER INTEGER);
CREATE INDEX I_TTRBNTS_ATTRIBU1 ON AttrOColE_nonInsertXmlElem (ATTRIBUTEORDERCOLUMNENTITY_ID);

CREATE TABLE AttrOColE_nonNullAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), NONNULLABLE_ORDER INTEGER NOT NULL);
CREATE INDEX I_TTRBNTS_ATTRIBU2 ON AttrOColE_nonNullAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID);

CREATE TABLE AttrOColE_nonNullXmlElem (ATTRIBUTEORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), NONNULLABLE_ORDER INTEGER NOT NULL);
CREATE INDEX I_TTRBNTS_ATTRIBU3 ON AttrOColE_nonNullXmlElem (ATTRIBUTEORDERCOLUMNENTITY_ID);

CREATE TABLE AttrOColE_nonUpdateAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), NONUPDABLE_ORDER INTEGER);
CREATE INDEX I_TTRBNTS_ATTRIBU4 ON AttrOColE_nonUpdateAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID);

CREATE TABLE AttrOColE_nonUpdateXmlElem (ATTRIBUTEORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), NONUPDABLE_ORDER INTEGER);
CREATE INDEX I_TTRBNTS_ATTRIBU5 ON AttrOColE_nonUpdateXmlElem (ATTRIBUTEORDERCOLUMNENTITY_ID);

CREATE TABLE AttrOColE_oNameTypeElem (ATTRIBUTEORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), orderNameTypeElements_ORDER INTEGER);
CREATE INDEX I_TTRBNTS_ATTRIBU6 ON AttrOColE_oNameTypeElem (ATTRIBUTEORDERCOLUMNENTITY_ID);

CREATE TABLE BONameE (id INTEGER NOT NULL, name VARCHAR(255), COLUMN_ID INTEGER, bo2mNames_ORDER INTEGER, PRIMARY KEY (id));
CREATE INDEX I_BRDRTTY_COLUMN ON BONameE (COLUMN_ID);

CREATE TABLE BONameXE (id INTEGER NOT NULL, name VARCHAR(255), XMLCOLUMN_ID INTEGER, bo2mNames_ORDER INTEGER, PRIMARY KEY (id));
CREATE INDEX I_BRDRTTY_XMLCOLUM ON BONameXE (XMLCOLUMN_ID);

CREATE TABLE DefOColE (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));

CREATE TABLE DefOColE_oColDefElem (DEFINITIONORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), OCDefElements_ODR INTEGER);
CREATE INDEX I_DFNTNTS_DEFINITI ON DefOColE_oColDefElem (DEFINITIONORDERCOLUMNENTITY_ID);

CREATE TABLE DefOColE_ovrOColDefElem (DEFINITIONORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), OVROCDefElements_ODR SMALLINT);
CREATE INDEX I_DFNTNTS_DEFINIT1 ON DefOColE_ovrOColDefElem (DEFINITIONORDERCOLUMNENTITY_ID);

CREATE TABLE DefOColE_xmlOColDefElem (DEFINITIONORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), XOCDefElements_ODR INTEGER);
CREATE INDEX I_DFNTNTS_DEFINIT2 ON DefOColE_xmlOColDefElem (DEFINITIONORDERCOLUMNENTITY_ID);

CREATE TABLE DefOColE_xmlOvrOColDefElem (DEFINITIONORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), XOVROCDefElements_ODR SMALLINT);
CREATE INDEX I_DFNTNTS_DEFINIT3 ON DefOColE_xmlOvrOColDefElem (DEFINITIONORDERCOLUMNENTITY_ID);

CREATE TABLE OColE (id INTEGER NOT NULL, PRIMARY KEY (id));

CREATE TABLE OColE_BONameE (COLUMNS_ID INTEGER, BM2MNAMES_ID INTEGER, bm2mNames_ORDER INTEGER, XMLCOLUMNS_ID INTEGER);
CREATE INDEX I_RDRCTTY_COLUMNS_ ON OColE_BONameE (COLUMNS_ID);
CREATE INDEX I_CL_BONM_XMLCOLUM ON OColE_BONameE (XMLCOLUMNS_ID);
CREATE INDEX I_RDRCTTY_ELEMENT ON OColE_BONameE (BM2MNAMES_ID);

CREATE TABLE OColE_listElements (ORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), OVRELEMENTS_ORDER INTEGER, LISTELEMENTS VARCHAR(255));
CREATE INDEX I_RDRCNTS_ORDERCOL ON OColE_listElements (ORDERCOLUMNENTITY_ID);

CREATE TABLE OColE_UONameE (ORDERCOLUMNENTITY_ID INTEGER, UM2MNAMES_ID INTEGER, um2mNames_ORDER INTEGER, UO2MNAMES_ID INTEGER, uo2mNames_ORDER INTEGER, XMLORDERCOLUMNENTITY_ID INTEGER);
CREATE INDEX I_RDRCTTY_ELEMENT1 ON OColE_UONameE (UM2MNAMES_ID);
CREATE INDEX I_RDRCTTY_ELEMENT2 ON OColE_UONameE (UO2MNAMES_ID);
CREATE INDEX I_CL_UONM_XMLORDER ON OColE_UONameE (XMLORDERCOLUMNENTITY_ID);
CREATE INDEX I_RDRCTTY_ORDERCOL ON OColE_UONameE (ORDERCOLUMNENTITY_ID);

CREATE TABLE UONameE (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));

CREATE TABLE XOColE (id INTEGER NOT NULL, PRIMARY KEY (id));

CREATE TABLE XOColE_BONameXE (XMLCOLUMNS_ID INTEGER, BM2MNAMES_ID INTEGER, bm2mNames_ORDER INTEGER);
CREATE INDEX I_XMLRTTY_ELEMENT ON XOColE_BONameXE (BM2MNAMES_ID);
CREATE INDEX I_XMLRTTY_XMLCOLUM ON XOColE_BONameXE (XMLCOLUMNS_ID);

CREATE TABLE XOColE_listElements (XMLORDERCOLUMNENTITY_ID INTEGER, element VARCHAR(255), OVRELEMENTS_ORDER INTEGER, LISTELEMENTS VARCHAR(255));
CREATE INDEX I_XMLRNTS_XMLORDER ON XOColE_listElements (XMLORDERCOLUMNENTITY_ID);

CREATE TABLE XOColE_UONameE (XMLORDERCOLUMNENTITY_ID INTEGER, UM2MNAMES_ID INTEGER, um2mNames_ORDER INTEGER, UO2MNAMES_ID INTEGER, uo2mNames_ORDER INTEGER);
CREATE INDEX I_XMLRTTY_ELEMENT1 ON XOColE_UONameE (UM2MNAMES_ID);
CREATE INDEX I_XMLRTTY_ELEMENT2 ON XOColE_UONameE (UO2MNAMES_ID);
CREATE INDEX I_XMLRTTY_XMLORDER ON XOColE_UONameE (XMLORDERCOLUMNENTITY_ID);