CREATE TABLE ${schemaname}.AttrOColE (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));

CREATE TABLE ${schemaname}.AttrOColE_nonInsertAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID NUMBER, element VARCHAR2(255), NONINSERTABLE_ORDER NUMBER);
CREATE INDEX ${schemaname}.I_TTRBNTS_ATTRIBUT ON ${schemaname}.AttrOColE_nonInsertAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID);

CREATE TABLE ${schemaname}.AttrOColE_nonInsertXmlElem (ATTRIBUTEORDERCOLUMNENTITY_ID NUMBER, element VARCHAR2(255), NONINSERTABLE_ORDER NUMBER);
CREATE INDEX ${schemaname}.I_TTRBNTS_ATTRIBU1 ON ${schemaname}.AttrOColE_nonInsertXmlElem (ATTRIBUTEORDERCOLUMNENTITY_ID);

CREATE TABLE ${schemaname}.AttrOColE_nonNullAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID NUMBER, element VARCHAR2(255), NONNULLABLE_ORDER NUMBER NOT NULL);
CREATE INDEX ${schemaname}.I_TTRBNTS_ATTRIBU2 ON ${schemaname}.AttrOColE_nonNullAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID);

CREATE TABLE ${schemaname}.AttrOColE_nonNullXmlElem (ATTRIBUTEORDERCOLUMNENTITY_ID NUMBER, element VARCHAR2(255), NONNULLABLE_ORDER NUMBER NOT NULL);
CREATE INDEX ${schemaname}.I_TTRBNTS_ATTRIBU3 ON ${schemaname}.AttrOColE_nonNullXmlElem (ATTRIBUTEORDERCOLUMNENTITY_ID);

CREATE TABLE ${schemaname}.AttrOColE_nonUpdateAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID NUMBER, element VARCHAR2(255), NONUPDATABLE_ORDER NUMBER);
CREATE INDEX ${schemaname}.I_TTRBNTS_ATTRIBU4 ON ${schemaname}.AttrOColE_nonUpdateAnnoElem (ATTRIBUTEORDERCOLUMNENTITY_ID);

CREATE TABLE ${schemaname}.AttrOColE_nonUpdateXmlElem (ATTRIBUTEORDERCOLUMNENTITY_ID NUMBER, element VARCHAR2(255), NONUPDATABLE_ORDER NUMBER);
CREATE INDEX ${schemaname}.I_TTRBNTS_ATTRIBU5 ON ${schemaname}.AttrOColE_nonUpdateXmlElem (ATTRIBUTEORDERCOLUMNENTITY_ID);

CREATE TABLE ${schemaname}.AttrOColE_oNameTypeElem (ATTRIBUTEORDERCOLUMNENTITY_ID NUMBER, element VARCHAR2(255), orderNameTypeElements_ORDER NUMBER);
CREATE INDEX ${schemaname}.I_TTRBNTS_ATTRIBU6 ON ${schemaname}.AttrOColE_oNameTypeElem (ATTRIBUTEORDERCOLUMNENTITY_ID);

CREATE TABLE ${schemaname}.BONameE (id NUMBER NOT NULL, name VARCHAR2(255), COLUMN_ID NUMBER, bo2mNames_ORDER NUMBER, PRIMARY KEY (id));
CREATE INDEX ${schemaname}.I_BRDRTTY_COLUMN ON ${schemaname}.BONameE (COLUMN_ID);

CREATE TABLE ${schemaname}.BONameXE (id NUMBER NOT NULL, name VARCHAR2(255), XMLCOLUMN_ID NUMBER, bo2mNames_ORDER NUMBER, PRIMARY KEY (id));
CREATE INDEX ${schemaname}.I_BRDRTTY_XMLCOLUM ON ${schemaname}.BONameXE (XMLCOLUMN_ID);

CREATE TABLE ${schemaname}.DefOColE (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));

CREATE TABLE ${schemaname}.DefOColE_oColDefElem (DEFINITIONORDERCOLUMNENTITY_ID NUMBER, element VARCHAR2(255), OCDefElements_ODR NUMBER);
CREATE INDEX ${schemaname}.I_DFNTNTS_DEFINITI ON ${schemaname}.DefOColE_oColDefElem (DEFINITIONORDERCOLUMNENTITY_ID);

CREATE TABLE ${schemaname}.DefOColE_ovrOColDefElem (DEFINITIONORDERCOLUMNENTITY_ID NUMBER, element VARCHAR2(255), OVROCDefElements_ODR SMALLINT);
CREATE INDEX ${schemaname}.I_DFNTNTS_DEFINIT1 ON ${schemaname}.DefOColE_ovrOColDefElem (DEFINITIONORDERCOLUMNENTITY_ID);

CREATE TABLE ${schemaname}.DefOColE_xmlOColDefElem (DEFINITIONORDERCOLUMNENTITY_ID NUMBER, element VARCHAR2(255), XOCDefElements_ODR NUMBER);
CREATE INDEX ${schemaname}.I_DFNTNTS_DEFINIT2 ON ${schemaname}.DefOColE_xmlOColDefElem (DEFINITIONORDERCOLUMNENTITY_ID);

CREATE TABLE ${schemaname}.DefOColE_xmlOvrOColDefElem (DEFINITIONORDERCOLUMNENTITY_ID NUMBER, element VARCHAR2(255), XOVROCDefElements_ODR SMALLINT);
CREATE INDEX ${schemaname}.I_DFNTNTS_DEFINIT3 ON ${schemaname}.DefOColE_xmlOvrOColDefElem (DEFINITIONORDERCOLUMNENTITY_ID);

CREATE TABLE ${schemaname}.OColE (id NUMBER NOT NULL, PRIMARY KEY (id));

CREATE TABLE ${schemaname}.OColE_BONameE (COLUMNS_ID NUMBER, BM2MNAMES_ID NUMBER, bm2mNames_ORDER NUMBER, XMLCOLUMNS_ID NUMBER);
CREATE INDEX ${schemaname}.I_RDRCTTY_COLUMNS_ ON ${schemaname}.OColE_BONameE (COLUMNS_ID);
CREATE INDEX ${schemaname}.I_CL_BONM_XMLCOLUM ON ${schemaname}.OColE_BONameE (XMLCOLUMNS_ID);
CREATE INDEX ${schemaname}.I_RDRCTTY_ELEMENT ON ${schemaname}.OColE_BONameE (BM2MNAMES_ID);

CREATE TABLE ${schemaname}.OColE_listElements (ORDERCOLUMNENTITY_ID NUMBER, element VARCHAR2(255), OVRELEMENTS_ORDER NUMBER, LISTELEMENTS VARCHAR2(255));
CREATE INDEX ${schemaname}.I_RDRCNTS_ORDERCOL ON ${schemaname}.OColE_listElements (ORDERCOLUMNENTITY_ID);

CREATE TABLE ${schemaname}.OColE_UONameE (ORDERCOLUMNENTITY_ID NUMBER, UM2MNAMES_ID NUMBER, um2mNames_ORDER NUMBER, UO2MNAMES_ID NUMBER, uo2mNames_ORDER NUMBER, XMLORDERCOLUMNENTITY_ID NUMBER);
CREATE INDEX ${schemaname}.I_RDRCTTY_ELEMENT1 ON ${schemaname}.OColE_UONameE (UM2MNAMES_ID);
CREATE INDEX ${schemaname}.I_RDRCTTY_ELEMENT2 ON ${schemaname}.OColE_UONameE (UO2MNAMES_ID);
CREATE INDEX ${schemaname}.I_CL_UONM_XMLORDER ON ${schemaname}.OColE_UONameE (XMLORDERCOLUMNENTITY_ID);
CREATE INDEX ${schemaname}.I_RDRCTTY_ORDERCOL ON ${schemaname}.OColE_UONameE (ORDERCOLUMNENTITY_ID);

CREATE TABLE ${schemaname}.UONameE (id NUMBER NOT NULL, name VARCHAR2(255), PRIMARY KEY (id));

CREATE TABLE ${schemaname}.XOColE (id NUMBER NOT NULL, PRIMARY KEY (id));

CREATE TABLE ${schemaname}.XOColE_BONameXE (XMLCOLUMNS_ID NUMBER, BM2MNAMES_ID NUMBER, bm2mNames_ORDER NUMBER);
CREATE INDEX ${schemaname}.I_XMLRTTY_ELEMENT ON ${schemaname}.XOColE_BONameXE (BM2MNAMES_ID);
CREATE INDEX ${schemaname}.I_XMLRTTY_XMLCOLUM ON ${schemaname}.XOColE_BONameXE (XMLCOLUMNS_ID);

CREATE TABLE ${schemaname}.XOColE_listElements (XMLORDERCOLUMNENTITY_ID NUMBER, element VARCHAR2(255), OVRELEMENTS_ORDER NUMBER, LISTELEMENTS VARCHAR2(255));
CREATE INDEX ${schemaname}.I_XMLRNTS_XMLORDER ON ${schemaname}.XOColE_listElements (XMLORDERCOLUMNENTITY_ID);

CREATE TABLE ${schemaname}.XOColE_UONameE (XMLORDERCOLUMNENTITY_ID NUMBER, UM2MNAMES_ID NUMBER, um2mNames_ORDER NUMBER, UO2MNAMES_ID NUMBER, uo2mNames_ORDER NUMBER);
CREATE INDEX ${schemaname}.I_XMLRTTY_ELEMENT1 ON ${schemaname}.XOColE_UONameE (UM2MNAMES_ID);
CREATE INDEX ${schemaname}.I_XMLRTTY_ELEMENT2 ON ${schemaname}.XOColE_UONameE (UO2MNAMES_ID);
CREATE INDEX ${schemaname}.I_XMLRTTY_XMLORDER ON ${schemaname}.XOColE_UONameE (XMLORDERCOLUMNENTITY_ID);