CREATE TABLE ElementCollectionEntityOLGH16686 (id INT NOT NULL, PRIMARY KEY (id));
CREATE TABLE EntMapDateTemporal (ELEMENTCOLLECTIONENTITYOLGH16686_ID INT, mykey DATETIME NOT NULL, temporalValue DATETIME);
CREATE INDEX I_NTMPPRL_ELEMENTCOLLECTIONENTITYOLGH16686_ID ON EntMapDateTemporal (ELEMENTCOLLECTIONENTITYOLGH16686_ID);