SET CURRENT SCHEMA = JBATCH;

ALTER TABLE "REMOTABLEPARTITON" DROP FOREIGN KEY "RMTBLPRTFKSTPXCTND";
ALTER TABLE "REMOTABLEPARTITON" DROP FOREIGN KEY "RMTBLPRTTFKJBXCTND";
ALTER TABLE "STEPTHREADEXECUTION" DROP FOREIGN KEY "STPTHRDXCTNFKJBXCD";
ALTER TABLE "GROUPASSOCIATION" DROP FOREIGN KEY "GRPSSCTNFKJBNSTNCD";
ALTER TABLE "JOBPARAMETER" DROP FOREIGN KEY "JBPRMETERFKJBXECID";
ALTER TABLE "JOBEXECUTION" DROP FOREIGN KEY "JBXCTNFKJBNSTNCEID";
ALTER TABLE "STEPTHREADINSTANCE" DROP FOREIGN KEY "STPTHRDNFKJBNSTNCD";
ALTER TABLE "STEPTHREADEXECUTION" DROP FOREIGN KEY "STPTHFKTPLVLSTPXCD";
ALTER TABLE "STEPTHREADINSTANCE" DROP FOREIGN KEY "STPTHRFKLTSTSTPXCD";
ALTER TABLE "JOBEXECUTION" DROP PRIMARY KEY;
ALTER TABLE "JOBINSTANCE" DROP PRIMARY KEY;
ALTER TABLE "STEPTHREADEXECUTION" DROP PRIMARY KEY;
ALTER TABLE "STEPTHREADEXECUTION" DROP UNIQUE "STPTHRADEXECUTION0";
ALTER TABLE "STEPTHREADINSTANCE" DROP PRIMARY KEY;
DROP TABLE "REMOTABLEPARTITION";
DROP TABLE "JOBEXECUTION";
DROP TABLE "JOBINSTANCE";
DROP TABLE "STEPTHREADEXECUTION";
DROP TABLE "STEPTHREADINSTANCE";
DROP TABLE "JOBPARAMETER";
DROP TABLE "GROUPASSOCIATION";

DROP SCHEMA "JBATCH" RESTRICT;