java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar activity.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar activityImpl.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar activitySession.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar asynchbeans-client.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar asynchbeans.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar bootstrap.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar channel.ssl.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar classloader.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar CmpCrmf.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar configmanager.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar crypto.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar cryptoimpl.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar ecutils.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar F007704.1.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar ffdc.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar ibmcfw.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar ibmcmsprovider.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar ibmjceprovider.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar ibmjsseprovider2.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar ibmkeycert.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar ibmpkcs.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar ibmpkcs11impl.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar idl.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar implfactory.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar iwsorb.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar iwsorbutil.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar javax.annotation_1.2.0.v201401042248.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar javax.inject_1.0.0.v20091030.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar javax.j2ee.management.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar javax.xml_1.3.4.v201005080400.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar ltcClient.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar mail.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar naming.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar namingclient.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar namingclient.nonlocal.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar nativefile.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar orbProperties.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar orbProperties_local.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.apache.batik.css_1.7.0.v201011041433.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.apache.batik.util.gui_1.7.0.v200903091627.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.apache.batik.util_1.7.0.v201011041433.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.apache.commons.jxpath_1.3.0.v200911051830.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.commands.nl1_3.6.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.commands.nl2_3.6.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.commands.nlBidi_3.6.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.commands_3.6.0.I20100512-1500.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.commands_3.7.0.v20150422-0725.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.contenttype.nl1_3.4.100.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.contenttype.nl2_3.4.100.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.contenttype.nlBidi_3.4.100.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.contenttype_3.4.100.v20100505-1235.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.contenttype_3.5.0.v20150421-2214.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.databinding.nl1_1.3.100.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.databinding.nl2_1.3.100.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.databinding.nlBidi_1.3.100.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.databinding.observable.nl1_1.3.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.databinding.observable.nl2_1.3.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.databinding.observable.nlBidi_1.3.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.databinding.observable_1.3.0.I20100601-0800.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.databinding.observable_1.5.0.v20150422-0725.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.databinding.property.nl1_1.3.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.databinding.property.nl2_1.3.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.databinding.property.nlBidi_1.3.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.databinding.property_1.3.0.I20100601-0800.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.databinding.property_1.5.0.v20150422-0725.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.databinding_1.3.100.I20100601-0800.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.databinding_1.5.0.v20150422-0725.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.expressions.nl1_3.4.200.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.expressions.nl2_3.4.200.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.expressions.nlBidi_3.4.200.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.expressions_3.4.200.v20100505.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.expressions_3.5.0.v20150421-2214.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filebuffers.nl1_3.5.100.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filebuffers.nl2_3.5.100.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filebuffers.nlBidi_3.5.100.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filebuffers_3.5.100.v20100520-0800.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.linux.ppc.nl1_1.0.200.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.linux.ppc.nl2_1.0.200.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.linux.ppc.nlBidi_1.0.200.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.linux.ppc_1.0.200.v20100505-1235.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.linux.x86.nl1_1.4.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.linux.x86.nl2_1.4.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.linux.x86.nlBidi_1.4.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.linux.x86_1.4.0.v20100505-1235.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.linux.x86_64.nl1_1.2.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.linux.x86_64.nl2_1.2.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.linux.x86_64.nlBidi_1.2.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.linux.x86_64_1.2.0.v20100505-1235.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.nl1_1.3.1.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.nl2_1.3.1.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.nlBidi_1.3.1.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.solaris.sparc.nl1_1.2.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.solaris.sparc.nl2_1.2.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.solaris.sparc.nlBidi_1.2.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.solaris.sparc_1.2.0.v20100505-1235.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.win32.x86.nl1_1.1.201.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.win32.x86.nl2_1.1.201.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.win32.x86.nlBidi_1.1.201.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.win32.x86_1.1.201.R36x_v20100727-0745.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.win32.x86_64.nl1_1.1.201.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.win32.x86_64.nl2_1.1.201.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.win32.x86_64.nlBidi_1.1.201.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem.win32.x86_64_1.1.201.R36x_v20100727-0745.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem_1.3.1.R36x_v20100727-0745.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.filesystem_1.5.0.v20150725-1910.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.jobs.nl1_3.5.1.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.jobs.nl2_3.5.1.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.jobs.nlBidi_3.5.1.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.jobs_3.5.2.R36x_v20110419.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.jobs_3.7.0.v20150330-2103.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.net.nl1_1.2.100.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.net.nl2_1.2.100.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.net.nlBidi_1.2.100.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.net_1.2.100.I20100511-0800.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.net_1.2.300.v20141118-1725.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.resources.nl1_3.6.1.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.resources.nl2_3.6.1.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.resources.nlBidi_3.6.1.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.resources.win32.x86_3.5.100.v20100505-1345.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.resources_3.10.1.v20150725-1910.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.resources_3.6.2.R36x_v20120712-1700.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.runtime.compatibility.auth.nl1_3.2.200.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.runtime.compatibility.auth.nl2_3.2.200.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.runtime.compatibility.auth.nlBidi_3.2.200.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.runtime.compatibility.auth_3.2.200.v20100517.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.runtime.compatibility.nl1_3.2.100.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.runtime.compatibility.nl2_3.2.100.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.runtime.compatibility.nlBidi_3.2.100.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.runtime.compatibility_3.2.100.v20100505.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.runtime.compatibility_3.2.300.v20150423-0821.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.runtime.nl1_3.6.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.runtime.nl2_3.6.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.runtime.nlBidi_3.6.0.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.runtime_3.11.1.v20150903-1804.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.runtime_3.6.0.v20100505.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.variables.nl1_3.2.400.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.variables.nl2_3.2.400.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.variables.nlBidi_3.2.400.v201102251823.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.variables_3.2.400.v20100505.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.core.variables_3.2.800.v20130819-1716.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.debug.core_3.10.0.v20150303-1130.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.core.commands_0.11.0.v20150422-0725.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.core.contexts_1.4.0.v20150828-0818.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.core.di.annotations_1.4.0.v20150528-1451.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.core.di.extensions_0.13.0.v20150421-2214.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.core.di_1.5.0.v20150421-2214.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.core.services_2.0.0.v20150403-1912.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.emf.xpath_0.1.100.v20150513-0856.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.ui.bindings_0.11.0.v20150422-0725.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.ui.css.core_0.11.0.v20150511-1937.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.ui.css.swt.theme_0.10.0.v20150422-0725.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.ui.css.swt_0.12.0.v20150511-1003.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.ui.di_1.1.0.v20150422-0725.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.ui.model.workbench_1.1.100.v20150407-1430.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.ui.services_1.2.0.v20150422-0725.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.ui.widgets_1.1.0.v20150427-1751.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.ui.workbench.addons.swt_1.2.0.v20150512-1414.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.ui.workbench.renderers.swt_0.13.0.v20150901-1347.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.ui.workbench.swt_0.13.0.v20150504-0621.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.ui.workbench3_0.13.0.v20150422-0725.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.e4.ui.workbench_1.3.0.v20150531-1948.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.emf.common.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.emf.common_2.11.0.v20150805-0538.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.emf.ecore.change_2.11.0.v20150805-0538.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.emf.ecore.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.emf.ecore.xmi.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.emf.ecore.xmi_2.11.1.v20150805-0538.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.emf.ecore_2.11.1.v20150805-0538.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.app_1.3.300.v20150423-1356.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.common_3.7.0.v20150402-1709.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.concurrent_1.1.0.v20130327-1442.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.ds_1.4.300.v20150423-1356.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.event_1.3.100.v20140115-1647.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.frameworkadmin.equinox_1.0.600.v20150522-2234.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.frameworkadmin_2.0.200.v20150423-1455.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.p2.core_2.4.0.v20150527-1706.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.p2.metadata_2.3.0.v20150511-1532.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.preferences_3.5.300.v20150408-1437.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.registry_3.6.0.v20150318-1503.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.security.ui_1.1.201.v20150803-1228.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.security_1.2.100.v20150423-1356.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.simpleconfigurator.manipulator_2.0.100.v20150423-1455.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.simpleconfigurator_1.1.100.v20150423-1455.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.equinox.util_1.0.500.v20130404-1337.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.help_3.6.0.v20130326-1254.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.jface.databinding_1.7.0.v20150406-2148.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.jface.nl1_3.11.0.v201509151231.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.jface.nl2_3.11.0.v201509151231.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.jface_3.11.0.v20150602-1400.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.osgi.compatibility.state_1.0.100.v20150402-1551.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.osgi.services_3.5.0.v20150519-2006.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.osgi_3.10.101.v20150820-1432.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.rcp_4.5.1.v20150904-0015.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.swt.gtk.linux.x86_64_3.104.1.v20150825-0743.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.swt.nl1_3.104.1.v201509151231.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.swt.nl2_3.104.1.v201509151231.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.swt_3.104.1.v20150825-0743.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.ui.forms_3.6.200.v20150506-2029.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.ui.intro_3.4.300.v20141007-1449.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.ui.views_3.8.0.v20150422-0725.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.ui.workbench.nl1_3.107.0.v201509151231.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.ui.workbench.nl2_3.107.0.v201509151231.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.ui.workbench_3.107.0.v20150825-2206.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.ui_3.107.0.v20150507-1945.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.eclipse.update.configurator_3.3.300.v20140518-1928.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.w3c.css.sac_1.3.1.v200903091627.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.w3c.dom.events_3.0.0.draft20060413_v201105210656.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.w3c.dom.smil_1.0.1.v200903091627.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar org.w3c.dom.svg_1.1.0.v201011041433.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar PM65468_WAS85GA.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar pmi.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar pmt.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar ras.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar runtime-utils.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar runtime.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar runtimefw.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar runtimeimpl.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar sas.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar sdrt.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar security.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar securityconfig.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar securityconfigimpl.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar securityimpl.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar securityutil.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar soap.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar tx.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar txEmbeddable.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar txImpl.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar txUtil.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar util.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar utils.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar validationmgr.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar was-wssecurity-wsspi.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar was-wssecurity.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar was.txClient.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar was.txClientImpl.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar wasproduct.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar wasRuntimeUtilV85Core.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar workspace.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar WsaEJBDeployUtility.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar wsexception.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar wsprofile.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar wssec.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar wxs71_66266_sessiontask.jar
java -jar C:\dev\repos-pub\open-liberty\dev\com.ibm.ws.org.jboss.jandex\build\libs\com.ibm.ws.org.jboss.jandex.jar xmlsecurity.jar
